### ISSUE TITLE
码农含泪支持，他墙任他墙，梯子打好，轮子自造

### ISSUE THREAD

**Issue by tingting1993** [sikaozhe1997/Xin-Yue#101]
也不是第一天被墙了！今天码农躲起来，自我审查，自我举报，明天轮到我们脑袋上，也没有人会再帮忙了。白帽子屎盆子够多了，某家园的耻辱也没过去。无法可依，有法不依要到什么时候？？

批评不自由，赞美无意义。妹子加油！

**Comment by Moreki** [comment]
真的很感谢！

**Comment by Richardplus** [comment]
转战码云～

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
