### ISSUE TITLE
我想加入进来，去帮你们

### ISSUE THREAD

**Issue by nidada** [sikaozhe1997/Xin-Yue#102]
您好，我想进来，帮助你们。强烈建议你们把条目关闭，先让女孩子安安静静顺利毕业，把家里的事情安文豪，把母亲的情绪安抚下去，现在有足够的法律去帮助你们维护自己的合法权利，不要一时气血上头，把事情闹得不可收拾。你们只是一群有着强烈正义感的大学生，却不知道如何去维护自己。

**Comment by MarcWong** [comment]
我可以联系到当事人，不过还是暂时不希望事情扩大化，她是对于学院的处理表示不满，而不想和学校站到对立面。您的好意心领了，不过目前还是先静观其变吧

**Comment by nidada** [comment]
一定要天天和她保持联系，帮她把家里的事情安抚好，这件事儿已经过去了23年了，我很理解你们此刻那种悲愤和无奈，但是，要安静，要冷静，这件事儿有无数的处理方法，不急在这一时

**Comment by nidada** [comment]
我建议你们，把这个条目关闭了，自己删掉吧。你们已经在违逆学校的意思了。这件事儿需要合理解决，就是这姑娘暂时全部放下，必要的隐忍，是可以的，不要争一时之快

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
