### ISSUE TITLE
原以为北大是当下中国唯一有风骨的学校，目前看来和武汉理工没啥两样

### ISSUE THREAD

**Issue by feipxyz** [sikaozhe1997/Xin-Yue#103]

**Comment by cvmax** [comment]
有风骨的是学生。不正说明了北大跟武汉理工不一样。

**Comment by lambda7xx** [comment]
可是现在的情况是大学不是学生的大学，是领导的大学

**Comment by CeresCheng** [comment]
因为是中共管理的

**Comment by nainoNa** [comment]
还有清华吧。。。。

**Comment by icewings1204** [comment]
武汉理工的学生也很有风骨啊！！

![-768x264](https://user-images.githubusercontent.com/38675937/39168076-096f2188-47c5-11e8-82ae-2d59c2addc5f.png)
![default](https://user-images.githubusercontent.com/38675937/39168077-099f40c0-47c5-11e8-9a21-fd055f4d2672.jpg)

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
