### ISSUE TITLE
狄更斯说

### ISSUE THREAD

**Issue by luyao777** [sikaozhe1997/Xin-Yue#105]
> It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.

**纪念这个时代最黑暗的日子。**

**Comment by Rangooo** [comment]
You really think it is the darkest right now？ Too young too simple

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
