### ISSUE TITLE
保持安静，放下一切，好好毕业

### ISSUE THREAD

**Issue by nidada** [sikaozhe1997/Xin-Yue#107]
我想告诉你们的是，一定要保持冷静，先让那个女孩子安静毕业，不要把事情扩大化，更不要往国外去说。不然以后国内很难生活。
先把这些事情全部放下，家里怎么说，学校怎么说，怎么做，注意保留证据，记录。你们一定要先毕业。
我不太会用github给你发信息。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
