### ISSUE TITLE
No man is an island entire of itself

### ISSUE THREAD

**Issue by sikaozhe1997** [sikaozhe1997/Xin-Yue#108]
关于GitHub这样使用我个人表示抱歉，但的却倘若不是微信的疯狂删帖，又有谁想用这种方式发布信息呢？
如果因为这个导致了GitHub的被封我个人真的十分的抱歉。
但我坚信，“为众人抱火者，不可使其冻毙于风雪； 为自由开路者，不可使其困顿于荆棘"。
岳昕是一个很优秀的北大人，没有人会是一座孤岛，帮助岳昕也就是帮助我们自己。

**Comment by tingting1993** [comment]
感谢，理解，支持。

**Comment by ZiJiaW** [comment]
支持

**Comment by MoeChaser** [comment]
为什么不考虑使用FB或者Twitter发布声明？反正这些站已经被wall了，也不用管什么。

**Comment by zeling** [comment]
Please have a look at #81

**Comment by 900Even** [comment]
北大最为全国高校的精神高地，现在北大学子被迫到这里来发声。是多么的悲凉 各位，别忘了当年的五四

**Comment by tongpinmo** [comment]
北大都这样了，欲盖弥彰，高等教育太悲哀了

**Comment by tongpinmo** [comment]
北大都这样了，欲盖弥彰，高等教育太悲哀了

**Comment by nainoNa** [comment]
@900Even  我觉得可能大部分考不上 PT 的人都对全国的最高学府抱有一份憧憬。结果P大这样做，让我觉得很幻灭。P大的学生不愧是P大的，可是这些人，配得上管理P大的学生吗？配享受全国的景仰吗？

**Comment by dpatrickx** [comment]
没有错，你做得很棒，已star~

**Comment by chungjin** [comment]
编程者都没有掌握科学上网的方式的话，那早点回家歇着吧。

**Comment by zss1995** [comment]
懂得上github的人一般都知道怎么翻墙，可以发在墙外

**Comment by yu45020** [comment]
事件大概浏览了。 支持， 加油。你没做错。

 可惜判断对错的界线由有权有势的人捏着  ╮(╯▽╰)╭

**Comment by meteorlxy** [comment]
不用抱歉哈哈哈，这种事情早就有了，看一下[git.io/99](git.io/99)和[git.io/100](git.io/100)这种神奇的ID吧

**Comment by pwy722** [comment]
支持！

**Comment by qyc777** [comment]
@meteorlxy 看到你的资源之后表示可以安心回去写代码了，感谢。

**Comment by lecter255** [comment]
History is also here. IPFS is different.

https://ipfs.io/ipfs/QmP7vt5Tbqy3wPZj7snZitw44zHKVZqKuM6mM2ZrZ2xD7C

**Comment by FreedomOfSpeech** [comment]
支持 做了个网页，  https://anonymous-xinyue.github.io

**Comment by FreedomOfSpeech** [comment]
you dont have to apologize

**Comment by mwonng** [comment]
每一个人都有表达自己想法的权利和自由，谁也没有权利去试图控制别人的自由。虽然自由这个词对于每个中国公民都看似很遥远，但是没有这样的年轻人，中国是没有希望的。

GitHub是一个中立的平台，但这并不意味着这里必须要遵守政治中立，每个人都有自己的政治倾向。在这里合理表达诉求并没有影响到任何一个其他人。如果你不愿意看到，完全可以不看。

愿每一个追求自由的优质青年最终都能站在自由的土地上

**Comment by xdcccr** [comment]
手刃github社区的到底是岳昕和她的支持者，还是建墙的人？

**Comment by RononoaC** [comment]
支持你

**Comment by linesh-simplicity** [comment]
路过此处，虽然尚不知道事情原委，但着实同意，「没有人会是一座孤岛，帮助岳昕也就是帮助我们自己」。在这些事情上，我们哪怕不能伸出援手，少一些所谓理所应当的评判，也对当事人是一份支持和敬重。当事人为了做正确的事情，受到了威胁，委屈，家人反目，即使这样依然要坚持。不容易，加油。

大力支持。

**Comment by rockywhisper** [comment]
权利要靠自己争取，
没有神仙皇帝，
忍让换不来和平。

这是 国际歌+历史 教给我们的。

**Comment by heduian** [comment]
评论挺搞笑的，不知道原委，你也来支持？

你一个不写代码的 ，别来这祸害

**Comment by InLAnn** [comment]
讲真不管好坏戾气也带上来了

**Comment by InLAnn** [comment]
把GitHub当作存档还行 做成个讨论组就有些过了 多少人能看见先不说  顺手把戾气也带上来了

**Comment by ShPG** [comment]
请不要在技术网站发布和技术无关的东西！如果github被封，你这种人就是千古罪人！你要发请到twitter，facebook上发，不要在这里发，这里都是学习技术，分享技术的码农们，不要毒害github！谢谢

**Comment by meteorlxy** [comment]
楼上也不怎么用github嘛，还千古罪人了。github能不能千古还两说

**Comment by kepsail** [comment]
@sikaozhe1997 非常敬佩你的勇气与担当，但还是建议能把这个公开信移到其他地方，比如以太坊上面也有人存了英文版，那里是删不掉的。GitHub是分享技术的地方，不是发这种公告的地方，在国内能访问实在来之不易，都是前辈争取来的结果，如果因为这个而被封站，那损失就太大了。事实上，现在你这个仓库地址已经被封了。

**Comment by LeiZeng** [comment]
支持信息公开，但是我觉得你们采用的方式和过程并不可取。
请求一个疑案信息的公开，是为了伸张正义，还是想要更多？当事人已经引咎开除，性侵案，他没有受到应有的足够的惩罚。请你们把方向指向当事人。

如果是为了指向北大*当年*对于事件处理方式有问题，可以指向当年处理这件事情的人。20年过去了，相信确实很难，但是方向是明确的。

我想说的是，从你们公开的信息来看，我没有看到比较合理的诉求。只是信息公开？这个不能解决任何问题，将来也不会有人因为此事受益。如果能促进立法，或者产生相关规定，会是更好的结果。
现在，这个事情被明显的导向到体制和政治，只会无法收拾。这是你们想要的吗？

这感觉，好像拿到一份祖传代码。本来只是想加个功能，但是发现需要重构的地方太多。
...干脆重写这个模块吧~
...还是把整个后端重写了吧~
hmm...要不整个应用重写了吧~

hmm...我原来要做的那个功能是啥呢？

**Comment by wangleeyom** [comment]
偶然在 github 上看到这个 rep，
但是作为一名普通程序员，我也只能在心底默默的支持你，


>风雨即将平息
云朵翻涌成画
黑暗终将过去
而阳光会和你不期而遇

祝福 ~

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。

**Comment by Xifeng2009** [comment]
@ShPG 操你妈赶紧墙 你爹有的是翻墙的手段 把你们这些傻逼墙完了 你爹身价暴涨的时候就到了

**Comment by boogoobird** [comment]
你们把岳昕同学的信息公开了,就要把这件事负责到底,帮助岳昕同学,让她能够正常完成学业.

**Comment by CodingPapi** [comment]
每次有赵国专属敏感信息放到GitHub上，都会有人说谈技术勿谈国事，被封后果严重。呵呵。
等权利欺负到你跟你家人头上的时候，我们都会让你闭嘴的。

**Comment by hunt978** [comment]
唉，诸君好自为之。热血盈头，昏聩的总先是自己。另，相比刘先生，本人对首页的诉求是极其不齿的。

**Comment by sjzjams** [comment]
没有人可以反对人家在自己的git上放什么东西吧！！再无五四 哎！！

**Comment by liu1084** [comment]
你把这样的文章放在毫不相干的地方，github如果被封，你知道多少人和公司受难？

**Comment by catvox** [comment]
不发表意见，但是我从知乎上看到有人再这里trending做这个，看来北大学生也就这样了，我们这些草莽小民也经常遇到类似的事情，全世界也有，来这里发表我们也帮不了你什么。

**Comment by fuguanghua** [comment]
我看你也不是什么好鸟，你知道你毁了github，会影响多少人吗？

**Comment by fuguanghua** [comment]
那些发表支持的人，有多少是需要依赖github的？你们站着说话不腰疼吗？

**Comment by AnyWAT** [comment]
🤣網上熱傳4月24日晚8點，武漢一名副教授跑到女生廁所偷窺拍照，被女生發現後將廁所門鎖住。這名副教授奮不顧身從二樓窗戶跳下逃脫，校方目前封鎖消息，告誡學生不要外傳……天朝叫獸不學無術，禍害學生，學校要封鎖就幚它火。 pic.twitter.com/EVrdD0IiGz

**Comment by weidlu** [comment]
震惊！！原来用git的还有这么多不会科学上网的。。。请联系我好吧，1080没有压力。

**Comment by yuldong** [comment]
关注进展

**Comment by HJ-StevenSun** [comment]
那些说不要影响技术论坛，害怕github被墙了的人是何等的可笑可耻。首先不懂得何为真正的自由，github在几年前都是要翻墙才上得了而且很卡。其次，就是自私，害怕自己上不了Github不方便。我们从来不解决问题，只解决提出问题的人。这是一贯作风。

**Comment by lindroy** [comment]
@fhfuih 日后要是欺负到你头上记得保持安静，不要手刃任何的社区，谢谢。
