### ISSUE TITLE
Add English support to allow more contributors to read and give best wishes.

### ISSUE THREAD

**Issue by Anduin2017** [sikaozhe1997/Xin-Yue#109]
Version: 
````
6576e840b6efc92208d346d7f6b69e7675d64361
````

Repro Stpes:

* Open the repo
* View readme.md

**Comment by iBug** [comment]
Shouldn't be too hard to do. But what exactly do you mean "English support"? Is it English translation of the text in this repo?

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
