### ISSUE TITLE
《有的人》

### ISSUE THREAD

**Issue by sunqibuhuake** [sikaozhe1997/Xin-Yue#110]
有的人活着，
　　他已经死了；
　　有的人死了，
　　他还活着。
　　有的人
　　骑在人民头上：“呵，我多伟大!”
　　有的人
　　俯下身子给人民当牛马。
　　有的人
　　把名字刻在石头上想“不朽”；
　　有的人
　　情愿作野草，等着地下的火烧。
　　有的人
　　他活着别人就不能活；
　　有的人
　　他活着为了多数人更好地活。
　　骑在人民头上的，
　　人民把他摔倒；
　　给人民作牛马的，
　　人民永远记住他!
　　把名字刻在石头上的，
　　名字比尸首烂得更早；
　　只要春风吹到的地方，
　　到处是青青的野草。
　　他活着别人就不能活的人，
　　他的下场可以看到；
　　他活着为了多数人更好地活着的人，
　　群众把他抬举得很高，很高。

**Comment by nidada** [comment]
其实你们说的很有理，但解决问题，让这个女孩子安静毕业，更重要。

**Comment by sunqibuhuake** [comment]
我是写css和切图的，性能、业务逻辑这些，接触不到。

**Comment by nidada** [comment]
兄弟，我太理解你们了，哲学家试图解释这个世界，更重要的是要改变这个世界，改变需要合理的方法和策略。

**Comment by sunqibuhuake** [comment]
有人掌管一个学校，一个城市，可是我只能在ps里管1920 x 1080 像素（移动端的素材更小一些）

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
