### ISSUE TITLE
既然发都发出来了，校方处理第一在场人是清楚吧，这件事情都没弄清楚，那起哄个啥？你们和29年的那帮学生比简直 ，没有一点长进

### ISSUE THREAD

**Issue by Lwp90** [sikaozhe1997/Xin-Yue#112]

**Comment by MXWXZ** [comment]
稍有常识的人都能看出，29年前的学生比现在的不知道高到哪里去了。

**Comment by sunqibuhuake** [comment]
29年是什么,历史爱好者虚心求教

**Comment by Lwp90** [comment]
在技术论坛传播一件没有第二人出来明说的事，那么多所谓的码农就被煽动起来，我是不是可以在这里申诉下64？

**Comment by gym487** [comment]
能不能把这些一个commit都没有就张口码农闭口技术论坛的全部close掉？

**Comment by MXWXZ** [comment]
不是很清楚一个刚注册的小号来洗地的目的，当事人可能是希望在网络上留下自己的痕迹，借助fork机制就算被迫删除也还是有人备份，没有任何所谓起哄的意思，只是希望不是像29年前一样被抹除历史。

**Comment by Lwp90** [comment]
我来洗干嘛？我跟这件事又没有什么关系？我删除这个对我有什么好处？我就是看不惯有些人在这里没有帮助这件事却在社区里煽阴风。你们在我评论下面口诛笔伐的又和你们口中的北大赵家人有什么区别？

**Comment by 121211xf** [comment]
您能不能把标题里的话说顺了再来对别人指指点点？

**Comment by gkjolin** [comment]
到底是咋回事？ 怎么看不明白

**Comment by Lwp90** [comment]
有些人在这个问题就是想搞事，根本不想解决这个事，ISSUES里面煽的几个，保不齐什么牛鬼蛇神

**Comment by THUcqb** [comment]
- 建议楼上 @Lwp90 **先回答**几篇推送以及当事人的公开信，违反了哪些网络监管法律，为什么遭到删除；**再来质疑**把内容**被迫迁移**到 GitHub 上的做法的合理性。
- 顺便吐槽一句楼上的楼上，您说的挺有道理。可以说 GitHub 偏技术，但请您不要把 GitHub 误解成是一个*论坛* =  =

**Comment by sd44** [comment]
LZ根本没有搞清楚REPO主们几个人的意思啊。。。

什么是《公开信息申请表》？申请的是公开什么信息？
正是当时对在场人处理的经过和结果。这方面北大给不出啊。

**Comment by tyizhou** [comment]
@THUcqb 谢谢，我知道不是论坛，顺着之前哪层楼的说法直接打出来了。。。。不过个人感觉虽然GitHub并没有限定这里只能用来搞开发，但还是不太适合发布这样的话题。

**Comment by Chenduoru** [comment]
楼主Lwp90的意思是否是北大官方最终公布的结果才算事实，才能拿来讨论？

**Comment by MagnusBai** [comment]
89年那帮孩子，虽然在`社会变革方面`失败了：没有推支共一把，让支共和苏共一起完蛋。

但无法否认，围绕89年的周边，已成为许多长脑子人记忆中的不朽的文化符号：

* 比如，挡在丑陋坦克前面的英勇tankman大叔，坦克绕着他走，他还冲到坦克面前，中途还爬上坦克甲板和解放军抗议~
* 比如，流亡诗人北岛，和他的名作：“我不相信天是蓝的，我不相信雷是回声，我不相信梦是假的，我不相信死无报应”
* 比如，中国的《日瓦格医生》作者，诺贝尔和平奖也给他了一座空椅子。


所以，从文化角度上，没有人可以忽视89年那帮孩子，以及支持那帮孩子人的巨大成功！
更没人有权力嘲笑8964。

**Comment by Lwp90** [comment]
@THUcqb 我说过信息违反了网络监管法律了吗？如果这个陌生信息散步社交平台，用户的第一印象是什么？对社交平台，这个行为可能是有问题的，懂？

**Comment by Lwp90** [comment]
@MagnusBai你能为学生申诉？那被掉天灯的士兵，29年里有人为他申诉吗？

**Comment by MagnusBai** [comment]
@Lwp90  

不多说了，我和谐发言，为了那个女孩儿不受牵连。
呵呵，
呵呵，
论杀人，你说说xxx杀了多少？

**Comment by sd44** [comment]
楼上那些29年前的事件鼓吹者，要么是在政治上和现实上极端幼稚，要么是别有用心。
建议删帖。

**Comment by Chenduoru** [comment]
楼主还是去北大未名bbs了解一下大概的过程好了，免得又说没有第二人说明

**Comment by phodal** [comment]
GitHub 是一个代码社区，请不要发表政治相关的言论 @MagnusBai @Lwp90 @sd44

**Comment by SiskonEmilia** [comment]
支持当事人的精神！不过楼上某些鼓吹29年前事件的人，学好政治学（此处非特指红色政治），或者收起你的美元再说话。

**Comment by wql7013** [comment]
@tyizhou 难道你不知道GitHub也可以用作博客吗？一个工具用作多个用途为什么不可以呢？纸是拿来擦嘴的，拿来擦屁股就是亵渎它了吗？

**Comment by aviot** [comment]
是啊，就算86学潮都比这帮连修宪都不敢bb的人高到什么地方去了

**Comment by Zone971016** [comment]
稍有常识的人都知道上面某些赵家人的狗保持了最大限度的克制

**Comment by Statham-stone** [comment]
申述逆玛壁，滚

**Comment by karolin4949** [comment]
這些討論最好不要發表在中國大陸看得到的論壇，盡可能的維持安定穩健公正的社會。
