### ISSUE TITLE
这里不适合发布这样的内容

### ISSUE THREAD

**Issue by tyizhou** [sikaozhe1997/Xin-Yue#113]
请大义凛然的各位不要逞口舌之快了，承担风险的毕竟也不是各位？我劝当事人在这个当口还是谋求安稳毕业，想要为社会做些什么，今后有的是机会，但不是现在。
想要翻译成英文传播给世界的那些人是什么心态？唯恐老大哥觉得github影响力不够吗？再说你逢外国人便说这事对于解决问题有什么帮助吗？

**Comment by tyizhou** [comment]
建议当事人先把repository删除，顺利拿到毕业证、学位证和三方协议等等是目前最重要的事情。

**Comment by ybsbbb** [comment]
了解一下 https://baike.baidu.com/item/%E7%8E%B0%E4%BB%A3%E7%8A%AC%E5%84%92%E4%B8%BB%E4%B9%89/2247237

**Comment by CeresCheng** [comment]
没有不合适，自我阉割的才不合适

**Comment by xiongwei-git** [comment]
19hours之前加入GitHub的人来评价这里不适合发布这样的内容，挺搞笑的。
真的挺搞笑的。

**Comment by CeresCheng** [comment]
19hours 之前加入，看来是真五毛了，Github什么时候轮到你们指手画脚了

**Comment by quxiaowei** [comment]
没什么不合适的

**Comment by quxiaowei** [comment]
没什么不合适！有些机构公器私用都习惯了。
没处发声，用个技术网站记录下有问题吗？！

**Comment by xujh0824** [comment]
你不应该反思一下，为什么能被逼无奈到这里发声呢？
请去看一下波士顿关于纳粹的那个纪念碑文好么？明天你遇到这种事，再也没人替你说话，你不觉得悲哀？

**Comment by icewings1204** [comment]
If not now, when?
If not me/us, who?

**Comment by Statham-stone** [comment]
在太监眼里，所有的性爱都是不合适的。

**Comment by throndiablo** [comment]
还以为阁下是老江湖，原来也是刚刚开GitHub啊

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
