### ISSUE TITLE
个人认为，统一用中文，不要star

### ISSUE THREAD

**Issue by darktxt** [sikaozhe1997/Xin-Yue#114]
不管怎么说，不希望引起国外朋友的围观。情况已经很不好了，弄个大新闻，又能怎么样？
这里只是一个揭露真相的平台，但不太可能是解决问题的阵地。
---------
楼下说搞大新闻引起关注的，为什么不去微博呢？这次事情能不能通过这种方式解决，心里没数吗？北电侯亮平忘了吗？

**Comment by stdrickforce** [comment]
这事还怕国外友人知道？谣言止于智者，外国友人不会不知道，我相信党和国家一定会给我们一个合理的交待和解释的。

**Comment by ybsbbb** [comment]
弄个大新闻可以引发关注，否则只会不了了之，坏人继续坏，善良的人继续被欺压，真相继续沉在海底。

**Comment by KSOra** [comment]
呵呵，微博早就删光了，就是要让外国人知道

**Comment by CeresCheng** [comment]
你的发言才是违反Github原则的
