### ISSUE TITLE
表达敬佩！天亮后的北大，会视岳昕同学之精神如珍宝。

### ISSUE THREAD

**Issue by MagnusBai** [sikaozhe1997/Xin-Yue#115]
岳昕同学，加油。莫愁前路无知己，天下谁人不识君。

**Comment by flufy3d** [comment]
https://memo.cash/post/f143b371da9e7320665d2d1e13f283666d8ac6da48d88e6583ee9af4c3a73f31

**Comment by flufy3d** [comment]
是的 支持岳昕同学

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
