### ISSUE TITLE
github挺住

### ISSUE THREAD

**Issue by lixiaosi33** [sikaozhe1997/Xin-Yue#117]
他们墙掉facebook时，我没有说话，因为我用人人；他们墙掉twitter时，我没有说话，因为我有微博；他们墙掉youtube时，我没有说话，因为我看优酷和土豆。最后他们朝着我的GitHub走来...

工信部惹程序员不明智哦！

**Comment by lixiaosi33** [comment]
工信部惹程序员不明智哦！

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
