### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by sd44** [sikaozhe1997/Xin-Yue#118]
1，对几位码农的意见不必过多在意。
Github，开放式版本管理系统，不是排斥非码农的产物，相反，wordpress,octopress,hexo等博客类架构并非是专为码农设计，更多的是寄托其特性可以自由、传播、继承、发展的架构。即使在GitHub代码是主流倾向，仍不妨碍其非代码方向的发展。

2，不要牵扯较多个人，如辅导员等，可将其笼统为对校方的批判。
作为个人，特别是制度下的个人，是不具备完整行为能力的。越牵涉其中，越容易面临更为复杂和不利于己的困境，甚至面临伦理上的问题。

3，适时低头。
理论上总是好的，理论上可能维权、公开信息是对的，理论上需要大无畏的理想人士。现实！现实！现实！！行动！！！行动！！！行动！！！
行动需要依托于现实性的考虑。过纯的理想化走向初心反面，或被反动、恶性势力利用导致更大错误有时是常态。这其中有太多高低不一的层次。
父母不是对立面，不是愚顽不灵，是因其所知而作出的聪明举动。这种举动可能是有局限性的，但另一方面也是更为宽广和充满爱护之情的。仔细斟酌、斟酌、斟酌。
身为北大学子不容易，理想报国报民渠道多种多样，如果没有产生切实的火光或者火花，那么这种牺牲是否有必要？是否真是为了大众而不是自我牺牲的满足感本身？
慎重！慎重！！慎重！！！

**Comment by nainoNa** [comment]
校方？

**Comment by sd44** [comment]
@nainoNa 你找了下事件经过吗？
这事早就上升成一个校方层面的问题了，北大已经公开发表对沈阳的处理意见，且被大众认知、称赞了。

而yue xin等人正是基于此对校方发申请表。
就后续发展来看，现在已经不是yue xin等与沈阳的对立，而是与校方的对立。

在此层面上，我甚至衷心希望yue xin等人能排除异议，能低头，甚至能“认错”或删帖。北大学子考上不易，未来能发挥的能量在很多时候也是不与常人相等。我希望他们更能是富有行动主义的，而不是过理想主义的。过理想主义不能成事，只能成就个人本人。当你能以北大一个完整同学身份对同学持续增加视界的时候，我觉得这可能更有行动上的意义。这个身份的获得可能需要这样的一个妥协。

利益相关，只是我没受过高等教育，我对学府可能仍抱有一种美好期望。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
