### ISSUE TITLE
妹子请坚持住，也要保护好自己

### ISSUE THREAD

**Issue by zhipwang** [sikaozhe1997/Xin-Yue#120]
谢谢岳昕同学的坚强，难以想象被迫在这种平台上记录事件的始末，深感悲哀。虽然不知道你能不能看到这个留言，但请坚持对自由的信仰，也要保证自己的利益。或许一个时代不是那么容易改变的，保护好自己。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
