### ISSUE TITLE
刚刚去P大论坛看了下，已经有人开始黑起她来了，真是令人恶心

### ISSUE THREAD

**Issue by nainoNa** [sikaozhe1997/Xin-Yue#129]
https://bbs.pku.edu.cn/v2/post-read.php?bid=64&threadid=16394737

醉了。我们学校的最近好像才开始论文，我觉得P大可能也差不多？
怎么还有人故意黑他人，人血馒头？

**Comment by sagittarish** [comment]
贵校林子大了，什么鸟都有

**Comment by cocoyimasa** [comment]
脑子进过水的小白兔？这智商怎么当的辅导员？
笑的我肚子疼，洗地洗的如此不专业。。给贵校公关水平抹黑啊

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
