### ISSUE TITLE
个人觉得还是不要转到Github

### ISSUE THREAD

**Issue by luckyxiaoer** [sikaozhe1997/Xin-Yue#13]
有其他的方式可以转吧，个人觉得还是需要保持Github做技术的独立性。免得增加政府墙Githu的决心

**Comment by MengzhenWang** [comment]
似乎有道理。。。

**Comment by liangxj8** [comment]
gayhub 是被墙过的，不过后来由于抗议又解封了罢

**Comment by luckyxiaoer** [comment]
嗯，墙过两次。希望以后不要把人民的内部矛盾转发到这里来。留一片程序员交流的净土

**Comment by andrewbxy** [comment]
良民证明天就能寄到了哟。

**Comment by iplus26** [comment]
没说GitHub是仅供程序员交流代码的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
