### ISSUE TITLE
微信直连已经屏蔽，对抗 404 的Terminus 项目更需帮助

### ISSUE THREAD

**Issue by tsai1993** [sikaozhe1997/Xin-Yue#131]
这个 repo 已经被微信停止访问。
更需要帮助的项目是 https://github.com/Info-cn/Terminus
https://github.com/sikaozhe1997/Xin-Yue/issues/85

**Comment by sczhengyabin** [comment]
有一百多个fork

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
