### ISSUE TITLE
先支持一波，不过请注意：GitHub 也有封禁条款的，不要过多讨论政治相关内容

### ISSUE THREAD

**Issue by phodal** [sikaozhe1997/Xin-Yue#134]
<del>虽然不知道发生了什么，但是作为 GitHub 上的**知名资深 markdown**工程师，我是带观众来看戏（看观众席的戏）的。</del>

---

还有，作为一个程序员，建议不要在 GitHub 上过多地**讨论政治相关的内容**  如 https://github.com/sikaozhe1997/Xin-Yue/issues/112 ，以免未来 GitHub 要科学上网。

**Comment by Dinghow** [comment]
个人感觉，以后这类东西如果发多的话估计要科学上网了。（还是表示支持一波

**Comment by noeagles** [comment]
Git也被墙是不是有点过分了。

**Comment by mage1028** [comment]
程序员不会翻墙还叫程序员么。。google都用不了咋解决问题

**Comment by 1994sunshine** [comment]
很简单，不是那个沈阳吗？各路新闻都在报道

**Comment by phodal** [comment]
@mage1028 你要考虑到有些程序员，还在成为程序喘气路上。还有 G 是大写的。

**Comment by mrlsaiyff** [comment]
最后也是程序员封禁的GitHub，太嘲讽了。。

**Comment by nainoNa** [comment]
@phodal 惊现知乎大V？

**Comment by Moreki** [comment]
正因为人们都抱着您这样看戏的心态，以及像是经历过十年浩劫后畏畏缩缩的姿态，这样的正义得不到伸张。况且，您的出发点是，讨论政治内容有可能导致github被墙。请问：1.申请信息公开，是过多的讨论政治内容吗？2.您是资深程序员，您不会科学上网吗？

**Comment by 1994sunshine** [comment]
我看各位平常也不关注时事新闻，我来说一下整个过程:20前年，也就是上世纪90年代，一个叫沈阳的教师任职北大，诱奸一名18岁本科生致其自杀，20年后，同系同学(40多岁了)实名爆料这件事，此时沈阳已在南京大学任职，南京大学核实后将其辞退。-以上都是公开新闻，可以直接搜到，应该不会被屏蔽。今天就是学生要求公开当年系处理意见和警察调查结果(疑问:这时候不应该记者去询问吗?)，然后被思想教育，剩下的你们都懂的。

**Comment by erDaren** [comment]
但是，这根本就不是政治问题啊…

**Comment by mrlsaiyff** [comment]
就因为谈论北大信息公开，可能会导致git被墙。就不能说了。因为程序员不能有一点利益被侵蚀。真是新时代小布尔乔亚。。
GitHub被封也是被程序员封的。。没什么利益不利益的。
千万别说，github不能讨论这些内容了。。会被墙的。
当年那些程序员可是得到了一大笔利益啊。
如果是我们这些程序员在当年，怎么选择。都诚实点吧。

**Comment by 1994sunshine** [comment]
这是毛线政治问题，因为公开当年的处理决定和警察的调查记录可能会影响北大声誉和相关领导前途问题，咳咳!点到为止，各位老司机应该都懂了吧。

**Comment by Seedarchangel** [comment]
如果能因为区区一个大学教封禁千万码农的交流场所，我看也没什么好说的了

**Comment by Rabenda** [comment]
@mrlsaiyff 我觉得可怕的是他们学某项目*hao 只对中国区域封禁 那这个项目的作用就完全消失了

**Comment by QuantumGhost** [comment]
@phodal 据我所知，GIthub 的 TOS 并没有禁止在 Github 上讨论政治内容，如果有的话还望指出。
如果你是想要通过避免在 Github 谈论政治来保护 Github，那这么做也只是苟延残喘罢了。
以及，墙的存在，本来就是一个政治性的议题。

**Comment by gaocegege** [comment]
首先作为一个 GitHub 重度用户，开源的爱好者，我尊重您在开源领域的贡献。正是因为有您这样的用户，才使得 GitHub 这个平台更加值得珍惜。

但是窃以为，开源之所以被人津津乐道，不是因为其他，正是因为它给了我们平等的，开放的使用代码的权利。虽然现在有时它只是公司的一种商业手段，但是我们不得不说开源的骨子里就带着某种对自由和平等的诉求。如果您熟悉 GitHub，那您一定知道它现在还在为争取网络中立性而努力着。它可能也带着自己的利益诉求，但是我们仍然尊重它。

如果今天您告诉我，我们因为担心 GitHub 被墙，所以不要发政治相关的内容，恐怕不敢苟同。讨论政治什么时候成为了不受欢迎的事情？起码我没有在 GitHub Terms of Service 看到任何类似的描述。更何况，现在 GitHub 开通了与各国政府的沟通渠道，如果真的有问题，自会有 xx 出手。

其实我与您一样，十分珍惜 GitHub 这个平台，其上也有我倾注了大量时间与精力的开源项目。但是我觉得这不是我们提出这样自我阉割的建议的理由。如果 GitHub 因为这一个 repo 被墙了，在这样一个 xx 写代码真的还有前途么？

WDYT

**Comment by huangzonghao** [comment]
其实我不太懂。。。现在在墙内的程序员反正无论如何也要翻墙上google不是吗？所以反正都要翻墙了GitHub是不是被墙有什么区别呢？

**Comment by phodal** [comment]
@Moreki @1994sunshine @gaocegege @mrlsaiyff 

和公开信息无关，issues 中很多在讨论与本贴无关的政治，诸如：https://github.com/sikaozhe1997/Xin-Yue/issues/112 。

我主要是在说这些总有人想借题发挥。

与此同时，诸位请断好句。我说的不是**不要讨论**，而是**不要过多也讨论**。

当然，如果你们愿意那么理解是你们的事。反正，我的意思就是，不要借题发挥，不要过多也讨论。

**Comment by phodal** [comment]
@gaocegege 还有，GitHub 有 DCMA

**Comment by phodal** [comment]
@Moreki 我说的看戏并不是指你理解下的看戏，而是在这个 repo 下发生的各种 “有趣” 的事。

**Comment by justjavac** [comment]
那些说github不会被强的是真的github粉吗？github以前被强过，是包括李开复在内的大V们集体发声抵制才又解封的

**Comment by mrlsaiyff** [comment]
@phodal 还有一个issues说要推qiang的呢。 一看是昨天# **注册**的用户。笑死。 我也赞成你的说法，不要借题发挥，只就事论事的说就可以了。

**Comment by wenhaoliang** [comment]
@justjavac

**Comment by jliao011** [comment]
##**支持大佬，大佬说的没毛病**

**Comment by Statham-stone** [comment]
github是你家的吗？你不让讨论就不讨论？

**Comment by phodal** [comment]
@huangzonghao 能好好断字吗。我只是建议不要过多地讨论政治，不是说不能讨论政治。

请 Google：GitHub DMCA

**Comment by huangzonghao** [comment]
@phodal 
<img width="358" alt="screen shot 2018-04-23 at 9 41 31 pm" src="https://user-images.githubusercontent.com/8278802/39161537-2cfaa586-473f-11e8-9102-9e5368e7e185.png">
不知道这是谁写的

**Comment by phodal** [comment]
@huangzonghao 请 Google：GitHub DMCA

**Comment by huangzonghao** [comment]
@phodal 
LOLOL
"Digital Millennium Copyright Act"
不如您查查字典这几个字是什么意思？
不理你自己还嘚瑟起来了。。。。。你的政治封禁条款呢？

**Comment by phodal** [comment]
@huangzonghao 

我根本没说过**政治封禁条款**，我不知道你从哪理解来的这个词。

**Comment by gaocegege** [comment]
据我所知，DCMA 是关于 copyright 的，与政治无关，xx 并不是这段文本的版权所有者。DCMA 用封禁条款来描述也不太合适，真正受到限制和禁止的内容在 ToS 里的。

当然，我对版权问题也有所保留，不知有无 Xin Yue 同学授权，但这些都不是政治相关的了。

**Comment by huangzonghao** [comment]
@phodal 哈哈不跟你聊了，你自己都乱套了

To the others who might be seeing this:
大家可以往上翻翻对话，看看这大哥起的题目。。。这大哥真的超级可爱😅

<img width="872" alt="screen shot 2018-04-23 at 9 54 28 pm" src="https://user-images.githubusercontent.com/8278802/39161961-23c829be-4741-11e8-9b6d-66ce22c18530.png">

**Comment by phodal** [comment]
不好意思，我发现是我关 DMCA 和封禁条款关联到一起了。

相关的封禁历史可以见：[对GitHub的审查和封锁](https://zh.wikipedia.org/wiki/%E5%AF%B9GitHub%E7%9A%84%E5%AE%A1%E6%9F%A5%E5%92%8C%E5%B0%81%E9%94%81#cite_note-zhao-28)

**Comment by huangzonghao** [comment]
冤有头债有主。。看来你自己也知道是谁封的。。。而且注意是封的是你而不是封的网站。。你不去找封你的人反而在这骂正常用户你讲道理吗？而且说句不好听的。。墙外的用户人家在不违反github规则的前提下爱怎么用就怎么用这个您怕是管不到吧。。。您要是实在不愿意天天翻墙上网那就只能祝您早日到没有墙的地方了。。

**Comment by phodal** [comment]
首先我没有骂正常用户，其次我的本意是想提醒大家，不领情就算了呗。


只做键盘侠是没用的~。
