### ISSUE TITLE
关于北大学生信息公开被骚扰路人看法

### ISSUE THREAD

**Issue by 1994sunshine** [sikaozhe1997/Xin-Yue#135]
2018年4月23日，在GitHub上看到这个事件，作为一个研究生，我感觉 Xin-Yue 同学很勇敢，但是个人力量很有限，需要他人发声。
看了 Xin-Yue 同学和其辅导员的文章，我有一个疑问：1.辅导员电话联系 Xin-Yue 同学时是晚上11:30之后了，我想说：
“导员你咋这么关心同学？这不是明显的施压吗？大晚上你联系学生干嘛。”
   对于  Xin-Yue 同学，我有话要对你说：国内就这样封闭迂腐，两千年前来就没变过，你学文的历史书看过不少吧，难不成还不懂
中国庞大的官僚系统的可怕？这种事牵扯很多利益关系：政绩表现、升职、加官进爵。关于沈阳性侵女学生致其自杀之事，前一段时间全国早就知道了，
再遮掩也就是：皇帝的新装，看破不说破。
   谁都懂国内的这些情况，好好学习，争取移民这些地方：瑞士、丹麦、新西兰、澳大利亚、加拿大，理由就不说了，都懂。
对了，刚刚又把 皇帝的新装 看了一遍，再想想国内的情况，嗯，果然还是很符合我国国情。

**Comment by lzfcc** [comment]
思想上支持学生的求真精神，行动上不支持，毕竟以卵击石、螳臂当车（没错，央视总结的就是很到位）

**Comment by Wenhaoran** [comment]
其实，中国还是好人多，大多数人都是 挺正直的。反正，从我做起，我 愿意做一个好人。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
