### ISSUE TITLE
致北大外国语学院的一封信

### ISSUE THREAD

**Issue by Fang-Haoshu** [sikaozhe1997/Xin-Yue#139]
除了在朋友圈转发和star，给北大外院写邮件也有助于推动事情的解决。北大外院公开的联系方式链接：http://sfl.pku.edu.cn/xygk/zzjg/index.htm

**Comment by Fang-Haoshu** [comment]
尊敬的北大外院校领导：

您好，我是上海交大的一名学生，在网络上了解到岳昕同学的《公开信》一事。目前社会各界对此事均十分关心，在阅读完公开信及贵院公布的《情况说明》说明之后，我也有不少疑问和困惑。同时我也相信这份困惑不止来自我一个人，否则也不会引起这么大的风波。如果可以的话，希望贵院之后可以针对此事再做一次公开的情况说明，打消社会各界的疑虑。

目前，贵院发布的《情况说明》避重就轻，并没有对《公开信》中提到的较为严重问题做出正面回应，这些问题包括但不限于

1. 贵院辅导员是否要求岳同学删除手机、电脑中所有与信息公开事件相关的资料，并于天亮后到学工老师处作出书面保证不再介入此事？如果是，相关理由是什么呢？
2. 贵院在与岳同学母亲沟通时传达了怎么样的信息？为何会导致岳同学家长受到惊吓？

贵院的《情况说明》中的第二段，存在粉饰事实的嫌疑，与岳昕同学的《公开信》存在较大出入。如果贵院没有进一步的说明，恐将损害贵院与北大的社会公信力。 在北大120周年校庆来临之际，相信这也是贵院领导所不愿看到的。 第二段的原文摘录如下：
“2018年4月22日下午和晚上，学院辅导员出于对学生的关心，通过多种方式、多次联系岳昕同学，均未能联系上，这种情况下，辅导员感到担忧。到23:30左右，该同学还未回到寝室。出于对同学安全的关心，辅导员与同学的母亲联系，询问岳昕同学是否回家等情况。该同学的母亲表示，孩子并未回家；之后，家长拨打电话未接，发微信未回，因此感到着急，随后赶到宿舍。此时，该同学已回到宿舍，母亲与其进行沟通。因担心影响其他同学休息，母亲决定和同学一起回家。”

不论是站在贵院的立场或是社会各界的期骥，都希望此事能够得到一个圆满的解决，因此在这里，我诚挚的希望，贵院领导能再发布一份公开说明，正面回应《公开信》中提到的问题（包括但不限于以上两点），同时对岳同学在《公开信》中的五点诉求也一并做出回应。 该五点诉求摘录如下：
“1. 北京大学外国语学院应公开书面说明越过我向家长施压、凌晨到宿舍强行约谈我、要求我删除申请信息公开一事的相关资料所依据的规章制度，对此过程中违法违规操作予以明确，并采取措施避免此类事件再次发生。
2. 北京大学外国语学院应立即停止一切对我家人的施压行为，向我已经遭受惊吓的母亲正式道歉并澄清事实，帮助修复因此事导致的家庭紧张关系。
3. 北京大学外国语学院必须公开书面保证此事不会对本人毕业一事产生影响，并不会再就此事继续干扰我的论文写作进程。
4. 北京大学外国语学院负责消除此事对本人学业、未来就业和家人的其他一切不良影响。
5. 北京大学外国语学院应明确就以上诉求进行公开书面回复，给关注此事的大家一个交代。”

北大外院院长宁琦女士曾在北大招生办的《我们的新时代系列访谈》中对青年表达了如下期许：“青年们在不断的理解和奔波中学会选择，从而能够做到更自觉地学习与掌握本领，培养自己实实在在的社会担当。” 我相信岳昕同学的作为正是社会担当的体现，也希望贵院能妥善解决此事，真正做到尊重每一位同学的基本权利、努力保障每一位同学的合法权益。

此致

敬礼

**Comment by Fang-Haoshu** [comment]
以上

**Comment by nainoNa** [comment]
写得非常好，我可以按你的信的内容发吗？

**Comment by Fang-Haoshu** [comment]
@nainoNa 是的，放上来就是希望大家能帮忙一起发，推动院方合理解决这件事情

**Comment by jhljx** [comment]
支持！大家一起帮忙

**Comment by joeyijun** [comment]
已发，支持！

**Comment by blacksong** [comment]
已发支持

**Comment by ViolaHuangup** [comment]
请发一个外国语学院邮箱地址，我上网找不到

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
