### ISSUE TITLE
已经有更全的 GitHub 仓库，希望不要重复劳动

### ISSUE THREAD

**Issue by tsai1993** [sikaozhe1997/Xin-Yue#14]
https://info-cn.github.io/Terminus/tags.html#高岩之死信息公开
https://github.com/Info-cn/Terminus
已经有相关的更详细的仓库，可以去那里贡献。

**Comment by weichengzhang** [comment]
上面的链接已经被Tencent封了

**Comment by tsai1993** [comment]
可以直接贴 md https://github.com/Info-cn/Terminus/blob/master/_posts/2018-04-23-pku-YueXin-gongkaixin.md

**Comment by tsai1993** [comment]
还有一个利用 dat 网络的版本
https://p2p-terminus.hashbase.io/

**Comment by luna0607** [comment]
nice啊

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
