### ISSUE TITLE
建议上传到npm

### ISSUE THREAD

**Issue by fmj95817** [sikaozhe1997/Xin-Yue#145]
由于npm没有办法删除已经发布的package，所以上传到npm可以尽量防止被删除，已经clone这个仓库创建npm package：https://www.npmjs.com/package/xin-yue

**Comment by iBug** [comment]
其实除了npm之外还有PyPi, RubyGems, CPAN, CRAN等

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
