### ISSUE TITLE
校园网，我上不去github了，我同学还可以

### ISSUE THREAD

**Issue by blacksong** [sikaozhe1997/Xin-Yue#146]

**Comment by naoyeye** [comment]
github 在这件事之前就受不明原因影响了： https://www.v2ex.com/t/448689

更多帖子： https://www.google.com/search?q=site:v2ex.com/t+github&newwindow=1&source=lnt&tbs=qdr:w&sa=X&ved=0ahUKEwjknLW6-dDaAhUlsFQKHR2jAvwQpwUIIQ&biw=1280&bih=646

**Comment by naoyeye** [comment]
close 吧，跟这件事无关的讨论。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
