### ISSUE TITLE
建议不要用github发布这些东西

### ISSUE THREAD

**Issue by miaoliu** [sikaozhe1997/Xin-Yue#148]
你们这是要害多少程序员登不上github。

有本事自己建个网站

**Comment by daquexian** [comment]
。。。。。。你是脑残？就显得你自己特立独行？

**Comment by jhdxr** [comment]
连科学上网都不会的程序员，不要也罢

**Comment by zxFNZF** [comment]
建议你搞清楚是谁不让你上GitHub

**Comment by shic** [comment]
对，不要做程序员了。丢人

**Comment by lianliu** [comment]
为虎作伥

终自毙

**Comment by weimilianqiao** [comment]
这网站要被封的东西多不胜数。不懂的外行。

**Comment by Psycho7** [comment]
引用量上千的科学家说出这种话？

**Comment by jacobswan1** [comment]
脑子是个好东西可惜你没有,建议立即回国评选青千

**Comment by huangzonghao** [comment]
https://www.linkedin.com/in/miao-liu/
https://scholar.google.com/citations?user=5xUOIqkAAAAJ&hl=en

**Comment by CeresCheng** [comment]
你也配代表程序员

**Comment by hsz1273327** [comment]
程序员不会翻墙?不会翻墙的程序员有企业会要么....
