### ISSUE TITLE
YOU THINK you are doing the right thing BUT NOT

### ISSUE THREAD

**Issue by fhfuih** [sikaozhe1997/Xin-Yue#152]
> In order to get rid of excessive emotions keeping me from expressing my idea properly, I have re-organized my words on a large scale. Thank you for participating in this issue to exchange ideas. Below is the main part

I am not referring to PKU or the gov, I am referring to everyone, including the repository creator, who brings this topic to GitHub. 
Let's just get down to the thing. 

### GitHub is a programming community. 
Every word you jot down here is supposed to be related to programming. **I doubt it is a place where you are encouraged to say anything you like and have it encrypted, anti-censored, and safely kept.** 

### GitHub is a programming community. 
Furthermore it is a international programming community. We, or at least a large part of us, as the aborigines of this community, sometimes **value getting access to this community more than the (temporary) "ability" to write everything we want**, especially concerning those topics not closely relavent to programming and in the meantime "troublesome". 

### GitHub is a programming community. 
Furthermore it is a open-source programming community. We don't always ask for new functions. If you think your idea is great, then it is better to **show your code, either a new repo, a pull request with a complete implementation, or a code snippet expressing your core idea**. In this case technically it is quite interesting if you give us your implementation of penetrating GFW, which itself is quite worth careful researching.

Why am I writing in English here is that this is a convention here, concerning the potential inspiration your every word can bring to every tech person in the world. Personally I would like to stick to this convention.

**Comment by heliy** [comment]
How about other nontechnical repos like "https://github.com/github/gov-takedowns" ?
It belongs to the official github group.  
(smile~)

**Comment by fhfuih** [comment]
@yilixir Indeed after consideration I have deleted NO 5. Sometimes I am overwhelmed, too. Sorry for that.

**Comment by byshen** [comment]
"GitHub is a programming community" does not necessarily implies that everything on github is related to programming. It is just a git for people to hold contents that does not violate [github terms](https://help.github.com/articles/github-terms-of-service/), and make money from it.

**Comment by sd44** [comment]
rule them all:
You think you are doing the right thing BUT NOT!

**Comment by iBug** [comment]
I gave you a thumb down.

*Some* of your claims have their stand, but most do not. While I agree that GitHub is a programming community, there's no restriction of the content that you put here and share from here. It's totally up to individuals to decide what they share via GH. I see no violation of GH ToS by sharing such open letters here.

Censorship? GH has always been censored. The famous "ladder", ShadowSocks, was taken down by its author "according to regulations". It's blatant abuse of governing power. That, however, has no effect on preventing or frightening people from sharing whatever that would've been banned in mainland China on GH.

And finally, the same can reflexively apply to yourself:

# You think you are saying the right thing, but YOU ARE NOT

**Comment by DanteAndroid** [comment]
Why don't you read the [GitHub Terms of Service](https://help.github.com/articles/github-terms-of-service/) then come back to judge others?
先读一下**GitHub服务条款**再来喷吧，骚年。

> https://help.github.com/articles/github-terms-of-service/#k-advertising-on-github
>**GitHub repositories are intended to host Content. **

**Comment by wsdjeg** [comment]
I agree with you @fhfuih, I just write something in chinese #176

**Comment by fhfuih** [comment]
@Ro5aline @byshe @iBug @DanteAndroid I have noticed that you all have mentioned TOS. Here is my argue:

Indeed because of the absence of related terms, no one can force you out of this community. Your accounts will not be suspended. But **TOS states what people are prohibited to do, not what people are discouraged to do.** I am here speaking, on behalf of every other developer who shares the same idea with me, speaking or not speaking under this repo, to tell you that what GitHub is intended for is a **pure developer community,** not a entire-web aggregation service.

 Every community has its target developer, and **as you can see in the [About Page of GitHub](https://github.com/about), this website is intended for software developers**. `Shadowsocks`, as @iBug pointed out, IS a software. It touches the red line mentioned by @heliy but it is useful and worth researching in terms of the technology it integrates. Other censored content, those completely irrelevant to developing like this one, is not supposed to be posted here. 

Also that's why I say for some of you who want to destroy the GFW, post a repo here. Although this repo may be blocked, in terms of programming we welcome you to do that.

If you have interpreted my words correctly, (also in reply to @Ro5aline), I don't mean I want you to shut up and keep silence. I want to tell you that you are not welcomed to say it here. Are you really familiar with foreign online communities, or just heard of GitHub and wrongly think it is all? Go find Facebook, go find Twitter, go find Medium. Or those not (yet) blocked, go find Reddit, go find Quora. People, or identities, there will definitely welcome you to talk anything you like and will not shut you up. You don't violate either TOS or the community philosophy there. Unfortunately there is one thing that they use database instead of git, if git is a necessity of @byshen 's ideal web memoir.

**Comment by DanteAndroid** [comment]
@fhfuih Did the creator invite you here or did we? If you don't like it, just leave. **People come here are those who care about the XinYue event and have no time to listen to your piece of shit. **
If the timeline of whom influenced you, unfollowing him is an option.

**Comment by fhfuih** [comment]
@DanteAndroid I think what we are arguing is exactly who to leave. Thank you for re-stating your point that I am the one to leave. But please convince me. The creator don't invite you either, right?

I apologize if I haven't made it clear in my last paragraph. Let me do it again: I don't say I am not caring about this event. In fact I am keeping track of it. I am only suggesting you to move to another more appropriate community. I would like to discuss about this event, the current progress, the morality, my point of view there. But definitely not GitHub.

**Comment by DanteAndroid** [comment]
@fhfuih If you really want to change this, maybe sending a feedback to GitHub is a better way. Here? I don't think you have any right or ability to complain about this(because you just can't, there'are so many repositories not related to programming directly). IMO, I have right to post any content I like since I conform to the terms. GitHub is literally a programming community, however, it's way more than a programming community, at least for some of us. It represents open source, and, **freedom**.

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
