### ISSUE TITLE
支持发到任何地方。

### ISSUE THREAD

**Issue by shic** [sikaozhe1997/Xin-Yue#153]
我整天都离不开github，但是不能因为有可能造成自己的不方便就不发声啊！如果12亿人都发声，国家会是这样吗？

从程序员做起有什么不对吗？

**Comment by KISSMonX** [comment]
支持, 有百分之一这么想, 国家就有救了

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
