### ISSUE TITLE
关注，感谢，支持

### ISSUE THREAD

**Issue by TinaHongBu** [sikaozhe1997/Xin-Yue#155]
感谢维护这个 repo 的同学。

说不要在 GitHub 上讨论政治问题的，第一，政治问题从来不是一个不应该被谈论的话题，这是女生被性侵学校包庇强奸犯的法律问题，是学生合理要求信息公开反被约谈恐吓家庭学业都受到重大影响的人权问题，是可能发生在任何一个普通的安分守法的人身上的问题；第二，如果你已经这么习惯了自我阉割，那也希望你随时随地人身自由都可能被剥夺，一辈子做只抬不起头的没JB的鸵鸟。

**Comment by phodal** [comment]
@TinaHongBu 我不知道你有没有查看所有的贴子，反正我是看了一遍，总有人想搞事情。因为 https://github.com/sikaozhe1997/Xin-Yue/issues/112 里的政治讨论，让我觉得很担心。所以，我所指的政治讨论是指类似的内容，而不是说公开信息是政治问题。

**Comment by TinaHongBu** [comment]
为什么要在这儿装外宾？我当然希望体面的发声， 如果这是个可以随时游行抗议的国家。微博被禁微信被删媒体失声不得已在毫无群众影响力的 GitHub 整理一些文字，还要被说不够理智？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
