### ISSUE TITLE
压抑,难受

### ISSUE THREAD

**Issue by jacobswan1** [sikaozhe1997/Xin-Yue#156]
不才,长了这么大,第一次体会到生活在一群猪中是什么样的可怕的感受,身边的一群人,包括家人,朋友无疑无例外的还在大谈中国社会价值观,中国独立国情都是为了团结.
我就真的是操他妈的了,什么样的团结要靠为恶魔隐藏真相来维持?什么样的中国特色主义要靠封杀言论,管控思想来维持?什么样的价值观国情,要靠随意更改宪法,踏,独裁一言堂来体现?
答案就是是因为猪太多了,猪太多了就只能靠洗脑,靠管控来维持,就是因为不思考没有脑子的灵魂太多了,才能这么轻松的粉饰太平.
跪久了的民族,最后抬不起头来的那一天就别指望着有人来给自己说话.

**Comment by JingfuReal** [comment]
猪可不会这么卑鄙阴险

**Comment by jacobswan1** [comment]
养猪人坏,我们只不过算一些在养猪场边缘的半野猪盯着养猪人一只只去杀猪

**Comment by WincerChan** [comment]
从前段时间李沉简院长写《挺直脊梁 拒做犬儒》后辞职那件事就能看出来北大的领导是帮什么玩意了

**Comment by Wenhaoran** [comment]
其实，中国还是好人多的。

**Comment by KISSMonX** [comment]
好人是多, 蠢人也多. 好 + 蠢会间接做出很多话是, 无意间成为帮凶.

**Comment by cocoyimasa** [comment]
学校社会都是一丘之貉。
钳制思想最终结果就是任人凌辱的满清后期的结果。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。

**Comment by Wenhaoran** [comment]
我倒是感觉，好人还是挺多的。
