### ISSUE TITLE
公开信被写入以太币区块链

### ISSUE THREAD

**Issue by tangbao** [sikaozhe1997/Xin-Yue#158]
查看交易：
https://etherscan.io/tx/0x2d6a7b0f6adeff38423d4c62cd8b6ccb708ddad85da5d3d06756ad4d8a04a6a2

完全没办法删除啦

就是这个英文翻译不怎么样233333

（并不是我发起的交易

**Comment by KoraXia** [comment]
大佬666

**Comment by vitrum** [comment]
贫穷限制了我的想象力

**Comment by tangbao** [comment]
@vitrum 不是我的呀，而且这就0.5刀，还是自己转给自己的
我觉得这个意义反而在于写入区块链了就真的删不掉了XD 这是除了加密货币之外我发现的第二种有实际意义的区块链的应用

**Comment by Wenhaoran** [comment]
限制了我的想象

**Comment by jhljx** [comment]
给大佬递茶水

**Comment by KISSMonX** [comment]
龟龟, 666

**Comment by xujh0824** [comment]
好主意啊！

**Comment by Hujun** [comment]
这个可以

**Comment by guoqing-tang** [comment]
翻译issue里面有一篇，稍微好一点

**Comment by guoqing-tang** [comment]
你这个直接Google translate的，连名字拼音都错了

**Comment by tangbao** [comment]
@guoqing-tang 是的一看就是直接机翻的（并不是我进行的交易23333

**Comment by kimffy24** [comment]
用base64给中文加密啊
不要英文。影响华人群体推广

**Comment by ziyaofeng** [comment]
66666

**Comment by ikacarrot** [comment]
可以可以，学到了

**Comment by yixuantw** [comment]
太6了
（雖然微信已經阻止訪問……）

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
