### ISSUE TITLE
所以你们在这里搞有什么用呢

### ISSUE THREAD

**Issue by jiangzemingzz** [sikaozhe1997/Xin-Yue#159]
真是一群牛逼的不行的程序员，不过是赶上了好的机会，赚的不就比别人多一点以为自己屌的不行都开始讨论政治了，你们就是一群屁民，star到1w又能怎么样，还不是只会在屏幕前面敲键盘

**Comment by MeteorYee** [comment]
你能在这儿讲话，靠的可不就是程序员嘛？

**Comment by wenhaoliang** [comment]
谢谢你

**Comment by doodlewind** [comment]
@jiangzemingzz joined GitHub on **April 24, 2018**
Welcome, keyboard man 🙂

**Comment by TracebackS** [comment]
@jiangzemingzz joined GitHub on April 24, 2018 with 0 repositories, 0 stars, 0 followers, 0 following and 1 first issue.

Welcome, keyboard man slightly_smiling_face

**Comment by OscarMCY** [comment]
issue区的程序员互怼我没什么意见，那是因为每个人的角度不同

而你，一个才注册的外人，有什么资格来这里怼我们？

**Comment by HenrryBryant** [comment]
print('welcome keyboard man and get fuck out of here')

**Comment by dinghao1994** [comment]
这种人 是什么心态

**Comment by LinkWoong** [comment]
这刚注册的。。。直接举报了

**Comment by KISSMonX** [comment]
这种 SB, 刷存在感还是秀智障?

**Comment by linfeng93** [comment]
@doodlewind
Wang shifu, hen gao xing jian dao ni. 🙂

**Comment by CodeReaperX** [comment]
一些同行略带个人心态地思考GH会不会被墙，思考此种方式是否过于激进，应该先毕业君子报仇十年不晚（最早爆出这个事情的人就是毕业了二十年有了权势才回来为当前同学伸张正义的），我都可以理解。。。。。但是您这种智障我就是真的看不懂了，如果您是水军那实在是太不敬业了。还有，我咋觉得你在夸赞我们呢？

**Comment by CodeReaperX** [comment]
一些同行略带个人心态地思考GH会不会被墙，思考此种方式是否过于激进，应该先毕业君子报仇十年不晚（最早爆出这个事情的人就是毕业了二十年有了权势才回来为当年同学伸张正义的），我都可以理解。。。。。但是您这种智障我就是真的看不懂了，如果您是水军那实在是太不敬业了。还有，我咋觉得你在夸赞我们呢？

**Comment by xujh0824** [comment]
话说你既然用的这么名字，为什么还会说这样的话？分裂了么

**Comment by TeapoyYinYue** [comment]
水军都水到这里来了么？道行深

**Comment by tangbao** [comment]
感觉是个轮子

**Comment by veryinterestin** [comment]
死妈蛤丝

**Comment by veryinterestin** [comment]
@xujh0824  膜蛤没有立场限制的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
