### ISSUE TITLE
Free GH alternatives: GitLab Pages and Bitbucket Website hosting

### ISSUE THREAD

**Issue by iBug** [sikaozhe1997/Xin-Yue#168]
With `git push` it's only a few lines in the terminal and the whole repo is over at GL and BB. Consider utilizing those sites in case GitHub is blocked or whatever happens.

**Comment by liyishuai** [comment]
In Simple English, this issue requests the repository to be mirrored on GitLab and BitBucket.

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
