### ISSUE TITLE
code页面已经被微信屏蔽掉了

### ISSUE THREAD

**Issue by LucienZhang** [sikaozhe1997/Xin-Yue#169]

**Comment by monstertony** [comment]
没有啊，我刚刚分享

**Comment by LucienZhang** [comment]
Issue 页面可以看到，code 页面被屏蔽了…

**Comment by theJian** [comment]
维稳应急措施可以说是相当完善了。

**Comment by iBug** [comment]
Looks like a temporary workaround: Add random HTTP GET variables after the URL and it's still accessible:

```
https://github.com/sikaozhe1997/Xin-Yue?asdfg=hjkl
```

The downside is you have to do this for every URL you share, so...

**Comment by MasterMiror** [comment]
微信里面已经没法打开朋友给我git的链接了

**Comment by sylxjtu** [comment]
可以加无关query，再用短网址缩短，没人能屏蔽掉

**Comment by bhdsbv** [comment]
好奇微信既然要屏蔽为啥只是屏蔽掉项目主页，是bug还是feature

**Comment by LucienZhang** [comment]
我觉得微信只是匹配了固定的URL吧，并没有更深层次的防火墙策略

**Comment by Hadron67** [comment]
可以先fork再发自己fork的项目地址

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
