### ISSUE TITLE
建议添加所有事件始末，以免事件被埋没

### ISSUE THREAD

**Issue by MrLevo520** [sikaozhe1997/Xin-Yue#173]
已star+fork，保护好自己，加油！
建议添加此事关联始末，不然消息被墙了就无法追根到底了

**Comment by tsai1993** [comment]
https://github.com/Info-cn/Terminus
https://info-cn.github.io/Terminus/tags.html

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
