### ISSUE TITLE
有没有朋友愿意一起发起，高校名兽录？

### ISSUE THREAD

**Issue by zhiyu1999** [sikaozhe1997/Xin-Yue#174]
有没有朋友感兴趣，准备发起一个开源项目，汇总各学校类沈阳的老师信息及事件，让考研的学生，多一个参考信源

**Comment by yifannir** [comment]
有，其实已经有一个叫教授评价网的网站存在了，不过学生去上面的评价不多，也就没产生什么实质性的作用

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。

**Comment by zhiyu1999** [comment]
大家有愿意参与一起协作的吗？@ yifannir 教授评价网 还不太一样 参与度不高。@jaegerstar 白名单 刚看了 [wukongbajie/BUPTNiceMentors: 北邮研究生导师口碑榜](https://github.com/wukongbajie/BUPTNiceMentors) 这个形式，确实不错，可以借鉴。感觉可以收集定点 定向的消息，追对特殊事件 汇总的小道消息~你们觉得怎样？有优化建议吗？
