### ISSUE TITLE
注意别受水军的issue影响

### ISSUE THREAD

**Issue by mbinary** [sikaozhe1997/Xin-Yue#178]
浏览这些issue时， 发现很多水军：最近几天创建账号，  0  repo ，  0 follower ，  1 issue（只在这个repo）   

这些水军发出一些极端的言论，  

在此提醒大家别受他们的言论影响，  别被情绪化

**Comment by tsai1993** [comment]
希望管理员能关闭一些类似的 issue

**Comment by xuedong** [comment]
我觉得更应该注意一些不是水军但带有明显政治立场的人，做这个repo的目的不是被某些人当工具利用的

**Comment by MrLevo520** [comment]
希望增设一些管理员来及时注意导向，千万不要沦落为某些人别有目的的工具！

**Comment by OscarMCY** [comment]
其实到现在差不多该关issue了

**Comment by daniel94104** [comment]
赞成关issue。 不停的提醒极大的影响了只想要关注问题本身并且支持的人群。

**Comment by OscarMCY** [comment]
额........我意思是rep的管理可以关issue功能了........
