### ISSUE TITLE
这个github的地址已经被微信给封了，😔😔

### ISSUE THREAD

**Issue by Leslin** [sikaozhe1997/Xin-Yue#179]
rt

**Comment by iBug** [comment]
Basic censorship circumvention:

https://github点com/sikaozhe1997/Xin-Yue

**Comment by EZElkins** [comment]
细思极恐

**Comment by jiangyangzhou** [comment]
issue 可分享

**Comment by 1994sunshine** [comment]
被封应该是学院组织人多次举报造成的，不知道能不能人工申诉

**Comment by iBug** [comment]
@1994sunshine 直接fork一个不就又是一个新链接了？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
