### ISSUE TITLE
岳昕支持你 memo.cash 区块链微博 勇于发声 不怕删除

### ISSUE THREAD

**Issue by flufy3d** [sikaozhe1997/Xin-Yue#180]
https://memo.cash/post/f143b371da9e7320665d2d1e13f283666d8ac6da48d88e6583ee9af4c3a73f31

**Comment by Ge-yuan-jun** [comment]
成本太大了

**Comment by 6ziv** [comment]
唔…不过写在链里也不是大家都会看的……至于这个网站本身还是可以墙的…………

（做成客户端倒是可以…然而大多数人并不会为了保留别人的信息付出计算力）

（仅从技术上说只是提供防删除的话…其实全网广播比区块链来的划算…………）

我还是人肉扩吧…只在一群程序员待的地方转来转去没用啊…………

**Comment by 6ziv** [comment]
@flufy3d  额…其实我的意思是这样访问还是依赖DNS的啊……而且尽管链没有中心但是网站有啊………GFW管控下的服务器拒绝解析，或者封禁网站…还是很尴尬…

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
