### ISSUE TITLE
能否理性选择发表内容的地方，不要让github因此被墙

### ISSUE THREAD

**Issue by xwarrior** [sikaozhe1997/Xin-Yue#181]
同学，
     作为一名清华的学生，一名程序员，应该你知道在当今环境下，一个没有被墙的github对中国软件行业有多重要，在github发表这类在社会敏感内容，对于真正解决问题毫无帮助，但却会有可能导致github从此远离中国，这带来损失有多大，相信不是一句道歉就可以解决的。

   我也希望这些事情得到传播，让正义得以申张，但是使用github做为武器的方式，图一时之快却对中国软件技术发展带来巨大的伤害，相信是我们都不希望看到的。

   其实到目前为止，微博和微信并没有阻止内容的传播，我们在微博和微信上仍然到处都可以看到和搜索到，何必要在这里发表呢？

  建议尽快删除，还请深思！

**Comment by ycraaron** [comment]
对不起不能。

**Comment by flufy3d** [comment]
@xwarrior 你跟这里喷妹纸有什么用  不如向妹纸推荐 区块链微博 https://memo.cash/post/f143b371da9e7320665d2d1e13f283666d8ac6da48d88e6583ee9af4c3a73f31

**Comment by Statham-stone** [comment]
果然
北大就是北大
清华还是清华

**Comment by cocoyimasa** [comment]
即便没了此github，还会有千千万万github。
防民之口甚于防川。
人活着就要说话，你越不让说我们越要说的人尽皆知。

**Comment by tobyxdd** [comment]
怎么没有帮助了，你说没帮助就没帮助了？

**Comment by kongyanye** [comment]
微信这个repository的链接被封了，微博相关的信息被删了，睁眼说瞎话？

**Comment by xwarrior** [comment]
其实个人翻个墙没什么，一年百把块钱的一个VPS不算贵，但如果中国有1000万人因此需要翻墙，相信成本不低吧，相信很多学生会因此止步墙内，减少接触开源代码的机会。

同时，很多服务器需要翻墙，各类CI/CD系统需要翻墙，原来运行正常的各类依赖github的脚本需要重新考虑，带来的各种成本和烦麻还是挺大的。

@flufy3d  在 btc/eth的blockchain上公开信息的做法不错，赞一个。

**Comment by MisakaMikoto-35c5** [comment]
我认为作为科研人员有收集境外资料网站的手段是必要的。如果中国政府屏蔽这个网站，也不会对软件行业有多大损失，只可能造成两种情况：1. 使用国内类似服务，2. 使用其它手段访问 GitHub。
众所周知，中国大陆的互联网言论管控非常严格，稍有不慎人身安全就会出问题。而现在，微博微信已经开始清理这类言论。

**Comment by shsjshentao** [comment]
如果被墙，那以后软件业的衰败就是当局的责任

**Comment by Time02** [comment]
新闻：某某拿刀杀人了！！ 楼主：赶紧把禁止卖刀

**Comment by frankwei98** [comment]
社会敏感内容？？？对于真正解决问题毫无帮助？？？请问你和你这个该死的政府对于真正解决问题有任何帮助吗？？？？？？？？？？？？？？？？？？？

什么时候清北学生都这么苟且了？？？

已Block

**Comment by numbcoder** [comment]
黑白不分，GitHub  被封你居然找自身的原因，你简直是清华的耻辱

**Comment by wql7013** [comment]
也好，让不会墙的程序员没法再做程序员，让没有求真精神的丧失竞争力，这样或许中国梦就能实现了。

**Comment by xwarrior** [comment]
从各自角度出发，各位讲的都没有错，看到年轻人们还有这样的血性，由衷感到高兴。

这世上的事情，上了年纪的人看得多了，也就麻木了，所以早已不问世事，只想埋头写写代码。

各位加油！

**Comment by huangzonghao** [comment]
不是， 楼上的同学们怎么都喷起清华来了？这个大哥是说这个repo的主人是清华的， 没说他自己是清华的吧。。。。清华真的是锅从天上来啊。。。

**Comment by Ge-yuan-jun** [comment]
@huangzonghao 他折行了，很容易被带节奏。你不提醒的话，我都没办法发现。。。

**Comment by lianliu** [comment]
`一个没有被墙的github对中国软件行业有多重要`

这样的行业倒了，邪恶帝国才有完蛋的可能

**Comment by Statham-stone** [comment]
@huangzonghao 对不起，理解错了，向您道歉

**Comment by TommyJerryMairo** [comment]
迫切的感觉到科普翻墙姿势的重要性……

**Comment by Woodu** [comment]
已Block。。

**Comment by stormltf** [comment]
火前留名

**Comment by lzhaoyang** [comment]
自我审查的很好，很棒，很强。不行

**Comment by turnureyes** [comment]
为什么关闭上条回复评论，上了年纪和麻木没有直接关系，真正有血性有灵魂的人更不会如此，好一个不问世事，在中国埋头做鸵鸟挺好，希望您毛都被烧光了的时候，还说的出我只想码码代码！
真正不问世事，你完全可以不来此发言，精致的利己主义就是您这位！千万别助纣为虐！
另外，也不知道您的所学所用是否用在改变社会改变世界往好的方向上发展了。。。

**Comment by fanwu4361** [comment]
墙了好，除了中兴，让华为、曙光都死了，墙也就倒了。

**Comment by yangkang5303** [comment]
GitHub的开放自由智慧，是独裁的掘墓人。

**Comment by ikariwing** [comment]
快趴在地上，不然胖虎要來了

「在戰爭與屈辱面前，你選擇了屈辱」

They chose dishonor.

**Comment by syutran** [comment]
你干脆替党国开发个屏蔽github的系统不就得了~

**Comment by grasscase** [comment]
就是，被墙了不知道梯子吗？既然害怕强，为什么不拆强？

**Comment by MobileStarChart** [comment]
国内这些爱写狗屁文章的臭老九们，你们难道不明白你们所做的一切都是徒劳吗？你们难道没学过历史吗？你们难道不清楚一个集权统治的崩溃都是从统治阶级的内部开始的吗？
就凭你们几篇狗屎文章就想呼风唤雨，未免也太幼稚了吧。臭老九，呸！中国人生来就注定应该被无情统治，你们还是省省力气，想办法移民跑路吧！

**Comment by ZxMYS** [comment]
清华的学生就这水平

**Comment by peter12138X** [comment]
恶臭的犬儒主义者，begging for food
以斗争求团结则团结存，以退让求团结则团结亡
总想着一点点自由都是别人施舍来的，永远都是奴隶

**Comment by IQ32** [comment]
这不是“这样下去，大家都没得玩”的翻版嘛，北京清华的 天灵盖学 看起来也教得不错。

**Comment by ayaservice** [comment]
清华是个什么大学呢？

**Comment by Colin6618** [comment]
这个 Issue 内容让我想起了鲁迅的一篇散文：

-----

《聪明人和傻子和奴才》


奴才总不过是寻人诉苦。只要这样，也只能这样。有一日，他遇到一个聪明人。

“先生！”他悲哀地说，眼泪联成一线，就从眼角上直流下来。“你知道的。我所过的简直不是人的生活。吃的是一天未必有一餐，这一餐又不过是高粱皮，连猪狗都不要吃的，尚且只有一小碗……”

“这实在令人同情。”聪明人也惨然说。

“可不是么！”他高兴了。“可是做工是昼夜无休息：清早担水晚烧饭，上午跑街夜磨面，晴洗衣裳雨张伞，冬烧汽炉夏打扇。半夜要煨银耳，侍候主人耍钱；头钱从来没分，有时还挨皮鞭……。”

“唉唉……”聪明人叹息着，眼圈有些发红，似乎要下泪。

“先生！我这样是敷衍不下去的。我总得另外想法子。可是什么法子呢？……”

“我想，你总会好起来……”

“是么？但愿如此。可是我对先生诉了冤苦，又得你的同情和慰安，已经舒坦得不少了。可见天理没有灭绝……”

但是，不几日，他又不平起来了，仍然寻人去诉苦。

“先生！”他流着眼泪说，“你知道的。我住的简直比猪窝还不如。主人并不将我当人；他对他的叭儿狗还要好到几万倍……”

“混帐！”那人大叫起来，使他吃惊了。那人是一个傻子。

“先生，我住的只是一间破小屋，又湿，又阴，满是臭虫，睡下去就咬得真可以。秽气冲着鼻子，四面又没有一个窗子……”

“你不会要你的主人开一个窗的么？”

“这怎么行？……”

“那么，你带我去看去！”

傻子跟奴才到他屋外，动手就砸那泥墙。

“先生！你干什么？”他大惊地说。

“我给你打开一个窗洞来。”

“这不行！主人要骂的！”

“管他呢！”他仍然砸。

“人来呀！强盗在毁咱们的屋子了！快来呀！迟一点可要打出窟窿来了！……”他哭嚷着，在地上团团地打滚。

一群奴才都出来，将傻子赶走。

听到了喊声，慢慢地最后出来的是主人。

“有强盗要来毁咱们的屋子，我首先叫喊起来，大家一同把他赶走了。”他恭敬而得胜地说。

“你不错。”主人这样夸奖他。

这一天就来了许多慰问的人，聪明人也在内。

“先生。这回因为我有功，主人夸奖了我了。你先前说我总会好起来，实在是有先见之明……。”他大有希望似的高兴地说。

“可不是么……”聪明人也代为高兴似的回答他。


 文丨鲁迅

**Comment by ywachao** [comment]
北大学生在为他人的权利挺身而出而遭到校方打压，清华学生指责他人把抗争信发到Github上。当然这两边都是个案，但我建议抱怨Github被“误用”的人学学区块链的人开明大度，别只关心自己不翻墙抄袭的那点小方便，这点小方便太恶心了。

**Comment by cobola** [comment]
自己发声就可以了 何必扯上清华呢 
无缘无故背这么大一个锅 找谁说理去！

**Comment by wqmmy** [comment]
清华怎么会有这样的学生，是来黑清华的吧？😄

**Comment by TobySkarting** [comment]
台灣是獨立國家
從來都不是中國的省或一部份

**Comment by Mason-Xu** [comment]
@TobySkarting  I am sorry that Taiwan is really a province. The constitution of the Republic of China stated that Taiwan Province belongs to the Republic of China....Taiwan is never a country....

**Comment by Statham-stone** [comment]
@TobySkarting 台湾这么吊，怎么不去和美国法国英国德国日本建交呢[抠鼻][抠鼻]

**Comment by BirkhoffLee** [comment]
看到 @Mason-Xu 講的這段廢話就代表這是個被共產黨歷史教育教壞的可憐人。

**Comment by billy3321** [comment]
衝著這個issue，立馬來fork一份。

**Comment by AnyWAT** [comment]
🤣網上熱傳4月24日晚8點，武漢一名副教授跑到女生廁所偷窺拍照，被女生發現後將廁所門鎖住。這名副教授奮不顧身從二樓窗戶跳下逃脫，校方目前封鎖消息，告誡學生不要外傳……天朝叫獸不學無術，禍害學生，學校要封鎖就幚它火。 pic.twitter.com/EVrdD0IiGz
