### ISSUE TITLE
想攻击本项目的人，先看一眼本issue再做决定

### ISSUE THREAD

**Issue by the0demiurge** [sikaozhe1997/Xin-Yue#182]
不好的事情现在没有发生在你和的家人身上，不代表未来不会。对本项目进行攻击的行为，实际上是在攻击你们自己。

“起初他们迫害共产党员，我没有说话，因为我不是马克思的信徒。”
“后来他们迫害犹太人，我没有说话，因为我是日耳曼人。”
“再后来他们迫害天主教徒，我没有说话，因为我是新教牧师。”
“最后他们迫害到我头上，我环顾四周，却再也没有人能为我说话。”

----马丁·尼莫拉 《我没有说话》

**Comment by the0demiurge** [comment]
你们希望中国人能用上GitHub，做了什么努力了呢？
而我为了中国人未来还能用得上GitHub，做了开源项目
https://github.com/the0demiurge/ShadowSocksShare-OpenShift

**Comment by sylxjtu** [comment]
@meteorlxy xjtu的，前段时间我校也出现了类似事件，所以对这方面比较关心

**Comment by meteorlxy** [comment]
@sylxjtu 所以说是校友啊哈哈。昨天看这个仓库还没什么人，今天一看这么多人了。咱们学校那破事儿到头来也是被压得死死的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
