### ISSUE TITLE
贴一篇杂文，希望要求删除的人看完了能打消自己的念头，鲁迅先生《聪明人傻子和奴才》，希望大家不要做文中的“聪明人”

### ISSUE THREAD

**Issue by TracebackS** [sikaozhe1997/Xin-Yue#184]
**聪明人和傻子和奴才**
奴才总不过是寻人诉苦。只要这样，也只能这样。有一日，他遇到一个聪明人。
“先生！”他悲哀地说，眼泪联成一线，就从眼角上直流下来。“你知道的。我所过的简直不是人的生活。吃的是一天未必有一餐，这一餐又不过是高粱皮，连猪狗都不要吃的，尚且只有一小碗……”
“这实在令人同情。”聪明人也惨然说。
“可不是么！”他高兴了。“可是做工是昼夜无休息的：清早担水晚烧饭，上午跑街夜磨面，晴洗衣裳雨张伞，冬烧汽炉夏打扇。半夜要煨银耳，侍候主人耍钱；头钱从来没分，有时还挨皮鞭……。”
“唉唉……”聪明人叹息着，眼圈有些发红，似乎要下泪。
“先生！我这样是敷衍不下去的。我总得另外想法子。可是什么法子呢？……”
“我想，你总会好起来……”
“是么？但愿如此。可是我对先生诉了冤苦，又得你的同情和慰安，已经舒坦得不少了。可见天理没有灭绝……”
但是，不几日，他又不平起来了，仍然寻人去诉苦。
“先生！”他流着眼泪说，“你知道的。我住的简直比猪窠还不如。主人并不将我当人；他对他的叭儿狗还要好到几万倍……”
“混帐！”那人大叫起来，使他吃惊了。那人是一个傻子。
“先生，我住的只是一间破小屋，又湿，又阴，满是臭虫，睡下去就咬得真可以。秽气冲着鼻子，四面又没有一个窗……。”
“你不会要你的主人开一个窗的么？”
“这怎么行？……”
“那么，你带我去看去！”
傻子跟奴才到他屋外，动手就砸那泥墙。
“先生！你干什么？”他大惊地说。
“我给你打开一个窗洞来。”
“这不行！主人要骂的！”
“管他呢！”他仍然砸。
“人来呀！强盗在毁咱们的屋子了！快来呀！迟一点可要打出窟窿来了！……”他哭嚷着，在地上团团地打滚。
一群奴才都出来了，将傻子赶走。
听到了喊声，慢慢地最后出来的是主人。
“有强盗要来毁咱们的屋子，我首先叫喊起来，大家一同把他赶走了。”他恭敬而得胜地说。
“你不错。”主人这样夸奖他。
这一天就来了许多慰问的人，聪明人也在内。
“先生。这回因为我有功，主人夸奖了我了。你先前说我总会好起来，实在是有先见之明……。”他大有希望似的高兴地说。
“可不是么……”聪明人也代为高兴似的回答他。

**Comment by cunzi** [comment]
你们在不合理的网站发声，造成了我们程序员群体将来也不能使用这争取来的，来之不易的网络资源。
你们才是可耻的人。滚出GitHub！！！！

**Comment by TracebackS** [comment]
@cunzi “人来呀！强盗在毁咱们的屋子了！快来呀！迟一点可要打出窟窿来了！……”他哭嚷着，在地上团团地打滚。

**Comment by jiangyangzhou** [comment]
程序员不会翻墙吗

**Comment by fancoo** [comment]
@cunzi 连被墙掉掉的github都不会上就别自称程序员了，我真的不屑与你为伍。

**Comment by MrLevo520** [comment]
@cunzi 请不要代表我们程序员谢谢，您在github上有何贡献，请告知，空白的更新页面，如果不是看你两年前注册，我还以为又是个小号。github上我们分享和交流信息，知道它的宝贵，所以我们会守护它，而你，又在做些什么？

**Comment by JQ1996** [comment]
当下的中国，红色势力渗透到教育的每一个边边角角，洗脑中国的社会，中国的学生，tg的史书已经污秽不堪了，tg就是在搞愚民政策，建高墙，辱民智，tg的媒体发的都是什么玩意儿？真的希望大家擦亮眼睛，独立思考，明辨是非曲直。还记得当年屏蔽Github的事件吗？哪一个正常的政府会做这样的事情？tg开倒车不是一天两天了。希望大家多了解关注事件的真相，捍卫我们最最基本的权利。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
