### ISSUE TITLE
究竟是什么事情？

### ISSUE THREAD

**Issue by woysl81** [sikaozhe1997/Xin-Yue#186]
你们能把事情将明白吗？自己也藏着掖着。

**Comment by Mrsususu** [comment]
文后附上的被删链接里讲得很清楚了。

**Comment by chungjin** [comment]
https://info-cn.github.io/Terminus/tags.html

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
