### ISSUE TITLE
说实话Github做出来的初衷和用途肯定不是用来干这个吧...

### ISSUE THREAD

**Issue by jasonHsi** [sikaozhe1997/Xin-Yue#187]
建个小号 怕被骂

Github毕竟是个技术网站，想让这件事情付诸真相的想法我觉得挺好，但是在这个纯技术分享平台上...这不是它的作用啊 又不是媒体...以后要是每出一个这种事儿就出这么一个几k star的项目...高star里面一堆这种项目各位看着不嫌着烦么？

建议做个集合(而且已经有了）而不是在这里激扬愤慨

还有就是为什么只要有不同意见或者想让删掉就一堆人恶语相向玩命说别人犬儒 没骨气 别人也没什么坏心眼...不是所有人都想“geming”的各位...别人有可能人到30+ 背着房贷还养孩子呢...

打到这里我突然觉得我在浪费时间 但是也不删了

**Comment by PeterYJC** [comment]
既然你都说了 你是小号，那人家为什么来这里你知道吗？
star 确实没必要

**Comment by Etamin** [comment]
If github been blocked,there was no innocent programmer in china.

**Comment by bohrasd** [comment]
非常烦很多不读github 条款，凭着一厢情愿的想法来这里bb github 是用来干什么的。
这种智障 Issue 还有好几个，排在前面，各位不烦么

**Comment by wql7013** [comment]
如果大家都没有geek精神、hacker精神、开源精神，上GitHub都是因为这里方便获取别人的劳动成果，那还是把GitHub封了吧，太不公平了！

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
