### ISSUE TITLE
Seems like GitHub will be beaten by China's censorship again very soon

### ISSUE THREAD

**Issue by BYJRK** [sikaozhe1997/Xin-Yue#189]

**Comment by xujh0824** [comment]
just try

**Comment by iBug** [comment]
Seems like you've surrendered to China's censorship already

**Comment by BYJRK** [comment]
Interesting. I was just stating my concern that GitHub might not be accessed by some programmers, especially who does not have a decent "ladder", in mainland China, which could be a terrible loss for them. Now you all just think I'm a loser who bow down to the government.

**Comment by YifanWang1021** [comment]
sad... but the GFW always blocks github
