### ISSUE TITLE
The fact comfirm that pushing to github is the best choice

### ISSUE THREAD

**Issue by DayChan** [sikaozhe1997/Xin-Yue#191]
截至目前已经有1400个star以及7个Pull request

我总结了以下几点 

- Github可以方便地更新以及Pull request

- Github作为一个程序员网站，官方在封禁前一定会三思对科技发展带来的影响。即使封禁也只会封禁单个仓库（之前有过这种例子）。所以在这里可以更好地维持国内能看到的状态，也不用担心整个github被封

- Github并非不能用来讨论政治，我就见过两个仓库是外国人监察在地政府的政府，以及一个发起示威有效流程的仓库（我记得有五千多个star但是忘记名字了）

- Github没有将这个仓库统计到Trending中

个人认为，如果监察公权力会导致网站被封，那么错误不是出在监察公权力行为，而是公权力封禁网站这个行为。应该思考的是，一个监察公权力就可能导致网站被封，始终难以监察政府的地区，是否真的正常。

**Comment by nirvanazx** [comment]
https://github.com/github/gov-takedowns

**Comment by xujh0824** [comment]
谁让墙内根本没有这种监察的渠道呢……

**Comment by LinkWoong** [comment]
no404的上Trending了

**Comment by Chenduoru** [comment]
@nirvanazx This is why when I view some repositories I would be informed " Unavailable in your location" if I use Chinese IP. But yes, it is still not means Github does not allow people to discuss politics. Also it is funny that only Russia and China are mentioned in that repository.

**Comment by wql7013** [comment]
这也正是geek精神、hacker精神、开源精神，正是GitHub上大多数人所追求的。

**Comment by phodal** [comment]
只是 push 文章到 GitHub 上的问题不大，只是我们担心 GitHub 未来会成为一个讨论政治的地方。如，这个项目的 issues 下，开始出现一些和本 repo 无关的政治话题。

极客，以技术带领潮流，开源，以分享、创造为乐。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
