### ISSUE TITLE
微信已经无法直接打开这个Github项目

### ISSUE THREAD

**Issue by kexiaoderenren** [sikaozhe1997/Xin-Yue#195]
刚刚分享到微信，发现微信已经无法直接打开这个Github项目，加油！

**Comment by wydwww** [comment]
[微信 = GFW](https://blog.yitianshijie.net/2018/02/02/wechat-equals-gfw/)

**Comment by Chenduoru** [comment]
分享README.ME页面就可以了

**Comment by dqwyy** [comment]
@wydwww 可能今后会出现
> `￥微口令￥4jdF7ejwD32` 复制后打开微信即可打开链接

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
