### ISSUE TITLE
支持一下

### ISSUE THREAD

**Issue by pzhu1996** [sikaozhe1997/Xin-Yue#2]
加油！从未见过如此厚颜无耻的学工老师

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。

**Comment by AnyWAT** [comment]
🤣網上熱傳4月24日晚8點，武漢一名副教授跑到女生廁所偷窺拍照，被女生發現後將廁所門鎖住。這名副教授奮不顧身從二樓窗戶跳下逃脫，校方目前封鎖消息，告誡學生不要外傳……天朝叫獸不學無術，禍害學生，學校要封鎖就幚它火。 pic.twitter.com/EVrdD0IiGz
