### ISSUE TITLE
#我有预感github被墙之日不远了

### ISSUE THREAD

**Issue by CodeinSimon** [sikaozhe1997/Xin-Yue#20]

**Comment by xpf960930** [comment]
我就是翻墙才上来的，不挂VPN根本打不开。。。

**Comment by sentryjun** [comment]
本来就是被墙的啊

**Comment by XuandongZhao** [comment]
GitHub快凉了…有点心痛

**Comment by lutein** [comment]
GitHub没有被墙好吗……只是以前墙过

**Comment by JiachuanXu** [comment]
+1， 这次谈论北大也就罢了，下次要是跨雷池分分钟把github墙掉

**Comment by liangxj8** [comment]
上次被墙是因为有梯子，后来因为抗议所以解封了。不挂`VPN`打不开的老哥可能要反思一下`ISP`？

**Comment by zzh428** [comment]
直接闭关锁国

**Comment by dingelish** [comment]
[直接封禁github的原因之一](https://github.com/programthink/zhao)

**Comment by yywing** [comment]
程序员竟成最大输家

**Comment by monkeylord** [comment]
放心吧，github是跟互联网产业利益捆绑的。墙的主人也不会动自己的经济基础的。

**Comment by adolli** [comment]
@monkeylord 国内知道github的人太少了

**Comment by monkeylord** [comment]
@adoli 不过程序员基本都知道。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
