### ISSUE TITLE
还愣着干嘛，赶紧fork保护，然后star\watch走一波！！！

### ISSUE THREAD

**Issue by LinXueyuanStdio** [sikaozhe1997/Xin-Yue#207]
听说已经有人在区块链上发了。github也是分布式账本，赶紧fork备份

**Comment by pklfz** [comment]
https://etherscan.io/tx/0x2d6a7b0f6adeff38423d4c62cd8b6ccb708ddad85da5d3d06756ad4d8a04a6a2
硬核区块链应用场景一刚

**Comment by tsai1993** [comment]
还有这个项目
https://github.com/Info-cn/Terminus/tree/master/_posts
