### ISSUE TITLE
到底是什么人能量这么大？

### ISSUE THREAD

**Issue by hyspace** [sikaozhe1997/Xin-Yue#210]
一件发生在98年的事，20年了，不过是申请信息公开，为什么全网封锁？如果触动了一些人的利益，这“一些人”是谁？为什么有这么大的能量？

**Comment by SangunU** [comment]
要过120大寿了，不想被这些事污了名声
不过现在来看适得其反了
随便猜的

**Comment by the0demiurge** [comment]
因为稳定性与政绩相连，详细请查Wikipedia 维稳

**Comment by hyspace** [comment]
我觉得有个人说的对，在这里讨论解决不了任何问题，关闭了。但是我会默默支持这个repo的。

**Comment by the0demiurge** [comment]
舆论是有巨大力量的，这就是为什么墙内拼命封杀言论
