### ISSUE TITLE
观Issue有感 - 勇者愤怒，抽刃向更强者；怯者愤怒，却抽刃向更弱者。

### ISSUE THREAD

**Issue by thuxx** [sikaozhe1997/Xin-Yue#215]
两个奴隶A,B同时被主人奴役，A被压迫得实在受不了，发出微小的抗议。
B却大骂之：“没有脑子的东西，不知道这样他会压迫得更狠吗？主人现在赏赐的自由还不够多吗？现在的生活都会被你毁了！”
可惜B忘了，他们应该是主人的主人。

**Comment by tonyxyl** [comment]
真会道德绑架。我看多数觉得发在github不妥的人，其观点也不是说不该发声，而是不该在github上，徒然给github带来伤害。你可以发到twitter、facebook、youtube都行，反正这些都被墙了，想看的人定能看到。github被墙了，伤害的是那些没有翻墙条件却有需求上的人。

**Comment by Hasaki1997** [comment]
我想请问楼上,用GitHub的人有[没有翻墙条件却有需求上的人。]吗?程序员还有不会翻墙的?

**Comment by thuxx** [comment]
# @tonyxyl 您好。
1. 首先墙不墙不能作为发不发在GitHub上的理由，起码不能是首要理由，如果您觉得我们生而应当遵守“墙”这个设定，那就当我没说；
2. 其次您说的“那些没有翻墙条件却有需求上的人”是哪些？是不会？还是不知道？还是不敢？他们有哪些需求是必须上GitHub才能满足的？
3. 发在推特脸书油管确实都可以，但这为什么是不能发在GitHub上的理由？
4. 我非常了解GitHub对于国内程序员的重要程度，可是这件事能发在GitHub上引起如此大的共鸣恰好能体现GitHub作用已经远超过代码仓库，这难道不是件好事吗?
5. 如果是这件事的性质让您觉得不妥，那么GitHub上还有非常多的值得您关注的反XX仓库，内容全部是百分百会被墙的，然而还是很好地活到现在了。

**Comment by channel960608** [comment]
说程序员还有不会翻墙，去年大会后ss就开始被针对了，之后翻墙手段更是越来越少，稳定的梯子也基本上没有了，保不齐哪一天vps都不能用，长城直接白名单，到时候就真的是局域网了

**Comment by thuxx** [comment]
@whiskyboy 如果因为害怕墙而不发 不就是对压迫的妥协？
