### ISSUE TITLE
能不能不要发在Github上？

### ISSUE THREAD

**Issue by gaoxiaosong** [sikaozhe1997/Xin-Yue#223]
原则上支持这种备份行为，但是希望不要误伤，Github毕竟是一个交流代码的地方。
看Issue有人说程序员还有不会翻墙的么，现实是有，而且现在封的越来越厉害了，找个好用的不容易。万一没找到，Github再被封了，怎么干活。。
Facebook、Twitter这种网站都可以发啊，而且还是社交网站。
现在这么做，只会把程序员里面中立的人群逼到对立面去。。

**Comment by zhudelong** [comment]
如果楼主离开了GitHub不能干话，建议还是回家卖红薯吧

**Comment by pi11n0tgates** [comment]
首先，Twitter 和 Facebook 上不是没有关于这件事情的描述；
其次，在 Twitter 或者 Facebook 上如何记录存档，如何保存已被删除的页面镜像？

**Comment by senhui-guo** [comment]
github被墙了就干不了活了？Google scholar也被墙了是不是就做不了科研了？你这智商还是去工地搬砖吧

**Comment by yun-long** [comment]
所以说被压迫我们就应该选择懦弱了，害怕被墙我们就选择不要发声了吗？

**Comment by superbogy** [comment]
支持，首先这种事不应该放在 github 上，什么鸡毛蒜皮家国仇恨都般上来，这是要把 github 当做新闻娱乐平台。

**Comment by gaoxiaosong** [comment]
@pi11n0tgates 是我说的不严谨，fb和twitter是交流讨论的地方，备份的话wikipedia上已经有了的，刚才去看了下，非常的全。
@Richardplus 后两个速度很慢，也可能是我网速不好，码云还是国内的，临时替代有可能，长期替代目前看来不太现实，或许以后有希望吧。

**Comment by gaoxiaosong** [comment]
人身攻击的懒得回，说不会翻墙的也懒得回，你自己会不代表所有人都会，事实上不会的是大多数，码农不是只有那些大厂的，在北上广待久了会忽略其他地方我能理解，有空多出去看看，祖国很大。
@yun-long 不是不发声，而是选择该发声的地方，github跟这事情八竿子打不着啊。。还有，见过太多热点新闻一个月之后就沉没的不见踪影，无人关注。。
@superbogy 已经是了，之前杭州买房攻略那个repo好像是一周Trending第一名。。

**Comment by yun-long** [comment]
你确定github不可以，做个网页就行了吧：
https://anonymous-xinyue.github.io/
