### ISSUE TITLE
请不要在github上谈论政治等有关话题

### ISSUE THREAD

**Issue by Nandayang** [sikaozhe1997/Xin-Yue#224]
github只是github，有事请转脸书油管推特。个人拙见，勿喷。

**Comment by kyojujor** [comment]
@kyojujor 另外求求键盘侠们去上访，去北京支援，而不是在键盘上输出，谢谢。就事论事，这里只交流代码。

那我是不是可以说,求求你们去找GITHUB官方把我们封了,而不是单独开个issue来怼?

**Comment by Nandayang** [comment]
随你怎么讲，你开心就好

**Comment by CeresCheng** [comment]
你代表Github？你也配？

**Comment by hafei** [comment]
怎么closed了，继续讨论
