### ISSUE TITLE
自由是文明之源，商业才是最大的公益

### ISSUE THREAD

**Issue by lbli** [sikaozhe1997/Xin-Yue#225]
自由是文明之源，所有对自由的打压，只会带来更多的社会乱象与人性扭曲，这个国家缺少的哪是芯片啊，是自由，学术自由和思想自由，缺少的是对私有财产的保护和个体权利的尊重。在这片古老的土地上，到处都有青春的力量

**Comment by lixiaosi33** [comment]
唉！好多人都忘了，宪法一章二条，国家一切权力属于人民.
结果......被逼到github这个角落里才能发言......

**Comment by killTheHostage** [comment]
@lixiaosi33 那天宪法给你把这句话去掉（滑稽
