### ISSUE TITLE
散了吧：如果不想让 GitHub 被墙，程序员可以尝试停止开相关的 issues ？

### ISSUE THREAD

**Issue by phodal** [sikaozhe1997/Xin-Yue#230]
正如我们现在看到的那样，在这个 repo 有越来越多的新注册的 GitHub ID，他们的意图并不能确认。但是，我觉得我们所能做的事情是停止相关的 issues：

1. 我们阻止不了这些键盘侠；
2. 减少关注也就意味着减少风险；

在这个 issue 里回复、开贴，并不能改变什么、解决什么问题——无非就是有一个可以发泄的地方。对于他们而言，**这个地方被封了，还可以有别的地方，对于我们则不是**。

可问题还是存在那里，需要做的不是在线上逞能。

**Comment by wallpusher18** [comment]
You may want to read this https://github.com/cirosantilli/china-dictatorship/blob/3f3afbec19ee8c35d5d6020a2662b269e3859f06/FAQ.md#why-are-you-attacking-websites-with-censored-keywords

**Comment by samrayleung** [comment]
摘自鲁迅先生<随感录四十一>
>愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。
能做事的做事，能发声的发声。
有一分热，发一分光。
就令萤火一般，也可以在黑暗里发一点光。
——不必等候炬火
比后如竟没有炬火，我便是唯一的光。
