### ISSUE TITLE
Related issue and previous effort

### ISSUE THREAD

**Issue by wallpusher18** [sikaozhe1997/Xin-Yue#237]
Plz checkout this repo and its FAQ: https://github.com/cirosantilli/china-dictatorship
and this guy's profile at SO: https://stackoverflow.com/users/895245/ciro-santilli-%E5%8C%85%E5%AD%90%E9%9C%B2%E5%AE%AA-%E5%85%AD%E5%9B%9B%E4%BA%8B%E4%BB%B6-%E6%B3%95%E8%BD%AE%E5%8A%9F

**Comment by hsfzxjy** [comment]
不要议论无关话题，谢谢
