### ISSUE TITLE
已经有人在这里带节奏了，你们能分清是非吗？

### ISSUE THREAD

**Issue by LinXueyuanStdio** [sikaozhe1997/Xin-Yue#239]
有心人开始把明显沙雕的反动理论链接贴这里了，就不指明是谁了。
反正一切和岳昕事件无关的都是在带节奏。
请大家不要被阴险的反动势力坑了。

**Comment by lengyanyu258** [comment]
去看了一下他的SO主页，里面竟然有F...L...G...……
一看就是SB……

**Comment by Tao-Quixote** [comment]
@lengyanyu258 怎么开始骂人了

**Comment by lengyanyu258** [comment]
@Tao-Quixote 看到楼主用“沙雕”这个词，于是我也开放了自己的“脏话字典”。不过攻击到了人身上确实是我的不对~应该在心里悄悄地说的。

**Comment by LinXueyuanStdio** [comment]
emm...带节奏就带节奏呗，只要是言论就应该被允许，是我欠考虑，只在主观的角度看待了

**Comment by LinXueyuanStdio** [comment]
虽然现在浏览评论的大多是中国人，但不要忘了，github不是中国的

**Comment by WeiJiaoWuMaoDang** [comment]
@LinXueyuanStdio 怎么感觉你就是上帝，您说谁是带节奏谁就是带节奏，您说谁是阴险的反动势力谁就是阴险的反动势力，大家都不用带脑子，跟着您走准没错。真理不是越辩越明的，您说的话就是真理，不需要争辩的。

**Comment by Tao-Quixote** [comment]
我们的国情就是：有言论的自由，但是不能自由言论

**Comment by Tao-Quixote** [comment]
这个评论，这的是扎心了各位老铁：

如何看待厦大田佳良因在网络发表不当言论，处理结果仅为留校留党察看？ - 知乎
https://www.zhihu.com/question/274350511/answer/374717018

**Comment by LinXueyuanStdio** [comment]
@WeiJiaoWuMaoDang ?????
我有指明谁带节奏谁阴险的反动势力了吗？
我有说大家都不带脑子了吗？
我有说跟着我走了吗？
我有说我的话是真理了吗？
好奇怪。
我就提醒了一下要大家要明辨是非，然后就被您吊了。莫名其妙。
github是世界性的平台，居心叵测的人多的是，看到国内发生这种事，想火上浇油、雪上加霜、落井下石的难道不存在？
专门开个小号来怼我有意思？
我都没说谁反动势力您就脑补了一大堆来怼我，怕是

**Comment by Freedom5400** [comment]
为什么都是反动势力背锅，真的想笑
