### ISSUE TITLE
建议北大废校,并入清华

### ISSUE THREAD

**Issue by ghost** [sikaozhe1997/Xin-Yue#25]

**Comment by initial-h** [comment]
清华也有这些问题，只是北大的人更愿意说出来

**Comment by JiachuanXu** [comment]
反正我不信清华能好到哪去，只不过清华学生更听话

**Comment by zzh428** [comment]
如果发生了同样的事，我没有信心说清华会表现得更好

**Comment by evzlk** [comment]
那还说个几把,学生开除,老师解聘,设备卖废品,岂不美哉

**Comment by Seris02200059** [comment]
清华封锁能力比隔壁强吧应该

**Comment by tomlelouch** [comment]
那要提一个pull request

**Comment by jordanpui** [comment]
恭喜我交荣升top2

**Comment by Songtao-Liu** [comment]
bad end

**Comment by gulus** [comment]
这里可以发表自由言论吗

**Comment by Soranii** [comment]
于是，9名北大学生为了拯救学校，站了出来，成为偶像。

**Comment by evzlk** [comment]
@Soranii 9名辅导员岂不更妙

**Comment by zhaobenx** [comment]
[**@jordanpui**](https://github.com/jordanpui) commented on [2018年4月23日 GMT+8 下午4:49](https://github.com/sikaozhe1997/Xin-Yue/issues/25#issuecomment-383501812 "2018-04-23T08:49:58Z - Replied by Github Reply Comments"):
> 恭喜我交荣升top2

明明是我蛋升top2好伐（滑稽）

**Comment by lambda7xx** [comment]
其实也要按照基本法来

**Comment by Statham-stone** [comment]
恭喜贵交贵旦荣升top3
恭喜贵浙荣升top4

**Comment by peer2peer** [comment]
应该拆分北大，相关院系及师资充实那些师资力量薄弱、长期投入不足的全国重点高校。什么985、双一流，无非是全国人民资源的堆砌，真正的一流，应该来自于生态自身的演绎和进化。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
