### ISSUE TITLE
愿中国青年都摆脱冷气

### ISSUE THREAD

**Issue by Zheaoli** [sikaozhe1997/Xin-Yue#253]
愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般，也可以在黑暗里发一点光，不必等候炬火。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
