### ISSUE TITLE
全篇看下来没发现北大哪件事做得不对啊？

### ISSUE THREAD

**Issue by aochulai** [sikaozhe1997/Xin-Yue#257]
反正我身为一个打酱油的围观人员是不太清楚你们GC的点在哪，哈哈。
另外说下，这样使用Github，就好像有人在足球论坛里出现个老司机发车，然后管理员又不删除，最后被封了一样，其他讨论足球的人只会感觉哔了狗了。当然了，我的态度绝对是哔那个发车的人还有管理员，而不会说什么“但凡有一个可以发车的网站，还会有人把车发在足球论坛吗？”这种毫无逻辑的言论。

**Comment by HallWoodZhang** [comment]
请开始你的表演

**Comment by xiekeyi98** [comment]
以为点进来会有论证。

**Comment by hqztrue** [comment]
No response.

**Comment by Tao-Quixote** [comment]
Mmmmm....
水军开始洗地了？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
