### ISSUE TITLE
岳同学真的很厉害了，作为同龄人，我忠心的感到敬佩

### ISSUE THREAD

**Issue by UsrnameX** [sikaozhe1997/Xin-Yue#259]
所以ballball Pku 珍惜这样的学生吧，作为中国高校的灯台，您配吗

**Comment by zzuyoung** [comment]
可是他一个人的力量太小了，我们又不知道该怎么帮助他

**Comment by wkmcyz** [comment]
@UsrnameX bbuh

**Comment by aminic** [comment]
人杰

**Comment by xyzbase** [comment]
自我审视里有句话：“这里的「原罪」不是来自神的国，它恰恰来自人的国；我背负的是整个社会结构不公的原罪”

这觉悟不是一般人有的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
