### ISSUE TITLE
溜了溜了 太可怕

### ISSUE THREAD

**Issue by massacreformash** [sikaozhe1997/Xin-Yue#262]
溜了溜了 啧啧啧

**Comment by Tao-Quixote** [comment]
@massacreformash 如果每个人、每个行业都像你这样只为自己考虑，那么可以预见，不久的将来，你即使挂 ss 也不能上某些网站；如果每个人都在不公平的事情面前站出来，争取自己应得的权利，尽到自己应尽的义务，那么将来，说不定我们访问什么网站都不需要使用 ss。

兄弟，什么都不做，只想维护自己的利益，那么你永远都不可能真正地维护自己的利益。个人表示非常不喜欢事不关己高高挂起的态度。
