### ISSUE TITLE
同情且支持 但这里是技术社区

### ISSUE THREAD

**Issue by Hivol** [sikaozhe1997/Xin-Yue#263]
GitHub只是一个技术社区 详见https://github.com/about

希望此类信息能够被放在它该在的地方，比如Twitter 或者 Telegram channel 亦或是自己搭建的博客论坛。而不是放在一个“代码托管”的网站

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
