### ISSUE TITLE
冲上了github trending 榜首！！

### ISSUE THREAD

**Issue by huoqiangf** [sikaozhe1997/Xin-Yue#265]
![screen shot 2018-04-24 at 2 52 13 am](https://user-images.githubusercontent.com/38682849/39170742-9ef6f6fa-476a-11e8-8bbc-7543bd67b991.png)

**Comment by nainoNa** [comment]
有点害怕。。。这么高调不会被GitHub删吧。。。

**Comment by LawlietZe** [comment]
药丸

**Comment by aminic** [comment]
推上去再说

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
