### ISSUE TITLE
给留点活路吧，我的github呀！

### ISSUE THREAD

**Issue by BARaphael** [sikaozhe1997/Xin-Yue#267]
行行好

**Comment by huoqiangf** [comment]
该干嘛干嘛去， 该搬砖搬砖，该抠脚抠脚， 跑这里充什么大鼻子蒜

**Comment by 1103874618** [comment]
zf对gifhub动手又不是一天两天的事了
![image](https://photos.app.goo.gl/yynmxtDntybv1P4B2)

**Comment by aminic** [comment]
github不是你的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
