### ISSUE TITLE
太无力了

### ISSUE THREAD

**Issue by throwaway199** [sikaozhe1997/Xin-Yue#268]
原谅我用了一个以前的小号问这个问题，大号个人信息太多，我猜测老大哥也在监视这个repo
我们能做什么呢？这里的呼声不会传达到所有人的耳朵里，我们能做的只是气愤，和一部分人心惊胆战github被封。我们在这里开的issue再多，呼声再大，可以帮助的到这些北大的学子们吗？

虽然国内趋势是舆论推动法律，但在这次事件封杀舆论如此毫不留情的地步，我想在这里呼声再大也是没有多少用的。我自己不担心github被墙，也不否定积极地利用这个平台呼吁社会公平，但是除了愤慨，我们还能做什么？

**Comment by xenss** [comment]
默默关注？我想是不是该做点啥！
其实没必要怕被封，本来就封的差不多。
如果在天朝不会翻墙还好意思说自己写过代码？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
