### ISSUE TITLE
也许可不用担心Github

### ISSUE THREAD

**Issue by heyuanree** [sikaozhe1997/Xin-Yue#269]
Github成为宣传的阵地早已不是什么新鲜事了。大家不是第一个发现这种用途的，细心同学可以发现，国内国外早有此类用法，并已经维持了很长时间。

以上仅是基于经验的判断。

**Comment by DanteAndroid** [comment]
也许列举几个例子能更好地说明你的观点。
比如 莆田系医院的曝光：https://github.com/open-power-workgroup/Hospital

另外我是站在可以自由使用 GitHub 这方。

**Comment by qq1012827513** [comment]
除了程序员不知道谁还上gt 以后要上gt看新闻？？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
