### ISSUE TITLE
读《申请公开信息事件经过》有感

### ISSUE THREAD

**Issue by nainoNa** [sikaozhe1997/Xin-Yue#270]
看完P大的同学是怎么争取自己权利的，我非常钦佩，这就是我心目中P大的样子。

多次按学校规定向学校提出要求，保留证据，针对校方给出的回答多次提出质疑，不因为校方的多次敷衍就得过且过，坚持要得到真相。在赶毕业论文之际还忙与这件事，面对校方的暗示依然勇敢坚定的继续参与这件事。在学校、学术和母亲的压力下依然坚持自我，我觉得换我是做不到的，非常钦佩岳同学。

还有昨天的湖底群魂贴的声明，也让我非常钦佩。

所以这真的是“两个北大”之争吗？

**Comment by jiapinghong** [comment]
我也觉得是两个北大之争，但是校方是很无奈的，需要权衡的事情太多。
实际上，事件一开始的落脚点仅仅是沈阳在20年前是如何被北大处理的，学校出示的文件是否是全部可得信息，但是现在这个事情已经没人care了。
问题是 院方到底有没有通过“顺利毕业”的方式对岳昕同学施压，有没有通过对其母亲采取非常手段使得其母发生情绪崩溃。（来自：不稳定电流）

**Comment by chungjin** [comment]
明明北大可以把事情处理得很漂亮。是不是手里握有权力的人都这么蠢+横

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
