### ISSUE TITLE
请自觉抵制在学术论坛发表此类文章，觉得有问题有那么多伸张正义的地址，不要来破坏这里的环境

### ISSUE THREAD

**Issue by lolo980** [sikaozhe1997/Xin-Yue#271]

**Comment by caoyun11** [comment]
术业有专攻，轿车请不要去沙漠中奔跑

**Comment by huoqiangf** [comment]
一个commit没有你以为别人不知道你干嘛的？ 还搞学术。。你不要污染学术这两个字好不好

**Comment by caoyun11** [comment]
我是渣渣啊，但是被封了我不能下载SDK了怎么办，你给我写？

**Comment by CeresCheng** [comment]
自我阉割成这样也是有趣

**Comment by hxuaj** [comment]
请问有哪些伸张正义的网址？

**Comment by caoyun11** [comment]
敲敲键盘就能达到目标？敲敲键盘会给你建堵墙，事分轻重缓急，谏有逆顺生死，没感觉到漫天传单对上世纪的帮助，只听说薛岳张自忠二十六、二十九路军血战长城，观全篇在介绍什么？？可有一条实质性解决方案？是各类zf机构拒不接受检举了吗，没有，舜父与舜弟典故请各位好好想想，当刀子当的这么顺手 CeresCheng我更是佩服你

**Comment by MAYDAYHAO** [comment]
墙都不会翻，你说你是个写代码的？求你别侮辱这个行业谢谢。

**Comment by WangYihang** [comment]
@lolo980 同问：请问有哪些伸张正义的网址？

**Comment by CastleBUPT** [comment]
墙就是因你这种人而建起来的

**Comment by VinsonGuo** [comment]
别给程序员丢脸了

**Comment by lolo980** [comment]
@WangYihang 东汉党锢之争，大宋大明书生有没有误国，说的就是你，请问这样做对当时时局可有丝毫积极影响，民意是要顾及，难道有人裹挟民意要挟zf也要追随？全是断送几代人的根基，自己想想吧，你要是敢去部门上访声援，你要是敢拉着热血维权的人去游行，去推动制度法律层面的反思与修正，我佩服你是条汉子，这是真为底层人民利益为出发点，只要你第一，不论是市局police还是国旗下请愿，我后你三步算你厉害，空口放炮键盘侠，我实在不明白你优越感从哪来

**Comment by aminic** [comment]
赵家的狗来吠了

**Comment by MAYDAYHAO** [comment]
优越感就是。我起码还敢说话，闭着嘴的花生人什么时候可以目中无人了？

**Comment by WangYihang** [comment]
@lolo980 您好

#### 一、关于`正面回答`
关于您说的：
> 觉得有问题有那么多伸张正义的地址

希望可以麻烦您正面回答大家的问题并给出“伸张正义的地址清单”
#### 二、关于`发表此类文章`
> 请自觉抵制在学术论坛发表此类文章

鄙人不是很理解何为`发表此类文章`
该仓库中的文件皆为援引自当事人发布或者相关机构声明
利用分布式版本控制工具可以有效保存证据以便于事后追踪事件进展
何来发表文章之说？
不知您说的`发表文章`是否为根据主观看法发布对改事件的评论
如果是，那么请给出具体引用
如果不是，请解释您的言辞

#### 三、关于`学术论坛`
希望给出链接，关于您说的`学术论坛`，不知您说的`学术论坛`是否指代 GitHub
参考如下：
> https://readwrite.com/2013/11/08/seven-ways-to-use-github-that-arent-coding/

如果您觉得 GitHub 只可以用来托管代码，请参考上述文章
目前有多国政府在使用 GitHub 来托管一些公开项目

#### 四、最后
> 引用鲁迅先生《热风——随感录四十一》
```
所以我时常害怕
愿中国青年都摆脱冷气
只是向上走,不必听自暴自弃者流的话
能做事的做事,能发声的发声
有一分热, 发一分光, 就令萤火一般
也可以在黑暗里发一点光
不必等候炬火

此后如竟没有炬火
我便是唯一的光
倘若有了炬火
出了太阳
我们自然心悦诚服的消失
不但毫无不平,而且还要随喜赞美这炬火或太阳
因为他照了人类,连我都在内
```

> 引用马丁.尼莫拉《起初他们》
```
起初他们追杀共产主义者
我不说话
因为我不是共产主义者 
接着他们追杀社会民主主义者
我不说话
因为我不是社会民主主义者

后来他们追杀工会成员
我不说话
因为我不是工会成员

之后他们追杀犹太人
我还是不说话
因为我不是犹太人

最后他们要追杀我
但再也没有人站起来为我说话了
```

#### 五、附
如果您开启这个 Issue 是为了帮助岳昕同学，请和大家一起
如果不是，请离开，并且不要再回复该条回复

**Comment by VictoryWangCN** [comment]
你线上东单那看看上访啥样再来逼逼叨好吗楼主
