### ISSUE TITLE
支持一下 ，但是我做了好几年的开源项目，加起来也没你的星星多。还是你社会。

### ISSUE THREAD

**Issue by Pearyman** [sikaozhe1997/Xin-Yue#275]

**Comment by huoqiangf** [comment]
你这种天天用脚本刷commit的人还好意思说自己做过开源？

**Comment by justbilt** [comment]
我相信你做这好几年的开源项目所受到的压力都没有他这一次大.

**Comment by zrdsj** [comment]
这时候就别睿智了

**Comment by yu-cao** [comment]
@huoqiangf 你看看你的库写过什么再说，别人至少还是有代码贡献的，你就一个刚注册的而且没有任何除了fork这个库外的其他东西提供，这样的嘲讽别人令人发笑

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。

**Comment by huoqiangf** [comment]
@yu-cao 哎呦，忘了这是自己小号了，不好意思。。不过我是站在一个真程序员的角度嘲讽的。。主要是不想跟用gitgreen的人为伍

**Comment by Pearyman** [comment]
@huoqiangf   你也太自作多情了  谁还要和你为伍？  您说的对  就您一个人是真程序员 您全家都是真程序员
