### ISSUE TITLE
写给担心GitHub被封的人

### ISSUE THREAD

**Issue by hxuaj** [sikaozhe1997/Xin-Yue#277]
滚。

**Comment by haohaohihi** [comment]
叫嚣着这个repo会影响他们使用GitHub的人，从来想的都是自己

**Comment by hxuaj** [comment]
愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者的说话。能做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般；也可以在黑暗里发一点光，不必等候炬火。--鲁迅
