### ISSUE TITLE
97年的孩子，你学会对抗，可你知道你对抗的是什么力量吗？

### ISSUE THREAD

**Issue by fandeus** [sikaozhe1997/Xin-Yue#278]
其实，这种事情到还行。比你这个严重的事情我们翻墙出去可以看到的太多了。艾未未，刘晓波，藏人自焚，等等。我不知道你能不能看到我的这个评论，如果你看到，我希望你明白你自己做什么。如果你知道，逆选择对抗，我支持你。至于那些说什么不要在技术的地方发表政治类的文章和事件之类的人，也不排除整个事情的可能性。一个翻墙工具，在手机页面被封锁。政府的技术能做到指定网站的指定页面封锁，只是看你的价值。就这个孩子的事情，把GitHub封锁了，别闹了。这孩子没那么值钱。这个是小事，就调查一下老师是不是性而已，孩子你牛逼。胆子可以，够厉害。
       那些主张不要在GitHub上发布政治类的文章的人。GitHub的作者创立这个网站的时候并没有这个主张。那你还在意什么呢？这个不是儿童色情，不是恐怖袭击策划。这个只是一个学术自由的方式而已。如同你写的软件一样。谁管你的软件是做什么的呢！！

**Comment by aminic** [comment]
言论即代码，言论即学术，没有什么是不能谈论的，这正是墙存在的理由。

**Comment by MAYDAYHAO** [comment]
虽以卵击石，但是也埋下了可以种子。种子发芽之后，世界就会改变了。我们无力改变这时代，但是种子终会发芽。等到上一代人离去，我们便能改变一些事情了。这些人所做的不是徒劳的。

**Comment by MAYDAYHAO** [comment]
@csrgxtu 所以需要足够多的种子。并且呵护它。分人吧，你这样的人，种下多少种子都于事无补，需要心怀希望之人才行。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
