### ISSUE TITLE
不建议在github上发表与技术无关的内容

### ISSUE THREAD

**Issue by lby1992** [sikaozhe1997/Xin-Yue#280]
你可以发Twitter，或者其他社交平台，github只是一个技术交流的网站，过多的无关内容会造成不必要的影响，最主要是程序员们也无法帮你做什么事。

**Comment by merlinengine** [comment]
@lby1992 不建議豬國人在github上

**Comment by LittlePrinces** [comment]
愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者的说话。能做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般；也可以在黑暗里发一点光，不必等候炬火。--鲁迅

**Comment by lby1992** [comment]
我只是不建议，没说不能这么做，你们想做就做吧

**Comment by CastleBUPT** [comment]
精致的利己主义者

**Comment by excitedFrog** [comment]
gayhub上还有小说呢

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
