### ISSUE TITLE
请远离git 谢谢！

### ISSUE THREAD

**Issue by hankai17** [sikaozhe1997/Xin-Yue#283]
才疏学浅 不知道git与github有什么区别 大不了晚上做个笔记学一下 你们要烦 就随便说我吧 我也不想以这种方式提issue了

**Comment by sylxjtu** [comment]
你说远离github还能正常讨论，你说远离git，你知道git是什么吗？

**Comment by WestFive** [comment]
helpful? no

**Comment by leciel-guo** [comment]
怕你是连想喷什么都没想清楚

**Comment by lilewis** [comment]
看他那农药的头像

**Comment by Voleking** [comment]
GitHub 和 git 都分不清。。。笑 cry

**Comment by asklogic** [comment]
逻辑混乱 打回重黑

**Comment by 498628255** [comment]
hehe 你这issue水平和觉悟请远离“git”

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
