### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by Kuangcp** [sikaozhe1997/Xin-Yue#285]

**Comment by Seedarchangel** [comment]
hhhh，企鹅电脑管家说这句话真的合适吗

**Comment by wydwww** [comment]
建议修改 issue 标题，比如

> “电脑管家”标记本项目网址为危险网站

**Comment by Hadron67** [comment]
分享的时候可以在链接后面随便加一点get参数，如https://github.com/sikaozhe1997/Xin-Yue/?param1=true

**Comment by Kuangcp** [comment]
![default](https://user-images.githubusercontent.com/20043659/39180523-b26b9f22-47e9-11e8-8796-015d6163a30f.png)

**Comment by XhstormR** [comment]
这个国真是可笑啊

**Comment by wanglz111** [comment]
微信也被显示被多人举报无法显示

**Comment by Kuangcp** [comment]
要是这个拦截和屏蔽的处理是在座的开发的， 会有何感想， 会不会内疚，但是我想，猿的话还是活命要紧

**Comment by zyfdegh** [comment]
乖儿子马化腾

**Comment by moonwater** [comment]
上github的同学还用电脑管家，　给他９９９个点赞．

**Comment by xx7777** [comment]
估计是被大量用户举报了

**Comment by lfq7413** [comment]
@Kuangcp 本项目的贡献者也在忙着活命，完全不在乎你是不是要活命：https://github.com/sikaozhe1997/Xin-Yue/issues/556
