### ISSUE TITLE
国人对政治的理解真有趣，实际上在中国之外的地方讨论政治本来就是正常生活的一部分。github上有各国宪法，宪法修正案，草案讨论，利用github保存版本和协作讨论本来就是它的正常用法。各国还有开放政府相关项目都在上面，只有到中国才有人觉得“不搭调”

### ISSUE THREAD

**Issue by yanz927** [sikaozhe1997/Xin-Yue#286]

**Comment by Richardplus** [comment]
有意思！

**Comment by yanz927** [comment]
https://github.com/github/government.github.com/blob/gh-pages/readme.md

**Comment by yanz927** [comment]
顶多HTTP 451呗，编程随想的项目在GitHub上都放了多久了，你们觉得哪个让党国更忌讳？

**Comment by Woolseyyy** [comment]
@yanz927 那你能否去看下该项目下的issue？
用git做文件的版本协作并没有什么，但滥用issue导致这里成为政治讨论社区才是我们担心的。issue的作用是对项目本身所提的建议，而不是在该处进行讨论。事实上，即使这个repo是技术repo，在issue下进行讨论而不是对repo进行建议和反馈也是我们所反对的。

**Comment by AplloBattlestarGalactica** [comment]
厉害了，你的国

**Comment by yanz927** [comment]
@Woolseyyy 你没资格教育别人什么是正确的使用姿势

**Comment by Woolseyyy** [comment]
@yanz927  我不是在教育你如何使用，issue的作用在github中有说明，不需要我教育你。
 If you have a bug or an idea, browse the open issues before opening a new one. You can also take a look at the Open Source Guide[https://opensource.guide/].

**Comment by LittlePrinces** [comment]
@Woolseyyy 难道这个不算idea吗？issue的意思不就是交流idea吗，这种是多么正确的打开方式。我们在声援这个时代这么珍稀的人。

**Comment by Woolseyyy** [comment]
@LittlePrinces  请问你的idea对提升本项目有何帮助，请注明。

**Comment by Seedarchangel** [comment]
@Woolseyyy 
哦？您对issue的见解比github团队还透彻啊？https://guides.github.com/features/issues/
`Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. They’re kind of like email—except they can be shared and discussed with the rest of your team.`
`Issues are great for tracking all kinds of things — and GitHub is a great place to easily share and collaborate on your issues. Here’s some of our favorites:
Bug tracker for your house including such gems as the door being hung incorrectly
Bug tracker for your open source projects
Request for recipes (maybe you have a good gluten-free pizza dough recipe?)`

**Comment by LittlePrinces** [comment]
@Woolseyyy 教育你这种只求自保还让别人都闭嘴的人就是对这个项目的帮助。

**Comment by Woolseyyy** [comment]
@Seedarchangel 你为什么要贴出支持我观点的材料.... 
我先再说一下我的观点：issue的作用是对项目本身所提的建议，而不是在该处进行讨论。它应该对提升本项目有帮助。
举个例子，你可以指出本项目材料在某处的错别字，或是在细节上与事实的出入。
官方说明的"Other uses"中提到的关于house的issue，也是对于房屋装修修理的记录和交流。

**Comment by Seedarchangel** [comment]
@Woolseyyy 

1. Here...我给你个建议。如果你觉得这是一个misuse,你可以给github团队发一封邮件，要求他们撤下这个repo和issue。我想他们最有发言权。
2. 团队成员是谁你说了算？

**Comment by Seedarchangel** [comment]
@Woolseyyy 
我还是不懂怎么威胁到这个场所的存在了。我maintain一个面向中国人的百星项目，I don't see a problem?
 As we speak, I'm pushing code onto my own repo. So...What's wrong?

**Comment by Woolseyyy** [comment]
@Seedarchangel 您的建议是对的，我已同github进行联系，感谢您的建议！

**Comment by Seedarchangel** [comment]
@Woolseyyy 
Wish you the best of luck. 虽然我知道github百分之百不会理会您的投诉，我想您还是蛮生动的阐述了自私的定义 :)

**Comment by Woolseyyy** [comment]
@Seedarchangel 好的 我也希望您能同我一起通过实际行动推动本事件的发展

**Comment by AplloBattlestarGalactica** [comment]
其实github的宗旨也是自由啊

**Comment by killTheHostage** [comment]
@Woolseyyy 精致的利己主义者

**Comment by huoqiangf** [comment]
上面的各位同学， 别浪费时间跟这个 Woolseyyy 争了， 这人是个五毛，大家散了吧， 让他吸引了火力就太可惜了

**Comment by yixuantw** [comment]
「莫談國事」在很多國人心裏並不是不得已的策略，而是具有正義性的真理。

**Comment by hssdx** [comment]
@Woolseyyy 你个傻逼，技术垃圾就算了，逻辑还这么混乱强词夺理，这么多程序员怎么就出了你这个败类

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
