### ISSUE TITLE
关于维护github技术性质的言论

### ISSUE THREAD

**Issue by MrLevo520** [sikaozhe1997/Xin-Yue#290]
首先：我在个人立场上支持北大的同学勇于发声的情况，并且对此保持时刻关注的状态。好了，我们来看看道理。

对于github是技术区，其他乱七八糟的别往上泼的言论

首先，我认为github是代表技术性的没错。但是，如果我们能找到一个合理且合适的平台，我们会不去尝试声援么？你在这里吐槽github性质的时候是否了解了现在这个新闻在各个发声渠道已经被封的一干二净？你知道我们只能使用github这种资源进行维权和发声时候的无奈么？而喊的最凶的几个人，点开他的主页，几乎空白的页面，几乎没有对这个我们深爱的社区提供任何贡献，你对我说不要去'污染'它？对不起，你不配。我个人提交的项目不算多，也不算少，我们更加知道github的珍贵性，所以我fork这个项目的时候，并没有什么不妥，这是我个人做的决定，我认为值得。

其次，对于表示精神上支持但是还是反驳在github上发文的同学们，我认为至少比那些就知道瞎喊的人要好很多，我理解你们的顾虑，知道你们经过思考。但是，请为北大的那个学生考虑一下吧，由于他正义的发声，他承受了多大的压力，寒窗苦读的北大被威胁毕业？家庭关系破裂？而你承受的仅仅是极小的可能github背墙的后果，我说您在这点上有些自私，请尽管来怼我。

再者，对那些冷嘲热讽的程序员，请不要代表我们去夸大由此带来的后果，至少不要代表我，我虽然默默无闻，但身行正直。还有那些趁机带节奏各种夸大跑偏的人，我们就事论事，请不要给自己加戏。

最后，对于github trending 榜首的事，我个人观点，算是一种程序员发声，让他们认识到我们所再做的努力，有人说家丑不可外扬，我真的很想骂人。今天有人问我，到底发生什么事了？你看，在社交网络上他们怕是再也找不到事情的真相。我们存档于github，保持的是事情的本身，如果你的github只能存下code，那么您不看也罢，没必要来阻止，谢谢。

还有，对于影响您高贵的github体验的人，呵呵，你不关注是不是屁事没有？难不成还给你的页面推小广告？？？

我珍爱github和code，我乐于分享和交流。并且这次我就要fork了这个非技术性的repo！

**Comment by MAYDAYHAO** [comment]
自己人都不给自己人说话，让我想到了那帮不肯开口的花生人。

**Comment by lolo980** [comment]
敲敲键盘就能达到目标？敲敲键盘会给你建堵墙，事分轻重缓急，谏有逆顺生死，没感觉到漫天传单对上世纪的帮助，只听说薛岳张自忠二十六、二十九路军血战长城，观全篇在介绍什么？？可有一条实质性解决方案？是各类zf机构拒不接受检举了吗，没有，我就是你说的一片空白，只在GitHub找别人的代码，没能力在技术层贡献，这算是污染了 你的地盘？，注明一下不配用也可以不用，东汉党锢之争，大宋大明书生有没有误国，说的就是你请问这样做对当时时局可有丝毫积极影响，全是断送几代人的根基，自己想想吧，你要是敢去部门上访声援，你要是敢拉着热血维权的人去游行，去推动制度法律层面的反思与修正，我佩服你是条汉子，这是真为底层人民利益为出发点，空口放炮键盘侠，我实在不明白你优越感从哪来

**Comment by LittlePrinces** [comment]
@lolo980 自己什么都不做还冷嘲热讽的人我也不知道你的优越感那里来

**Comment by LittlePrinces** [comment]
@lolo980 要不要我给你贴几个上访户遭毒打的新闻？SB检举都是说给你这种白痴信的。

**Comment by dustars** [comment]
@lolo980 

你看，你就是那个，别人在发声，你拼命捂住别人的嘴别让他发声的人。 

那种，在每个时代，最令人不齿，最令人感到愤怒的东西。

**Comment by MrLevo520** [comment]
@lolo980 呵呵，你的feed都是洗地的，主页提交都是空白，你和我说对github的贡献？拜托，你能不能不复制粘贴，feed上都有记录的。自己的repo就一个，敢说有技术层面贡献？大佬，能不能好好洗地

**Comment by MrLevo520** [comment]
@lolo980 follows和following都是同个人啊，@Senh Linsh这个是大号的意思呗？？如果是真的，我看提交蛮多的，我收回技术贡献没有的话。但，为什么人品却是这样的？

**Comment by lolo980** [comment]
@MrLevo520 拜托  说技术我就是个渣渣，完全不会  我什么时候跟大言不惭的说过对论坛的贡献了？

**Comment by lolo980** [comment]
@dustars 明白你的意思了总结一下就是大家打个字表示表示我知道了  我支持你  你加油，于事无补，所以说不能去当谭嗣同  强烈谴责谴责得了呗  那你还不如不说呐，你不负责解决问题，只想着丢人丢全球去，我不知道你这算是什么样的推动法治健全，构建哪门子的团结和谐的社会

**Comment by ZenoTian** [comment]
他们只是害怕没有地方copy代码了。自己写又不会写，只有粘粘代码过日子。

**Comment by RuochengHan** [comment]
@lolo980 1. 这种事就没有无风险的解决方案 许多人也不求解决方案 这与转载的目的无关 2. 转载的最终目的不是发泄 而是让更多的年轻人知道有这么件事 不求现在的行政机关有所作为 求的是30年后的这一代在行政机关处理事务时能多一些想法

**Comment by lolo980** [comment]
@RUochengHan 如果是这样的原因  我为你点赞，不过请参考抵制日货时各地都发生了些什么，都是些什么肮脏的思想，学而不思固然错误，思而不学也不见得多好 @MAYDAYHAO 如果将来你的子女经理相同情况，请你四处博人眼球诉求不公，看看行动有用还是嘴说一句有用
@LittlePrinces 你的第一句是在否定埋头实干推动发展的行为，请自行思考妥当与否

**Comment by MAYDAYHAO** [comment]
你可能想多了。



-------- 原始邮件 --------
发件人：Willam <notifications@github.com>
时间：周二 4月24日 16:01
收件人：sikaozhe1997/Xin-Yue <Xin-Yue@noreply.github.com>
抄送：MAYDAYHAO <ch13611301359@outlook.com>,Comment <comment@noreply.github.com>
主题：Re: [sikaozhe1997/Xin-Yue] 关于维护github技术性质的言论 (#290)


@lolo980<https://github.com/lolo980> follows和following都是同个人啊，@SenH<https://github.com/SenH> Linsh这个是大号的意思呗？？如果是真的，我看提交蛮多的，我收回技术贡献没有的话。但，为什么人品却是这样的？

**Comment by MAYDAYHAO** [comment]
我一定会有行动。不过你的肯定会问你子女为什么反抗。



-------- 原始邮件 --------
发件人：dream <notifications@github.com>
时间：周二 4月24日 16:58
收件人：sikaozhe1997/Xin-Yue <Xin-Yue@noreply.github.com>
抄送：MAYDAYHAO <ch13611301359@outlook.com>,Mention <mention@noreply.github.com>
主题：Re: [sikaozhe1997/Xin-Yue] 关于维护github技术性质的言论 (#290)


@RuochengHan<https://github.com/RuochengHan> 如果是这样的原因 我为你点赞，不过请参考抵制日货时各地都发生了些什么，都是些什么肮脏的思想，学而不思固然错误，思而不学也不见得多好 @MAYDAYHAO<https://github.com/MAYDAYHAO> 如果将来你的子女经理相同情况，请你四处博人眼球诉求不公，看看行动有用还是嘴说一句有用
@LittlePrinces<https://github.com/LittlePrinces> 你的第一句是在否定埋头实干推动发展的行为，请自行思考妥当与否

**Comment by MAYDAYHAO** [comment]
如果无力改变这个时代，就为这件事埋下一颗种子。等这代人有地位了，这颗种子未曾死去的话，就会生根发芽。良知和真相不会死去。



-------- 原始邮件 --------
发件人：dream <notifications@github.com>
时间：周二 4月24日 16:58
收件人：sikaozhe1997/Xin-Yue <Xin-Yue@noreply.github.com>
抄送：MAYDAYHAO <ch13611301359@outlook.com>,Mention <mention@noreply.github.com>
主题：Re: [sikaozhe1997/Xin-Yue] 关于维护github技术性质的言论 (#290)


@RuochengHan<https://github.com/RuochengHan> 如果是这样的原因 我为你点赞，不过请参考抵制日货时各地都发生了些什么，都是些什么肮脏的思想，学而不思固然错误，思而不学也不见得多好 @MAYDAYHAO<https://github.com/MAYDAYHAO> 如果将来你的子女经理相同情况，请你四处博人眼球诉求不公，看看行动有用还是嘴说一句有用
@LittlePrinces<https://github.com/LittlePrinces> 你的第一句是在否定埋头实干推动发展的行为，请自行思考妥当与否

**Comment by lolo980** [comment]
@MAYDAYHAO 本来想说 幼吾幼以及人之幼  不过看你第三句还是挺好的  坚守本心吧  回到最初的话题  如果真实帮忙不敢人后 喊口号嘛也就那样了， 在无法制定更改规则的前提下，维护当下是最稳妥的做法，@RuochengHan 首先说水准吧，不是相信不相信而是事实上的是与否，就事件本身来说，你点到的思潮是核心，这才是问题，裹挟民意游刃有余的借刀（然而不知道真实的事实是什么，既然可以选择相信学生，有没有可能师德也许没有瑕疵），在当别人棋子与冷静维稳中，还是相信当局理智些

**Comment by RuochengHan** [comment]
@lolo980 1. 我说的相信是指相信大家有不把事件引向“抵制日货”式的结局 而且两者的可比性的局限我已经陈述过了 不是相信学生或者他/她人的陈述 2. 再说相信不相信学生或者老师 真实事件无从得知我同意 所以我从来没有从这里立论 你也可以在这里发表自己的所见所闻如果你想从这个方便面讨论 3. 维稳固然重要 改变也重要 当然不能一朝一夕改变 但如果纠结于思潮作为“裹挟民意游刃有余的借刀” 那我们可能没有讨论的必要了 毕竟我还是认为人类有进步的必要的 并且思潮不能消失 多谢讨论~ ：）

**Comment by MAYDAYHAO** [comment]
@lolo980 如果我连口号都不喊，我跟死人有什么区别？善用你的权力，即使再微弱，也要尽力。

**Comment by TinaHongBu** [comment]
为什么还有人在这儿装外宾？我当然希望体面的发声， 如果这是个可以随时游行抗议的国家。微博被禁微信被删媒体失声不得已在毫无群众影响力的 GitHub 整理一些文字，还要被说不够理智？
楼主说得好，认为这个项目影响 GitHub 使用的人，先来秀秀你 publish 了几个 repo 为 open source community 做过什么贡献。

**Comment by quanquan2100** [comment]
不知道有没有学法律的人知道信息公开申请的合法途径, 说实话, 我觉得在那里更合适.  不得已而在这个平台是我们的可悲. 

每个人都有自己的立场无可厚非, 我认为提出自己的担忧同样是言论自由的体现, 难道我们只允许自己支持的观点言论自由, 不允许其它言论自由?

github 建立这个平台是为互联网技术服务, 不是建立时事评论论坛的, 不合适的地方自己要认.

**Comment by LittlePrinces** [comment]
@quanquan2100 https://government.github.com 这可是github主动牵涉到政治事务的。要不要向白宫请愿封锁GitHub?

**Comment by LittlePrinces** [comment]
@quanquan2100 yuexin会得到这样的待遇，不就是申请信息公开？？不能更加合理合法，结果呢。

**Comment by quanquan2100** [comment]
@LittlePrinces  不合适的地方自己要认, 不要理直气壮. 我说出我的看法, 没问题. 就事论事而已

国内没有平台, 只能在这里, 那是我们占用别人的资源. 心里得清楚, 我看很多人倒是觉得理所应当.

**Comment by LittlePrinces** [comment]
@lolo980 你居然能把这件事和抵制日货联系在一起。抵制日货的时候，人们说上街就上街了，现在呢？畏畏缩缩生怕多说一句，上街试试？这说明什么，人们只有在安全的时候才爱国，还说明什么？官方明显是纵容这种民族主义的。完全两码事你真厉害

**Comment by LittlePrinces** [comment]
@quanquan2100 看来你还是没明白。github用处之一，就是参与政治事务的讨论。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
