### ISSUE TITLE
如果你说github不可以做这个，你是真的会用github吗？

### ISSUE THREAD

**Issue by MAYDAYHAO** [sikaozhe1997/Xin-Yue#293]
有的是保存宪法等文档的项目。你怎么不看看？

**Comment by MAYDAYHAO** [comment]
还是你国思想教育做得好。

**Comment by merlinengine** [comment]
PR: 还是~你~豬国思想教育做得好。

**Comment by Woolseyyy** [comment]
用git做文件的版本协作并没有什么，但滥用issue导致这里成为政治讨论社区才是我们担心的。issue的作用是对项目本身所提的建议，而不是在该处进行讨论。事实上，即使这个repo是技术repo，在issue下进行讨论而不是对repo进行建议和反馈也是我们所反对的。

**Comment by LittlePrinces** [comment]
为什么讨论政治会变成滥用issue？还有别的地方可以讨论吗？政治不是我们生活息息相关的日常吗。听到政治躲之不及的是你国大型魔幻现实吧。

**Comment by MAYDAYHAO** [comment]
@Woolseyyy 哦？您对issue的见解比github团队还透彻啊？https://guides.github.com/features/issues/
Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. They’re kind of like email—except they can be shared and discussed with the rest of your team.
Issues are great for tracking all kinds of things — and GitHub is a great place to easily share and collaborate on your issues. Here’s some of our favorites:
Bug tracker for your house including such gems as the door being hung incorrectly
Bug tracker for your open source projects
Request for recipes (maybe you have a good gluten-free pizza dough recipe?)
CV的，但是觉得很有用。

**Comment by Woolseyyy** [comment]
@LittlePrinces  @MAYDAYHAO  请参考 #286  的回复

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
