### ISSUE TITLE
程序员的解决方式

### ISSUE THREAD

**Issue by twx314** [sikaozhe1997/Xin-Yue#295]
以程序员的角度来说，如果遇到了巨大的BUG，就先停一停，想想看有没有别的办法可以实现，
如果真的没办法，那就告诉老板，办不到
要是老板强硬，那就只能辞职换公司了，
这北大的妹子,建议你换个方式来解决问题，如果那学校你不满意，就换个学校吧，
天下的学校千千万，不要吊死在一棵树了。

**Comment by Richardplus** [comment]
换大学跟换公司可以比较吗？

**Comment by twx314** [comment]
我只是打个比方，当对手太强大的时候，硬撼是不明智的行为。我觉得这妹子可以再成熟点。

**Comment by aminic** [comment]
妹子行此，已为人杰。

**Comment by twx314** [comment]
杀敌0个，自损一千，勇敢了无畏了，但是行为SB。

**Comment by Sudsakorn123** [comment]
你们不站出来，然后对站出来说话的人说是Sb,我也不知道谁是sb

**Comment by twx314** [comment]
当时是痛快了，现在痛苦了
作事情不过脑子，等毕业了再作这件事情就那么难？等三个月会死？
除了骂她SB我是一点同情心都没有。心智太不成熟，
先给学校服个软，拿到毕业证再说吧，真以为自己是世界中心了。

**Comment by vzxxbacq** [comment]
@gaocegege 
或许我们该关闭这个issue
