### ISSUE TITLE
写代码是不会写的

### ISSUE THREAD

**Issue by Naville** [sikaozhe1997/Xin-Yue#297]
这辈子都不会写的，就只能靠蹭热度搞大新闻才能勉强维持得了生活这样子。Github上小粉红和民智未开的潜在fandong分子又多，说话又好听，我超喜欢这里的

**Comment by LawlietZe** [comment]
代码也不会写，打工是不可能的

**Comment by quanbrew** [comment]
所以请问您开这一个 issue 就是为了用讽刺性的口气说一个 meme 吗？
哪怕是在这里请求「政治滚出GitHub」的人，至少会好好说话，好好表达自己的观点。
我也希望阁下能好好说话，而不是在 issue 里面玩梗、诛心别人蹭热度。
祝好。

**Comment by wkmcyz** [comment]
@quanbrew 别这么认真嘛，调个侃，有的人就是什么场合都笑而已呀

**Comment by asklogic** [comment]
阴阳怪气在nga都卜行 github还不直接****警告

**Comment by wkmcyz** [comment]
@asklogic sgga!

**Comment by wkmcyz** [comment]
莫名想笑。。。真的玩成论坛了，，，好玩好玩，[👏👏👏👏]

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
