### ISSUE TITLE
网页版 https://anonymous-xinyue.github.io/

### ISSUE THREAD

**Issue by anonymous-xinyue** [sikaozhe1997/Xin-Yue#300]
https://anonymous-xinyue.github.io/
 
![image](https://user-images.githubusercontent.com/38684040/39173359-cc3e9a02-47a4-11e8-8a40-6e3d6634f78b.png)

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
