### ISSUE TITLE
偌大一个中国局域网都没有能让人自由发声的地方，而你们还在讨论github的技术中立性，这是整个中国程序员的悲哀！

### ISSUE THREAD

**Issue by YuzhouZhang** [sikaozhe1997/Xin-Yue#303]
# **担心github被封的人你们还是程序员么？翻墙不会么？左转lantern，右转XX-net，再不行自己搭shadowsocks！**

**Comment by darktxt** [comment]
就事论事，去年gfw升级后，shadowsocks的有些内容已经可以识别并屏蔽了。翻墙，成本越来越高。

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by guozixi** [comment]
@darktxt 不要用 rc4-md5 加密。最起码也要 aes-128-cfb 或者 chacha20

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
