### ISSUE TITLE
那么一个技术社区如何才能保证自己的中立性

### ISSUE THREAD

**Issue by Hypnoes** [sikaozhe1997/Xin-Yue#304]
# 那么
1.  禁止一切非技术性的讨论
2.  允许一切观点的共存

__如果同意1， 请点👍。如果同意2，请点👎。__

声明：👍或👎仅代表投票选项，并不意味着本人(hypnoes.liu)支持观点1或反对观点2.

**Comment by ky0ncheng** [comment]
不違反 TOS 都可以接受

**Comment by merlinengine** [comment]
1. 禁止一切豬國人來討論
2. 允許一切人類

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
