### ISSUE TITLE
担心被墙的，看看 git.io/99 和 git.io/100 之后放心写代码去吧

### ISSUE THREAD

**Issue by qyc777** [sikaozhe1997/Xin-Yue#306]
不会搭梯子的各位，可以买个VPS，之后看这个，一键操作。
https://blog.phpgao.com/auto_install_shadowsocks_and_kcptun.html

**Comment by sunxhh** [comment]
谢谢大佬提示。。

**Comment by asklogic** [comment]
当时该有以往版本的....

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
