### ISSUE TITLE
声援岳同学，并说说我的看法

### ISSUE THREAD

**Issue by endeavorchan** [sikaozhe1997/Xin-Yue#313]
在这件事情上，北大确实做的太过火了。我本人是支持中共的。中国目前的政治体制的办事效率确实是全球其他国家无法比拟。改革开放40年，人民生活水平确实是提高的，作为一个既得利益者我支持目前中共的政治体制。不过，一党专政必然会有言论的压制。我同意审查那些诋毁中共体制，中共高层的言论。但是对于这种在宪法框架能的民主诉求，岳同学一不反共，二不反政府，三不反体制。中共是否应该适当的开放一些这方面诉求的言论自由。一而再，再而三不分青红皂白删除帖子（联想到前几天同性恋相关话题的帖子也被无故删除），是不是只会激起民愤，激起更大人民的反弹？ 希望中共的高层能够好好思考思考孰轻孰重。

**Comment by LIsmooth** [comment]
我觉得这件事和政府应该没什么关系，最多只是几个腐败的问题，极有可能是沈阳事件背后有更大的黑暗吧

**Comment by merlinengine** [comment]
誰要你聲援，支持豬共就是蠢貨。

**Comment by endeavorchan** [comment]
孙子哎， 我支持谁管你屁事，在这狗吠

**Comment by merlinengine** [comment]
豬國人最愛到牆外表現普世價值，你豬在牆內哼都不敢。

**Comment by chenchongsong** [comment]
Youtube评论区既视感…

**Comment by endeavorchan** [comment]
孙子哎，虽然我不知道你是哪个傻逼国家的。但是你真是tm够蠢的。老子定居美国，但是我就是支持中共，你来咬我啊 傻逼

**Comment by merlinengine** [comment]
你豬到哪裡也是豬啊，你基因沒變過吧。

**Comment by endeavorchan** [comment]
孙子，你刚在哪个猪圈吃猪粪呢，嘴巴这么臭。

**Comment by merlinengine** [comment]
豬化人民共和國啊，你豬的基因發源地。

**Comment by endeavorchan** [comment]
你娘被公猪草生出你这么个猪狗不如的玩意儿，老子懒得跟你对骂。去死吧 傻逼 贱畜

**Comment by talkxin** [comment]
要吵去fb吵，我还要用github写代码呢

**Comment by jlu52161927** [comment]
傻逼湾湾吃屎好吗

**Comment by jlu52161927** [comment]
楼上那位猪来猪去的是猪化冥国的屎人吗

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
