### ISSUE TITLE
针对以下两个论点(

### ISSUE THREAD

**Issue by CoderLiang** [sikaozhe1997/Xin-Yue#316]
第一个论点：github是做软件的地方，不适合放有关其他话题；github宣传自己是世界第一的软件开发平台，可是从来没有规定只能用于软件开发吧？事实上从近几年github pages 支持个人网站上来看，我倒感觉github在积极探索其他的商业模式，请看别人是怎么多样使用github的：https://readwrite.com/2013/11/08/seven-ways-to-use-github-that-arent-coding/

那些说要维护社区纯净的筒子们，你们是为谁着急呢？

第二个论点：在写码的时候不想突然看到这种页面，被无关的信息影响，请注意github没有推送功能，只有搜索功能(也许再加上follow和unfollow)，只有自己进行搜索才能找到对应repo，请注意这种方式得到垃圾信息的比率是很低的，github有海量的数据，其中垃圾数据肯定也是海量的，但因为接入口是搜索，再加上rank by star，所以得到的结果一般都是高质量的，从这个意义上来说很不容易被无关信息影响

**Comment by hxuaj** [comment]
说到底，这些人只是彻底的自私者。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
