### ISSUE TITLE
please don't publish article  that related to politicized event ！

### ISSUE THREAD

**Issue by flwwd** [sikaozhe1997/Xin-Yue#317]
github is a technical community，the purpose of establishing  it is only for sharing,managing project  of various types of pograming language,the noble community environment needs to be maintained by us together.
The agreed brother send me up.

**Comment by merlinengine** [comment]
send you to commie's heaven.

**Comment by Jinglei-Cheng-THU** [comment]
ummm，还是希望大家心明眼亮，这个账号明显是全零用户。不知道是校方的还是所谓的境外势力的。

**Comment by YuzhouZhang** [comment]
Take your 50 cent and f**k off

**Comment by bohrasd** [comment]
Here's how GitHub itself use GitHub. https://github.com/github/gov-takedowns
Just f*** off.

**Comment by NonvolatileMemory** [comment]
f**k off

**Comment by lanthlove** [comment]
语法错误一堆，chinglish学的好，请个水军都不多花点钱

**Comment by FreedomOfSpeech** [comment]
溥仪: 拉倒吧，朕的大清比你们开放多了

**Comment by Peiyang** [comment]
Go f**k yourself your lowest form of human scum. Freedom forever!

**Comment by gwsh1234** [comment]
Joined an hour ago and commented an hour ago .

**Comment by csdnail** [comment]
this is not about politicized, but for the lives of people

**Comment by borzhang** [comment]
反正你这也是给中国人看的，就直接写中文吧，光标题英文就不止一个错了，没眼看。

觉得这个repo不合适的人去向github官方举报啊，这可是商业公司，官方如果觉得不合适，就自然会处理，这么简单的事儿不去做，在这儿嘚吧什么？举报了之后如果没有处理，就说明github认为没有不合适的，那就更不用说什么了吧？

不知道在吵吵些什么。

**Comment by csrgxtu** [comment]
塔利班：fuck Americans!!!!

**Comment by The-Earth** [comment]
看不出此事件和政治的关联。如有失察，还请明示。

**Comment by chengts95** [comment]
其实某个邪教组织早就把github当做宣传阵地了

**Comment by TinaHongBu** [comment]
为什么这么多人在这儿装外宾？我当然希望体面的发声， 如果这是个可以随时游行抗议的国家。微博被禁微信被删媒体失声不得已在毫无群众影响力的 GitHub 整理一些文字，还要被说不够理智？

**Comment by chengts95** [comment]
话说现在这个仓库已经远远偏离里面的内容了，github超过百度贴吧指日可待...

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
