### ISSUE TITLE
如何证明自己不是键盘侠？

### ISSUE THREAD

**Issue by imfht** [sikaozhe1997/Xin-Yue#320]
star一下 repo，然后该上班上班，该写代码写代码。
发条朋友圈表示愤慨，然后该上班上班，该写代码写代码。
我们是键盘侠吗？

**Comment by brentian** [comment]
链接也不敢发，姓名也不敢留，我们要造反吗

**Comment by MrLevo520** [comment]
@imfht 让更多人了解事情本身，给予舆论压力，给予我们的认同支持，让她知道她的价值观该得到鼓励，而不是无视。的确我们不是当局，提供不了更多的帮助，但是上述那几项，我们都能提供。而不是视而不见，听而不闻。

**Comment by MAYDAYHAO** [comment]
我们只是事件的传播者。这就够了。我们只有这点权力，我们用了。我们不是沉默的羔羊。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
