### ISSUE TITLE
目前已经有部分高校学生反馈github被校园网路由解析到127.0.0.1本地回环地址

### ISSUE THREAD

**Issue by Just2co** [sikaozhe1997/Xin-Yue#321]
RT：学校怕学生上来知道真相，传播真相，进而聚众起事！

**Comment by lilewis** [comment]
改DNS就ok啦🤣

**Comment by Yanstory** [comment]
是不是一个host+代理就可以了呢，还是说怎么解决这个问题（

**Comment by lilewis** [comment]
如果真的确定是校园网的问题（用4G移动网络可以访问），用校园网上网默认用的肯定是校园内部DNS服务器，把DNS服务器改成校园外部的不就可以了👌

**Comment by Just2co** [comment]
@Yanstory  解决办法就是不要用校园网自动获取的DNS服务器地址，而是改成公共DNS，比如223.5.5.5 114.114.114.114  还有一种办法就是改系统hosts文件，手工增加正确的github解析

**Comment by CreeperGo** [comment]
找一个支持DNSSEC的dns服务器，替换掉原来的，当然如果连除内网以外的dns都block了那就。。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
