### ISSUE TITLE
新青年

### ISSUE THREAD

**Issue by rotencode** [sikaozhe1997/Xin-Yue#322]
看到现在的年轻学生还具有很大的勇气，说明中国的复兴还是很有希望的。少年强则国强，虽然20岁已经进入青年的界限了。

社会和国家的演变是需要数十年时间的。欧美哲学家研究苏联和集权政治的出来的一些结论。妄图在不成熟的条件下加速进度是非常危险的事情。过去20年，已经有无数人为此付出了非常可惜的代价。而且，还被认定成汉奸，被污名化。非常不值。理性的也可以说功利性的角度来看，来处理这些事情，都是冷眼旁观。如果只是想改变自己的居住生存环境，则简单到只需要移民。

中国离民主，还至少需要20年的时间。

一则，没有话语权。需要20十年时间，让70，80，90后成为社会主力，掌握绝对话语权，70后是改革开放后出生的，没有经历过毛泽东时代的熏陶，对集权政治的认同感不高，而对个人权益的追求个性解放的追求都接近目前其他国家。目前掌握话语权的是50代。个人意识的觉醒和反思是社会进步的非常关键的一环。如果妄图跳过这一环节，则需要高层掌握话语权的领导人支持，目前来看，显然并不具备。习本人应该是发自内心的希望维护社会主义制度。

其二，社会阶层的进化。当前中国主流，任然是每天提个购物袋在大街上吆喝讲价唠叨人长里短的人。去菜市场走一圈，去大街小巷走一圈，他们的意识里面，根本没有阶层利益，根本没有形成阶层的利益共同体一说。所说的，所关心的，就是生计。经历了毛邓时代的人，毛邓时代就是他们的青春年少时代，提起这几十年，经历饥荒、能吃饱饭、有一点零碎资产能做一些更多的事情，他们肯定是充满了怀念的。再过20年左右，社会阶层普遍脱离生计危机的时候，社会阶层整体才会寻求其他需求的满足。所谓饭饱思淫欲也。

**Comment by straylion** [comment]
生产力决定生产关系,生产关系反作用于生产力

**Comment by wkmcyz** [comment]
老哥你的话是有道理的（我真的把这个网站当论坛了。。），我也是这么觉得的，我认为愤怒的青年们的存在是有意义和作用的，但是要尊重客观事实。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
