### ISSUE TITLE
覆巢之下安有完卵

### ISSUE THREAD

**Issue by lilewis** [sikaozhe1997/Xin-Yue#323]
1. 北大作为国内最高学府之一，如果连一个敢于发声的人都没有，那真的国人无救。
2. 在说github，作为世界范围内最大的（基佬）分享平台/社区，放什么内容是个人自由，如果真的被FW墙了导致“你”访问不了，那也是你自己的问题，需要用的人依然能用。
3. 在这里讨论这个问题并不是说有其他的思想，而是想通过这个事件得到大众的关注从而推动社会法制的进程。有问题不可怕，可怕的是列功覆过，事不关己高高挂起。
4. 看到部分issue说在github是放这个是害了大家，我突然觉得好悲哀，出头的人没有得到应有支持就算了，反而说害了自己....好可笑😂
5. 此时我仿佛已经看到某些人的嘴脸--> 奴化的^(*￣(oo)￣)^
6. 要明白 “覆巢之下安有完卵”，你怎么知道下一个不是你？
7. 可能有些人跪的太久了，以至于自己认为自己与生俱来就应该跪着，这样的人跟他多说无益。
8. 新闻联播是个好东西，那些说害了github（你个人）的人，没人要求你们看这个repo，去生活在新闻联播里吧，哪里没有痛苦，没有是非恩怨
9. 有的人就说了，我们可以去人民日报，百度贴吧，等等讨论声援。我就非常奇怪了！ 每个工具平台都有不同受众群体，不同的群里面向不同的对象，一类人在自己习惯的平台上讨论合法的事情(平台也没有禁止)。为什么就被某些人不待见呢? 
10. 别用自己的世界观去要求别人！加入这件事情的主人公是你？ 或是你的家人朋友？ 你还能独善其身吗？
11. 人生而平等，每个人都有说话的权利，你可以不支持，不赞同！ 但是并不意味着可以随意伤害别人。
12. 此时我脑海中浮现一个场景，出头的人在前方为大众要求合理合法的权利做抗争，而背后却有人害怕触动自己的一点点蛋糕，在后方偷偷捅刀子。
13. 在1931~1945年，这些人只有一种身份，你们都懂得！
14. 昨天star还2000~，现在就变成4000~，高兴又沮丧，高兴有这么多人在关注、沮丧自己的repo😂

**Comment by hxuaj** [comment]
别人的人身安全受到威胁，他们只关心自己的GitHub。

**Comment by tanoak10** [comment]
因为每个人对这个事的理解不一样，再明白一点就是他认为损害了他的利益，所以说。。。。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
