### ISSUE TITLE
请尊重github

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#324]
1. github是个代码托管平台
2. 代码文档,任何开源文档都是欢迎的
3. 请尊重技术工作者,他们虽然也是人,有喜怒哀乐,会八卦但是他们不想在本该高效工作的地方.看到你们的这些事.不管你们是正义,还是邪恶,善良还是愚蠢
4. 技术社区是一片净土
5. 有更好的途径宣泄你的情绪,也有更好的途径让你制造混乱.用区块链技术的社区,国外的论坛等等.

**Comment by MAYDAYHAO** [comment]
滚

**Comment by wintry** [comment]
请你好好读读github的官方说明，去看看github的属性是什么

**Comment by Dr-Bluemond** [comment]
额这怎么还能实时聊天？

**Comment by flufy3d** [comment]
github上面还可以更新宪法章程呢 小伙子多读读书

**Comment by lilewis** [comment]
忍不住我脑海又浮现了一副嘴脸^(*￣(oo)￣)^

**Comment by lilewis** [comment]
这么多年，头一次发现竟然是实时的😄

**Comment by MAYDAYHAO** [comment]
还是牛逼啊。，真的是实时聊天……

**Comment by dp199313** [comment]
你们这些英语水平不过关的就别去读说明了,很丢人.

**Comment by haohaohihi** [comment]
github又没推送，谁强制你看了啊？

**Comment by wintry** [comment]
@dp199313 就算我们英语不过关，但是我们会用翻译软件产品去阅读

**Comment by dp199313** [comment]
会用翻译软件很骄傲?那翻译翻译用户指南第一段?

**Comment by dp199313** [comment]
What is github?

**Comment by wintry** [comment]
你先去读读吧

**Comment by dp199313** [comment]
读用户指南为难你了,来给我翻译一下上面那句话 @wintry

**Comment by dp199313** [comment]
@wintry 找到用户指南位置了吗?需要帮助吗?

**Comment by hxuaj** [comment]
https://government.github.com/ 
了解一下

**Comment by firogh** [comment]
大学谁来尊重? 大学不是净土? 双标狗, 记住装逼, 就得被草.

**Comment by dp199313** [comment]
爱国青年和碍国青年们公共厕所不干净.你们就要去广场拉屎?这就是你们抗议方式,在本该干净的地方制造脏话,愤怒,这就是你们认为的道德,正义

**Comment by hxuaj** [comment]
@firogh 不要和井底之蛙一般见识，墙就是给这种人准备的。

**Comment by haohaohihi** [comment]
对，各位，没必要和dp这种人一般见识。

**Comment by xiaoyuhen** [comment]
工作找到了再来逛 github 吧

**Comment by JohnTian** [comment]
Here's how GitHub itself use GitHub. https://github.com/github/gov-takedowns
Just f*** off.

**Comment by zaishuiyixia** [comment]
你代表的了技术工作者？你知道他们愿不愿意看到啊？

**Comment by leciel-guo** [comment]
连说话的权利都没了，你跟我讲净土？

**Comment by Mioke** [comment]
好一个“制造混乱”

**Comment by dp199313** [comment]
技术中立,技术社区中立,那这么讲,你快饿死了就要去别人家抢东西

**Comment by Zheaoli** [comment]
https://github.com/github/gov-takedowns
看看 GitHub 怎么用 GitHub 再来说吧。

**Comment by gaocegege** [comment]
求求你，求求你们，看看 Terms of Service 花不了几分钟。为什么这样一个没有任何意义的问题会被翻来覆去地问？

> 这一类内容并没有被 GitHub 限制或禁止 https://help.github.com/articles/github-terms-of-service/#2-content-restrictions

**Comment by dp199313** [comment]
@gaocegege 虽然你可能英语水平可能限制了你阅读理解,但是还是感谢你们这些自以为是的人帮你们同类找到了文档.
+ 禁止发布任何违法内容
+ 禁止虐待任何团体和个人
+ 禁止发布煽动暴力的内容
其他的不一一列举了,至少违反一半禁止内容和行为

**Comment by gaocegege** [comment]
@dp199313 嗯我的英语是很差，也因此限制了我的发展。不过我还是想问问，这个 repo 违反了上述哪些条款，还请您赐教。

**Comment by Dr-Bluemond** [comment]
@dp199313 我英语还行能看懂，但是请你告诉我
1.你能举出哪条法律是这些文章违反的吗？
2.你能告诉我谁被虐待了吗？岳昕吗？
3.煽动谁来做什么暴力的事情？

**Comment by lilewis** [comment]
eeee...先不说文档的其他内容，就这三条，违法？虐待？煽动暴力？ 
这......无力吐槽了，我英文确实不太好，但是难道中文理解能力也有问题吗？还是你有问题？

**Comment by Declarcall** [comment]
问题是，这个平台不是你一国的。这下好了，全世界都知道了！

**Comment by lilewis** [comment]
大家！别被某些分子带跑偏了，咱们的目的只是支持作者要求信息公开的合理要求，和政治、派别等无关！无关！

**Comment by dp199313** [comment]
+ 阅读理解我没法教你们
+ 法律常识自己去补
+ 道德素养在于教育和自觉
+ 合适的地方,合适的场合,做合适的事,这是有自尊,以及懂得尊重他人的表现

**Comment by gaocegege** [comment]
@dp199313 抱歉，我在上海交通大学拿到了法学学士学位，但也实在没看懂到底什么内容有违上面的 ToS，能不能请你指出来？

**Comment by dp199313** [comment]
@gaocegege 骗自己开心就好

**Comment by gaocegege** [comment]
@dp199313 emmmmm OK

由衷地希望，我们各位都能够多了解一些法律知识。能理解您的观点，但并不认为这是对的。

**Comment by lilewis** [comment]
从下午到现在我眼看本repo 的star从2千~ 涨到3千~~，这个速度真惊人，这也意味着大家的共识基本一致。但不排除有一些文理理解能力差或者道貌岸然的人😔

**Comment by hxuaj** [comment]
说违反了规定，又不能自圆其说。
对于这种一叶障目的人，TOS甩他脸上也没用。大家说的东西可能触及到楼主的知识盲区了。怎么能要求一个井底之蛙和人的视野一样宽呢？这种人就是喜欢以自己的喜好衡量别人。所以也不用和不讲道理的人讲道理了。

**Comment by dp199313** [comment]
把一件好事能做到恶心人的程度的,只有你们这些个"名校高材生"了

**Comment by meteorlxy** [comment]
哎呀大家分析一下他的话术就知道了：
- 你们这帮辣鸡，什么都不知道不要来搞事，去看看xxxx吧
- 你们这帮辣鸡，英语水平不行，xxxx你们也看不懂的
- 你们这帮辣鸡，xxxx的英语能看懂，但是你们阅读理解不过关，不管你们怎么理解的，反正我就是根据这个可以推断：
- 你们这帮辣鸡

**Comment by dp199313** [comment]
@meteorlxy 你对你们的定位总结很贴切

**Comment by xiaowinner** [comment]
一个没有脊梁，不入流的程序员罢了。

**Comment by sylxjtu** [comment]
你的观点我在这里面已经反驳了

https://github.com/sikaozhe1997/Xin-Yue/pull/298

**Comment by Hasaki1997** [comment]
你如果有至少1000 followers,我还基本能听你一句,就你这种三无用户也配代表整个GitHub?

**Comment by Hasaki1997** [comment]
你没感受到所有人都在骂你吗...心里能有点数吗...

**Comment by ayaservice** [comment]
滚

**Comment by CreeperGo** [comment]
> 爱国青年和碍国青年们公共厕所不干净.你们就要去广场拉屎?这就是你们抗议方式,在本该干净的地方制造脏话,愤怒,这就是你们认为的道德,正义
1.公共厕所阻止过人们去广场，所以“去广场拉屎”就变成和公共厕所利益相关了？
2.当××的铁拳砸在你头上时不知道你做何感想
3.至于你说的扰乱社区，请问这个repo是给你推送到首页了还是给你发邮箱了，？
4.按照您的爱国少年定义，看来我们都该去面壁思过，然后去当个受到不公平对待甚至侵权行为还喊着乌托邦万岁的p民？:D

**Comment by Vargnatt** [comment]
![1524570013 1](https://user-images.githubusercontent.com/6397830/39184789-653426bc-47f7-11e8-89c1-6449179ba8c7.png)
啥都别说了，点进主页，左下角有一个report

**Comment by Vargnatt** [comment]
一些人可能不知道github是干什么的，也不知道什么叫技术中立。
他们以为技术中立就是使用技术的人应该保持中立，殊不知其实他们以最大的偏见对待每一个使用版本控制技术的人。
他们不明白什么是法律，也分不清法律和道德。这不是最大的问题，最大的问题是他们把自己的道德当做楷模。
他们不共情，并且用“别人不懂阅读理解”来掩饰自己对除了二流前端技术之外的无知，他们口口声声说着中立，其实在作恶。
我说的就是这个issue的initiator，一个需要被举报的人。

**Comment by ayaservice** [comment]
@Vargnatt 对政治的理解真有趣，实际上在中国之外的地方讨论政治本来就是正常生活的一部分。github上有各国宪法，宪法修正案，草案讨论，利用github保存版本和协作讨论本来就是它的正常用法。各国还有开放政府相关项目都在上面，只有到国内部分码农才有人觉得“不搭调”

**Comment by ayaservice** [comment]
ネタか？と思っていたら、本当に日本国憲法がGithubに上がっていた…。
https://t.co/9qM4to5X3b

**Comment by dp199313** [comment]
诸位可以辱骂我。诸位可以贬低我的技术及人格。诸位亦可抱团取暖。今天裹挟众人之诸位，就是明日被裹挟之人。若国民有辨别是非的能力何须一墙。君子不党。我无意再与你们做无谓的争辩。祥林嫂很可怜，岳昕也很可怜，死者更可怜。但当某一天你发现github上都是这些可怜人的时候，谁可怜。一个人带歪了风气，就必定有第二个。受了伤就要哭要闹的孩子，学会去解决合理地解决问题了才是心智成熟。用伤害自己以及伤害别人的方式来解决问题。只能体现出诸位的无能。这是个合作的社区，不是个对抗的社区。这里是开源共享精神体现的地方，不是卖惨的地方。这里是仓库，不是地区法律禁止信息的集散中转之地。若有公德与公心，应是心里有着对公共场合的尊重，不为一己之私而损人。若有理智与情志，应取得体之法为得体之事。

**Comment by gaocegege** [comment]
@dp199313 事实上，我只是想烦请您指教一下，这个 repo 到底哪里违背了 GitHub Terms of Service。您就当是为我们这些不知法者解惑，略作说明可以么

**Comment by Fanzwicky** [comment]
Next level provokotive stuff...
Good job moving towards post-materialism.

**Comment by Vargnatt** [comment]
> 受了伤就要哭要闹的孩子，学会去解决合理地解决问题了才是心智成熟。用伤害自己以及伤害别人的方式来解决问题。只能体现出诸位的无能。这是个合作的社区，不是个对抗的社区。这里是开源共享精神体现的地方，不是卖惨的地方。这里是仓库，不是地区法律禁止信息的集散中转之地。若有公德与公心，应是心里有着对公共场合的尊重，不为一己之私而损人。若有理智与情志，应取得体之法为得体之事。

如果你非要这么说以显示自己超然于世的自由自在赛仙圣；既要嘲讽我们关注的secular affair又不能做出任何secular的意见，反而非要给出了微信朋友圈式的哲思，那我就只有辱骂你了。
我倒是想知道你这样的人生导师知不知道：什么是法律？什么是道德？法律是如何产生的又是如何发展的？什么是法律应该管辖的，它的边际在哪里？你这么喜欢标榜integrity、这么喜欢言必称common good，那你有没有看过十九大报告的“深化依法治国实践”？
你只是像无能无德之辈一样，说着一些不着边际的话，就像是你除了写一些垃圾前端代码以外就只会看一些uc震惊中国人。这样做的你，优越感一定很强吧。
我们为校友发声、为同是大学生的陌生人发声、为不公平的抗争发声、为了解事实发声，这么说来我们的确很惨，毕竟我们的社会生产还不是极大完善、资源分配还没有极大丰富、又缺少你这样的精神力量，只能羡慕你吃够了肉糜，长得如同歌利亚一般威武雄壮，还有空教导别人不要过得太惨——至少不要拿出来卖。但是既然这样的话你为什么只能commit一堆三流前端代码？你充足的时间难道都没有用来传播你圣洁的开源共享精神吗？

我真的，好好奇哦。顺便问一句你配姓赵吗？

**Comment by sylxjtu** [comment]
https://github.com/sikaozhe1997/Xin-Yue/issues/371

真是阴阳怪气啊

**Comment by ziystory** [comment]
> 若国民有辨别是非的能力何须一墙。君子不党。我无意再与你们做无谓的争辩。祥林嫂很可怜，岳昕也很可怜，死者更可怜。但当某一天你发现github上都是这些可怜人的时候，谁可怜。一个人带歪了风气，就必定有第二个。受了伤就要哭要闹的孩子，学会去解决合理地解决问题了才是心智成熟。

当看到上面这句话的时候，大家其实也没必要和他说了。
