### ISSUE TITLE
github已经被当成社交平台了啊 

### ISSUE THREAD

**Issue by flufy3d** [sikaozhe1997/Xin-Yue#325]
厉害了

区块链微博  了解一下 memo.cash
https://memo.cash/post/f143b371da9e7320665d2d1e13f283666d8ac6da48d88e6583ee9af4c3a73f31

**Comment by Dr-Bluemond** [comment]
思路清奇，用户体验较差

**Comment by Dr-Bluemond** [comment]
If memo were to be blocked, who would be in charge of selecting messages from block chains?

**Comment by asklogic** [comment]
py圈看到的一句话：

区块链里数据那么珍贵 放什么好呢

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
