### ISSUE TITLE
haha

### ISSUE THREAD

**Issue by xuan11235813** [sikaozhe1997/Xin-Yue#326]

**Comment by Seedarchangel** [comment]
Oh Really?
Piss off friend

**Comment by SallyKAN** [comment]
I feel fucking sorry for you

**Comment by firogh** [comment]
你这嘴和屁眼子有什么区别. 先自尊吧.

**Comment by merlinengine** [comment]
@xuan11235813 豬國人也學了英文？

**Comment by TinaHongBu** [comment]
hehehehe you are so proud of yourself that you have 5 followers?

**Comment by xuan11235813** [comment]
@TinaHongBu  "1 more follower" not means "more than one followers"..please relearn your elementary english courses....
