### ISSUE TITLE
今天才知道github没被墙

### ISSUE THREAD

**Issue by mutou172** [sikaozhe1997/Xin-Yue#327]
刚刚试了一下关闭才知道的
不过开着它已经成为习惯了.....
还有那些说担心什么的,你们只是想着自己的利益不受波及.
说明github有利于他们的地方，
墙了，说明危及到了他们，他们很敏感，很不自信
或许还能证明“落后就挨打”是一句屁话

回头看了看，我用v..在google查了代码资料
为了新鲜感注册推（关注了几个名人），face（加了一个好友。。。），油管（订阅了几个视频）；油管一周看了几次吧歌曲mv什么的
上班，下班做些生活琐事，看一两篇技术文章，玩一两局王者都没时间了。。。

时间久，我渐渐地也麻木了，但还是可以，给某些人捐个五毛；当我有饭吃时,请某些人吃顿饭，并希望他们活着。
希望这些勇士好好的，平安的，健康的，
希望不要影响或过大的影响你们的将来，你们没有错，他们为了光鲜声誉而隐藏污垢是可耻的
我觉得危机公关应该是积极地向上地努力地
北大这是消极公关，北大可能不会扩大宣传，但也不应该这么消极处理事件
北大作为北大，应该拿出北大的样子来。
唉。
上午写的，本不想发的。之前只知道“沈阳事件”，现在既然知道了这件事，也表个态吧！

**Comment by tanoak10** [comment]
然后你的态度呢
