### ISSUE TITLE
Poem

### ISSUE THREAD

**Issue by Yanstory** [sikaozhe1997/Xin-Yue#328]
> The world belongs to you, and us.
> However,in the end,it's you that can hold the world.
> You youth are active,in the best age.
> You're like the sun in the morning.
> Hope of the society is on you.
> The world belongs to you.
> The future of the country belongs to you.

**Comment by csrgxtu** [comment]
you belong to me

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
