### ISSUE TITLE
PR:添加辅导员回复

### ISSUE THREAD

**Issue by RicardoWang99** [sikaozhe1997/Xin-Yue#33]
[北大未名原帖链接](https://bbs.pku.edu.cn/v2/mobile/post-read.php?bid=64&threadid=16393718&from=groupmessage&isappinstalled=0)

建议在readme下统一一下文件的命名规范like this:

`[1983-12-32]Name:Title.md`

一些小建议:可以用wiki或者用readme记录一下全过程的timeline

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
