### ISSUE TITLE
别哪天github我们都访问不了了。。。

### ISSUE THREAD

**Issue by fengbai** [sikaozhe1997/Xin-Yue#333]

**Comment by csrgxtu** [comment]
大哥，不要因为害怕就不敢看，不说，然后任由泛滥。

**Comment by csrgxtu** [comment]
github访问不了了，我们就用国内的code caffe

**Comment by fengbai** [comment]
我微信转发的都已经被删完了，

**Comment by HDYA** [comment]
@csrgxtu 不是那么简单的事情

**Comment by Dr-Bluemond** [comment]
Since I have my own ladder, I don't care whether github would be blocked.

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by 2efPer** [comment]
已经被墙了这么多了，多个github不在乎了，翻墙都是程序员标配了

**Comment by swwind** [comment]
github 被墙你们就真的一点都不在乎？

**Comment by csrgxtu** [comment]
@HDYA  恩恩，是的。但是不要因为怕就不说了。

**Comment by meteorlxy** [comment]
google不也是被墙，该用一样用。

**Comment by EliezerWu** [comment]
we have blockchain

**Comment by wkmcyz** [comment]
继续说，coding很喜欢

**Comment by HDYA** [comment]
@csrgxtu 我不怕所以我选择不在技术社区谈政治←←

**Comment by HDYA** [comment]
@Dr-Bluemond Does it make any difference for package managers relying on GitHub, for other developers and even ordinary users facing potential impact?

**Comment by Dr-Bluemond** [comment]
@HDYA Well. When everyone needs to have their ways to bypass the restriction of the gfw, it would be necessary to figure out more and more ways to do so. Then China might cut down the Internet or use white list mode to avoid this, which would further irritate Chinese people and cause unstable.  That's my opinions

**Comment by lowy** [comment]
嗯 应该谢主隆恩 赐予我们github的访问与使用 愿GFW与你同在

**Comment by wangduheng** [comment]
github甲不能访问，自然有github乙来代替，你需要要操心天别塌下来就好了

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
