### ISSUE TITLE
不得不说这公关做的很不错

### ISSUE THREAD

**Issue by thaixp** [sikaozhe1997/Xin-Yue#334]
![np6 7 a3yrgwg_s qwd1 f](https://user-images.githubusercontent.com/23304696/39180548-c46bf596-47e9-11e8-9efb-8aadc9a7fd66.png)

**Comment by csrgxtu** [comment]
就是危险网站，国外最大的同性基友平台。

**Comment by mutou172** [comment]
我也觉得是危险网站，有可能把他们惊醒。QQ好友多，我被捆绑了，不然QQ也是被弃的对象，说到底是圈子问题。

**Comment by StarryVoid** [comment]
于是国内所谓的网站安全联盟，交钱申请就是安全的。可以自己体验。

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by Hadron67** [comment]
可以看一下#285

**Comment by kilobtye** [comment]
Duplicate of #285
