### ISSUE TITLE
理中客不少啊

### ISSUE THREAD

**Issue by AlexiaChen** [sikaozhe1997/Xin-Yue#336]
呵呵

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
