### ISSUE TITLE
该repo已被微信和谐

### ISSUE THREAD

**Issue by lybc** [sikaozhe1997/Xin-Yue#340]
其他GitHub项目可在微信正常访问

![image](https://user-images.githubusercontent.com/9601872/39182343-3379b7b6-47ef-11e8-8347-b0ef9a61bba3.png)

**Comment by AiQLee** [comment]
可以fork一下，再发自己fork的项目地址。。。

**Comment by Hadron67** [comment]
见#285

**Comment by kilobtye** [comment]
Duplicate of #285
