### ISSUE TITLE
我是程序员，我支持大家在这里畅所欲言

### ISSUE THREAD

**Issue by zyfdegh** [sikaozhe1997/Xin-Yue#344]
对部分持 “这里只允许技术相关讨论” 的人，我想说：GitHub 又不是你家的，怎么用关你卵事。另外，适应 “新时代” 的反审查聊天软件、论坛急需开发了，这才是有常识、有良知的程序员应该关心的。将对此事持续关注

**Comment by haohaohihi** [comment]
同程序员bd

**Comment by ayaservice** [comment]
在中华人民共和国现阶段互联网时代需要言论自由，只需微博删贴，不需技术发声吗？

**Comment by Cap32** [comment]
希望珍惜不用翻墙上的 GitHub 的日子

**Comment by IvanWangBo** [comment]
顶

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
