### ISSUE TITLE
北大和武理工还真是难兄难弟啊，也请求众网友关注下陶的事件，仓库链接在正文。

### ISSUE THREAD

**Issue by DFVSQY** [sikaozhe1997/Xin-Yue#345]
[陶崇园永久真相档案库](https://github.com/lonufate/ArchivesOfTaoChongyuan)

**Comment by yyong119** [comment]
加油吧

**Comment by tsai1993** [comment]
凑个热闹 https://github.com/Info-cn/Terminus

**Comment by CONNERYEP** [comment]
这个人到底是为什么要这么恶心我真的想不通，最无耻的是在发所谓的悼文的时候还要从死者角度去吹嘘自己一番，事后竟认为这是因为学生不能够忍受自己的恶心行径心理建设不够强大，真的是无耻无畏

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
