### ISSUE TITLE
发言请不要代表程序员群体

### ISSUE THREAD

**Issue by sylxjtu** [sikaozhe1997/Xin-Yue#347]
在座的哪一位认为自己一个人能干所有程序员的工作？如果有人觉得可以的话，那随便代表，我们都没意见。

**Comment by sylxjtu** [comment]
https://github.com/sikaozhe1997/Xin-Yue/issues/83

**Comment by sylxjtu** [comment]
https://github.com/sikaozhe1997/Xin-Yue/issues/324

**Comment by WangNianyi2001** [comment]
enmm 捉个虫，兄弟
应该是『别打着程序员的旗号来这瞎tm水军』
（还是相信大部分人包括猿们是有自己的是非观的）
嗯就酱

**Comment by sylxjtu** [comment]
反正就这个意思吧，具体这个事情我没有激进的观点，我只想让这个repo下面的issue清净一点，不要一会来一个就精神github股东，一会又来一个“开源世界的代表”。还有想挑起程序员和非程序员之间的矛盾的，想挑起学生和社会人之间的矛盾的，想挑起大学之间的矛盾的。这样斗来斗去事情还是不能解决。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
