### ISSUE TITLE
每次这种事我都会想到这段著名的话

### ISSUE THREAD

**Issue by vanishcode** [sikaozhe1997/Xin-Yue#349]
“他们追杀共产主义者的时候，我没有说话——因为我不是共产主义者；
他们追杀犹太人的时候，我没有说话——因为我不是犹太人；
他们追杀工会成员的时候，我没有说话——因为我不是工会成员；
他们追杀天主教徒的时候，我没有说话——因为我是新教教徒；
最后他们奔我而来，已经没有人能为我说话了。”         ——马丁·尼莫拉牧师

**Comment by sunvincent** [comment]
愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般，也可以在黑暗里发一点光，不必等候炬火。此后如竟没有炬火：我便是唯一的光。倘若有了炬火，出了太阳，我们自然心悦诚服的消失，不但毫无不平，而且还要随喜赞美这炬火或太阳；因为他照了人类，连我都在内。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
