### ISSUE TITLE
家耻却只能在这里诉说

### ISSUE THREAD

**Issue by thenoNOno** [sikaozhe1997/Xin-Yue#350]
见不善而不能退,退而不能远,过也

**Comment by haohaohihi** [comment]
唉

**Comment by daijiang** [comment]
这个 repo 也已经被墙了。哎，北大势力真大啊。

**Comment by killTheHostage** [comment]
@channel960608 是被自查势力屏蔽了

**Comment by daijiang** [comment]
@channel960608 至少被微信墙了。

**Comment by channel960608** [comment]
@daijiang 被墙和链接被屏蔽是两回事情好吗，一个主体是微信客户端，一个主题是中国互联网，性质不一样的

**Comment by TinaHongBu** [comment]
在中国想体面的维权真难

**Comment by wydwww** [comment]
@channel960608 [微信 = GFW](https://blog.yitianshijie.net/2018/02/02/wechat-equals-gfw/)

**Comment by WangNianyi2001** [comment]
@wydwww 不存在的吧……国房网貌似还没高级到屏蔽具体 url 的地步吧233
只是蔡氏变异后代和鹅厂围脖串通一气罢了

**Comment by wydwww** [comment]
@WangNianyi2001 您可能没有点开我发的那个链接

> 在今天微信已经成为很多中国人事实上的浏览器的情况下，它对域名的封锁在实际效果上已经接近 GFW 的封锁：微信无法打开的链接，对大部分人而言就是打不开的链接。单单这一点，就足以成为不用微信的理由。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
