### ISSUE TITLE
Repo毕竟还是可以删的，有人弄个区块链版的微博不

### ISSUE THREAD

**Issue by XUJINKAI** [sikaozhe1997/Xin-Yue#352]
往简单易用了弄，感觉很有前途，受那个交易链接启发

**Comment by goldimax** [comment]
ZeroNet可以搞 但是那玩意官网被墙了

**Comment by gaoxiaosong** [comment]
ZeroNet，翻墙下载下来，后续不用翻墙。。

**Comment by XUJINKAI** [comment]
@goldimax @gaoxiaosong 感谢，下载试了下挺好用，不过不仅要翻墙下载，还得翻墙更新节点。。。看来还是GitHub对大部分人更容易一些

**Comment by YoungSx** [comment]
已经有人发到ETH了

**Comment by YoungSx** [comment]
https://etherscan.io/tx/0x2d6a7b0f6adeff38423d4c62cd8b6ccb708ddad85da5d3d06756ad4d8a04a6a2?from=timeline&isappinstalled=0

**Comment by XUJINKAI** [comment]
@YoungSx 就是受这条链接启发的，不过看二三楼 已经有这个东西了

**Comment by gaoxiaosong** [comment]
@XUJINKAI 之后更新不用翻墙啊。。

**Comment by XUJINKAI** [comment]
@gaoxiaosong 第一次打开需要，看issue说是tracker被墙了

**Comment by gaoxiaosong** [comment]
@XUJINKAI 第一次确实需要。。注册id需要，后面就不需要了。。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
