### ISSUE TITLE
分析下岳昕同学能不能顺利毕业?

### ISSUE THREAD

**Issue by zhichiyuexin** [sikaozhe1997/Xin-Yue#353]
把岳昕同学的事情放到自己身上想想都很可怕,我也是个大四学生,深知毕不了业对一个大四学生的打击有多大,就像那个被跨省抓捕的医生一样,他们也只是个有正义感的普通人,却没想到惹出这么大的祸,医生尚且有国家力挺,学生,呵呵!

为什么我会有这样的疑问.毕业证被扣基本上是老生长谈的问题了,连平时不好好干活都会被扣,更别说现在这种非常严重的事情了,如果因为这件事岳昕同学无法毕业,并且家庭关系因此崩溃,那对一个人的心理摧残可想而知.

所以真的希望有能力的人能帮助她!

**Comment by zkcpku** [comment]
*她能把毕业论文写完之后就能毕业了......校内并没有关于学姐不能毕业的消息*
*还有，我并不知道为什么有人会认为学姐被控制，在github上也要兼听则明吧*

**Comment by zhichiyuexin** [comment]
@zkcpku 学校会这么轻易的放过她?至少现在学校已经把她的生活搞崩溃了,都回家了

**Comment by zkcpku** [comment]
学校如何处理也是你我的猜测，我也只是感觉您说的法律途径解决毕业问题有点太夸张了
**学校并未发表任何以毕业要挟的话语**个人感觉您有点偏激了，也有点太夹杂个人猜测了

**Comment by nidada** [comment]
她要是很坚强就可以毕业，但很痛苦，看看她现在的状态。母亲如何如何。。。。这是心理战吗。。。。

**Comment by zhichiyuexin** [comment]
好吧,我改了

**Comment by zhichiyuexin** [comment]
@nidada 我也感觉她现在肯定非常痛苦,我现在都不敢在朋友圈发表任何观点了,埃,希望广大网友能给她一点希望吧,不要又让一个家庭破碎

**Comment by nidada** [comment]
@zhi xhi yue xin我想和你聊聊具体的事儿用微信可以吗

**Comment by nidada** [comment]
@zhi xhi yue xin我想和你聊聊具体的事儿用微信可以吗

**Comment by nidada** [comment]
此处省略

**Comment by zhichiyuexin** [comment]
@nidada 算了吧,我没毕业,胆小怕事

**Comment by nidada** [comment]
你已经卷进来了。。。我是做计算机的，很清楚网络行为。没什么，只要不犯法

**Comment by nidada** [comment]
你已经卷进来了。。。我是做计算机的，很清楚网络行为。没什么，只要不犯法

**Comment by Uyouii** [comment]
@zkcpku 毕业肯定是学校的筹码呀，让一个学生延期毕业的手段太多了

**Comment by nidada** [comment]
其实这也是你们年纪太小了，一腔热血涌上头，事不机敏，反遭其累。熬过去就成熟了，小时候受些罪，是好的。

**Comment by zhichiyuexin** [comment]
@nidada 可能真是做事没考虑后果,想想以后我也不会用真实身份发表反对言论,承受不起后果,但是这事情感觉不是一个20几岁的大学生能熬过去的,即使熬过去了,心理也会出问题,除非有个合理的结局

**Comment by nidada** [comment]
@zhichiyuexin 我建议你们如果有条件，好好看着她，就组成个心理辅导医生小组给她，她的心里压力太大了，很容易出事故，不要再和学校硬着来了，现在成本太高了，要求事半功倍，可以用法律途径讨个公道的，而非用错误的方法，但不是现在，我的qq是2240342910

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
