### ISSUE TITLE
各位为啥不换ZeroNet讨论

### ISSUE THREAD

**Issue by gaoxiaosong** [sikaozhe1997/Xin-Yue#354]
上面微博、博客都有。。翻个墙下载之后，后续就不用翻墙了。。

有精力在Github上扯淡，没精力去试试Zeronet。。我知道Github是不禁止这些，然而一两天就冲到Trending第一，真觉得政府不会封么，又不是没封过。还有那些会翻墙的，说不会翻墙的开发什么程序的人，也就是键盘侠，或者对Github毫无感情，非要祸害死Github才算完。。别贴其他仓库的，看看Star数心里没点B-Tree么。。。
官网：www.zeronet.io

**Comment by dp199313** [comment]
因为北大学子没听过其他可以不被墙的手段。

**Comment by gaoxiaosong** [comment]
有精力在Github上扯淡，没精力去试试Zeronet。。我知道Github是不禁止这些，然而一两天就冲到Trending第一，真觉得政府不会封么，又不是没封过。还有那些会翻墙的，说不会翻墙的开发什么程序的人，也就是键盘侠，或者对Github毫无感情，非要祸害死Github才算完。。别贴其他仓库的，看看Star数心里没点B-Tree么。。。
官网：www.zeronet.io

**Comment by YoungSx** [comment]
一大批“正义人士”即将到来

**Comment by CPCer** [comment]
大概需要您尽力科普宣传咯。
用您毕生精力干这个，怎么样
