### ISSUE TITLE
别怕。

### ISSUE THREAD

**Issue by ddos4500** [sikaozhe1997/Xin-Yue#360]
在这里说没有关系的。我查阅了半个小时服务条款，没说不许。都是用着github的同学，难不成隔壁的ssr梯子不会拖下去编译不成？github被大规模攻击次数多了去了，怕个甚？

**Comment by dp199313** [comment]
就凭你这句我就得赞你一个，怕啥?我们北大交大校园网就能翻墙。30几块vpn都买不起的穷逼，写什么程序？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
