### ISSUE TITLE
这类政治相关的事情发长 Twitter 更合适？

### ISSUE THREAD

**Issue by texzhichen** [sikaozhe1997/Xin-Yue#363]
1. 根据 GitHub 自己的 [About](https://github.com/about)，人家是 a community where more than 27 million people learn, share, and work together to build software. GitHub 是家私人公司，其商业模式是靠企业级 git repo 盈利，如果因为这类不属于软件的事情导致国内公司都不再会考虑付费使用 GitHub，以致 GitHub 的商业利益受损，我不知道 repo 主明明有其它平台选择却把政治事件挂在 GitHub 上的目的何在？

2. Twitter 现在支持长文章、平台本身欢迎发表政治类事件、有大号可以转发、且他们的信息流广告商业模式对这类容易引起广泛讨论的文章相得益彰。比起 GitHub，显然 Twitter 更适合发布这类政治相关的文章。

**Comment by mghlrng** [comment]
个人斗胆猜测一下用github的逻辑吧。用github的原因是希望文章不被删除，而不用twitter的原因是不希望被外媒利用使事件升级。如果被“境外势利”利用，对当事人的影响可能就难以估计了。不知道这样理解是否正确。

**Comment by WangNianyi2001** [comment]
支持 @mghlrng 的说法，另外发 twitter 国内大部分人看不到呀（

**Comment by mghlrng** [comment]
刚刚搜了一下，已经在twitter有传了。

**Comment by iBug** [comment]
#406

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
