### ISSUE TITLE
为啥要来祸害GitHub。。。

### ISSUE THREAD

**Issue by chengdong0421** [sikaozhe1997/Xin-Yue#364]
对此事被压制表示愤慨，但求不要把火往GitHub上引啊。。。

**Comment by firogh** [comment]
真是是不关己高高挂起, 回去好好想, 如果当年被性侵的是你妈, 喊冤而死, 你还能说出这话吗?

**Comment by tangtangtangtangtang** [comment]
如果天总也不亮，那就摸黑过生活；如果发出声音是危险的，那就保持沉默；如果自觉无力发光，那就别去照亮别人。但是，不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意洋洋；不要嘲讽那些比自己更勇敢、更有热量的人们。可以卑微如尘土，不可扭曲如蛆虫。

**Comment by tigermount** [comment]
好奇怪的论调，我刚刚查了查，GitHub还是在美国吧？党妈手伸的这么长，连在美国说话都要管？

**Comment by chengdong0421** [comment]
@firogh 你这么关心你写信给国务院不就行了，在这里讨论来讨论去就可以把事情解决了？

**Comment by tigermount** [comment]
@chengdong0421 人家爱写在哪里是人家的自由吧？你这么不爽写信给国务院检举他好了。

**Comment by chengdong0421** [comment]
@tigermount 那又关你什么事呢？

**Comment by VictoryWangCN** [comment]
sb

**Comment by chengdong0421** [comment]
@VictoryWangCN 你很有自知之明

**Comment by VictoryWangCN** [comment]
@chengdong0421 你这是狗？我点你名了？
