### ISSUE TITLE
惊了！

### ISSUE THREAD

**Issue by xujh0824** [sikaozhe1997/Xin-Yue#366]
突然看到油管VOA在直播这个事件！“2018.4.24话题：北大学生要求信息公开，为何这么难？”

**Comment by gaoxiaosong** [comment]
看了两眼，在扯些啥乱七八糟的。。少看VOA保智商。。

**Comment by xujh0824** [comment]
gaoxiaosong   起码看到有媒体在报道了……

**Comment by gaoxiaosong** [comment]
@xujh0824 跟听新闻联播感觉差不多，差点没睡着了，那个带着耳机的男的说话调子太犯困了。。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
