### ISSUE TITLE
作為一個台灣人，路過講幾句話

### ISSUE THREAD

**Issue by bater** [sikaozhe1997/Xin-Yue#369]
一個國家體制欺負一個小女生，你們居然只關心github會不會被和諧？
有人站起來抵抗社會的不公義，難道不也是為你們的家人：母親、姐妹、兒女發聲嗎？

台灣人是怎麼狗幹到國民黨跪下，這點你們應該要學學。
祝你們一切安好

**Comment by xujh0824** [comment]
哎，果然生活在自由氛围环境下人的思想就是不一样

**Comment by zhaobenx** [comment]
但你也要看到，所有反对使用github下踩的人有多少，谁是多数谁是少数很明显

**Comment by zhongxigong** [comment]
目前的中国大陆，言论自由被严格控制，宪法赋予的言论自由被国家网信办阉割。在国内的所有社交平台上看不到任何反对的声音，有的只是普大喜奔。

**Comment by SiskonEmilia** [comment]
楼上可能没见过网易

**Comment by xujh0824** [comment]
gaoxiaosong    网易新闻还是算了吧……评论区没法看

**Comment by huoji555** [comment]
知乎上可以试着发下

**Comment by GONGCHEN1003** [comment]
楼下一个男人病得要死，那间壁的一家唱着留声机；对面是弄孩子。楼上有两人狂笑；还有打牌声。河中的船上有女人哭着她死去的母亲。人类的悲欢并不相通，我只觉得他们吵闹。  
可能那些人是这么想的吧

**Comment by xujh0824** [comment]
huoji555 知乎现在也是管控的重要地方，前段时间不是才被下架app做处罚了么……

**Comment by tomfriwel** [comment]
最近在一篇关于鸿茅药酒事件的文章里看到这么一句话：

“民不与富斗，富不与官争”

不能以偏概全，但它的确真实存在，就像一种潜规则存在着。

比如各种知名社交平台（“富”）都会对一些关键词进行处理。很少会具体说明其原因（“官”）。

虽然很少人直接说出来，但大家（“民”）都懂（“潜规则”）。

**Comment by FloydaGithub** [comment]
不是嘲讽, 客观的说, 国民党撤到台湾不是没有道理的.
