### ISSUE TITLE
牺牲一下github怎么了？

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#371]
我们北大的学生啥时候受过这样的委屈？
github谁规定不能用来发微博了？
其他外国网站像谷歌又不是没被墙过？
今天你不和我们站起来反抗，明天被叫兽草的就是你。
我们交大的法学博士是告诉你们，国内不允许发的消息只是违法了中国法律。
别和我们说什么区块链，那东西新鲜玩意哪有github用户多。
我们海龟有学之士告诉你们我们不仅在开源社区讨论宪法。我们还在东京热网站上讨论安倍晋三。
我们过不好，你们也别想好过。
我们香港有骨气的学生最受不了这个了，敢和我作对我就让你们开车上不了道。
我们是国家的希望合理诉求。

**Comment by twx314** [comment]
天底下受委屈的人多了，就你们娇情。要发声去推特脸谱去。

**Comment by sylxjtu** [comment]
真是阴阳怪气，怎么不回你之前那个issue了？

**Comment by chengdong0421** [comment]
有些issue下面的有些人动不动就是“你国”、“猪国”是几个意思。。。难道不是中国人吗？他们看似代表正义，实际上包藏祸心，和这几天“精日”的田佳良是一路人吧

**Comment by dp199313** [comment]
我们没别的本事，我们说话又没人听得见。我们不到处贴怎么行。在中国这个大环境里，我们不闹事怎么解决问题。我们才不管当初为啥要支持岳昕同学，现在反正那些被奴隶惯了的人说我们影响他们工作了，那就是跟那些强权分子一样，他们这个社区我们还就和他们斗争到底。我的同学遭遇这么可怜了，难道这些人都没有同情心吗？整个国家的人都这样，国家要完了。

**Comment by firogh** [comment]
@chengdong0421  中国的人向来是最缺自知之明的, 人家嘴上说国家是你的, 你就信以为真?  从你出生那天这个国家就连一天都不属于绝你, 诚然, 你出生在这片土地, 但是你国被偷走了. 没有选票, 只能是奴隶长工, 竟然, 这样也好, 可千万不能做那奴才!

**Comment by WincerChan** [comment]
怎么不到你之前那个repo讨论了，喔，原来被你关闭了，害怕了？

**Comment by MAYDAYHAO** [comment]
你这前言不搭后语啊。你的issue怎么不回复了

**Comment by WincerChan** [comment]
上一个issue被教育得没脾气了，又另起一个新的issue换一种论调在这阴阳怪气，很好玩？

**Comment by Vargnatt** [comment]
都举报你了你怎么了还没有被你心里伟大圣洁的开源社区教育？
说的所有话都只会离题万里，你倒是解答一下问题：什么叫违反社区规定？什么叫违反法律法规？什么叫“不是地区法律禁止信息的集散中转之地”？什么叫“对公共场合的尊重”？

就事论事，你就是既不懂法律又不懂道德还不懂github的ToS。论阴阳怪气，你也只会离题万里，拜托请嘲讽到点子上，学着说反话的时候多看一看莫言，不要像一个小学生一样从不知道什么地方的句子里面学一两句，发出振聋发聩的groaning babyrage.

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
