### ISSUE TITLE
比被体制阉割更可悲的是自我阉割。

### ISSUE THREAD

**Issue by iVeego** [sikaozhe1997/Xin-Yue#373]
GitHub被封了，就去抗议GitHub被封这件事。而不是在被封之前，就先自我阉割。一步一步的退让的结果就是，不知道什么时候，你写的代码都政治敏感了。

**Comment by Everttylestevan** [comment]
莫名想到微信的版本號永遠跳過 x.6.4 或者 6.4.x

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
