### ISSUE TITLE
在这里其实我都不太敢说话，奴性吗？

### ISSUE THREAD

**Issue by shinkeika** [sikaozhe1997/Xin-Yue#375]

**Comment by tangtangtangtangtang** [comment]
怕是人之常情，不去冷嘲热讽发声的勇士就不算奴性

**Comment by nidada** [comment]
害怕是人之常情

**Comment by nidada** [comment]
害怕是人之常情

**Comment by zhichiyuexin** [comment]
不是奴性,因为你已经意识到了,但在这不用怕吧,注册个小号,没人知道你

**Comment by zhichiyuexin** [comment]
我就专门注册了个小号

**Comment by KenshinAsai** [comment]
毕竟大多数人还要赡养抚养，背着车贷房贷小心翼翼地生活着；不逃避，理性讨论，扩大影响力已经算出力了吧。
害怕的是如果在如此大环境中麻木下去，再过十年会是什么样呢

**Comment by AndreHelle** [comment]
为众人抱薪者，都已死绝。

**Comment by zyfdegh** [comment]
习惯了自我审查（self censorship），就像放到水中的鱼一时半会不会游一样。斯大林主义的遗毒

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
