### ISSUE TITLE
文档存档在github并没有错；不要把issue搞得乌烟瘴气

### ISSUE THREAD

**Issue by channel960608** [sikaozhe1997/Xin-Yue#377]
很多人把issue当做发泄的途径了，以至于把很多在其他地方会被屏蔽掉的话像倒垃圾一样全都扔到了issue这个版块，甚至这里面掺杂着什么繁体党，反华党，还看到有人为fa lun正名的我的天。逞口舌之快之前，别忘了这个repoi初衷是什么，多为岳同学想办法。现在想想，如果微博不能进行舆论控制，可能早就被下架了，你们还能把微博当做是舆论监督的利器吗。如果因为垃圾话，github上的这个repo被屏蔽了，下一步这个存档是不是只能扔国外仓库了？

**Comment by wql7013** [comment]
同意，issues越来越多了，提议不要发太多的new issue了，想发言找相应的issue，重复性的、发泄性的issue建议关掉。

**Comment by WincerChan** [comment]
兄dei，你这头像😆

**Comment by XiaoxingChen** [comment]
哥们你这头像比反华党还反华啊。。

**Comment by xxtlant** [comment]
表示赞同，但是兄dei你这头像。。。

**Comment by huoqiangf** [comment]
Duplicated with #364 #324 #271 #223
Please stop spamming and abusing github issues

**Comment by yixuantw** [comment]
總算看到不是以「不要污染Github」為幌子實則想諷刺幾個學生為鍵盤俠的了。這纔是真為岳同學著想也真想解決問題的。

**Comment by TemmieFromMars** [comment]
看着一片issue感觉跟进了微博一样…
