### ISSUE TITLE
热血请用在正确的地方。

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#378]
学生是一个很有朝气的群体。
我自己亦是刚毕业不久的学生。
步入社会我一直在做的事情就是反抗这个对年轻人不友好的社会。
我相信学生们声援岳昕同学的初衷是好的。
我亦是热血之青年，所以我会在这和你们撕逼。
既是有正义感，有热血之人，也请理智发言。
github不是北大bbs。
诸位热血之人尽可做热血之事，不必泄愤于此，徒耗精力，又惹人厌烦。
若真要泄愤，亦或是广而告之，游行，抗议如何不能成事？
偏要在网络的庇护下怼一下同族来满足自己的需求。
有人带头在这里做了这件事，下回谁受了委屈亦有效仿，最终买单的不是你们这些学生。

**Comment by dp199313** [comment]
有何不妥。本人文采好。用三种不同方式怼你们这些，键盘侠怎样。
第一篇说各位无知。
第二篇主题说各位自私自利头脑简单。
第三篇说各位已忘初心只敢网络泄愤。

**Comment by rmctJ** [comment]
楼主既然知道”泄愤于此“是”徒耗精力“、”惹人厌烦“，自己又为何在此”徒耗精力“？
又说自己”一直在做的事情就是反抗这个对年轻人不友好的社会“，并且还支持”游行、抗议“，那真是太好了，支持楼主亮出自己的线下身份，带头上街为岳同学抗议，给这群只会在github里”徒耗精力“的人做个表率。

**Comment by TinaHongBu** [comment]
为什么这么多人在这儿装外宾？我当然希望体面的发声， 如果这是个可以随时游行抗议的国家。微博被禁微信被删媒体失声不得已在毫无群众影响力的 GitHub 整理一些文字，还要被说不够理智？

**Comment by dp199313** [comment]
我可没说过我比在座的各位有种。我的重点只是以上那三条。我为了维护github的氛围而战，诸位为把自己平时不敢发泄的愤怒而喷。只不过你们好像忘了最初的目的是惩恶扬善

**Comment by reng99** [comment]
假装心平气和得看完三个issue～～～

**Comment by merlinengine** [comment]
@dp199313 豬國老大說了句『莫忘初心』，所有的豬都跟著『初心初心』，結果連『芯』和臉都丟盡了。你豬還舔著臉說『初心』呢。

**Comment by Vargnatt** [comment]
> 有何不妥。本人文采好。用三种不同方式怼你们这些，键盘侠怎样。
> 第一篇说各位无知。
> 第二篇主题说各位自私自利头脑简单。
> 第三篇说各位已忘初心只敢网络泄愤。

你的文采好个屁，你要真的语文那么好至于深造于职业发展学院？
github的氛围不是你定义的，是用户自发形成的。没有人不能在一个版本控制/内容托管网站上发表站方禁止的内容，反而是你，跑到别人的repo底下满嘴仁义道德其实只是因为你发现别人跟你不一样。
所以这些就是你开展朋友圈哲学讨论issue兼职人生导师，我可不想被一个蠢货指导应该怎么样遵守github的ToS和怎么符合一个蠢货的道德标准。


一口一个“你们学生”“得体”“有理有志”，你真的知道你指代的都是什么吗？你真的查过字典明白各种词语的正确意思吗？
你没有，因为你蠢，因为你不懂语文，因为你只能去职业技术学院。

**Comment by WeiJiaoWuMaoDang** [comment]
@dp199313 “我为了维护github的氛围而战”， “我一直在做的事情就是反抗这个对年轻人不友好的社会”，那么请你讲讲你反抗这个不友好的社会的经历吧，希望你不是只在这里维护你认为的“github氛围”。

**Comment by 513286483** [comment]
你如果身为一个码农，github让墙了你就上不了了，你怎么不go die?

**Comment by rockywhisper** [comment]
@dp199313  

关注我们认为不公正的事情，也是一种支持，这也是一种抗争方式。
奉劝楼主不要只沉溺于自己的小世界中，团结的力量才是伟大的。

都希望社会变好，国家变好，大家心里是妥妥的正能量。热血正直的中国人没有过错，所争的事情坦坦荡荡、明明白白，最终能够合理、透明、公正地解决，这才是众人所愿。

**Comment by rockywhisper** [comment]
@dp199313 

到处戾气很重，营造的社会环境就是这样，没法避免。
不信你可看看部分官方微博，只需喊一个口号下面评论纷纷高潮。你说的热血可能也有出处吧，希望你能去那里评论一番，让真的热血上头的国人冷静、奋进，绝对是你的功德，到时给你赞。

**Comment by rockywhisper** [comment]
@dp199313  其他的无Fxxk说，就这，建议关闭issues。

**Comment by yixuantw** [comment]
「成功的先烈們」不過是在失序的大環境下先鬧大再趁亂摸魚火中取栗罷了，有序的環境下「鬧大——倒逼——推翻/自己重建」的路子走得通？呵呵。

但凡能說出有種上街一類話的，求你們坦坦蕩蕩說出心底的真實想法：逼官方的就是緩則。
「莫談國事」在很多人心裏並不是不得已的策略，而是具有正義性的真理。

**Comment by zxc479773533** [comment]
敢问除了github还能发在哪里？发哪里不是被zf删掉？还不是被逼无奈才在这里发声的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
