### ISSUE TITLE
放心吧，不把事闹大，这种事以后只会越来越多，因为以前的许多事就是这样消失的，真是可怜

### ISSUE THREAD

**Issue by XhstormR** [sikaozhe1997/Xin-Yue#379]
最近厦门大学的事，在知乎也被限制了，厦大的处理方式跟北大的处理方式如出一辙啊。

**Comment by chengdong0421** [comment]
所以，在这里写几句就可以把事情闹大吗？要是可以的话，我愿意发他一整天的帖子不带休息的

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
