### ISSUE TITLE
希望我们以此为契机，建立微信被删稿件的存档项目

### ISSUE THREAD

**Issue by wearchive** [sikaozhe1997/Xin-Yue#38]
如你们所见，我在去年申请了一个Github账号，存放了一些当时微信被删的文章（当时的文章只是随手转存一份，也没有系统地进行整理）。为了保证一定的匿名性，我没有用我自己的github账号来做，也没有将这个项目公之于众。今天，我认为是时候做这件事情了。

我的项目地址：
https://github.com/wearchive/archive

我希望更多的人来一起合作，建立一个属于我们自己的微信存档项目。不光是为了现在，更是为了未来的历史。

如果你希望参与这个项目，可以在comment中提出你的建议。希望可以参与编辑的，我也会将你加入collaborator。当然，也请大家尽量注意自己个人信息的安全性。

谢谢！

**Comment by tsai1993** [comment]
已经有了， https://info-cn.github.io/Terminus/about.html
https://github.com/Info-cn/Terminus

**Comment by chandlerzhao** [comment]
参照自由微信

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
