### ISSUE TITLE
兄弟不要牺牲github行么,你们蔡元培我不管,但是GitHub的李开复你们忘了?

### ISSUE THREAD

**Issue by VincentLieie** [sikaozhe1997/Xin-Yue#381]

**Comment by CPCer** [comment]
仓库不是你家的，有意见找官方

**Comment by pi11n0tgates** [comment]
这哪里是 **牺牲** GitHub ? 
这违反了 **哪条** GitHub 的 ToS 或者 EULA？

**Comment by firogh** [comment]
看来自由之于某些人确实是不必要的， 至于良知已浑然不觉， 苟且的人多了，就成了现在这个国家民族的性格。

**Comment by WangNianyi2001** [comment]
@firogh 苟且的人多了+1，大不了就把梯子竖着放

**Comment by VincentLieie** [comment]
是是是,那你们以后上GitHub都得翻墙就开心了不是么?

**Comment by VincentLieie** [comment]
@CPCer 上来就无脑喷,回去多读读书在来这bibi谢谢🙏

**Comment by Jawnkuin** [comment]
@firogh 我也想好好活着 in a decent way.
你可以在屋檐下再把头低一点，再低声下气一点去乞求铁拳不要往下砸了(if that works)

**Comment by huoqiangf** [comment]
Duplicated with #364 #324 #271 #223
Please stop spamming and abusing github issues

**Comment by asklogic** [comment]
拨乱反正是常态 

不行讨论就全部下架

能讨论就疯狂______

**Comment by czypku** [comment]
真是利益驱动的丑恶人性，当不公平降临到你们头上，估计就不怕被封了

**Comment by xairzy** [comment]
那你慢慢低头 等着铁拳降临

**Comment by ayaservice** [comment]
兄弟你不关心政治，迟早政治关心你，你一样没饭吃

**Comment by aminic** [comment]
同性交友万岁！言论自由万岁！自由结社万岁！

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~

**Comment by zibengou** [comment]
@VincentLieie 这些人明显都是其他势力请的水军，看他们的repo就知道了。他们金主的目标就是鼓动一部分懵懂的码农搅乱国内局势，不必太在意，成不了气候
