### ISSUE TITLE
声援勇士岳昕

### ISSUE THREAD

**Issue by pi11n0tgates** [sikaozhe1997/Xin-Yue#382]
###### *（本文乃 2018 年 4 月 23 日 晚上匿名者在北京大学三角地张贴的 「大字报」）*

# 声援勇士岳昕
昨天，一位多年力行公义的北大同學，終于因为关心**一件最切身的公共事务，依法申请信息公开**，而被深夜约谈，**以至于母亲精神崩溃，自己失去自由**。我们这些匿名者敬佩岳同学具名上书的勇气，更钦慕他临事不惧的正气。而**有司諸公**，你们究竟在怕什么？岳同学最怕的是，对不起百廿年前的**五四先辈**，毁了**精神上的校庆**，而你们最怕的是“出乱子”，毁了作为政绩的校庆。我们于是想问，这到底是**誰和谁**的斗争？这是“两个北大”之间的斗争。

湖底群魂

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219
