### ISSUE TITLE
请给互联网留一片净地

### ISSUE THREAD

**Issue by bigboy44** [sikaozhe1997/Xin-Yue#384]
不管出于何种目的，将此类事件放在GitHub上，个人是严厉反对的。
可悲。

**Comment by xujh0824** [comment]
同样对你的想法感到可悲！

**Comment by rmctJ** [comment]
楼主想要的”净地“就是各方面完全符合 gfw 那个浑身G点的标准的 github 吧。

这样的”净地“国内到处都是，何止”一片“？楼主赶紧去。

**Comment by chengdong0421** [comment]
为什么都喜欢在网上声讨，而不是去北大游行示威？我觉得那样比较有效。repo的作者好像是清华的，可以组织一下啊，离得也近。

**Comment by wql7013** [comment]
@chengdong0421 既然你支持游行，那应该也支持在这里发声吧。我们以各种方法支持北大学生的努力，有何不可？难道反对恐怖主义，也要每个人都扛上枪冲去跟恐怖分子对峙吗？

**Comment by wql7013** [comment]
@chengdong0421 如果有人在GitHub发一个反对恐怖分子的repo，你是否也会在issues里这样说？

**Comment by ajielee** [comment]
要跪着做人呆在国内论坛就好，何必特意来丢人

**Comment by CyengineKiko** [comment]
@wql7013 他会说我们的裆怎么能跟恐怖主义比:sleeping:

**Comment by chengdong0421** [comment]
为啥我支持你们，你们还是要踩我。。。我的意思就是，光声援没啥用啊。找一帮人去学校一闹，看他还怎么封锁消息。

**Comment by chengdong0421** [comment]
@CyengineKiko 所以，你认为在这里发几个帖子就有效果了？

**Comment by 513286483** [comment]
github是每个人都可以用的，怎么用，是否合理不是你说了算。
我始终觉得，有些东西，是比写几行代码，学几门技术要重要的。那就是人的良知，还有就是身为青年人，对国家，对社会的责任感。

**Comment by CyengineKiko** [comment]
@chengdong0421 所以你觉得去闹就有效果？北大还不会权利大到让新浪和腾讯审查就审查吧¯\_(ツ)_/¯

**Comment by Vargnatt** [comment]
不关你的事情。你不是这个repo的所有者，没有权利要求repo的参与者做或者不做什么。

**Comment by rmctJ** [comment]
@chengdong0421 你自己在当地办一个游行，如果是在国外那就到中国大使馆门口去游行，再拿着照片过来说 ”口说无用，赶紧上街“ 会比较有说服力。

**Comment by bigboy44** [comment]
瓦萨，各位嘴炮厉害。🐂
不要一口一个国内论坛，说的好像GitHub要用VPN才能上一样。能上Twitter才能显得你丫高贵了？
恐怖主义？你怕是zz哦。
只能说嘴炮都无敌，你们才是中国人的骄傲。

**Comment by firogh** [comment]
想清净，去终南山吧，还还凉快！见不得你们这般沉默的大多数，别人死活你不管， 碰到你的利益就炸毛起来，最恬不知耻的，美其名曰，留块清静地。

**Comment by TinaHongBu** [comment]
@chengdong0421 岳昕同学去学校申请信息公开结果现在人身自由都被限制，全面禁声。中国是个可以自由游行和抗议的国家么

**Comment by chengdong0421** [comment]
@TinaHongBu 那在这里发声到底可以起到什么作用？没错，在这里什么都可以说，可是能达到你们想要的目的吗？还是你们想要的目的只是图个嘴上痛快，消一消胸中怨气？

**Comment by TinaHongBu** [comment]
@chengdong0421 我人在美国，在这里发声是我能做的最基本的。你做了什么？

**Comment by chengdong0421** [comment]
@TinaHongBu 我在支持你们呀

**Comment by huoqiangf** [comment]
Duplicated with #364 #324 #271 #223
Please stop spamming and abusing github issues

**Comment by Kuangcp** [comment]
@chengdong0421 华夏里搞游行？根据《中华人民共和国刑法》第二百九十六条规定， 非法集会、游行、示威罪是指举行集会、游行、示威，未依照法律规定申请或者申请未获许可，或者未按照主管机关许可的起止时间、地点、路线进行，`又拒不服从解散命令`，严重破坏社会秩序的行为。 摘自百度百科

**Comment by xairzy** [comment]
真可悲

**Comment by aminic** [comment]
如果国内有可以正常发声的地方，也不会闹到这里。

**Comment by xiaoming821** [comment]
就算是网上支持一下，也是一份微薄的力量，总比蝇营狗苟自私自利的那些人强。更可笑的是这些人还帮着压迫封禁他们的势力来维稳，来责怪那些发布真相的人，真是可悲之极。

**Comment by ayaservice** [comment]
中国人对政治的理解真有趣，实际上在中国之外的地方讨论政治本来就是正常生活的一部分。github上有各国宪法，宪法修正案，草案讨论，利用github保存版本和协作讨论本来就是它的正常用法。各国还有开放政府相关项目都在上面，只有到中国才有人觉得“不搭调”

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
