### ISSUE TITLE
厉害了我的名校高材生们。

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#385]
想当年你们的师兄。
雄姿英发，慷慨激昂。
如今，你们只敢在网络上。
骂那几句不押韵的脏话。
叫兽沈阳是什么，打不过他。
腾讯爸爸是什么，技术斗不过他。
政府法院是什么，反正都是一个鼻子出气的。
不如发文章来得方便。
推特脸书微博区块链是什么？
我们弄懂github的英文文档也废了老大劲呢。

**Comment by xujh0824** [comment]
你说的什么上街游行啊，抗议啊。表达不满就非要用这种方式么？
互联网时代在网上声援也要经过您这样的道德标准审判么？
我们微不足道，但我们也会发出自己微弱的声音。

**Comment by quanquan2100** [comment]
好可悲, 原来中国还是不能发声.

还得靠外国产品

2018-04-24 22:53 GMT+08:00 hehefazhi <notifications@github.com>:

**Comment by chengdong0421** [comment]
是啊，在网上发泄两句有什么用呢？不如组织一下游行来的实在，一针见血。再说，快到五四青年节了，时间也正合适。

**Comment by FanWuTuoBang** [comment]
@chengdong0421   你可拉倒吧，你这话一说，墙内ZF更有理由说你们是反动分子在煽动了，更加害了人家妹子

我们只是希望有更多的人去关注，然后有媒体介入，有了群体的力量，保证岳同学不受非公正的待遇。

**Comment by IrisJinyanZheng** [comment]
你去上街游行吧 毙了你

**Comment by dp199313** [comment]
要发声换个平台真的效果好很多。你们要是只希望把事闹大，又不想自己擦屁股，那你们也算是好样的

**Comment by CyengineKiko** [comment]
@dp199313 比如什么平台？微博 知乎还是去上访？:blush:

**Comment by sylxjtu** [comment]
没必要和楼主好好说了，你看一下他提的所有issue就行了

**Comment by chengdong0421** [comment]
@IrisJinyanZheng 搞了半天，你们也是怕死的，我以为你们会为了心中的正义不畏牺牲

**Comment by IrisJinyanZheng** [comment]
@chengdong0421 那当然了哦 你说的很对哦

**Comment by yixuantw** [comment]
在秩序沒有失效的環境下，無論下位者提出什麼意見與建議，他們都不會在最開始就有機會直接參與到所謂的「解決問題」之中去。即無論他們做了什麼，起到的實際作用，就是「鬧大」。

所有以「鬧大」誅心的人，非蠢即壞。

**Comment by yixuantw** [comment]
你說的遊行示威，作用是什麼？不也是「鬧大」？從鄧到岳，都提出了具體的建議和訴求，在你們眼中這是「鍵盤俠」，諷刺人家不敢上街折騰。香港佔中一類的倒是上街了呢，評價是什麼來著？呵呵，可別裝理中客了，你們對遊行示威者的真實態度還真以為沒人見過。

**Comment by chengdong0421** [comment]
@yixuantw  你说的好像在这里发发见解、表表态度，当局对你们的评价就会好似的。。。
