### ISSUE TITLE
假如有人在GitHub发了反对恐怖主义或者伊斯兰极端教义的repo，大家都会有什么反应？

### ISSUE THREAD

**Issue by wql7013** [sikaozhe1997/Xin-Yue#387]
你是否会说GitHub不是发表这些言论的地方，请立即删除？
你是否会说有本事别在这里废话，请扛上枪直奔叙利亚？
如果你有什么意见，请参与讨论，谢谢！我只是希望清楚我们到底应不应该这么做。

**Comment by dp199313** [comment]
不会有人这么做，因为没卵用。

**Comment by dp199313** [comment]
只有你们脑洞清奇

**Comment by wql7013** [comment]
@dp199313 但是如果有人这么做了，我们应该批评他，还是支持他？

**Comment by sylxjtu** [comment]
那要看说的是谁的所为之事了，把相关资料放在这里的人所做的事是煽动舆论吗？

**Comment by dp199313** [comment]
把资料放在这里是没煽动舆论，但是能把issue关掉？能不往朋友圈发？是谁在口口声声要闹大？要闹就不能去别的地方闹？

**Comment by wql7013** [comment]
另外，希望大家不要在这里使用反问句，尽量使用多种选择的疑问句。

**Comment by wql7013** [comment]
@dp199313 按你之前的意思，如果有人在GitHub发反恐和反极端伊斯兰repo的话，我们不应该批评，而应该支持的，对吧？这个问题大可直接回答。
是的话，那现在剩下的问题就是，反恐和反权力威压（暂且认为这是反权力威压吧）是不同的，或者更准确说反中国内的权力威压。按我理解，你的意思是反恐确实比反中国内权力威压更重要。为什么呢？我理解的原因可能有两个，一个反恐是全人类的，而这件事只是中国的，确实前者影响范围更大，后者看上去最多也就影响一个国家，这个原因我是赞同的。另一个原因可能是反恐比反权力威压更重要（不只是中国），从功利上来看，反恐确实比反权力威压能给人类带来更大的利益。我是赞同反恐更重要的，资源分配要优先考虑反恐。你是否也赞同？
那我们分歧根源在哪里？我认为是，在GitHub反恐我们应该支持，但是在GitHub反中国的权力威压应不应该支持？按你的意思是不应该支持，原因有两个，一是GitHub是世界人民的，不只是中国人的，会损害非中国人的利益，二是GitHub是技术社区，不应该讨论非技术问题。对于第一个原因，我认为不会损害非中国人利益，因为GitHub并不会推送信息，不主动搜索也无法进入这个repo，所以大可放心。对于第二个原因，既然认为GitHub只能用作技术社区，那你应该也反对在GitHub发表反恐言论吧，这就有点不能理解了，求解析。

**Comment by dp199313** [comment]
反恐我不反对，亦不支持。他有更合适的途径，只是不予批评，他们没有搞得站队，党同伐异。因为没人会关注，这个不一样，这个会在这里引起剧烈的争论，效果你也看到了，而且并不是所有人都是素质高的，这个属于程序员合作交流的，这个地方现在变成了你们反对强权的社交平台，这和占篮球场跳广场舞的区别在哪？github没有推送，github有热榜，不光对其他国家网友不尊重，对本国也是如此，没有人应该有义务同意你们的所为，和你们所为不认同就要被谩骂。我这原住民只想好好写代码，并且不想在出门逛街的时候看到广场舞,更不想原来出门就能到的地方，现在要靠梯子爬过去。

**Comment by wql7013** [comment]
我认为这应该是符合“GitHub精神”的，开源共享，追求自由、互助，拒绝垄断、封锁，GitHub不只是给人copy代码的，它还传递着一种精神。

**Comment by szl0834** [comment]
如果有人这样做，我会选择无视。而不是去抨击，举报，让自己不喜欢的声音闭嘴。

**Comment by SakuraLove** [comment]
反恐我觉得无关紧要，但是恐怖主义是对整个人类都是百害而无一利的，我会选择举报

**Comment by gaocegege** [comment]
sexual harassment topics
