### ISSUE TITLE
其实我觉得这边发泄情绪没啥用,为啥不实际点说说这个项目的具体诉求?

### ISSUE THREAD

**Issue by hsz1273327** [sikaozhe1997/Xin-Yue#389]
老实说我关注这个项目到现在都还没闹明白它是要干嘛.....只知道小姑娘受委屈了,但它的诉求是啥呢?讲清楚这个才有的想对策吧?瞧瞧这边工单快300个了,都是怼来怼去发泄情绪或者推销区块链或者带节奏黑zf的,一点有实际意义的都没有.

github让不让这么用咱不管也不是重点,重点在究竟是要干啥.....比如要是想打官司找赔偿,没准这边有人做法律的可以提供帮助;想让大家知道北大的尿性,没准有做前端做文案的可以来帮忙这样.

另外小姑娘太楞了,有点有勇无谋.往好了想这也算上了一课,人在屋檐下哪能不低头.我也算是个喝过洋墨水的人,哪儿都不是净土,希望小姑娘以后知道人在哪儿都要能屈能伸.

**Comment by wql7013** [comment]
诉求是信息公开，公开“沈阳案”的调查处理细节，同时解释校方为何多次为难申请公开信息的北大学生，并就校方的不合理行为作出解析和道歉。据资料介绍，申请公开信息的不只是岳昕一个人，一开始有20个人，有不少人都被约谈，被叫家长，对学生和家长进行恐吓。

**Comment by hsz1273327** [comment]
我觉得不会有啥效果,你想你要是有个娃也不告诉你他要干啥就是在那边又哭又闹,你也一定会当他就是无理取闹无视掉吧

**Comment by quanquan2100** [comment]
我觉得这是 勇士

2018-04-24 23:26 GMT+08:00 Dragon Wolf <notifications@github.com>:

**Comment by one-smiling** [comment]
信息公开，舆论关注，不光明的事情就不会暗地里自我消化，就减少该事件的持续发生

**Comment by hsz1273327** [comment]
其实从这个过程的描述看这个诉求已经触及对方红线了,闹成这样不如想办法退一步达成和解止损,谈判嘛不就是这的.闹崩了两边都不好办.学校还好说,过阵子就没人记得了,这小姑娘后面可就难办了,.....其实公开“沈阳案”的调查处理细节这个北大肯定不可能同意,当年姑息养奸算谁的,相当于从犯了...那不是打自己脸么?其他的行为都是在为圆这个.

我觉得现在负责任的态度是为这个小姑娘想办法,而不是在这边扯什么公道正义其实啥帮助也没有.

**Comment by vc1** [comment]
明白人

**Comment by hsz1273327** [comment]
诶,想到冰菓里面的`ice cream -> I scream`,这个小姑娘也要变成`犠牲`么?

**Comment by findNextStep** [comment]
> 学校还好说,过阵子就没人记得了

我不太认同这个观点：试想一段时间之后，是“辣鸡老师王攀”还是“武汉理工的辣鸡王攀”被人记住呢

在学校发生事故之后

- 学校的处理很难获得关注
- 发生的事情对学校的负面影响更大
- 消除言论的成本明显更低

这样的话学校会坚持什么，也就一目了然了

**Comment by yingziwu** [comment]
以斗争求团结则团结存，以退让求团结则团结亡。权利不是上面恩赐的，而是从下面争取来的。另外，你说要进行和解、要谈判。我同意这种说法。谁不喜欢和和气气嘛。但是，和解、谈判是双方的事，双方都要做出一些退让。如果一方步步紧逼，寸步不让，那只能狭路相逢勇者胜了。另外，现在这个紧张的局面，官方有相当大的责任。官方的工作方式问题多多，粗暴不已。在一些事情的公开上也完全不够。就拿这次公开信，辅导员的答复来说，完全没有说服力，对于信中的关键问题根本没有解释，只看见删帖删帖。而且，双方的力量对比太过悬殊。一边轻轻松松的就让你的帖子被删了，半夜三更搞个约谈什么的；另一边，发给贴子还担心受怕的，到处都是404，不得已逃到github上还要被各种人责难。想要谈判，总要拿出一些诚意来。强势一方步步紧逼，这样的情况下是没有谈判的可能的。其实从这个过程的描述看这个诉求已经触及对方红线了,闹成这样不如想办法退一步达成和解止损,谈判嘛不就是这的.闹崩了两边都不好办.学校还好说,过阵子就没人记得了,这小姑娘后面可就难办了,.....其实公开“沈阳案”的调查处理细节这个北大肯定不可能同意,当年姑息养奸算谁的,相当于从犯了...那不是打自己脸么?其他的行为都是在为圆这个.
我觉得现在负责任的态度是为这个小姑娘想办法,而不是在这边扯什么公道正义其实啥帮助也没有.

**Comment by hsz1273327** [comment]
@findNextStep 其实都不会被人记住,我记得传播学有个论断就是公众舆论热点来的快去的也快(具体的忘记了,毕竟不是专业干这个的),举个例子,16年南邮被逼跳楼的研究生这个事儿我不提还有几个记得?去年被媳妇威胁逼自杀的程序员这个事儿我不提还有多少人记得?这还是近的.通常社会发展是一个缓慢渐进演变的过程,有研究即便是法国大革命对当时的法国人民也没有带来什么跨越式的思想转变.

**Comment by wql7013** [comment]
问题久了，总要有些改变，不然积累越久可能爆发越严重，不希望哪天有更多流血的事情发生。

**Comment by goldimax** [comment]
@wql7013 我觉得这事很难说 比较六四的学生也是这样想的

**Comment by hsz1273327** [comment]
@wql7013 同学肯定没看过冰菓,这边的牺牲不是自愿的牺牲,而是被社区(社会网络中的community)舆论绑架不得不`牺牲`.

**Comment by wql7013** [comment]
@hsz1273327 我确实没看过，根据你的话，我大概明白说了什么。但是我们对这件事保持沉默，似乎也不太对吧，像知乎那样把所有相关言论都删除，似乎不太对吧？

**Comment by wql7013** [comment]
@goldimax 六四争议点比较多，就不讨论了吧。那一步跨得有点大，这应该只是一小步吧。

**Comment by findNextStep** [comment]
@hsz1273327  改变总是要慢慢进行的，但是害怕的是没有改变。

如果始终没有人把加害者放在正确的位置上的话，怕是改变不会再发生，这样的隐瞒和怒火只会继续。

现在我看到的是大多数人在支持岳欣，这是好事。但是没有人去改变学校承认事实就更糟糕的环境，这样的事情还是会继续发生，会有更多的岳欣出现。

这位同学把被封杀的内容放到github我认为没有什么大的毛病，但是按照现在的issues上的讨论的风向，出大问题只是时间问题。

**Comment by gaocegege** [comment]
sexual harassment topics
