### ISSUE TITLE
希望能有人建立一个Telegram群组或用一个Twitter账号及时跟进这位同学的状况

### ISSUE THREAD

**Issue by vzxxbacq** [sikaozhe1997/Xin-Yue#391]
当然，如果有同学挺身而出，请匿名保护好自己，用新邮箱注册新账号，注意安全。

**Comment by vzxxbacq** [comment]
希望贵校有了解的同学能开一个专用的telegram群组或Twitter账号，及时更新信息。也让支持者更有一个中心，既不要被墙内抢过话语权，也不要被墙外某些人利用。

**Comment by goldimax** [comment]
兹磁 希望如果建好了别忘了通知我

**Comment by aminic** [comment]
群组被掌控就更危险的
