### ISSUE TITLE
《大宋提刑官》宋慈弹劾刁光斗片段

### ISSUE THREAD

**Issue by vc1** [sikaozhe1997/Xin-Yue#394]
https://www.zhihu.com/video/971882891056152576

**Comment by FanWuTuoBang** [comment]
我想起郭达演的那个官了，最后笑嘻嘻的，当初差点气死

**Comment by Kuangcp** [comment]
// 这个片段看了好几遍;
assert 历史不会重演;

**Comment by aminic** [comment]
历史一直在重演，只是不会简单重复。

**Comment by MiraYin** [comment]
看起来宋大人赢了 但实际上刁老师才是真正的赢家啊 杀人诛心

**Comment by yijinbandouya** [comment]
还有大明王朝1566 胡宗宪教育马宁远的那一集

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
