### ISSUE TITLE
Github is not for this purpose....

### ISSUE THREAD

**Issue by hoyin258** [sikaozhe1997/Xin-Yue#395]
......

**Comment by wydwww** [comment]
Duplicated with https://github.com/sikaozhe1997/Xin-Yue/issues/324 https://github.com/sikaozhe1997/Xin-Yue/issues/224 https://github.com/sikaozhe1997/Xin-Yue/issues/223

**Comment by Jawnkuin** [comment]
This repository is

**Comment by lianggaoquan** [comment]
yeah...however, they may have no choice, all the information was deleted inland. If they put this to twitter,  some people and medias abroad will use it for other plans, which will push this girl in danger.

**Comment by huoqiangf** [comment]
Duplicated with #364 #324 #271 #223
Please stop spamming and abusing github issues

**Comment by LMC4S** [comment]
THEY GONNA BLOCK GITHUB IF WE CONTINUE DOING THINGS LIKE THIS.

**Comment by huoqiangf** [comment]
@LMC4S Who are they?

**Comment by yu45020** [comment]
But Github is NOT for you.

**Comment by aminic** [comment]
github is not redhub.

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
