### ISSUE TITLE
内容引起强烈不适，已举报

### ISSUE THREAD

**Issue by guodong** [sikaozhe1997/Xin-Yue#396]

**Comment by FanWuTuoBang** [comment]
人如其头像

**Comment by guodong** [comment]
@FanWuTuoBang 帅不帅？

**Comment by FanWuTuoBang** [comment]
@guodong 内容引起强烈不适

**Comment by guodong** [comment]
@one-smiling 哈哈，看把你认真的

**Comment by firogh** [comment]
石乐志？

**Comment by guodong** [comment]
@firogh 不是

**Comment by goldimax** [comment]
@guodong 这个也就影响到了北大的利益 也没影响到党的利益或国家的利益 我觉得不太会 最多仓库主人约谈删仓库

**Comment by guodong** [comment]
@goldimax 你们这些人呐，唯恐天下不乱

**Comment by goldimax** [comment]
@guodong 我觉得是你太安于现状了

**Comment by guodong** [comment]
@goldimax 不，我可是有理想有抱负的有志青年

**Comment by goldimax** [comment]
@guodong 我看你到处打广告是想借此捞一笔吧……

**Comment by guodong** [comment]
@goldimax 游泳健身了解一下

**Comment by goldimax** [comment]
@guodong 你这人有毒吧……= =

**Comment by guodong** [comment]
@goldimax 你是妹子嘛？约吗？

**Comment by xairzy** [comment]
vpn不会搭? 还是不要当码农了吧

**Comment by guodong** [comment]
@xairzy 能教教我不

**Comment by LittlePrinces** [comment]
@guodong 看来封了也没啥，至少能过滤掉一些低端程序员和伸手党

**Comment by aminic** [comment]
是举报到中纪委了么？

**Comment by guodong** [comment]
@aminic 举报到了党中央

**Comment by leciel-guo** [comment]
有些人跪久了就是见不得别人站起来

**Comment by autodataxx** [comment]
@guodong you have been reported due to inappropriate language and comments. #411

**Comment by goldimax** [comment]
@guodong 汉子，不约，谢谢
郭东被狼吃，也有自己的错误 
你这样自己被狼吃就算了
还带着大家被狼吃
还邀请大家被狼吃

**Comment by CeresCheng** [comment]
你算个什么

**Comment by liyuelu** [comment]
请问何处引起你强烈不适？ 你可以说在这里发这个不妥，也不需要如此让人恶心的说出这句话吧。

**Comment by kilobtye** [comment]
你好 谢谢关注 无意义的issue我就关闭了哈~
