### ISSUE TITLE
0

### ISSUE THREAD

**Issue by Ufinhub** [sikaozhe1997/Xin-Yue#399]

**Comment by dp199313** [comment]
首先恭喜各位同学所做的事情有成效。但请恳请大家不要再把github当成国内法律禁止的内容的集散地。我是github的普通用户，我热爱着这个社区的开源共享及合作。不要把这里变成戾气冲天对抗政府的前线。搭个vpn是简单的事，但不是我们该因为你们的行为，被你们的大义所裹挟去做的事。

**Comment by guodong** [comment]
赶紧墙了吧，这样我就可以做个国内的github了，想一起创业的follow me

**Comment by jacobswan1** [comment]
没人要挟你啊？我要挟你了吗？但是表达想法是我的自由，我觉得这里能自由的表达想法，怎么了有问题吗？所以你不能要求我不做这个事情，为我的行为买单vpn也不是我所要在乎的事情

**Comment by guodong** [comment]
百兆VPN年付99了解一下，买一年送2个月

**Comment by dp199313** [comment]
如果你觉得这么做没问题，那请为了你的大义，给不想这么做的人把vpn买了。

**Comment by jacobswan1** [comment]
首先我这么做了就是支持国家分裂，提供反动资金，我不能这么做。其次你确实是属于脑子不好使的那一拨人，既然我的行为不违反githu规定，why would I give u a shit?

**Comment by dp199313** [comment]
在公园里拉屎然后问我为啥要踩到这陀屎。谩骂这就是你增加自信的方式？

**Comment by aminic** [comment]
谁是别有用心的人？还是墙了吧，墙国软件业两大支柱gayhub墙了，反正还有SO呢，怕什么，一条腿照样赶英超美的。希望中国越来越好，但是不希望赵家人以及赵家的狗越来越好。

**Comment by jacobswan1** [comment]
所以我说你脑子不好使是有道理的，因为你想不清楚因果关系，如果按照你的逻辑，我是一个强人，我挣了钱，那穷人因为我的行为变得更穷了，但是作为富人我没有违反任何法律，我应该打包给所有的穷人发钱？我该说你们真棒真有逻辑。再问你一遍，我违反任何github关于讨论的规定了吗？我的行为间接导致你要买vpn，我承认有关联，可是我需要care吗？违反道义了吗？我一定要遵守你的正义你的规则吗？想明白了？所以我骂你有道理吗小猪？

**Comment by vc1** [comment]
搭vpn是情分，不搭是本分。

**Comment by dp199313** [comment]
富人要比穷人交更多的税。这事你不知道？说我智商有问题我至少没把同样谩骂的话复制粘贴几编。我每次骂你都是变着法骂的。于你不予论理，我们不在同一水品。

**Comment by 900Even** [comment]
来回有那么几个跳梁小丑上蹿下跳，每个回复里都乱喷一遍，岳同学敢于实名去申请信息公开，而你们只敢在这种地方乱喷。既然标榜自己是程序员又没有过硬技术，只好这样展示你们的无能么？

**Comment by AnyWAT** [comment]
🤣不识码的以为：没在标榜、无所不能的过硬程序员，貌似可以不用神马仓库一次搞定？
