### ISSUE TITLE
请中国政府赶快禁止境内网民访问github吧！

### ISSUE THREAD

**Issue by huoqiangf** [sikaozhe1997/Xin-Yue#400]
突然想起来一句话， 其实墙是帮助墙外人民净化网络环境的。。。

看看看看，就这么一件简单的事情，大家要在github上做一下相关文件的version control。不知道从哪里冒出来了这么多牛鬼神蛇上蹿下跳，搞得issues乌烟瘴气，github正常用户都无法进行正常思想交流。希望中国政府负担起大国的责任，为境外网站创造和谐友好的交流氛围，尽快屏蔽掉其境内捣乱分子对境外网站的破坏。为提高境外网民的平均素质做出其应有的贡献。

**Comment by dp199313** [comment]
赶紧墙，过滤掉。一月花30块钱买vpn，这些人，就得考虑考虑再说话了。

**Comment by navono** [comment]
>`github正常用户都无法进行正常思想交流`

这么严重了啊。

**Comment by Mason-Xu** [comment]
你在这说说有屁用，你举报丫   #滑稽
