### ISSUE TITLE
Github is a plate for knowledge!!!!!

### ISSUE THREAD

**Issue by Yashuo** [sikaozhe1997/Xin-Yue#401]
喂 Github已经被封过一次了， 你不要因为你自己认为的正义就影响别人啊啊啊啊啊啊啊啊啊啊。
我还要学习呢！！！！！！！
轮子都不在github上面发东西，你跑过来捣什么乱。
有没有道德啊！

**Comment by guodong** [comment]
@Yashuo 说得好，我选择死亡

**Comment by smy20011** [comment]
`轮子都不在github上面发东西，你跑过来捣什么乱。`

随便搜一下就知道你这个言论有多荒谬。TG爱封就封，有本事让中国还算可以的互联网业界倒退10年。

**Comment by LNZ001** [comment]
不会个vpn学什么c

**Comment by guodong** [comment]
@LNZ001 你说说vpn是啥？

**Comment by Yashuo** [comment]
@LNZ001 噗。。。 你是来搞笑的吗
