### ISSUE TITLE
非常有趣的一个现象是，中国的学生和cxy们天生就认为政治这个事情是不能谈论的，也不能讨论的，讨论了就是别有用心，就是境外势力，就是敏感话题，政治天生只能是领导人在人大讨论，有趣有趣，难怪有人把跪着的名族放在我们的头上，一个息息相关的话题竟然能成为一个敏感话题。

### ISSUE THREAD

**Issue by jacobswan1** [sikaozhe1997/Xin-Yue#402]

**Comment by guodong** [comment]
小伙子很有想法嘛，跟我做微商吧，保你一年提保时捷

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by aminic** [comment]
政治就是，谁是干活的，谁是吃肉的，谁是被管理的，谁是自在存在的。
政治就是，获取价值如何分配，食物如何张嘴吃饭，如何说话得受充分支配。

**Comment by shanezhiu** [comment]
萌萌，站起来，站起来，站起来，看见你站起来了，我好开心。

**Comment by jacobswan1** [comment]
@shanezhiu 你还是写好您的黄色网站吧先
