### ISSUE TITLE
北大校长，可记得刘和珍吗？

### ISSUE THREAD

**Issue by Hdzi** [sikaozhe1997/Xin-Yue#404]

**Comment by guodong** [comment]
不记得

**Comment by FanWuTuoBang** [comment]
蔡元培先生还说过“兼容并包，思想自由”呢，他还记得这句话的意义么？

**Comment by MrKuanYi** [comment]
苟活者在淡红的血色中，会依稀看见微茫的希望；真的猛士，将更奋然而前行。

**Comment by xiaoming821** [comment]
记念刘和珍君。。。。

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by guodong** [comment]
@1994sunshine 传图片可以吗

**Comment by aminic** [comment]
北大校长应该只知道领导的马屁怎么拍的恰到好处，领导的屁眼怎么一舔升花。
北大校长应该只知道学生的诉求怎样精确弹压，学生的表达如何完全压制。

**Comment by guodong** [comment]
@aminic 已截图发给网警，能吃点啥吃点啥吧

**Comment by aminic** [comment]
@guodong 好的，谢谢，承您的大情了，让我也能喝喝茶。

**Comment by guodong** [comment]
@aminic 哈哈，看把你吓得

**Comment by aminic** [comment]
@guodong 我有什么好怕的，小人藏鸡鸡，君子坦荡荡。因为推动中国民主法治，而有机会喝茶是我辈青年的无上荣耀。

**Comment by shanezhiu** [comment]
😂北大只记得庙小妖风大，池浅王八多这句毛语录。

**Comment by shanezhiu** [comment]
那个说推动民主政治的让我想到明末党争。御史以骂皇帝为荣，都在争名，没有建设意见。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
