### ISSUE TITLE
The key point to be solved

### ISSUE THREAD

**Issue by jiapinghong** [sikaozhe1997/Xin-Yue#405]
In fact, the first point of the incident was only about how Shenyang was dealt with by Peking University 20 years ago. Whether the document produced by the school is all available information, but now this matter has no one care about.
The question now is whether the authorities has pressured XinYue by “successfully graduating” in the end. Did the school make any emotional disruption to his mother by taking extraordinary measures ? These need those people concerned to respond normally.
When all questions are answered, just do it！ As for the worries about Github will be blocked, I believe it won't , At the same time , he should have such inclusiveness and tolerance.  Anyway，we need voice. 
There's an old saying goes：
They first came for the Communists,
and I didn't speak up because I wasn't a Communist.
Then they came for the Jews,
and I didn't speak up
because I wasn't a Jew.
Then they came for the trade unionists,
and I didn't speak up
because I wasn't a trade unionist.
Then they came for the Catholics,
and I didn't speak up
because I was a Protestant.
Then they came for me,
but by that time,
there was no one left to speak up.

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
