### ISSUE TITLE
对于质疑github用途的人，可以来睁大眼睛看清楚github的官方说明，有没有禁止政治的讨论和github用途的说明：

### ISSUE THREAD

**Issue by jacobswan1** [sikaozhe1997/Xin-Yue#406]
In addition to source code, GitHub supports the following formats and features:

**Documentation, including automatically rendered README files in a variety of Markdown-like file formats (see README files on GitHub)**
Issue tracking (including feature requests) with labels, milestones, assignees and a search engine
**Wikis**

**Besides, Github never posted any prohibition about politics discussion.**

所以你们说明的github is not for this purpose是站不住脚跟的，github issue用于问题的版本讨论没错但不会因为涉及政治就禁止讨论，贵程序员们只是怕github被墙，了解一下一种基本的技能叫做vpn，很神奇，点一下vpn你就能看到墙外的世界，github搜索一下vpn竟然还有开源项目，真是伸手党程序员和低级程序员们的天堂呢。

**Comment by ajielee** [comment]
我就像问，之前这个神奇 repo https://github.com/houshanren/hangzhou_house_knowledge 出现的时候，这些质疑的人都哪里去了？

有些人跪久了，就是见不得别人站一下😒

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by gin-lsl** [comment]
老外发个nocode都能🔥。中国人发个杭州买房都要被国内程序员嘲讽几天。见怪不怪了。

**Comment by quanquan2100** [comment]
没有禁止就代表同意是吗? 不允许的事情全给你列出来才能明白吗? 

商城里也没有贴标识说禁止洗澡, 你见谁在商场里洗澡?

**Comment by aminic** [comment]
皇帝都没了，没有人值得跪！

**Comment by LittlePrinces** [comment]
@quanquan2100 哇已经贴出来了Besides, Github never posted any prohibition about politics discussion.，难道商城也贴出来，这里不禁止洗澡？

**Comment by jacobswan1** [comment]
法律和规定的基本定义就是法不禁既可行，如果你连这种基本的原则都不知道，你还是先回去初中好好复习下法律规定的定义

**Comment by jacobswan1** [comment]
商店的例子，还真有规定，商店没有规定不能洗澡，但是法律规定不能当众裸露，智商是硬伤何必硬要秀一把操作呢

**Comment by tuanweishuji** [comment]
@jacobswan1 现在的墙只是黑名单了解一下，哪天换成白名单了，麻烦你写个tunnel给国内滞留人员用一下

**Comment by quanquan2100** [comment]
真心累, 就不能承认确实可能会给一些人带来不便的事实吗?

举个例子, 我说洗澡你们就那洗澡说事, 那我说打扫卫生呢? 到时候组织上千人去商场打扫卫生, 这个没禁止吧, 但是这么一来二去真心没意思.

唉...

**Comment by jacobswan1** [comment]
好的,如果有变成白名单了我发我地址我去接你,咱一起出国奔向美好未来

**Comment by society765** [comment]
敢问一下 LZ这段英文在哪看到的 我Google了半天没找到

**Comment by jacobswan1** [comment]
@quanquan2100  我理解你的意思,你想表达的就是这种讨论会给国内的程序员带来极大的不便,但是你有没有想过这种事情是不能够怪在讨论问题的人们身上的,就像我说的那样,从规定上来说他们可以讨论,带来的后果是会影响你我承认.但是谁不想在一个能够自由讨论问题的地方说话,谁不想能在一个有更多人关注的地方说话.如果weibo,weixin能够自由的说想说的看法,如果论坛内网能不被言论管控,会有人到这地方讨论问题?我想不会吧.你想说的无非就是来这里讨论问题会对你们的生活带来不便,但这根本不是讨论问题的人说主动选择的啊

**Comment by jacobswan1** [comment]
@society765
Scope
GitHub is mostly used for code.

In addition to source code, GitHub supports the following formats and features:


Documentation, including automatically rendered README files in a variety of Markdown-like file formats (see README files on GitHub)
Issue tracking (including feature requests) with labels, milestones, assignees and a search engine
Wikis


最后一句话是我懒得切输入法自己打的,但弄清楚一点在美国的网站根本不会有人问"我们讨论政治是合法的吗"的这种sily问题的.你可以quora问一下看看美国人会怎么diss你

**Comment by quanquan2100** [comment]
@jacobswan1  我的意思是, 心里知道会有不便. 我看很多人觉得这种不便是你们应该的牺牲. 还有就是大家在这个事情上争吵太多了, 真的没必要, 我自认为说话够客观一样会被 cue. 我就是希望事情往解决事情的方向发展. #417

**Comment by aminic** [comment]
能力越大，责任越大。不让人心世道滑向更恶，这句话对于程序员同样适用。

**Comment by jacobswan1** [comment]
@quanquan2100, same there, 这不是程序员应有的牺牲,但是也不能blame倒讨论问题的人上去. 同样希望向好的事态发展,不过恕我直言这种管控和压制的态势光靠我们的领导人们自己去反思去更改恐怕是改不好的.

**Comment by quanquan2100** [comment]
@jacobswan1 恩恩, 我完全尊重你的看法.

**Comment by flymrc** [comment]
被墙，我就不好抄了呀。

**Comment by lqxx2005** [comment]
自我审查者 真是可悲

**Comment by acgtyrant** [comment]
请贴 URL，不然可信度低。

**Comment by jacobswan1** [comment]
GitHub Enterprise has all the great stuff you’ve come to expect from GitHub: commit histories, code browsing, compare views, pull requests, issues, wikis, gists, organizations and team management, powerful APIs, and a beautiful web interface.

**Comment by jacobswan1** [comment]
https://blog.github.com/2011-11-01-introducing-github-enterprise/

**Comment by jacobswan1** [comment]
@texzhichen 喜欢打脸呗

**Comment by jacobswan1** [comment]
**issues, wikis**

**Comment by jacobswan1** [comment]
有些没有智商的人总喜欢秀智商的，
