### ISSUE TITLE
如果那些邪恶的人聚集在一起，能够成为一种力量的话，善良正义光明的人，也应该这么做。

### ISSUE THREAD

**Issue by yuechuanx** [sikaozhe1997/Xin-Yue#408]
某种程度上，在发声渠道怎样匮乏的情况下才会选择在github上发声，我不认为在这里能有多大的舆论影像力，但多一些人关住就就多一点可能性，支持这件事情的人保持关住即可，认为这不妥的无视这个repo也不打扰。在这里吵闹很无聊。

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输出几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by lafiezh** [comment]
首要的任务是保护岳同学。

**Comment by aminic** [comment]
没有舆论压力岳同学不好保护的。

**Comment by nidada** [comment]
首要的任务是保护岳同学。

**Comment by ayaservice** [comment]
今天是西藏政治犯-十一世班禪喇嘛29歲生日｡他6歲就遭中國劫持,一個手無寸鐵的孩子也能把中國嚇成這樣!他失去自由已經整整23年,請各界關注! https://t.co/FZeoIpsrhE

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
