### ISSUE TITLE
我觉得大家还是注意点吧，北大的锅，尽量别扯体制

### ISSUE THREAD

**Issue by goldimax** [sikaozhe1997/Xin-Yue#410]
之前有前车之鉴了，github还是会对一些仓库进行区域管制的，要是搞过了被限制了就麻烦了，反而会起负面作用
[「编程随想-赵国」被封通知](https://github.com/github/gov-takedowns/blob/78775b09e64d85f08547287cab204b48b2491192/China/2016/2016-06-08-programthink-zhao.md)

**Comment by aminic** [comment]
北大的是小锅，体制的是大锅，没有大锅那来小锅。

**Comment by FanWuTuoBang** [comment]
这就看你如何看待了，治标不治本，未来还有千万个Xin-Yue遭受这个问题。

当然我不是反对你的想法， 你的担心也是能理解的。

**Comment by gin-lsl** [comment]
多事之春。

**Comment by aminic** [comment]
还有红黄蓝呢，没曝出来的有多少？奸佞横行，祥瑞自然多多益善的。

**Comment by goldimax** [comment]
@Peiyang @aminic 但我感觉现在应该先把这个Xin-Yue的问题先解决掉再去解决更多问题 不然可能会给妹子带来麻烦啊

**Comment by cwang101** [comment]
老铁，知道什么是维稳吗

**Comment by Hzzone** [comment]
北大是不是中国顶尖的两所高校之一？
北大校长是不是正部级别的干部？
举国之力发展的两所学校，每年拿着远超其他高校的教育经费，就是让他们来欺压学生，维护官僚资本集团？
如果这不是体制的错，何来本应该纯洁的校园带来污秽？这本来就是大环境所致啊！

**Comment by goldimax** [comment]
@Hzzone 说得有理 但是现在我更担心Xin-Yue

**Comment by szl0834** [comment]
HTTP 451

**Comment by gledos** [comment]
把事情闹大也许是保护 Xin-Yue 的最佳方式，Xin-Yue 写公开信的目的也在于此

**Comment by zhangsen1992** [comment]
一切的一切 就是体制的锅啊

**Comment by goldimax** [comment]
同意大家的观点 希望事件有所进展吧
