### ISSUE TITLE
如果github是最后说话的地方了，那没问题

### ISSUE THREAD

**Issue by tuanweishuji** [sikaozhe1997/Xin-Yue#414]
其实还有很多途径：比如说，去广场上自建热点，定制欢迎界面。这个办法还能让几亿农民知道你在干嘛，他们可能不太懂GitHub。

**Comment by 1994sunshine** [comment]
人民日报社评  https://info.3g.qq.com/g/s?aid=news_ss&docId=6096220144588445274&id=news_20180424A1DYC4&icfa=home_touch&f_pid=135&iarea=242

**Comment by tuanweishuji** [comment]
行动是争取权利的唯一途径，只在小圈子里动动手指没有任何意义

**Comment by Woolseyyy** [comment]
不行，出门多累啊，站着多累啊，还可能被人打，这里好，舒服的很，她岳昕死活关我什么事，我在这爽一把就好了，有的说话就好了，说出来有多少用我才不关心

**Comment by Seedarchangel** [comment]
@Woolseyyy 
你说你有什么意思呢？每天说这个repo污染你眼睛，每天又在这里蹦跶，你是有斯德哥尔摩还是什么？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
