### ISSUE TITLE
讨论这么久大家有什么结果不?

### ISSUE THREAD

**Issue by quanquan2100** [sikaozhe1997/Xin-Yue#417]
第一: 选择在这里讨论因为国内渠道封锁, 对于可能对其他人造成的潜在影响表示抱歉
第二: 我们在这里说言论自由, 但却对反对在这里说话的人却进行攻击, 这不是言论自由
第三: 有什么想法, 可以对作者表示支持, 也可以帮忙查阅相关文件, 也可以帮助搜索资料或者新的途径, 有的话都可以说出来

**Comment by 1994sunshine** [comment]
人民日报社评  https://info.3g.qq.com/g/s?aid=news_ss&docId=6096220144588445274&id=news_20180424A1DYC4&icfa=home_touch&f_pid=135&iarea=242

**Comment by 1994sunshine** [comment]
发微博头条文章不被秒删方法:将文章标题截图放置于封面，文章标题处随意输入几个数字，正文放全文。实例:https://media.weibo.cn/article?id=2309404232311234294219

**Comment by quanquan2100** [comment]
#342 
#382
#394

**Comment by dp199313** [comment]
真正干实事的如二楼这位兄弟即可。吃瓜群众在这里发泄的不亦乐乎。

**Comment by aminic** [comment]
吃瓜群众只能在这吃瓜了

**Comment by quanquan2100** [comment]
#419

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
