### ISSUE TITLE
把最近的大字報添加進去

### ISSUE THREAD

**Issue by zqcc** [sikaozhe1997/Xin-Yue#432]
聲援勇士岳昕

昨天，意味多年力行公益的北大同學終於因為關心一件最切身的公共事務，依法申請信息公開，而被深夜約談，以致母親精神崩潰，自己失去自由，我們這些匿名者，敬佩岳同學具名上書的勇氣，更欽慕他臨事不懼的正氣，而有司諸公你們究竟在怕什麼？岳同學最怕的是，對不起百廿年前的五四先輩，毀了精神上的校慶，而你們最怕的是“出亂子”毀了政績上的校慶，我們於是想問，這到底是誰和誰的鬥爭？這是“兩個北大”之間的鬥爭。

**Comment by FengWenPei** [comment]
明显有人在混淆视听，带节奏。
建议仔细看看那几个文档，各方的回应，好好理解下。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。

**Comment by zqcc** [comment]
我認為你說的對，你的意思是否是清華在過度宣傳呢。

在 2018年4月25日 週三 06:27，FengGuiFeng <notifications@github.com> 寫道：
