### ISSUE TITLE
请不要毁了GitHub，给码农留点空间

### ISSUE THREAD

**Issue by boogoobird** [sikaozhe1997/Xin-Yue#434]
有很多学生是不会翻墙的，懂翻墙原理的毕竟是少数人，更多人和我一样只是在用翻墙工具。作为程序员我绝大部份时间都是通过GitHub学习的，所以任何政治敏感话题请不要在GitHub上讨论，大家可以维护一个列表记录各个反馈平台，同样也可以维护一份请愿书，但不要在GitHub上发表任何政治言论，GitHub从来都不是一个讨论社区，请各位同仁理性爱国，为我们保留一个学习的空间。

**Comment by boogoobird** [comment]
如果讨论的话，给各位推荐一个国内的平台，支付宝新出的文档管理兼博客平台-语雀，这方面你们可以互补掉，一个需要发声，一个需要推广。

**Comment by oliverxyy** [comment]
你这样说也无可厚非，那么当事情发生在你身上的时候，我们大抵是不会发声的，也正因为一部分人只顾自己的一亩三分地，这种事情才总是溅不起水花，不说国外的正当游行争取自身权益，在中国当个键盘侠呐喊一下都不受支持，另外，不只是针对这件事情，还有其它类似事件，期望zf能够正面回应并处理，而不是一味的封删，连自由言论都只能发到github上了，你还有多少自由空间？开民智，广纳谏，嗯，当我没说。。

**Comment by boogoobird** [comment]
在中国是没有这样的平台,我不反对各位发声,也不反对各位去伸张正义,更不会阻止各位讨要公道.我只是想为国家的发展和互联网从业人员保留一点学习空间.前几年爆料的事也屡见不鲜,杜绝吗?没有,你们只是满口的想着不公,却从来没有想过怎么去解决问题.不解决问题的讨论一切都是瞎扯淡.

**Comment by Devorantis** [comment]
Im inounter of the rullers in general!!

2018-04-25 2:16 GMT+03:00 oliverxyy <notifications@github.com>:

**Comment by skywhat** [comment]
有的人简直是喷子，搞一个VPN当然easy，用VPN很有优越感吗？？但是不被墙不是更好吗，干嘛给自己每天要用的工具找麻烦，github多好的平台。

**Comment by boogoobird** [comment]
开民智，广纳谏.很好的提议,3年前我会和你一样,并且我现在依然认同你的看法.但是给XX提议要注意方式方法,如果你会翻墙的话,我建议你去看下youtube,中国自古以来就不缺少热血男儿.我们不仅要有一个爱国之心,还要有一颗聪明的大脑.

**Comment by boogoobird** [comment]
针对这次事件的当事人,我很同情你们的遭遇,也对那你们的行动表示支持和鼓励.

**Comment by oliverxyy** [comment]
@boogoobrid 你就是来推广语雀的吧，那么语雀和微博，知乎有啥区别，可以保证不会删帖删热搜删用户吗？

**Comment by boogoobird** [comment]
我不是阿里的人,我不清楚大概也是会删的吧

**Comment by huoqiangf** [comment]
就你们这些连翻墙都不会的人还配用GitHub。。太搞笑了。。。

**Comment by navono** [comment]
@boogoobird 
`既然国内没有这样一个言论自由的平台,那我们可以建立这样一个平台,并获得国家的授权与许可,只有国家认可了,言论自由才能落到实处.`

too young, too simple.

**Comment by skywhat** [comment]
@huoqiangf 自己github主页就是个三无用户，会用VPN哪里来的优越感

**Comment by PlexPt** [comment]
In addition to source code, GitHub supports the following formats and features:

Documentation, including automatically rendered README files in a variety of Markdown-like file formats (see README files on GitHub)
Issue tracking (including feature requests) with labels, milestones, assignees and a search engine
Wikis

Besides, Github never posted any prohibition about politics discussion.

**Comment by boogoobird** [comment]
@navono 是我想的简单了,到要在国内做到这件事必须这么做,要不然做不起来,当然中间会有一些妥协.

**Comment by boogoobird** [comment]
@PlexPt In addition to source code, GitHub supports the following formats and features:Documentation, including automatically rendered README files in a variety of Markdown-like file formats (see README files on GitHub)Issue tracking (including feature requests) with labels, milestones, assignees and a search engineWikisBesides, Github never posted any prohibition about politics discussion.
--翻译
除了源代码外，GitHub还支持以下格式和功能：

文档，包括以各种Markdown-like文件格式自动呈现的README文件（请参阅GitHub上的自述文件）
问题跟踪（包括功能请求）与标签，里程碑，受派人和搜索引擎
维基

此外，Github从未发布任何关于政治讨论的禁令。

**Comment by zhichiyuexin** [comment]
@SIDmao 什么时候用匿名保护自己成了怂货了,你算什么?你算什么?在这骂人就有用了?你为什么不去政府门前抗议?能说这话只能说你是站着说话不腰疼,而且没有任何自我反思能力

**Comment by SIDmao** [comment]
@zhichiyuexin 
因为我怂啊 
你好厉害哦 
敢在这里用键盘反抗
给你鼓鼓掌
啪啪啪

**Comment by boogoobird** [comment]
@zhichiyuexin 匿名保护没有错,我只是不想Github被封,那样写代码会很难受,当然翻墙我也会@huoqiangf ,我一是想那些不会用的人,保留一个学习的地方,二是Github被墙的话,国内很难出现一个这么有影响力的平台.开源中国那种做法,无异于闭关锁国.

**Comment by zhichiyuexin** [comment]
@SIDmao 看了下你的简历,果然是站着说话不腰疼

**Comment by zhichiyuexin** [comment]
@boogoobird 我现在就一直翻墙用github,直接打开经常奇慢无比,你说为什么

**Comment by boogoobird** [comment]
@zhichiyuexin现在github不用翻墙,翻墙还没有直连快,打开慢可能是长城在搞鬼,网络我不懂你可以去翻墙工具下面留言,请高手解答.

**Comment by RockyQu** [comment]
我也是一名开发者，但是封不封我觉得无所谓，你查资料上不上 Google，Google 你怎么上去的？别说你一个技术人员只用百度，不翻墙有些包你都引不了，科学上网是程序员的必备技能

**Comment by heiyantutu** [comment]
1.在QQ中打开这个项目的链接和其他github项目的链接 显示的提示是不一样的（一个是危险网站，一个是未知）
2.在中国既要有仰望星空的人，也要有脚踏实地的人。

**Comment by CrazyKidCN** [comment]
连我这种三流无作为的咸鱼都会翻墙
您不会翻墙您好意思自称程序员？

**Comment by Uyouii** [comment]
能不能别动不动自己就代表码农代表程序员的，我不想让你代表，你也不配

**Comment by ayaservice** [comment]
今天是西藏政治犯-十一世班禪喇嘛29歲生日｡他6歲就遭中國劫持,一個手無寸鐵的孩子也能把中國嚇成這樣!他失去自由已經整整23年,請各界關注! https://t.co/FZeoIpsrhE

**Comment by szl0834** [comment]
自我审查是最后的底线

**Comment by 0kaguya** [comment]
编程随想了解一下

**Comment by szl0834** [comment]
GitHub本质上就是一个开源社区，这样子自我审查，那是不是以后代码也要自我审查，代码也要符合核心价值观？

**Comment by SIDmao** [comment]
@zhichiyuexin 
我们工地狗天天在工地当然是站着说话啊
哪像你们程序员坐着喝喝咖啡打打键盘这么高贵哦

**Comment by firogh** [comment]
相比为社会公义和20年前含冤而去的人， 学个翻墙算什么！今日，信息锁国，而技术又多来自国外，难道只用GitHub学习？学出来一个个十足的精致的利己主义者。

**Comment by wujians** [comment]
看你就一脸地道的奴才相，倍儿想挨抽。
奴隶主把奴隶虐了一顿，一群奴隶就相互指责，怎么就惹主子生气了，再惹主子生气，饭都没得吃了。
这种奴隶可以评个模范奴隶，下次发个奖状给你。

**Comment by boogoobird** [comment]
代码是要审查的，万一出了bug怎么办？代码走差是为了降低bug的数量，代码中不存在什么价值观的@szl0834

**Comment by hu970804** [comment]
现在用ss浏览器可以进github，命令行不能clone怎么办？

**Comment by CeresCheng** [comment]
你代表不了

**Comment by liyuelu** [comment]
自我审核最为可怕

**Comment by GabrielKidd** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。

”
— 馬丁·尼莫拉

**Comment by grasscase** [comment]
@boogoobird 国内要被删，这里不用删，哈哈

**Comment by boogoobird** [comment]
你们发吧,要被封了,以后爬梯子好了
