### ISSUE TITLE
那些讨论github会被封的，无非是为了自己的一点私利。

### ISSUE THREAD

**Issue by navono** [sikaozhe1997/Xin-Yue#436]
不管这私利是借助定位这是什么样的平台（而且还是自我定义），还是是五毛。他们都甘愿做13亿人民外的一座孤岛。当大风大浪打到这座孤岛时，撕心裂肺指责对面那13亿人连接的大陆。

>起初他们追杀共产主义者
我没有说话----
因为我不是共产主义者
后来他们追杀工会成员
我没有说话----
因为我不是工会成员
接着他们追杀犹太人
我没有说话----
因为我不是犹太人
最后他们奔我而来----
却再也没有人站出来为我说话。

可以看到很多账户都是这几天注册，还有甚至是十几小时前注册的，来宣称给GitHub是什么什么。这些都是什么人我想大家都清楚。

**Comment by jiangzemingzz** [comment]
那你呢，到最后不还是怕没人为你说话吗，不还是为了自己的私利吗

**Comment by ryanaltair** [comment]
封 github 既不现实 也没有益处

**Comment by huoqiangf** [comment]
@jiangzemingzz 他的私利也是你的利益的超集啊。而反过来你的私利对别人又有什么好处呢？你还真的是zz哦

**Comment by RockyQu** [comment]
我也是一名开发者，但是封不封我觉得无所谓，你查资料上不上 Google，Google 你怎么上去的？不翻墙有些包你都引不了，科学上网是程序员的必备技能

**Comment by leungsky** [comment]
搞笑呢？一个程序员连翻墙都不会

**Comment by SakuraLove** [comment]
@jiangzemingzz “没人为你说话”不是私利，是社会病态

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
