### ISSUE TITLE
《阉割与自我阉割》、语文教学及newspeak的原则

### ISSUE THREAD

**Issue by Fassade-Muspel** [sikaozhe1997/Xin-Yue#437]
还是忍不住评论一下“闭嘴利于社区”的谬论。正反双方都朝着奇怪的方向去了

这根本不是翻不翻墙的问题。
问题在于：一件可以被讨论的事情不能被讨论了这是见怪不怪的，可是令人惊讶的竟然还有人自发地在可以讨论问题的地方呼吁不要讨论问题。一来，站方的regulation清清楚楚明明白白告诉你真正不能干的是什么；二来竟然还有人摆出一副大义凛然的样子，在别人私人所有的repo底下摆出一副样子——声称自己代表了common good。对同一个问题的好恶自然是正常的，但是也仅仅是个人层面的好恶。

他们根本不知道为什么，只是应激性的去对陌生的主题做出反应，丝毫不关心其内容。他们只知道自己的屁股和脑袋以及脑袋前面github上面可以工作——只fork不commit的那种。无可厚非，并不是所有人都对热点事件感兴趣的。但是他们竟然摆出一副这是为了大家好的样子，丝毫不考虑是谁让大家变得如此之糟。

我是愿意相信码农群体的平均智力发展水平在社会上是更高的，那么是不是也就意味着不少同侪，并不是蠢，而是精妙地运用了——有意或者无意地——语文的技巧，把所有一开始只想找个地儿说一句“这个事儿这么做不应该”的另一群人排挤在了社区之外，成为了所谓的commonweal之敌。坏到未必是坏，不过这种自私的嘴脸确实值得我来学习一个。

既然都快被定性成了社区之敌，那我这样的人又能干什么呢？毕竟我一开始也只是想说一句，“他们这么做凭什么”，现在却被上了深刻的一课：你不够格，欲练此功还需先自宫。沉浸在遇到群众自发组织的Miniluv支部的感动中，我想，我是应该学着说一些新话了。至少不能让社群的骨干们觉得不安，好让他们在fork下来几段js下来时候安心一些。

那么我应该说些什么，才能像你们一样为贯彻落实“社区里禁止讨论你们或者一些人不想看到话语”的新规做出贡献呢？
想来想去，只有四个大字：你好呀，这位犬儒，请多指教。

**Comment by huoqiangf** [comment]
是的。。。赶紧除了天天无奈的被党国代表意外，作为一个程序员现在又要被这些上蹿下跳污染github氛围的人代表。。还真的是恼火和无奈啊。。。

天啊， 大家就不能好好的做自己吗，为什么总要去代表别人？？

**Comment by huoqiangf** [comment]
现在真的是希望中国赶快把GitHub封了，要不然真的没有办法好好讨论问题啊

**Comment by AnyWAT** [comment]
貌似2楼与1楼不是同类🤣

**Comment by garden4hu** [comment]
既然杭州程序员买房教程可以长居trending前几名，为什么这个就不可以，违法了么？违反社区规定了么？反人类了么？合他们口味的窃窃自喜，不合他们口味的坚决反对。一般这种人被称为“双标狗”

**Comment by Vargnatt** [comment]
从不contribute的犬儒反过来说被墙了就影响写代码了，滑稽。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
