### ISSUE TITLE
公开什么信息了呢= =

### ISSUE THREAD

**Issue by Kooklen** [sikaozhe1997/Xin-Yue#44]
==

**Comment by liyujie1221** [comment]
刚才和北大的同学了解了一下。
岳同学要求公开 调查沈阳教授的会议记录 
至于具体什么时间，为啥要公开会议记录，自己查一下吧。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
