### ISSUE TITLE
中国的程序员都这么自私么？

### ISSUE THREAD

**Issue by TinaHongBu** [sikaozhe1997/Xin-Yue#441]
作为程序员，我很开心 GitHub 能起到这样一个信息记录、分享的作用，我很自豪这里没有政府审查没有删帖，我非常希望我们的平台可以起到一些帮助，哪怕只是给在前线努力的同学一些鼓励。不知道多自私的人才会觉得可能影响自己使用，所以来干涉别人的维权和自由发声。

如果说程序员需要的平台的话，google 你没有，Medium 你没有，中国仿制的类似工具你也用的好好，并自认为技术大牛。叫我们自己建个平台讨论的人，你开发这么厉害，请你自己建个平台去 version control 你的 code 吧。

**Comment by kitety** [comment]
这里政府没有审查?你太天真了吧?!

**Comment by zhichiyuexin** [comment]
政府都能公关github? @kitety

**Comment by TinaHongBu** [comment]
@kitety 你在墙里跪了一辈子，其实也可以试试站起来

**Comment by shanezhiu** [comment]
萌萌，站起来，站起来，站起来，站起来

**Comment by goldimax** [comment]
一只鸟从生下来就关在笼子里 就算长大后笼子打开了 鸟也不会飞了

**Comment by nullpointerxyz** [comment]
我一个每篇文章都从头读到尾，再加上最近的武汉理工，厦大事件，看完半天没心情工作，晚上朋友圈发声的五线Javaer又被代表了？

**Comment by liuyou** [comment]
mdzz

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
