### ISSUE TITLE
现在github成了国内唯一净土

### ISSUE THREAD

**Issue by jiajunhui** [sikaozhe1997/Xin-Yue#443]
这种事件儿估计国内媒体没有敢接的。就怕以后github也需要梯子！

**Comment by huoqiangf** [comment]
github不是中国的，是世界的，希望你能认清这点

**Comment by jiajunhui** [comment]
@huoqiangf 我说是中国的了吗？不要总觉得自己很懂觉得众人皆醉唯我独醒一样！愤世嫉俗代表不了什么！
