### ISSUE TITLE
文中的故事也许是一个"丑恶的事情",但是他作者这样发布"新闻",其实是一件更丑恶的事情

### ISSUE THREAD

**Issue by flarejune** [sikaozhe1997/Xin-Yue#445]
一个比一个丑恶.没有更丑恶的了.
你国度之所以出现那么多丑恶的事情,其实就是因为大部分的人都是和你一样的思想,懂得"占空子",太过于自作聪明.
充分利用"空子"去做一些不顾及他人感受的事情,其实和强奸有什么区别?

**Comment by solayao** [comment]
认同你的观点

**Comment by flarejune** [comment]
为什么别人会侵犯女生?不就是因为觉得你们奈何不了他嘛?
为什么你会发布这些文章?不就是因为你觉得发布到这里,"档"和"人民"奈何不了你嘛?

**Comment by liangsongyou** [comment]
你说他人丑恶的时候请备注一下你自己也很丑恶，不然的话会给别人造成一种（他人丑恶你很干净的错觉）。

**Comment by YuzhouZhang** [comment]
@flarejune 请不要带上“人民”，我不想被你代表！

**Comment by XhstormR** [comment]
对，就是因为裆奈何不了我，就是因为这是你国能访问的最后的净土

**Comment by guodong** [comment]
@flarejune 小伙子我资词你

**Comment by jadegong** [comment]
不要论断人，因你如何论断人，也将被人如何论断

**Comment by FanWuTuoBang** [comment]
惊奇的脑回路！
你为什么不思考一下，人家做的这件事有没有错？
她不是代表这自己，她是代表着所有的女生去要求信息公开。
谁能保证下一个受伤害的不是你的朋友或者说未来你的女儿，当明明是做一件正义的事，却被一群体制洗脑的人来质疑和攻击，只能说明这样的被洗脑者本身是没有脑子的。

@guodong  请不要像个跳梁小丑一样了好么？不知道你头像的名字和你信息的大学是否真实，真的，别给同济学子丢人了好么？你还Following的XilongPei 同济大学电子与信息工程学院实验中心教师，你以为带上个小丑的面具，别人不会知道你是谁了么？

**Comment by guodong** [comment]
@FanWuTuoBang 打扰了

**Comment by flarejune** [comment]
@FanWuTuoBang  发生这样的事情,就应该用你聪明的脑袋去找解决办法,去取证,去讨公道,
而不是和傻子一样,只会发布一篇片面之词的文章.在这个时代,各种信息乱七八糟,真假难辨,你以为就凭一篇片面之词的文章,能起到什么作用,或者说有何意义?
如果真的有公理,在这个时代,也不至于会被某些组织只手遮天掩盖一切的.
所以说,发的这些文章,除了恶心人或者是取乐某些人之外,毫无存在价值.

**Comment by guodong** [comment]
@FanWuTuoBang 我也去申请个马甲和你互怼

**Comment by mutou172** [comment]
我一点也想不明白。墙内没梯子，那么待墙好就好了嘛！
联想到电视或现实鸣冤的事情，
后面一想到历史，真可怕，犹太人哪时怎么办？日本侵华哪时，国人怎么办？
滚粗去，不要影响我。。。
我认为说影响他们的，这些人已经暴露了，你们要么是连萌萌都不如，要么就是帮凶。
不会庆幸没出生在战乱年代，
也不会为自己出生在战乱年代而感到可怜。
不管自己处在什么时代，做不到挺身而出，但也不能落井下石。

**Comment by xcb-window-t** [comment]
@FanWuTuoBang 申请好了

**Comment by flarejune** [comment]
@mutou172  你难道认为我是落井下石?我只是路过看到一个奇怪的"PROJECT",居然排行在热门列表第二位,我好奇进来看下,结果......
你们发东西看下环境好不,发来GITHUB给谁看?给码农看?是不是只有码农才有"知事之权"?要不然,为什么要发到GITHUB,我依然是那句:为什么要发布到GITHUB?
互联网那么大,大可以发布到其它国外论坛,一样可以传播你的"事迹",你们一样可以"挺身而出".
全世界就只有GITHUB能自由发布信息?

**Comment by FanWuTuoBang** [comment]
@flarejune OK我可以听取不同的声音，但是你在墙内给我找出来一篇相关的文章或者报道啊？只有官媒的漏洞百出的解释，微博和谐关键字，微信公众号相关的文章全部删除，你告诉我从哪里听取“多面之词”？
你认为恶心请你离开啊
我还告诉你，有的组织真的可以随便只手遮天掩盖真理的。
如果说墙内司法独立，媒体自由，公权力得到有效的监督，你觉得还会有这种事情么？你为什么不去想这些？还去质疑人家的目的？

**Comment by daodangui** [comment]
来，你给我找一个不丑恶的有效的发声方式

**Comment by FanWuTuoBang** [comment]
@flarejune 发到国外其他论坛有什么用？有多少人会去关注？
为什么要引起这么多人去关注这件事，因为只有关注的人多了，舆论的压力才会督促官方较为合理的去解决问题，也能保证同学不会受到不公正的待遇

**Comment by mutou172** [comment]
照某些人的理论，你们自己的理论，我认同你们的理论，所以发布在github也没错啊

**Comment by xcb-window-t** [comment]
@FanWuTuoBang 非要挑起大众的反共狂潮么？你以为我党会纵容犯人么？来来来，你行你来当领导试试

**Comment by chengdong0421** [comment]
@FanWuTuoBang 所以，发在这里有用？

**Comment by chewenkai** [comment]
@flarejune @FanWuTuoBang  

要是能讨到公道，还用跑到国外的网站丢人显眼吗？

要是连这里都没有声音了，还有哪里能发声呢？难道就这样悄无声息的最后不了了之了？有舆论总是有用的，不能像陶崇园同学一样，现在还有感觉已经没有什么消息了。要不然你告诉我她应该发到哪里？发到国内然后坐等被删是吗？

你可以不理解别人的处境，你可以不支持，但不要随意反对。
你可能已经被工作磨平了边角，你不知道她这是怎样的一个英雄，但我们知道，我们广大的学生群体知道。

**Comment by FanWuTuoBang** [comment]
@guodong 对于你这种，这两天阴阳怪气的言论，懒得和你BB。
跪久了，连挺直腰板都做不到，然后还去嘲笑其他挺直腰板的人。
又是you can you up的神奇借口。
纵不纵容犯人另说，但权力凌驾于法律之上这是事实
我没有说反这反那，我只是维护做人基本的尊严。言论自由是最基本的人权。

**Comment by FanWuTuoBang** [comment]
@chengdong0421  觉得没用，你别来这里啊。

**Comment by SakuraLove** [comment]
来，你给我找一个不丑恶的有效的发声方式

**Comment by flarejune** [comment]
@daodangui  @FanWuTuoBang @chewenkai 
花费几百元(实在没钱的,你可以去募捐),随便到国外服务器申请一个空间(主机托管),就可以随心所欲发布你想发的信息了,不需要来污染GITHUB.....
懂得来GITHUB的,难道连申请服务器都不会吗?
我依然是那句:为什么要选择GITHUB,抓破脑袋也想不通.

**Comment by SakuraLove** [comment]
？？？申请空间，不保准某一天就被墙了，你自己去看看，github.com就https://github.com/sikaozhe1997/Xin-Yue/这个地址已经被QQ辨别为危险链接了，如果自己弄服务器和域名，保准2天就墙。

**Comment by chengdong0421** [comment]
@SakuraLove 所以，还是来祸害GitHub比较好

**Comment by flarejune** [comment]
@SakuraLove 你懂得这个道理,你还要做殃及池鱼的事情?非要拖GITHUB下水?居心何在?
就是要等GITHUB被封了才爽对吧?
什么心态?丑恶不?知道丑不?

**Comment by SakuraLove** [comment]
能发声的地方自然就会有声音，有人拿github项目来写博客、有人拿issue来做评论系统楼主你就是个杠精吧

**Comment by chengdong0421** [comment]
@FanWuTuoBang 这。。。我来这里不是为了所谓的伸张正义的呀。。。

**Comment by SakuraLove** [comment]
凭什么发声就是要殃及鱼池了，一没传谣二不违法，难道客观事实都被不能说了吗？

**Comment by xcb-window-t** [comment]
@SakuraLove 唯恐天下不乱

**Comment by flarejune** [comment]
懒得讨论了,你们爱闹哪样是哪样,纵使全国人都知道了这件事,又如何.和看一个故事/电影有什么区别.没有切身体会的事情,永远都只是一个故事.继续辩论只会帮你HOT起来,老夫闪了.你们继续.

**Comment by SakuraLove** [comment]
你不觉得你更自私吗，大学性侵是一个更大更恶劣的社会事件，不值得被关注吗？
唯恐天下不乱？真的要把伤口全都捂住等着腐烂才叫“稳”？

**Comment by SakuraLove** [comment]
文中只不过是要求公开信息，一没传谣二不违法三没反动。唯恐天下不乱？

**Comment by xcb-window-t** [comment]
@SakuraLove 学校已经做过处理了啊，家丑非要外扬啊

**Comment by SakuraLove** [comment]
这就更可笑了，学校这是处理？掩人耳目的伎俩罢了。

**Comment by xcb-window-t** [comment]
@SakuraLove 非要把一个教授关到监狱里你就开心了是吧

**Comment by SakuraLove** [comment]
好吧

**Comment by SakuraLove** [comment]
原来教授犯法不用受处罚
那这个讨论就没有意义了

**Comment by SakuraLove** [comment]
可以close issue了

**Comment by xcb-window-t** [comment]
@SakuraLove 处罚啊，肯定处罚啊

**Comment by chengdong0421** [comment]
@xcb-window-t 你这话说的就不对了，如果事件属实，该教授必须得到应有的惩罚！！！

**Comment by xcb-window-t** [comment]
@SakuraLove 你以为学校纵容这样的行为？

**Comment by SakuraLove** [comment]
没有看到有相关处罚的官方公告或新闻哦

**Comment by xcb-window-t** [comment]
@SakuraLove 圈内人知道这样的后果就行了，爆出来影响不好

**Comment by daodangui** [comment]
@xcb-window-t 你的意思是，因为他是个教授，所以犯了法也不应该被关进监狱里是吗？你脑子瓦特了吗

**Comment by SakuraLove** [comment]
楼主所谓的删项目是为了确保github不被墙，既得利益者是广大的国内码农，
如果这个事件真正引起关注，国家关注乃至引此未戒完善法律，既得利益者是大学生乃至全社会。
以既得利益者范围来看，
假如楼主说在这里发布新闻是一件更“丑恶的事情”，那楼主不是“以百步笑五十步”吗？
按我来说，在这里发布新闻更是一个可笑的行为，也确实是一个外扬家丑的行为。
凭什么一个人民当家做主的国家，这种恶性社会事件都不能拿在国内的主流媒体去讨论？
老回找三星维权但至今仍无结果，甚至被某些地方官员殴打，这已经让我心寒一次了。
那这一次呢？
@flarejune 其实说得很好，殃及池鱼。
城楼失火，救火，殃及池鱼。为了我们这群鱼，当然是选择不救火了。

**Comment by nbwuzhe** [comment]
当年相关的信息该公开吗？当然应该。
岳昕该声援吗？当然应该。

可是，

你们明明可以选择发到其他外面的网站，比如F，比如T，可你偏偏选择了GitHub来做贴吧式的事情。你有没有想过有多少人靠着在G上写代码养家糊口，而有些人还在大言不惭地说“不会翻墙还好意思说自己是程序猿”——我们的职责是写代码，不是翻墙，谢谢。

为了自己的利益拉上无辜的人当炮灰，打着如此政治正确的口号。很棒。
