### ISSUE TITLE
好了，现在真成“境外势力”了（逃

### ISSUE THREAD

**Issue by IIzzaya** [sikaozhe1997/Xin-Yue#446]

**Comment by zhangn1985** [comment]
整个文章的语气就是境外势力的语气。
指正，阐述完全就是单方面的。
看上去好像是，共产党你犯了错，赶紧道歉，解释，我不听我不听。

**Comment by ayaservice** [comment]
今天是西藏政治犯-十一世班禪喇嘛29歲生日｡他6歲就遭中國劫持,一個手無寸鐵的孩子也能把中國嚇成這樣!他失去自由已經整整23年,請各界關注! https://t.co/FZeoIpsrhE

**Comment by zhangn1985** [comment]
@ayaservice 滚，藏独。

**Comment by IIzzaya** [comment]
还好吧，人总不能做到绝对客观，一切说法都有服务需要的，即使是最小的个人。

**Comment by zhangn1985** [comment]
@IIzzaya 你看到了吗？境外势力进来了，对吧，你还能相信这个事件没有境外推手？或者潜伏在中国境内的第五纵队吗？

**Comment by ayaservice** [comment]
不滚 这个社区是世界的，而且这个帖子并没有说西藏独立哦，你自己说的哦

**Comment by IIzzaya** [comment]
倒不是不同情政治犯，只是为了中华民族伟大复兴，部分牺牲品是必定存在的。自然会变成别人的傀儡棋子也是很正常的

**Comment by zhangn1985** [comment]
@ayaservice 你要不是藏独分子，我把头给你当凳子。

**Comment by IIzzaya** [comment]
我只是站在中华民族角度看待这些藏独台独分子。他们确实不值得同情

**Comment by ayaservice** [comment]
西藏是世界的 该滚的是你们

**Comment by zhangn1985** [comment]
@ayaservice 暴露了吧，还说自己不是藏独！！！

**Comment by IIzzaya** [comment]
世界是谁？

**Comment by zhangn1985** [comment]
@IIzzaya 当然是西方哦。。这还用说！！

**Comment by ayaservice** [comment]
这些人不是不明白，是故意把统一和民主对立起来，忽悠脑残煽动独立分裂，只要有人搞独立分裂最开心的是谁，当然是共匪了，搞的越欢共匪越能煽动民族主义，共匪的江山也越坐的稳。看看达赖尊者多次公开声明不会搞西藏独立，共匪都得给人扣个藏独的帽子，还有谁看不明白这种独立分裂的把戏吗？

**Comment by ayaservice** [comment]
西藏流亡精神领袖达赖喇嘛4月16日在印度接见逾1,500信众及游客，并发表近两小时的演说。达赖重申不寻求西藏独立，强调随着时代的变迁，中国在未来几年可能会有正面的改变

**Comment by IIzzaya** [comment]
江山稳不稳，与你何干。哦，无非是触动了你的利益。又或者是自我满足罢了

**Comment by ayaservice** [comment]
请问中华民族是哪个族呢？大汉沙文族吗？

**Comment by IIzzaya** [comment]
西藏地方政府还会见百万藏民呢

**Comment by IIzzaya** [comment]
这都被你发现，这不是儒家文化圈最喜欢最擅长的事么？

**Comment by IIzzaya** [comment]
中华大地历史了解一下

**Comment by ayaservice** [comment]
拒绝以中华民族的名义统一思想，我不一样，我就是要活出张牙舞爪的个性来😂

**Comment by zhangn1985** [comment]
@IIzzaya 别跟他吵了，没意义，真的，他就是原西藏奴隶主，怎肯放弃自己的特权，在西方的支持下，肯定是要求复辟的。西藏好不好，问翻身做主的农奴就可以了。

**Comment by ayaservice** [comment]
赶紧封了吧 墙内傻逼浓度多

**Comment by IIzzaya** [comment]
anyway了，我就是消遣消遣。溜了溜了，听课

**Comment by zhangn1985** [comment]
@IIzzaya 你要了解到，每次这种事件被推向高潮，少不了境外势力。我们亲历境外势力吧

**Comment by ayaservice** [comment]
倍受中共推崇的苏俄干爹，在历史上对中华民族犯下了滔天罪行！
美国帮助中国加入世贸，获得经济腾飞，历史上三次曾经拯救过中华民族！
那为什么教育民众反美不反俄？
基于意识形态的需要，反美能巩固专制独裁政权，让民众永远活在愚昧中！反智化洗脑很恶毒，导致这个国家迟迟无法取得真正的文明和进步

**Comment by IIzzaya** [comment]
利益都是流动的，利益链遍布全球，有境外势力是正常的，关键是如何处理好，利用好。

**Comment by ayaservice** [comment]
中华人民共和国局域网防火墙内太多的愚民，他们被长期的洗脑灌输欺骗，已经不能用自己大脑来分辨是非了。告诉他们真相，他们完全不相信，而且还会给你下道德评判地大骂你，，，，

**Comment by zhangn1985** [comment]
@ayaservice 我们是真相的大多数。

**Comment by IIzzaya** [comment]
墙本来就是个相对的东西，洗脑也是。都是成年人了，B数藏在自己心里，价值观没那么容易改变的。不吵了好吧

**Comment by ayaservice** [comment]
爷有点想笑，草榴上讨论政治问题大家都团结一致骂你匪，几个舔着他匪嘴角流的剩汤活着的码畜看见在github讨论的敏感内容却如临大敌

**Comment by ayaservice** [comment]
你的脑袋是里面全是浆糊吗？

**Comment by ayaservice** [comment]
@zhangn1985 你的脑袋里面全是浆糊

**Comment by ayaservice** [comment]
发个段子：牛逼！不扶墙只服你！同样是失去的国土，喊“钓鱼岛是中国的”是爱国，喊“还我海参崴”就是别有用心

**Comment by zhangn1985** [comment]
听话，我们在批判你藏独的问题，你的错误还没有被清楚的认识！！

**Comment by ayaservice** [comment]
@zhangn1985 很多中国人喜欢用“你是某独！”等轻易下结论的语句评论别人，我表达的本来就是我的个人观点，而不是别人的观点。是我认为正确的观点，而不是人人认为正确的观点。

**Comment by gaoxiaosong** [comment]
@ayaservice 滚你妹的藏独。

**Comment by Croash** [comment]
@ayaservice smoe noe wlil hakc yuo。。。
