### ISSUE TITLE
大家都别吵了，一起来帮忙收集资料吧

### ISSUE THREAD

**Issue by wql7013** [sikaozhe1997/Xin-Yue#448]
项目作者一直在默默的更新资料，一直没有参与争吵，值得敬佩。我们也一起帮忙收集信息然后pull上来吧，起码可以把这个项目当做相关事件的文档库。
通过这个项目，我发现，GitHub还是很适合用作资料文档库的，更准确说是基于web的Git仓库很适合用于文档库。
突发奇想，是不是我们应该建立一个专门用于各领域资料共享的web Git仓库呢？甚至有一天实现“论文开源”呢？或许是不错的创业项目。

**Comment by oliverxyy** [comment]
证据齐全的陶崇园事件也没有任何处理呢，见https://github.com/lonufate/ArchivesOfTaoChongyuan

**Comment by wql7013** [comment]
@tsai1993 不是这个。我觉得基于Git的web仓库比基于blockchain的更合适作为资料库。代码库上的成功我觉得可以推广到其他方面。类似于维基百科，但是维基百科作为资料库总有些缺点。Git我觉得开源弥补维基百科的缺陷。多人参与的项目，通常项目管理者值得信任，项目参与者可以共同审核、修改和添加内容，我觉得很好，可以作为一个强大的各领域专业知识库。

**Comment by wql7013** [comment]
@oliverxyy 但是有一个完整可信的资料库，总是好事，谣言也会少。
