### ISSUE TITLE
要是年轻人都不敢发声了，这个nation还有救？事不关己听之任之？

### ISSUE THREAD

**Issue by EVA1stgeneration** [sikaozhe1997/Xin-Yue#451]

**Comment by zhangn1985** [comment]
但是，这个git这么做，完全不是正确的发声方式。

**Comment by crescendo007** [comment]
很羡慕100多年前，那时候的年轻人可以为了国家的命运，走上街头去宣讲自己的诉求，于是有了伟大的五四运动。而今的大部分年轻人，除了关心娱乐和游戏，心里面什么都没有，很担心这个国家的未来。想起犹太人大屠杀纪念馆的一首诗：

起初他们迫害共产党人，我没有说话，因为我不是共产党人；
后来他们迫害犹太人，我没有说话，因为我不是犹太人；
再后来他们迫害天主教徒，我没有说话，因为我不是天主教徒；
最后他们迫害到我头上，我环顾四周，却再也没有人能为我说话。

**Comment by one-smiling** [comment]
@zhangn1985 来来来，你给推荐个国内不用翻墙，广大网民能看到的地方

**Comment by EVA1stgeneration** [comment]
何妨不视之为1980年光州的胶卷

**Comment by FanWuTuoBang** [comment]
跪久了，觉得跪着才是常态，站起来或者挺直腰板的人都是异类。

**Comment by tuanweishuji** [comment]
@one-smiling 你可以自建热点来发声，去广场上走一圈，效果比在这打字好

**Comment by zhangn1985** [comment]
@tuanweishuji @one-smiling 当年利比亚也是被无线热点击垮的，你就知道西方颜色革命的厉害。

**Comment by tuanweishuji** [comment]
@zhangn1985 同意

**Comment by zhangn1985** [comment]
卡扎菲也许真的不好，但是一个稳定的国家，多么重要，为了一时激情，走上街头，以为这个就是民主？？看到下场了吗？利比亚，多么繁荣的世界。现在满目残垣断壁。

**Comment by tuanweishuji** [comment]
别动不动”再也没有人为我发声了“。非要在GitHub上发声，可以用你的真实账户，fork一下。这都不想做，你怕是对发声有什么误解。

**Comment by aminic** [comment]
一个稳定的猪圈对吃好喝好的猪们当然很重要

**Comment by zhangn1985** [comment]
中国有句老话，乱离人不如太平犬。

**Comment by aminic** [comment]
有能力你也出国，没能力安心做韭菜？

**Comment by zhangn1985** [comment]
不，我绝不出国。国家是我自己的，我要在国内贡献自己的力量。
但，我现在清楚的意识到，是谁给了我们安定的生活，谁又想来破坏这个安定！

于是，我知道谁是我的敌人！

**Comment by zhangn1985** [comment]
如果哪天，共产党给不了我们安定的生活，也用不着你们外国人来干预，我们自己的事情自己处理！！！

**Comment by EVA1stgeneration** [comment]
一个国家原则不容置疑，只是我们共同的希望都是 权力能够倾向于使广大人民沾惠受益的方向。事非盲目，可以去看看北大未名BBS上理性的思考。此issue终结，谢谢各位。

**Comment by zhangn1985** [comment]
理性一点，耐心一点。

**Comment by one-smiling** [comment]
@zhangn1985 @tuanweishuji 
利比亚的无线热点也是建立在用户基数大的facebook和twitter，而国内广大网民又访问不到
![2018-04-25 10 59 15](https://user-images.githubusercontent.com/6986063/39224086-ec03dd1a-4877-11e8-84a6-777552126956.png)

**Comment by zhangn1985** [comment]
@one-smiling 看问题片面了，FB等我们是访问不了，当年卡扎菲也屏蔽网络了，是用手持的卫星网络。
而且不一定只能用FB，国内很多自媒体都不在党的视野下的。

**Comment by one-smiling** [comment]
@zhangn1985 你可以列举几个，让当事人去试着找一下呗
1、如果是依托在腾讯、微博等国内自媒体平台就算了
2、就算你说的这几个自媒体能够发声，谁又能他们的平台能够正常访问而不被屏蔽吗？
