### ISSUE TITLE
大兄弟们，别这样玩

### ISSUE THREAD

**Issue by Geniune** [sikaozhe1997/Xin-Yue#453]
惊奇的发现居然还有这种操作，然而并没什么luan用，在各大社交平台里贴的链接直接点击根本打不开，民不与官争,穷不与富斗，如果天朝真的言论自由就不会有墙

**Comment by GameBunring** [comment]
不想贡献还是别来掺和了，如实记录事件本身就是意义

**Comment by Geniune** [comment]
什么贡献记录事实，虚伪而且还作死。平台本来就是一个清净之地，通过这个平台发声国内有谁能听得见？有能耐就去跟执政党撕逼不要在这里发文章，很猥琐还不受人待见

**Comment by GameBunring** [comment]
是你猥琐还是贡献者猥琐？

**Comment by Geniune** [comment]
贡献者无处发声，跑这来吐槽，就是猥琐
关键点是还有你们这些无脑支持的猥琐玩家
跟gov对着干，于公于私对你们这些小老百姓有没有好处自己心里没点B数？一定要墙了平台才开心？

**Comment by Geniune** [comment]
所以说，你连程序员基本的素质都不动，跟我谈贡献，这平台本质是干什么用的自己不知道？有没有想过不是你一个人在用？
你愿意用梯子就要所有人都跟你一样？真的以为在国外就可以为所欲为了？
有能耐不要生活天朝，赶紧偷渡去国外，那里言论自由

**Comment by GameBunring** [comment]
1. Github的是用贡献量说话的，你这个0级小号在这里是没有发言权的
2. 我在湾区，不需要偷渡，也比你更懂什么叫程序员
3. 我不会再和你做无畏的争论，你看看大家的拇指就好

**Comment by Geniune** [comment]
请你这个弯的直不起来的程序员该干嘛干嘛去，别在这里贡献这种rep
巴掌点大中国台湾县出来的乡巴佬也想干涉大天朝的政事，你配吗？台独分子肯定有你
叫一群水军来点拇指就能说明情况了？有本事就来国内发个试试，看警察请不请你吃牢饭

**Comment by ayaservice** [comment]
@Geniune 妈的 习包子赶紧把这个网站封了吧，不封我天天来发敏感政治信息

**Comment by Hardrain980** [comment]
@Geniune 湾区=台湾?
笑死我了
傻逼玩意先撒泡尿照照自己的智商再出来放屁吧

**Comment by Hardrain980** [comment]
@Geniune 可惜你中国话都不会读真是不能更废柴了
我给你亲妈逼里塞进个篮球 你瞎妈流出的B水都让洞庭湖水位上涨辣

**Comment by Seedarchangel** [comment]
哈哈哈哈哈哈哈哈湾区台湾傻傻分不清楚

**Comment by Geniune** [comment]
@Hardrain980 对你这种说着中文还满嘴喷天朝的人需要文明两个字？有本事在这里把你家地址贴出来，看看明天有没有人请你吃牢饭，傻吊

**Comment by Hardrain980** [comment]
@Geniune 废物还玩信砍呢怕不是要成为侯聚森第二

**Comment by ayaservice** [comment]
@Geniune 傻逼 你在中国人民共和国网吧里吃了多少年的泡面了呢？大脑都成浆糊了吗？

**Comment by ayaservice** [comment]
@Geniune Free Tibet

**Comment by Geniune** [comment]
@ayaservice 你个泰国人妖赶紧回厕所吃屎，想搞分裂你还嫩着，我们叫中华人民共和国，是你这乡巴佬也配评头论足的？

**Comment by ayaservice** [comment]
@Geniune Tibet belong to Tibet people.中国人民共和国的居民们你们好好在猪圈里吃猪食得了，跑到自由世界丢人现眼

**Comment by leciel-guo** [comment]
这个傻逼

**Comment by Geniune** [comment]
@leciel-guo 注册个小号就来这里满嘴喷粪？

**Comment by ayaservice** [comment]
@Geniune 你只是中华人民共和国的居民，只不过是中国共产党的奴隶而已，国家大事归总书记习包子统治哦

**Comment by Geniune** [comment]
@ayaservice 那也好歹比你这个被阉割了的人妖强，也好意思用中文对喷，滚回你自己的国家去，知道习大是谁还不收敛，不见棺材不掉泪

**Comment by ayaservice** [comment]
@Geniune 郭叔最后一次和陈氏兄弟通话，是2月15号
之后二人去新加坡交易肖建华的全部卷宗，被臭不要脸的土共绑架回中国
2月24号，李克强的大秘杨晶被处分
罪名是“长期与不法企业主，补发社会人员不当交往”
杨晶是陈氏兄弟的妹夫 https://t.co/DzYuuTQMe2

**Comment by ayaservice** [comment]
给你发各种敏感信息，看看党国警察请你喝茶不

**Comment by ayaservice** [comment]
@Geniune 每天给你发各种敏感信息 看看党国警察来不来这里请你喝茶呢？习包子修宪法遗臭万年

**Comment by Geniune** [comment]
@Mason-Xu 你是国人我不想喷你，自己看看上面那几个人，都是搞分裂的，弄清楚我喷他们的原因再说话

**Comment by leciel-guo** [comment]
@Geniune 妈的，喷的就是你，智障

**Comment by ayaservice** [comment]
@Geniune 厉害了你的国，用战狼还是抗日神剧来展示你的智障大一统的思维呢？自古以来海参崴也是你大中国的一部分，你怎么不敢骂俄罗斯呢？谁是卖国贼历史都很清楚哦

**Comment by ayaservice** [comment]
忘了蒙古貌似自古以来也是你大中国的一部分哦

**Comment by wangduheng** [comment]
别人是女的

**Comment by Geniune** [comment]
@ayaservice 死人妖能别说话了？儿子都生不出来还想搞分裂，就你那小国家屁大点地，我天朝人民一人一口痰都能淹死你们这群牲畜，在这里做喷子就想要什么收效就跟你的吊一样，没用。早点回泰国继续做你的人妖表演吧

**Comment by Freedom5400** [comment]
楼上叫什么Geniune就是个弱智小粉红，大家也别和他计较
