### ISSUE TITLE
那群从来没在这里贡献过的请离开。

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#454]
一群注册不到二十四小时的人。
夸夸其谈和我讲社区精神。

本来觉得他们的遭遇挺可怜的。
如今看他们嘴脸这般恶心。

github被封了你不会vpn？
说得好像我们就应该用vpn来访问这个本不需要vpn的网站一样。

你和他们讲道理，他们和你扯皮。
你和他们扯皮，他们说你是跪惯了？

这社会很多不如意的地方，所以我们去占领github吧。

岳昕太惨了，所以我们去恶心程序员吧。

脑洞清奇，栋梁之才。

一个个把自己说成如此进步青年，却窝在这地方做一些损人不利己之事。

一个个出自高等院校，却连表达气势也要用脏话谩骂的方式。

一个个天之骄子，竞无正经所为之事，只躲在这个角落里自怨自艾。

睡醒了就闹事，闹困了就睡。为什么闹事，找一点存在感呗。

**Comment by EVA1stgeneration** [comment]
分享并传承前辈们的智慧成果不算是贡献？

**Comment by jason19659** [comment]
一群傻吊，艹，今天老子clone都卡的要死

**Comment by FanWuTuoBang** [comment]
Repositories 29
Stars 26
Followers 5
Following 2

**Comment by xiongwei-git** [comment]
Repositories 0
Stars 1
Followers 0
Following 0

**Comment by FanWuTuoBang** [comment]
@xiongwei-git 呵呵  我就是昨天才申请的马甲，看我的名字也看出来了吧？
理论上说不过别人，开始用身份来彰显自己的存在感了么？
言论自由是不是也分身份的高低呢？
所以赵家人能说的，你只能默默的跪着

**Comment by 2lei** [comment]
你暴露的个人信息太多了，再跳，怕是往火坑里跳

**Comment by dp199313** [comment]
连恶心人都要用小号，你们当这是百度贴吧？

**Comment by FanWuTuoBang** [comment]
@jason19659 可笑了，区区这么点访问量还能让github卡顿了？你以为这是ddos攻击呢？
这点流量对于guthub来说能占多少？上来就喷，狺狺狂吠

**Comment by FanWuTuoBang** [comment]
@dp199313  你觉得恶心你走啊，或者说你给出切实可信的方案啊？
没有大众的支持，这件事能得到广泛的关注么？能有舆论压力么？

你是不是还要来一句：“何不食肉糜”？

**Comment by turnureyes** [comment]
你这般嘴脸才真让人恶心，典型的一副共匪的流氓姿态，您所谓的贡献标准是什么？谁制定的？小屁孩？

**Comment by jiangzemingzz** [comment]
你个傻屌贡献了啥

**Comment by dp199313** [comment]
你们这群人吃不起饭的时候我们还有义务教你们种地？方法如何没有，只不过你们苟在这里有人和你们聊天存在感更强，更省力气罢了。

**Comment by daodangui** [comment]
@dp199313  所以你希望大家怎么做？在微信、微博上发声，等着被删，或者一直隐忍，等着最后迫害到自己头上？对国内疯狂删帖、禁止自由言论的行为，竟然没有一点意见和想法的妈宝，自己选择做个所谓聪明人、识时务的奴才，那这样就好，并没有人胁迫你，可你非要自诩清高的跑出来，要求别人也像你一样做个奴才，就是你的不对了

**Comment by lester88a** [comment]
# # # # #464

**Comment by CeresCheng** [comment]
啧，那我也资格了，你又不是官方你代表什么？

**Comment by nbwuzhe** [comment]
@dp199313 和这帮没事找事的废什么话，直接report这个user和repo就行了。要发泄情绪去他们的贴吧微博发泄去，找不到地方去外面的F家T家都行，非要找一群写代码养家糊口的当垫背，拉下水，是何居心。

**Comment by CeresCheng** [comment]
@nbwuzhe 啧啧，阉割至此
