### ISSUE TITLE
GitHub已经被封过了，更别提gists一直被封禁了，也许有的人已经没有腿了都不知道

### ISSUE THREAD

**Issue by gledos** [sikaozhe1997/Xin-Yue#457]
GitHub再次被封是最好的，激起民愤。

政府不敢这么做，放心，顶多像steam一样墙到残废

**Comment by jiangzemingzz** [comment]
政府不敢这么做？？

**Comment by aminic** [comment]
党国体制碾压一切，还搞不定码农？一颗赛艇啊兄弟。gayhub封了最好，最好全面封了。

**Comment by gledos** [comment]
@aminic 

碾压一切那么为毛搞不定 GitHub ，明明当时都封了好几天

**Comment by iBug** [comment]
很多人是在党国面前跪久了站不起来了，不要理他们。GitHub上次是因为李开复等大佬发声取消封锁的

**Comment by aminic** [comment]
@gledos 党国碾压一切难道是错觉？墙内还是能随意虐杀的吧。
