### ISSUE TITLE
是不是已经被屏蔽了？

### ISSUE THREAD

**Issue by xu-song** [sikaozhe1997/Xin-Yue#458]
## QQ

![image](https://user-images.githubusercontent.com/13825126/39222787-018b3fe0-4871-11e8-9994-75104a163fa2.png)

**Comment by DemoHn** [comment]
只要github不屏蔽，复制到浏览器就可以了啊
再不济，那么多fork， 随便一个其他链接都可以啊
https://github.com/DemoHn/Xin-Yue/
