### ISSUE TITLE
我们程序员自私怎么了？难道你们键盘侠不是更自私？

### ISSUE THREAD

**Issue by bramblex** [sikaozhe1997/Xin-Yue#462]
# 请看看评论下面的字眼 “奴性” “下贱” “败类”，你们只是发泄垃圾情绪的键盘侠，你们自己去看看你们的评论是不是和网易新浪腾讯新闻底下的评论惊人相似？

# 祝愿GitHub早日被封，反正我是无所谓的

**我就问一句，假如人民起义要推翻黑暗统治。你们是准备抛头颅洒热血呢？还是逃跑国外？**

你们这些人蠢就蠢在不明白让一个国家疯狂会把自己身牵扯进去。你怎么知道下一个死的人不是你或者你的家人朋友以及爱人？
所以真忍受不了黑暗统治，有能力那就移民吧。
我们这些移民不了的人，只要保证苟活就好了，没你们那些远大理想。

***

GitHub 被封怎么了？当然不怎么啊，对于你们这群键盘侠来说，GitHub 被封了你们不过少一个贴吧，少一个论坛，少了一个博客，少一个拿起键盘发泄自己不满的垃圾场而已，但是你们砸掉的却是成千上万程序员的饭碗知道吗？

对于我个人来说，GitHub 封了就封了，反正我有 VPN，我家在深圳，再不济我过个关去香港上个 GitHub 没问题吧。但是对于三四五线城市的孩子，那些企图从农村里走出来的孩子呢？我们这些一线城市具有一定基础能力和环境的人是不是相当于垄断了技术和知识资源？那从此三四线穷人家孩子是不是别想进程序员行业了？你用百度搜得到 VPN 吗？

本来就阶级固化了，上升渠道收窄了，我们这些 “既得利益” 都在为以后的行业和后来者考虑，你们这些键盘侠呢？除了发泄一些垃圾情绪，有为别人考虑过吗？有为别人做点实事吗？就靠转发个微博，转发个朋友圈点个赞？

你们就说说你们跟那些抗日打砸抢烧的“爱国贼”有什么区别吗？都是打砸抢烧别人的东西，然后高呼一声口号——“你不爱国/你程序员自私”

顺便说一句，那个说“中国程序员那么自私”的程序员人在外国。呵，慷他人之慨，妙啊。

**Comment by FanWuTuoBang** [comment]
你说的有道理，能理解你的担忧
可是，墙内几个大的发声地。微博，关键字都搜不到。微信朋友圈，相关文章全部删除。还能去哪里发声？

来github不是无奈之举么？

还有如果github真的因为这件事被墙，你会不会思考为什么？为什么一件正确的事情反而会被墙？
如果真的被墙，全中国的程序员不会抗争与反对么？
奴性教育已经深入基因了么

**Comment by YumeMichi** [comment]
emmm 为什么你觉得你发这段话就不是键盘侠了

**Comment by bramblex** [comment]
@FanWuTuoBang 
因为程序员是弱势群体啊

**Comment by bramblex** [comment]
@YumeMichi 

所以你咋不去天安门广场散步、自焚、自爆呢？

**Comment by aminic** [comment]
党国体制赵家狗是拿任何人作为博弈对象的，炸不出来点血肉是不甘心的。如此苟延残喘祈求赵家狗们的恩德不如彻底全部墙了，让疯狂和黑暗来的更彻底。

**Comment by bramblex** [comment]
@aminic 

我就问一句话，如果让疯狂和黑暗来的更彻底一点，那一定会死人。
你怎么保证死的不是你或者你的家人朋友或者爱人？
你们这些人蠢就蠢在不明白让一个国家疯狂会把自己身牵扯进去。
所以移民吧。

**Comment by qfzc** [comment]
你不能代表大部分程序员!

**Comment by GenkunAbe** [comment]
导致 GitHub 被封、阶级固化、上升渠道收窄到底是因为把文章发在 GitHub，还是因为网络封锁这个错误政策的存在？如果说「键盘侠」就是只敢在网络上发表异见，不敢在现实中采取行动，那么比「键盘侠」更可悲的就是即使到了网络上也因为跪久了而站不起来。

移民当然是作为一个精致的利己主义者的最好选择，不用承担风险就能享受别国先辈毕生奋斗换来的美好生活。但是精致的利己主义者为何还要关心阶级固化这么大的社会问题呢？

最重要的一点是，这个 repo 目的只是为了声援岳同学要求信息公开以及可能存在的被违规约谈，其诉求只是针对一场校内的事件，或者稍大一点，只是针对国内高校现有的不透明的约谈制度。把讨论的范围扩大到国家层面，转移了注意力，对于各方都只会产生更坏的结果。所以，请不要带节奏。

**Comment by bramblex** [comment]
@GenkunAbe 
无所谓了，反正封就封了。
你自己看看这几年的政治风向吧。
我努力做一个精致的利己主义者好了。

**Comment by Jawnkuin** [comment]
几年的墙已经让这么多人思考无能了，

如果没有这个repo，你能保证github今后不会被墙吗？
如果这次事件沉下去，你能保证你的家人今后不被铁拳砸到吗？

哪里来的自信以为“乖乖听话”你自己就不会牵扯进去？
你这种人蠢就蠢在不明白如果你完全什么都不做，共产主义铁拳就不会砸到自己身上。
感谢现在微博还能短暂地传播声音吧，感谢现在还有人愿意成为勇者吧，你什么都不做明天一定是完全黑暗的。

我们完全在合理范围使用自己的自由，在你眼里“打砸抢烧”和“做赵老爷不喜欢的事”是等同的？

今天限制普通人用VPN的是他们，不是我们这些用VPN的人，
明天限制底层孩子获取技术资源的还是他们，不是我们这些在github做事件记录的人。

一个连赵家人边都没摸到的破程序员能在自由和权利已经被侵犯的情况下，还能义正言辞地斥责其他期望站起来的人，奴性深种！！！

**Comment by bramblex** [comment]
@Jawnkuin 对对对，我奴性我奴性，然后呢？你能改变什么？你说呢键盘侠

**Comment by wujians** [comment]
请你不要自称程序员，你是程序员中的败类。
一天想的不是抗争而是怎么苟延残喘，真是下贱。

**Comment by SakuraLove** [comment]
出国 = 叛国？
思路可真是清奇呢。

**Comment by SakuraLove** [comment]
大家可真是奇怪呢
明明是一个恶性的社会事件，关注点却放在了应该在哪个平台发，不应该在哪个平台发。

**Comment by Vargnatt** [comment]
“你的所作所为没有结果所以你的所作所为没有意义。”
“不闹革命的作为都是键盘侠。”
“你连死都不敢，还敢评论社会事件。”

你的这个思想很危险、很蠢，建议重学《近现代史纲要》。
犬儒起来还理直气壮的人不配说自己精致利己，毕竟这种智力发展水平未必判断出来利没利己，而且也不精致。
