### ISSUE TITLE
感觉一大波五毛混了进来

### ISSUE THREAD

**Issue by daodangui** [sikaozhe1997/Xin-Yue#464]

**Comment by meteorlxy** [comment]
是啊，好神奇，突然就刷起来了

**Comment by zhangn1985** [comment]
没错，我是自干五！
我深刻的相信党能处理好这个问题。
所以不需要吵吵嚷嚷。
给事件的双方带来巨大的压力！

**Comment by daodangui** [comment]
@zhangn1985  它忙着删帖呢，没工夫理你

**Comment by zhangn1985** [comment]
@daodangui 我真是自干五，别误会。

因为自从混入了境外势力，就不是学校和学生之间的交流了。
那是战场，你死我活的战场！！

删帖是必须的！

哪有境外势力？ 藏独都混进来了！知道吗？

看看这个issue
https://github.com/sikaozhe1997/Xin-Yue/issues/446

**Comment by shanshuiluli** [comment]
境外势力是块砖 哪里需要往哪搬

**Comment by zuoge85** [comment]
@zhangn1985 五毛死全家，白干五出门被撞死

**Comment by zhangn1985** [comment]
@zuoge85 不要那么激动，我也不会死全家。肯定比你活得好！

**Comment by zhangn1985** [comment]
@zuoge85 你要知道我以前可是美分啊。

**Comment by zuoge85** [comment]
@zhangn1985 你只是一条狗，跪好，含住别说话

**Comment by GabrielKidd** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。

”
— 馬丁·尼莫拉
