### ISSUE TITLE
那些说害了自己的人都去看你的新闻联播吧

### ISSUE THREAD

**Issue by lilewis** [sikaozhe1997/Xin-Yue#465]
<img width="688" alt="123" src="https://user-images.githubusercontent.com/7970836/39223017-5973f296-4872-11e8-8c52-73504e142d3b.png">

**Comment by FanWuTuoBang** [comment]
赞同
也让我想到《至暗时刻》，如果丘吉尔继续沿用张伯伦的绥靖政策，可能今天这个世界的格局都不一样了。
也让我想到美国那些曾经站出来为黑人平权的白人。
有文化的文化人太多了，而有思想的文化人太少了。
加油，相信随着技术的提升，你也会成为github上的大佬

**Comment by turnureyes** [comment]
客观公正全面

**Comment by gyckey** [comment]
记录在区块链上去吧,这样永远清除不了.

**Comment by lilewis** [comment]
不才，区块链技术目前只有耳闻，还未曾实践😂
