### ISSUE TITLE
别他妈自私不自私，你不写代码github被封了你无关痛痒

### ISSUE THREAD

**Issue by liuyou** [sikaozhe1997/Xin-Yue#467]

**Comment by meteorlxy** [comment]
- 写代码，虽然不多，但是起码比你勤快一点
- 被封了也无关痛痒

**Comment by fancoo** [comment]
1.你写代码，但你分享给整个git社区的全是`README`，你只是github的索取者。
2.被封了也无关痛痒。

**Comment by huoqiangf** [comment]
对， 我觉得现在跳出来闹的没有几个是真写代码的。。。现在就算还被被墙但上github的时候也用梯子啊。。。。直联的这个渣网速。。。。真程序员是受不了的。。。

**Comment by meteorlxy** [comment]
@huoqiangf 是啊，访问的话还好，有时候clone一个大项目要抓狂

**Comment by FanWuTuoBang** [comment]
我给你分析分析为什么不会被墙。
假如被墙，全体程序员是不是要问为什么？
不要低估了程序员的信息检索能力
一番检索，发现原来是因为这个问题？然后很多人会去了解这是什么事情，然后变成了更多的人来声援。

**Comment by three1bro** [comment]
@meteorlxy 别说大项目了，有些小东西的速度看着都是奔着天去的

**Comment by laobie** [comment]
程序猿不知亡国恨 大清完了还在写代码

**Comment by CeresCheng** [comment]
老子会翻墙，你还是滚走吧

**Comment by SakuraLove** [comment]
别他妈自私不自私，教授违法犯罪没人管了你无关痛痒！

**Comment by wujians** [comment]
谁封的你找谁去，对封你的人屁都不敢放一个，在这里来吠，一个字：贱。

**Comment by Vargnatt** [comment]
你他妈一年就三个contribution两个issue一个create你他妈有脸跟我们说这个？？？？

**Comment by UpJunior** [comment]
你是怕github被墙，自己没处抄代码了吧??

**Comment by aminic** [comment]
大清自有国情在此，诸码退散？

**Comment by zhangsanlonglong** [comment]
封了不就封了嘛,天天指望抄GitHub也不中

**Comment by jacobswan1** [comment]
我写代码怎么了？你这种底层程序员care你的死活有意义？

**Comment by Vargnatt** [comment]
@jacobswan1 终于有人说了我想说的话了。至少最近几天的观察并不能导向一个对js程序员友好的结论。

**Comment by joname1** [comment]
看了你的主页，你tm从2013年开始注册，一年就2~3个contributions、两个issue、一个create。你tm有脸跟我们说这个？？？？
你自己的repo里面除了README没有别的东西了？脸都没有？

**Comment by beyondxuxingwang** [comment]
写代码也觉得封了就封了白，就你自己写代码

**Comment by Hardrain980** [comment]
你写的readme比代码行数多多了

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~

**Comment by jerzygao** [comment]
作为一个程序员还特么担心网站被封，你也真牛逼啊，艹

**Comment by harryge00** [comment]
借宝地问下 clone 如何快。我用代理也就100k 多

**Comment by ethermoto** [comment]
换个好代理，我这还挺快的
