### ISSUE TITLE
微信入口也被墙了

### ISSUE THREAD

**Issue by young-mu** [sikaozhe1997/Xin-Yue#468]
![wechatimg22452](https://user-images.githubusercontent.com/7543236/39223150-eb36be8e-4872-11e8-93b5-8ce35ad07a7a.jpeg)

**Comment by wjwzju** [comment]
真是快准狠

**Comment by aminic** [comment]
毕竟墙国，怕的要死。

**Comment by zyfdegh** [comment]
乖儿子马化腾

**Comment by kilobtye** [comment]
Duplicate of #285
