### ISSUE TITLE
我写代码啊，可是我翻墙写啊。你不会只用百度吧哈哈哈

### ISSUE THREAD

**Issue by AplloBattlestarGalactica** [sikaozhe1997/Xin-Yue#470]

**Comment by asklogic** [comment]
大家都会翻qiang 干脆把地址不在中国的网站都____了 嘻嘻

**Comment by AplloBattlestarGalactica** [comment]
我感觉好多人貌似不会自己架梯子，所以一直觉得会被block。利益相关。

**Comment by bramblex** [comment]
我们当然有 VPN ，我们怕被 Block 不是因为怕我们上不了。

那些三四五线以及农村的孩子呢？他们用百度可搜不到 VPN

**Comment by fusonglin** [comment]
哈哈哈哈，大学生，男，坐标西部五线城市。莫名躺枪觉得很无辜😅😅😅

不过三四五线及农村的孩子，还是好好学习为好。。。

**Comment by aminic** [comment]
三四五线以及农村的孩子选择还是很多的呀，不用百度，可以用搜狗呀，可以用360呀，可以用qq呀，总有一款适合你。

**Comment by kilobtye** [comment]
你好 谢谢关注 与这个repo无关的issue我就关闭了哈~
