### ISSUE TITLE
Git＋theGreatfirewall＝comfort！

### ISSUE THREAD

**Issue by fusonglin** [sikaozhe1997/Xin-Yue#472]
如果你想问：Git墙了，那以后怎么浏览这些优质内容?

借之前issue一句话送给你 ：我们不解决问题，我们只解决提出问题的人。

**Comment by Chris-WuYiming** [comment]
别带节奏了 唯恐天下不乱 墙了就高兴了

**Comment by fusonglin** [comment]
我给你分析分析为什么不会被墙。
假如被墙，全体程序员是不是要问为什么？
不要低估了程序员的信息检索能力
一番检索，发现原来是因为这个问题？然后很多人会去了解这是什么事情，然后变成了更多的人来声援。 
                               By FangWuTuoBang

**Comment by aminic** [comment]
墙国软件业两大支柱，gayhub&so，屏蔽了就是自动断腿，发展的更慢。
