### ISSUE TITLE
删掉吧，git不是给你传这些东西的。

### ISSUE THREAD

**Issue by liangchenhe55** [sikaozhe1997/Xin-Yue#473]
github（感谢提醒 已纠正）是全球著名的开源网站，曾经也因为有人在上边传一些东西被墙。后来又开了，希望各位可以自律珍惜。自觉维护git纯净，抵制非技术性东西。尤其是既非技术性又是敏感的东西。

我只是说别发在github，并不是本身不关注这件事或者说不支持这位同学。也许有其他平台可以发声呢。强行猜测引申我的意思的不回了。

**接受不同观点，不再一一回复。但是骂人的是不是应该注意下。**

**Comment by dontpanic92** [comment]
老铁请先分清git和github

**Comment by MagnusBai** [comment]
git的作者Linus Torvalds肯定是支持这个姑娘的。反正他也耍github，有人英语好可以问问他 。

**Comment by firogh** [comment]
官方都没说什么，你到积极自我阉割。

**Comment by liangchenhe55** [comment]
抱歉，一激动就没打全(๑•́ ₃ •̀๑)

**Comment by liyufan** [comment]
晨鹤

**Comment by TommyJerryMairo** [comment]
即没有违反ToS，又没有违反EULA。
剩下的是用户自由

**Comment by fornotec** [comment]
有什么敏感，阉党做惯了，不习惯了吗

**Comment by CeresCheng** [comment]
滚你大爷的，人家政府还放公文呢

**Comment by liangchenhe55** [comment]
@CeresCheng 可以接受不同观点，但不接受爆粗。

**Comment by wujians** [comment]
总有些太监一天就劝别人自我阉割，还自称纯净，我只想叫你自己滚犊子。

**Comment by liangchenhe55** [comment]
@wujians 同上。

**Comment by abowloflrf** [comment]
其实我真的不知道这个事情无关政治无关黄暴恐毒的，到底敏感在哪里

**Comment by StrongManCoder** [comment]
看到你被喷我就放心了

**Comment by Chandelier309** [comment]
敏感在，有人想歌颂以外的搞事情，赵政委觉得不妥

**Comment by fmj95817** [comment]
连git和github都分不清，一看就是刚注册的水军或者机器人

**Comment by liangchenhe55** [comment]
@abowloflrf 体现在各种删帖。比如这个链接在腾讯系也挂掉了。

**Comment by liangchenhe55** [comment]
@fmj95817 关于写成git上面已经解释了。至于水军机器人以及刚注册？emmm 你点进去看看就知道了嘛

**Comment by aminic** [comment]
五毛维稳大队早就登陆gayhub了，要一起gay么？先退党再加入彩虹党再说。

**Comment by liangsongyou** [comment]
这些东西是指你在轻描淡写的描述一个人被欺压，恐吓，威胁？
如果这个人是你，别人都轻描淡写的说“这些东西”呢？

**Comment by governormars** [comment]
以为自己很理智的样子，真的好可笑呢。

**Comment by Shiratsuyu** [comment]
徐州怎么出了你这么个东西

**Comment by beyondxuxingwang** [comment]
可笑

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
