### ISSUE TITLE
不喷不骂，不就是想了解事态发展么？我给个传送门大家都散了吧。

### ISSUE THREAD

**Issue by lesliehan9210** [sikaozhe1997/Xin-Yue#477]
这玩意贴出来开骂的比想了解事态发展的多。我个人不愿意看到github上有这些东西，不是人人都有VPN。

**传送门戳** ——————————[时代先锋](https://sdxf29.gq)

**Comment by lesliehan9210** [comment]
①按照域名的规律访问，比如sdxf29.gq被封锁之后就更换成sdxf30.gq

②前往导航网站查看，比如362导航网（www.362dh.top）

③下载时代先锋网app：点击此处下载或者长按图片扫码下载

**Comment by liangsongyou** [comment]
开骂的越多，想了解事态发展的就越多。你第一句话就是错的

**Comment by yijinbandouya** [comment]
我反应比较慢，想知道共同提交申请的另外9名同学怎么样了？好像没这个报道。

**Comment by lesliehan9210** [comment]
@SakuraLove 没错，真正关心事态发展的人就应该想办法去了解，然后寻找正确的渠道发声，以这样引起骚乱的张嘴就骂不可取。我个人不建议在github发也是不愿意看到这里乌烟瘴气的。

**Comment by ARGGRON** [comment]
门呢？
