### ISSUE TITLE
github 自己也曾以横幅的形式请求援助，对抗美国政府的信息审查

### ISSUE THREAD

**Issue by wmzy** [sikaozhe1997/Xin-Yue#478]
大概是去年的事，具体记不清了。

正义都不敢声张了，要这技术有何用。

而且github被封了，也不会影响诸位码农挣钱。
因为我们又不和国外码农争饭碗。
大家水平都低，还是公平竞争。

话说做技术就要讨论，讨论就不会只讨论技术，所以防民之口，就要落后。

**Comment by liangsongyou** [comment]
支持黑暗的技术不打击就会暗中增长

**Comment by GabrielKidd** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。

”
— 馬丁·尼莫拉

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by wmzy** [comment]
@GabrielKidd 拿着不负责任的小号，顶着黄不拉叽的头像，转发着不合逻辑的言论，不相信你是什么善类。
