### ISSUE TITLE
那些担心github被墙的，请转用国内的产品，像gitee, coding等。

### ISSUE THREAD

**Issue by holymonk** [sikaozhe1997/Xin-Yue#480]
自己选择做哑巴还不让别人说话，还表现得好像是为大家着想。如果真想为大家好就把gfw推倒去。

**Comment by nbwuzhe** [comment]
你不怕项目被盗被腌并不代表所有人都这样认为。

**Comment by nbwuzhe** [comment]
你是想让zf封起github时候就更没有后顾之忧吧？

**Comment by ayaservice** [comment]
https://youtu.be/0k_2TXfqqRs

**Comment by quietTrojan** [comment]
我日你妈呀，我喜欢的项目在github上，你让我去其他地方。

**Comment by Geniune** [comment]
请你自己用国内平台发声，不要在好好的一锅粥里做老鼠屎

**Comment by nbwuzhe** [comment]
@quietTrojan 虽然我也很鄙视这个repo的作者，但是我们说话还是要文明、知性一点嘛。

**Comment by nbwuzhe** [comment]
@holymonk 你倒是可以试试把这个repo的内容放到你所说的国内同类产品上试试，看看警察过多久来敲你家门。

**Comment by quietTrojan** [comment]
@nbwuzhe 老子天天在twitter骂政府，但是不会在github上骂。

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~

**Comment by wangzaiNZ** [comment]
@quietTrojan 你不怕被抓吗
