### ISSUE TITLE
[Discussion]说GitHub不适合放这类内容的，你们算什么，能代表GitHub官方？看看GitHub官方发的文章。

### ISSUE THREAD

**Issue by CeresCheng** [sikaozhe1997/Xin-Yue#481]
[Government opens up: 10k active government users on GitHub](https://blog.github.com/2014-08-14-government-opens-up-10k-active-government-users-on-github/)

如果阅读能力不行，看不懂英文我也没办法了

**Comment by GabrielKidd** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。



”
— 馬丁·尼莫拉

**Comment by quietTrojan** [comment]
我是你爹呀，不会写代码来github干嘛。

**Comment by CeresCheng** [comment]
@quietTrojan 啧，五毛也就这鸟样了，还写代码，也不嫌丢人

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Galaxy S7 发送_

**Comment by CeresCheng** [comment]
@quietTrojan 哟，HTML程序员

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Galaxy S7 发送_

**Comment by wmxl** [comment]
有些人真是自私

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
