### ISSUE TITLE
在这里抱怨说不应该发到GitHub的人，你们最需要抱怨的不应该是为什么中国会有网络审查吗？

### ISSUE THREAD

**Issue by crescendo007** [sikaozhe1997/Xin-Yue#482]
以前我也是一个不关心政治的青年，可是自从2017年到2018年初，出现了那么多事情：北京驱赶低端人口，北京整治天际线，北京红黄蓝，2018年的修改宪法，武汉理工大学陶崇园坠楼事件，陕西张扣扣杀人事件，以及北大这件事。我彻彻底底不再是以前的一个小粉红。

我以前想着毕业之后要回国，现在照这样发展下去，还有谁敢回去？说不定哪一天上面说到的那些人就是你自己。尤其是修宪这件事，我去修车，修车师傅都知道这件事，都觉得这件事不好。目前问我中国修改宪法这件事的外国人，超过6个，我也是醉了。

说多了，不过希望那个小姐姐能够最后平平安安毕业，找到工作了。

------------------------------------------------------------------------------------------------------------------
那些说和自己不想关，只想闷声发大财的人，他们的昨天就是你们的明天。

奉上一首诗：

起初他们迫害共产党人，我没有说话，因为我不是共产党人；
后来他们迫害犹太人，我没有说话，因为我不是犹太人；
再后来他们迫害天主教徒，我没有说话，因为我不是天主教徒；
最后他们迫害到我头上，我环顾四周，却再也没有人能为我说话。

**Comment by gaoxiaosong** [comment]
小号来带节奏，鉴定完毕。

**Comment by zhangn1985** [comment]
@crescendo007 不欢迎你回来。

**Comment by CeresCheng** [comment]
@gaoxiaosong 看不懂人话就回墙内

**Comment by zhangn1985** [comment]
@CeresCheng 好好待在外国。

**Comment by zhenweigc** [comment]
我也对TG迷茫了，别玩脱啊，玩脱了还不是我们P民药丸？

**Comment by quietTrojan** [comment]
你给我滚，我日你妈的，你有意见跑到github上说个屁呀，这是程序员的论坛，草泥马的，你在这里找不到知音，懂吗？这里都是写代码的本分程序员。

**Comment by rmctJ** [comment]
看全球的共产党，凡是一党专制的，没几个不玩脱的。
为了长期一党专制，对于反对的声音容忍度很低，因为担心被推翻。
反对声音小，很容易形成 ”楚王好细腰，宫中多饿死“ 的正回馈。
这种机制下，领导的一句话会被行政机构一级一级加码放大到令人震惊的地步传递到基层被执行。就是这么玩脱的。
实际上中共不知道玩脱过几次，中共自己的”七不讲“里就有一条”中国共产党的历史错误不要讲“，可见一斑。
因此这样的国家政策风险是非常巨大的，整个国家很容易掀起一波接一波的政治运动，哪怕基层知道这些政治运动，不论是过去还是现在，在将来的历史书上都会是笑料，都无法阻止这种荒唐的行动一而再再而三地重演。

**Comment by aminic** [comment]
@crescendo007 ，2017年少说了一件事，今年也还在持续发酵中，就是郭文贵爆料事件。
远离故国，不要回来。

**Comment by GabrielKidd** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。

”
— 馬丁·尼莫拉

**Comment by FanWuTuoBang** [comment]
@crescendo007  愿安好，出去了就别再回来了。
但是还是要保护好个人信息，不要让家人受迫害

**Comment by zhangn1985** [comment]
@FanWuTuoBang 不要说的那么吓人，就算暴露了也没有什么，做中国共产党的敌人，人身安全还是可以保证的。你看达赖不是活的好好的。当年解放军已经跑到他们前面了，真的要动手一个都别想跑，最后请示了毛主席，才放他们走的。

**Comment by zhangn1985** [comment]
做美国人的敌人就没好下场了，萨达姆，卡扎菲。。。洗衣粉大规模杀伤武器。

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
