### ISSUE TITLE
五毛死全家，白干五出门被狗咬死

### ISSUE THREAD

**Issue by zuoge85** [sikaozhe1997/Xin-Yue#483]
没被结扎就别当白干五和五毛！

**Comment by zhangn1985** [comment]
气急败坏了吧。
多读书有好处。
自少修身养性。

**Comment by liangsongyou** [comment]
不要侮辱狗，现在狗都被培养的吃狗粮不吃屎了

**Comment by zuoge85** [comment]
@zhangn1985 对付五毛，只能用砖头，捅菊花，讲道理浪费时间

**Comment by zhangn1985** [comment]
@sikaozhe1997 感谢，我估计你也不愿和这种人打交道。以人身攻击为乐，那就怪不得别人从肉体上消灭他们了。

不过我估计他们不在国内，没有享受到国家稳定发展带来的红利，气急败坏，但人身攻击真是白在国外待了那么久了。

**Comment by zuoge85** [comment]
@zhangn1985 是别人不想理你这种狗东西
