### ISSUE TITLE
大清都亡了，怎么还有人跪着？

### ISSUE THREAD

**Issue by jamesmarva** [sikaozhe1997/Xin-Yue#486]
## 别人砍了你，不让你说，你忍无可忍，大喊了出来，**跪着的人说：别喊了，嗓门不是你这么用的，万一强盗以后让大家都不会说话了咋办？**
人家github都没说啥，皇上不急，太监急？
不会用梯子，自己能力问题，怪谁？

> 皇上都没了，没人值得你们跪——让子弹飞

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**
