### ISSUE TITLE
[Discussion]有些人怕封是怕丢工作吧，没得代码抄了，自己又写不出了.......

### ISSUE THREAD

**Issue by UpJunior** [sikaozhe1997/Xin-Yue#487]
有些人怕封是怕丢工作吧，没得代码抄了，自己又写不出了。。。。。
大家不要生气，我不是针对谁，我是说和我一样抄代码的都是垃圾。

**Comment by GabrielKidd** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。

”
— 馬丁·尼莫拉

**Comment by aminic** [comment]
天下文章一大抄，代码也一样。墙了gayhub & so 天朝软件业也许要完蛋，也许自力更生更美好，大清国自有国情，挺好。

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by 6ziv** [comment]
刚才看到有人说还靠着github养家糊口呢…
我也是懵逼的………
自己写代码不能养活自己？非得“靠github”？
github是个分享想法，一起工作的地方，其次才是顺手抄代码的地方。
当你把抄代码当做github的主要功能时…………
大学教材买吗？还是复读吧。
