### ISSUE TITLE
牛逼。

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#488]
为我们的高材生们点赞。

他们虽然说不过，但是他们可以闹啊。

虽然他们闹也被人嫌弃，但是他们可以骂人啊。

虽然他们骂人也没有营养，但是他们可以诅咒威胁啊。

诅咒威胁不管用，大不了集体跳楼嘛对不对。

就是要让程序员知道。小爷们贼心酸。

行了行了，这些我们都知道了，政府打开对话窗口和你们约谈呢，你们去正式场合谈吧。

小爷们:我们不要，这是他们的陷阱，去了我们可能就回不来了。我们要在这里等政府跪着投降，满足我们要求

**Comment by aminic** [comment]
这样就对了。党国怕的就是这一招。

**Comment by nbwuzhe** [comment]
哈哈哈一针见血。还有人说可以不用GitHub，用国内的托管去。你们有种倒是把这个repo复制到国内的托管去给更多人见识见识啊，我倒是想看看查水表/送快递/抄煤气表会不会当天就来找你。

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**
