### ISSUE TITLE
GitHub墙不墙又怎样？有能耐把劳资梯子拆了

### ISSUE THREAD

**Issue by iostyle** [sikaozhe1997/Xin-Yue#489]

**Comment by dp199313** [comment]
有梯子为何不出门左转推特。那里可以治国，特朗普都能听到你的声音

**Comment by thc51240** [comment]
@dp199313 像你这种人，真的是只配活在恐惧之中。你应该入党。

**Comment by iostyle** [comment]
@dp199313 又不是我发的，搞笑

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
