### ISSUE TITLE
有关READEME的一点小建议

### ISSUE THREAD

**Issue by RicardoWang99** [sikaozhe1997/Xin-Yue#49]
建议在readme中不要放正文而是放仓库中所有相关文章的索引(markdown超链接了解一下~)

如果有需要的话可以贴一个timeline上去

给sikaozhe哥哥点一个大大的赞!

**Comment by gaocegege** [comment]
我觉得在当下没有那么多文章的情况下，可以把所有内容都放在 README 里，WDYT？

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
