### ISSUE TITLE
[Discussion]此时此刻，岳昕本人的状况如何？她未来的前途如何？

### ISSUE THREAD

**Issue by wearchive** [sikaozhe1997/Xin-Yue#491]
自从前天早晨的公开信和前天下午的学校声明以后，再也没有任何关于岳昕本人的消息传出。

我非常敬佩岳昕同学。感谢她选择站了出来，让这么多沉默的键盘侠不再保持沉默，当然也包括我。

然而，成为舆论风暴最中心是很难从中脱身的。目前同学的人身自由是否得到保障？即使她能重获人身自由，她又能否在这片土地上自由不受打扰的生活下去？她不仅会成为校园的热点人物，更会成为某些其他势力探求的目标。以目前删帖的情况来看，我真的很难对她的未来有乐观的估计。

此时此刻我真的很担心她，但我却不知道我能做什么。是的，我连自己github的大号都不敢用。希望有认识的人能报个平安吧！

**Comment by SakuraLove** [comment]
祝好！

**Comment by aminic** [comment]
祝好～！

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by Veronicaaaaaa** [comment]
一位创业公司的老师是北大毕业生，他承诺可为岳昕同学提供就业岗位，若想出国也有哈佛耶鲁等众多名校毕业生及讲师为其提供推荐信
