### ISSUE TITLE
把项目地址转换成短链在转发出去如何？ 

### ISSUE THREAD

**Issue by lilewis** [sikaozhe1997/Xin-Yue#492]
转换地址： [http://dwz.wailian.work/](http://dwz.wailian.work/)

转换后：[http://t.cn/RuUTAm0](http://t.cn/RuUTAm0)

**Comment by 15921483570** [comment]
估计跳转服务器都会被墙吧。。

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by laosb** [comment]
直达 raw 版公开信： git.io/xinyue
