### ISSUE TITLE
思想自由、兼容并包

### ISSUE THREAD

**Issue by sunqimin09** [sikaozhe1997/Xin-Yue#493]

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by dp199313** [comment]
兼并别人去，闲散p民求放过。

**Comment by aminic** [comment]
闲散p民还是去吃赵家狗拉的屎好了
