### ISSUE TITLE
。

### ISSUE THREAD

**Issue by grasscase** [sikaozhe1997/Xin-Yue#494]

**Comment by dp199313** [comment]
我们在这哭，不代表我们是懦夫呀，我们这叫明哲保身。我们还开了小号。发泄起来就更爽了。无所顾忌。

**Comment by grasscase** [comment]
没有说你们，主要说某些人。

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by thc51240** [comment]
@dp199313 您误会了， 楼主说的是那些五毛。哈哈哈～

**Comment by aminic** [comment]
怎么叫发泄呢？保持热度，让事态进一步发酵，借此能推动民主民治进步，那怕只是表面上的，也值得。
