### ISSUE TITLE
20年前的旧案翻出来干什么？得不到结果，只会伤害更多人。不要在github搅混水。

### ISSUE THREAD

**Issue by SeAL80s** [sikaozhe1997/Xin-Yue#496]
你就是钻了法律的空子，等有一天gfw把github封了，你会害了很多人。你是亲历了事情真相吗？

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by thc51240** [comment]
@SeAL80s 你这个五毛，对得起你爸妈吗？

**Comment by ayaservice** [comment]
封了最好奥，免得你们这些傻逼码农来这里抄代码吗？

**Comment by ayaservice** [comment]
@SeAL80s 赶紧回百度自己玩去吧

**Comment by grasscase** [comment]
这不是讨论技术吗？ 把那段放到区块链，没有错误啊

**Comment by zhangsen1992** [comment]
斯德哥尔摩综合征

**Comment by Chandelier309** [comment]
很难想象这位朋友的repo里有 PAC, SSR, V2ray 和 GFWlist

**Comment by grasscase** [comment]
“	起初，他們追殺共產主義者，我保持沉默，因為我不是共產主義者；
當他們追殺猶太人，我保持沉默，因為我不是猶太人；

當他們追殺工會成員，我沒有說話，因為我不是工會成員；

當他們追殺天主教徒，我保持沉默，因為我是新教徒；

最後，當他們對付我的時候，再也沒有人站出來為我說話了。

”
— 馬丁·尼莫拉

**Comment by SeAL80s** [comment]
@ayaservice 百度是啥？不是卖假药的吗？
@Chandelier309 像你这种轻易被洗脑的，真没智商来想象。PAC, SSR, V2ray 和 GFWlist我都有
@ayaservice 一看你就是五毛，被人拿来当枪使的。

**Comment by aminic** [comment]
还有墙国实力碾压不了的么？gayhub?so?不存的，党国体制碾压一切的，川普也不在话下。

**Comment by FanWuTuoBang** [comment]
说这句话，不是法律意识淡薄到无知可怕的问题了

而是骨子里的奴性与跪都不愿意跪了，直接五体投地

**Comment by firogh** [comment]
如果二十年前， 被性侵的是你妈，含冤自己，你还能说出这样的话？

**Comment by Hardrain980** [comment]
墙了最好
让你们这群颠倒黑白
还助纣为虐的傻逼
永远被关在猪圈里

这是坠吼的

**Comment by laserroger** [comment]
@Chandelier309 
全是fork的

**Comment by keepongjl** [comment]
这是傻逼吧

**Comment by 6ziv** [comment]
所以，有人死去，有人受尽迫害，我们也必须不管不问吗？只是因为事不关己？不是家属就不能过问？
啊，对不起，我暂时自认为不是个程序员，只是个偶尔上以及为了大作业上github的学生…所以贵站被墙也与我无关哦……
顺便…我们拒绝参加政治讨论…嗯，等你们被墙的时候，还请所有自认为不抄github也能写出来代码的人不要声援…谢谢。

**Comment by SeAL80s** [comment]
法定最高刑为不满5年有期徒刑的，追诉时效的期限为5年；法定最高刑为5年以上不满10年有期徒刑的，追诉时效的期限为10年；法定最高刑为10年以上有期徒刑的，追诉时效的期限为15年；法定最高刑为无期徒刑、死刑的，追诉时效的期限为20年。如果20年后认为必须追诉的，须报请最高人民检察院核准后，仍然可以追诉。
@firogh 像你这样，动不动拿家人说事的，是最无耻的。
沈阳是无耻的，你也好不到哪里。任何社会都没有完美的，都有不平等，就像你侮辱我妈，我不能过去把你卸了一样。但是现在中国需要的是稳定，那些觉得中国腐败、压制言论的，要不你跟官方去申诉，改变。要不你可以自由的离开。那些开口称"中共"的，中共(大陆)再怎么不好，也比台湾好吧(蔡大妈竟然在军演的时候跑了，还口口生生说跟台湾人民在一起。)。沈阳事件已经过了追溯实效，高岩的事件是个悲剧，沈阳确实禽兽。但是20年后还要来公开，没觉得有什么特别理由。就你们五毛这种非把水搅混的态度，也间接证明了互联网监管的必要性。这个是国际共识，不是中国一家在做。
作为一个大陆人，虽然社会会有不公，但我知足。不用担心有战争，不用担心走在街道上被枪击，不用像台湾某些人一样，明明被甩了几条街，还自以为很先进。随你们五毛怎么喷(我不拿钱，确实喷不过你们)，那些张口骂人的，用不着我回应。

**Comment by peter12138X** [comment]
简直跟猪圈里吃食的猪没两样

**Comment by leciel-guo** [comment]
就是想让github被墙，没本事翻墙的就下岗吧，还少些人竞争，不爽？咬我啊

**Comment by haocs** [comment]
很多issue都是站在自己的角度讨论顶多说自私。这是唯一一个让人觉得“坏”的！！！！！

**Comment by jhdxr** [comment]
@SeAL80s 你口中的稳定，只有对当权者才有利，而对一般民众毫无意义。人民争取的这些所谓的不稳定，只是怕某一天是自己遇到类似的事情，能够有更公正的待遇。你后面的那些比较，无非是五十步笑百步，比谁更烂有意义吗？

另外说一句，这么一件事情，你们都能认为是政治敏感，自我阉割的程度也太过了吧？

**Comment by flufy3d** [comment]
哎 可怜啊 
看来很多楼主这样的认 中国的路还很远

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
