### ISSUE TITLE
部分没良心的程序员喊滚出GitHub？？？

### ISSUE THREAD

**Issue by zzjas** [sikaozhe1997/Xin-Yue#497]
看到好多程序员批评这样使用GitHub，先假设这些人不是五毛。你们根本没一点点资格能代表中国程序员！！！现在这个时代靠网络封锁压制言论，不还是得程序员来打破这封锁？你让鲁迅活过来他写破头发不出去也救不了中国人啊！这些程序员不但自己没有一点责任感，还来这里秀优越感？？？还GitHub是程序员交流的圣地，你有本事去把墙推了啊没了墙谁还在这里发。跪着久了就以为跪在特殊一点的地方很厉害？？不喜欢请闭嘴好好工作挣钱跑路不要一副GitHub老大似的来喷想站起来的人。说的有些急躁，实在是看了气得很，希望岳昕同学和其他相关的同学平安无事。

**Comment by grasscase** [comment]
这么多高级程序员都搞不定gfw吗

**Comment by thc51240** [comment]
**YouTube上最大的华语政治评论Up主，开始关注这个事件了： 
https://www.youtube.com/playlist?list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by haohaohihi** [comment]
有些人跪久了，习惯了

**Comment by boogoobird** [comment]
这事是我起的头，我没有秀优越感，打破长城是黑客干的事，我没那个能力，如果各位可以翻墙外语好的话，可以上facebook，YouTube，你自由发表你们的言论，我不想因为你们的冒失，失去一片净土

**Comment by boogoobird** [comment]
GitHub是自由开放的，这也是开源精神所在，开源最初的目的是打破技术封锁，让世界各地的人共享创意.

**Comment by aminic** [comment]
breakwall是每一个人都可以去做的事，点滴之水，聚沙成塔。放弃一个好好使用的区域，只能让弱势群体在博弈中处于更加弱势的地位，然后就可以被赵家狗随意撕杀了。

**Comment by zzjas** [comment]
我理解有些人担心GitHub被封，这是正常的担心我们可以互相表达自己的看法，我相信其他人和我一样也很尊重你们的想法。我写这些针对的的是那些上来就说脏话，说类似“GitHub是程序员交流的地方，你们不是写码的不要来乱搞”的话的人。这样的人实在是没有被我尊重的资格。如果有些人只是正常担忧却被我写的东西侵犯到了我在这里说一句对不起！

**Comment by SeAL80s** [comment]
@zzjas 墙的存在是有理由的，虽然会对很多人造成不便。但是，预防的就是像你一样被洗脑，最终破坏社会稳定的一类。信息封锁与言论自由是两个概念，你知道信息战的危害有多大吗？就算在彪炳自由的美国，言论也不是一点没有限制的，也是以不分裂国家、不危害社会为前提的。你骂总统可以，你持枪可以，但是你不能危害国家安全，不能分裂国家统一。

**Comment by RockyQu** [comment]
请把标题前面加上“部分”

**Comment by UpJunior** [comment]
@genuinegift 据说加班的大部分都是写代码不行的，脑子不够时间来凑。就知道抄啊抄，改啊改，一旦没抄的东西的时候他们就慌了。

**Comment by lxy128** [comment]
@SeAL80s 在美国 言论还真的是没有限制的。。。。我看你才是被洗脑傻了吧。你现在是稳定了。小心哪天就变成了你渴求大众看到自己遭遇的不公正了。关太久了 m了吧哈哈

**Comment by boogoobird** [comment]
瞎说，加班是无良老板带的，没有成就感，没有加班补贴，鬼才乐意加班呢

**Comment by juliosueiras** [comment]
因为没有人喜欢政治，在Github发文件是为了共同开发，可是怎么共同开发政治？

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
