### ISSUE TITLE
GitHub不只是给我们copy代码的，它还有自由、开放、互助的精神

### ISSUE THREAD

**Issue by wql7013** [sikaozhe1997/Xin-Yue#498]
另外推荐大家看一下两小时前更新的文档[《那些珍贵的年轻人》](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E9%82%A3%E4%BA%9B%E7%8F%8D%E8%B4%B5%E7%9A%84%E5%B9%B4%E8%BD%BB%E4%BA%BA.md)

**Comment by aminic** [comment]
北大精神与gayhub社区规则是兼容的。
