### ISSUE TITLE
YouTube最受欢迎的政治评论Up主，也开始关注这个事件啦！（内附链接）

### ISSUE THREAD

**Issue by voy76348** [sikaozhe1997/Xin-Yue#499]
**YouTube上最大的华语政治评论Up主， 开始关注这个事件啦 ： 
https://www.youtube.com/watch?v=in26D2ZNQ6g&list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0
（欢迎大家转发分享）**

**Comment by dp199313** [comment]
请大家转移阵地

**Comment by keepongjl** [comment]
没VPN啊

**Comment by yyssjj33** [comment]
哈哈，文昭可以的
