### ISSUE TITLE
希望都来看看。

### ISSUE THREAD

**Issue by FanWuTuoBang** [sikaozhe1997/Xin-Yue#500]
以下内容由看视频，部分相关内容转录为文字。来自某华人自媒体的评论（非轮子），别扣什么境外势力的大帽子。
觉得有意义可以共勉，觉得无意义请退出。
    大约是在今年3月，原北京大学女生李悠悠实名举报原北大教授沈阳20年前性侵了她的闺蜜高岩，后面还说高岩有精神疾病，最终导致高岩于1998年自杀。今年这个舆论热起来的时候，沈阳已经不再北大中文系任职了，他2011年就调任南京大学，2017年还在上海师范大学任职，国内媒体也又说他仍在北京大学中文系和北大中国语言研究中心还有兼职，总之李悠悠的举报信公开了之后，沈阳北人是否认了指控，而他所在的南京大学任职的南京大学文学院以及上海师范大学都很快终止了他的教职，其实就是相当于确认了这个事实。就算这个事实在细节上还可以商榷，但大体上可以确认了。
    为什么有过这样前科丑闻的人为什么这么多年他的学术和讲坛生涯几乎没受影响呢？那个女生高岩自杀后，他继续在教授的位置上呆了十几年，还被评为长江学者。大约在今年的4月9日，多名北大的学生向北大提交了信息公开申请表。要求把当年讨论沈阳教授师德问题的会议记录，连同公安部门的调查结果和沈阳检讨书的内容一起公开。也就是说这些学生是怀疑校方在此问题上有袒护，导致沈阳没有收到应有的制裁，而高岩的父母20多年来承受着痛苦与屈辱，没有得到公道。在这个情愿活动中，这个叫Xin-Yue的女生，比较坚持，也比较活跃，于是她被校方凌晨约谈，要求她放弃诉求，并且联系家庭父母，通过父母来向她试压。还以能否顺利毕业来警告，而Xin-Yue这个女孩比较坚韧，倔强。她将这个公开信披露，然后舆论大哗。
    事情的大概过程是这样。
    首先任何违背了当事人意愿，而带有性目的的接触，往轻了说是性骚扰，严重点说就是性侵犯，它发生在高校就属于公共安全事件，假如得不到足够的关注，得不到足够的处理，造成同类行为的蔓延，既败坏社会风气，也损害公众安全。只要你的姐妹，女儿，亲人要进入高校接受高等教育，这就是一个和你自身利害相关的事情。
   其次，北大属于公立大学，它的资金来自教育部，是公共机构而不是私人机构，作为纳税人，你是有权问责的，那用税金雇来这么一个教授，干着与公共福祉背道而驰的事情，可他的教职在几十年来却没有收到任何影响，那校方在这个事件中扮演者何种角色呢？它是否有掩盖渎职之嫌呢？提出这个问题就是有质量的。
   第三，教师性骚扰和性侵犯女学生这不仅仅是所谓的教师的“师德”问题，而是构成了公权力犯罪。假如真是两情相悦发生了师生间的不伦之恋，但这个老师有自己的家室，然后他和另一个女学生好上了，这个确实是道德问题。但假如不是这种情况，这个教师是用胁迫手段，以学生的毕业，论文答辩能否通过作为要挟，逼迫学生与其发生性关系，这就构成了权力犯罪，中国的高等教育学历学位是教育部认可才有效的，而公立大学是教育部下属的事业单位，那公立大学授予学位就有行使公权力的色彩了，那教师以学历、毕业为条件，逼奸、诱奸女学生就属于职务犯罪，兹事体大不是一句什么师德败坏，批评教育检讨就可以轻描淡写地掩盖过去的。
    所以Xin-Yue的请愿行动应不应该支持？当然是应该了。所谓民主就是要公众意见参与到公共事务的决策中去，基于上面的三点理由，沈阳性侵高岩事件他不是一个单纯的师德伦常事件，也不是一个学校关起门来它自己小圈子里面的事，而是公共生活领域的事件，公共意见当然是有必要参与。
   其实北大的这些掩盖，并不需要用校庆，对招生造成影响的理由来解释，就是在一个缺少透明度和公平基础的社会里面，任何在权力上有相对优势的组织和个人，他都会很自觉地利用这个优势防止不利于的消息扩散，大学也不例外，大学是小社会，是这个体制的缩小版，如果它干的这些维稳的举措，激起众怒闹大了，又会有中X部，教X部这样的大体制为他兜底消毒，原因也很简单，任何追求真相的行为，只要你进入公共领域，成为一起公共事件，它就会变成对体制的威胁，你所追求的真相是什么一点也不重要，关键是你这个行为，只要你追求真相，你就是不稳定因素。
   马丁路德金有句名言，“Injustice Anywhere is a Threat to Justice Everywhere”，意思是“任何地方的不公平都威胁着全天下的公平”，这句话反过来也成立，当这个社会被谎言所支配以后，任何一个地方追求真相的行为都是对所有地方谎言的威胁挑战，都会被后者所仇视。
    其实民主也好，君主也罢，他是个谁做主的问题，前提都得是有真相，不管谁做主，只要是谎言还是这个社会流行的通货，并且这个通货还在不断膨胀，这个世界都不会变的更好。

**Comment by voy76348** [comment]
**这个文章，是一个视频的文字版本，作者是YouTube上面最大的华语政治评论Up主，原视频在这里：
https://www.youtube.com/watch?v=in26D2ZNQ6g&t=0s&index=1&list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by FanWuTuoBang** [comment]
@voy76348  我自己码下来的字，就是怕有些人说境外势力啥啥啥的扣帽子

**Comment by aminic** [comment]
@FanWuTuoBang 境内生存的境外势力么？

**Comment by dp199313** [comment]
嗯，我们看了，很惨。yutube。推特，脸书，有我们在国外支持我们的华人团体。我们去那里比在这和这些死脑筋的程序员bb管用

**Comment by Tao-Quixote** [comment]
作为一个公民和纳税人，我没有偷税漏税，缴纳了税，履行了自己的义务；但是到行使自己权利到时候，却要被和谐？要被墙？要被删除？这个国家是人民到国家还是官宦到国家？

**Comment by MobileStarChart** [comment]
哈哈，看好github被封！！

**Comment by SeAL80s** [comment]
以现在的观点和法律来看20年前的事件对吗？为什么又平白无故的把20年前的事情翻出来？确定还在法律实效追溯期？沈阳的行为可耻！于道德所不容，这是确定了的。高岩没有控告沈阳，高岩不是沈阳亲手所杀。死者已以，希望死者家属也能安息。但是20年后再提起来，除了给受害人家属带来再次伤害，有什么意义？口口声声说为受害人打抱不平，你想过高岩家人的感受吗？20年了，本来可能都平静了，过去了。这些起事，唯恐社会不乱的人，其目的太可恶了。尤其是打着所谓"正义"的旗号。

**Comment by FanWuTuoBang** [comment]
@SeAL80s 请看完这篇文章好么？如果性侵女生的事实属实，这是属于刑事犯罪！根本不是什么道德问题。
刑事犯罪最高的追诉期是20年。这是法律范畴。
而对于这个社会的危害是永远。

给你的回复了很多次，你就是不看，这次事件不是完全针对高岩，是这个时间经过了20年再次被报道，Xin-Yue要求校方信息公开，公开当年的会议讨论极其沈阳的检讨书，还历时一个真相，还被害人一个真相。而这种合理的诉求，竟然遭到了校方多次约谈，威胁。

你有什么资格站到高岩家属的角度上说逝者安息？
这种事情得不到公正的解决，逝者永远不会安息，逝者的家人也不会因为随着时间变化就觉得这事过去就过去了。而且未来还会发生，只要你的朋友，你的家人，你的子女在这个社会，就有可能同样的再次落在他们身上。
