### ISSUE TITLE
搬瓦工传家宝到货

### ISSUE THREAD

**Issue by nideerdaye** [sikaozhe1997/Xin-Yue#501]
戳http://t.cn/Rut8Ob4

**Comment by SakuraLove** [comment]
？？？？？？？？

**Comment by zjgbql** [comment]
哥，虽然这个可以搭梯，不过发这里显然不合适吧，有点讨骂啊，哈哈。

**Comment by GabrielKidd** [comment]
Unfortunately, it does not support direct connection with CN2 or Unicom.

**Comment by kilobtye** [comment]
你好 谢谢关注 与这个repo无关的issue我就关闭了哈~
