### ISSUE TITLE
有认识Xin-Yue的吗？我就问一下，20年前的旧案，你怎么知道的。你当时才5-6岁吧？谁跟你提起的，灌输的信息，让你想写公开信的？

### ISSUE THREAD

**Issue by SeAL80s** [sikaozhe1997/Xin-Yue#502]

**Comment by Tao-Quixote** [comment]
@SeAL80s S 你是怎么知道到？20 年前你多大？你是洗地专员？

**Comment by voy76348** [comment]
**给大家分享一个比较客观的视频评论，作者是YouTube上最大的华语政治评论Up主： 
https://www.youtube.com/watch?v=in26D2ZNQ6g&list=PL2DywIam67jsFoEhIvVhB0HukSP8IAIt0**

**Comment by aminic** [comment]
20年前的旧案为什么不能知道？论灌输信息，党国还是最牛的，充分体现了社会主义初级阶段一百年不动摇的优越性。

**Comment by 6ziv** [comment]
老哥您这是阴谋论了啊……
谁告诉她不重要吧…问题是她做的事没有任何问题……………
难不成您怀疑有“境外势力”？（艾特辅导员）
还是说您认为这段历史就应该被淹没无人记得？

**Comment by WAAutoMaton** [comment]
任何一个有正义感的人都有权这么做
否则哪天这种事就可能会落到你头上
>起初他们追杀共产主义者
>我不说话
>因为我不是共产主义者 
>接着他们追杀社会民主主义者
>我不说话
>因为我不是社会民主主义者
>
>后来他们追杀工会成员
>我不说话
>因为我不是工会成员
>
>之后他们追杀犹太人
>我还是不说话
>因为我不是犹太人
>
>最后他们要追杀我
>但再也没有人站起来为我说话了
>——马丁.尼莫拉

**Comment by Vargnatt** [comment]
就攻击个人的这么多方法里面，诉诸莫须有是成本最低而且最无赖的方法了。

**Comment by FanWuTuoBang** [comment]
首先请您了解一下事情经过再来。
是高岩的闺蜜李悠悠实名举报20年前沈阳性侵了她的闺蜜高岩，导致了高岩的自杀。
Xin-Yue不是翻案着，她是要求北京大学公开当初针对这一事件所开会的相关讨论文件以及沈阳的检讨书。

知道事情经过了么？Xin-Yue不是去翻案，而是要求当初的信息公开！

**Comment by grasscase** [comment]
自己不知道，还不知道从别人那里知道吗？

公开就公开，甚至不怕影子斜，为什么不公开，有大鬼？ 怕什么？

**Comment by Uyouii** [comment]
楼主不要在这里秀智商了，麻烦关注一下前因后果再来这里带节奏好吧

**Comment by genuinegift** [comment]
现在的码农智商都感，怪不得天天加班都不敢反抗，一个月万把块钱沾沾自喜。到他们社区发表言论都不让，你不喜欢别看啊。
呵呵

**Comment by firogh** [comment]
国内为什么全面封禁, 删帖!? 分明此地无垠三百两. 理不便不明, 国内删帖, 就是做贼心虚.

**Comment by zhdlispd** [comment]
89 年的6/4 到明年就是30年了。中国人，你们会忘记吗？你们又忘记了吗？

**Comment by SeaHOH** [comment]
其实吧，如果再过 20 年提这个事是没问题的。

为什么呢？因为当时的既得利益者和现在的已经不是同一批人了。

他们可以任人批判过去，关乎现在就不行，放眼人类社会莫不如是。

**Comment by wmxl** [comment]
你这坏东西，难道又想扯境外反华实力？
