### ISSUE TITLE
360浏览器也屏蔽了链接

### ISSUE THREAD

**Issue by Neilai** [sikaozhe1997/Xin-Yue#504]

**Comment by 6ziv** [comment]
enmmmm...360 also blocked my Homework

**Comment by wearchive** [comment]
@neilai 
Re：建议reopen this issue
从浏览器层面进行访问限制可能是有关部门的新手段，建议保持关注

**Comment by Hardrain980** [comment]
@wearchive 这套早有了，几乎所有国产浏览器都受影响
CAC(Google下就知道是什么)有个blacklist
之前还被从miui的浏览器里提取出来过https://gist.github.com/uulmkiller/cc5de8ad3f9ffdb6ae62b6ade5762191

**Comment by kilobtye** [comment]
参见 #285
