### ISSUE TITLE
转战推特，脸书，yutube吧，同志们

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#505]
那里有我们的国外华人团体和我们同仇敌忾。
不要再和这里的程序员们说了。

他们有稳定的工作有家庭，是既得利益集团，和我们不是同志。

**Comment by aminic** [comment]
程序员更是同志了，墙国直接让他们感受到信息交换的不便 。

**Comment by firogh** [comment]
我昨天怼过lz, 有点凶, 见谅. 有不同声音是好事, 应理性看待.

**Comment by dp199313** [comment]
@firogh 我从不会反感怼我的人,我只是反感无脑从众无脑喷.
就算这件事板上钉钉的,北大做的不对,其他人惹着学生了吗?

为了这件事,就要推翻其他人多年努力的成果,这是很自私的行为.

github是千千万万程序员贡献智慧的社区,他们在这里辛勤耕耘.
尽管有人也用作私有用途,但是私用的他们会付费买vip

尽管有人游走在规则边缘没有破坏规则.但对社区氛围的破坏有目共睹.

学生们对抗政府没人反对.对抗我们又是何苦?

**Comment by MobileStarChart** [comment]
老子要赚工资交房贷，你们这群傻屌这是砸我饭碗！！

**Comment by zhangn1985** [comment]
@dp199313 你说我们国内的是既得利益集团，这个帽子有点高，戴不住，但是我们的确享受到了中国共产党领导下的社会稳定，发展带来的红利，看到了共产党是代表着我们全民族的利益，我们捍卫我们的红利，同时捍卫我们的党。

不允许任何势力破坏这来之不易的稳定和发展！！！

**Comment by GameBunring** [comment]
@MobileStarChart 
1. Github哪有你想的这么脆弱：https://github.com/programthink/zhao/ 
2. 你repo都没有，不知道哪里惹到你了

**Comment by firogh** [comment]
@zhangn1985 来了个有奶就是娘的主儿. 你这表述, 帽子就是你的, 而且分明是自己戴上的.  为人要做到有话时才说, 要说也要言之有物, 说出来才不会前后矛盾, 牛头不对马嘴.

**Comment by goldimax** [comment]
@zhangn1985 最基本的生活要求是保证了 但最基本的精神要求没了

**Comment by zhangn1985** [comment]
@goldimax 这个事情我想起了“古田会议决议”批判的“单纯军事观点”，现在有点“单纯经济观点”，以为经济搞好了，社会矛盾就能自然而然的解决。其实不是这样。还是要加强教育，宣传。把党的方针政策成绩，宣传到每个人心里。

**Comment by Vargnatt** [comment]
@zhangn1985 那你这不是“单纯的宣传观点”吗？社会的每一个阶段都有其无法解决的问题，你不能把原因归咎在propoganda上面。况且，你的这个思路恰恰是经济无法搞好情况下的应对。

如果你是个马克思主义者，你就应该承认社会发展的规律；如果你是个保守主义者，你就应该相信动态的帕累托均衡；如果你是自由主义者，你就应该相信我们社群的力量。但是现在看，你难道不是个修正主义者？

**Comment by GabrielKidd** [comment]
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。

**Comment by zhangn1985** [comment]
@Vargnatt 不不，我说了“还要”，并不单单只要宣传。你说我是那派，我不是自由主义者，这个肯定。
我不信帕累托均衡，肯定不是保守主义。马克思主义，也许是，具体点是中国化的马克思主义，马克思的原教旨已经不适用了。修正主义，是啥？

**Comment by Vargnatt** [comment]
@zhangn1985 
阶段性社会问题的发生是必然的，那么解决问题是一个方面，但宣传阵线肯定不是另一个方面。现在不是用50年代的思想指导的时代了，不应该把一切问题都算在凝聚一个民族国家的成本里面去。维持一个马尔萨斯极限和寻求经济发展的社会变革出路是矛盾的，同样地，后者与维持精神上的贫瘠状态也不可调和。这才是问题的根本。
