### ISSUE TITLE
我想知道你们在学校都学了些什么?说话都不动脑子吗?

### ISSUE THREAD

**Issue by boogoobird** [sikaozhe1997/Xin-Yue#506]
我们同情不幸者的遭遇,也乐于帮助不幸者走出困境,同样也希望罪恶者受到应有的惩罚,如果各位证据充足的话,可以诉诸法律,一味的争吵是解决不了问题的,你们总是在抱怨社会,却不愿意为社会贡献自己的力量.能力有限还妄图成为世界救星.我一直有一个想法,我想改变教育体制,十年前我甚至想到北京去陈述我的想法,但我的想法是不能被认可的,后来我一直在学习如何与人交流相处,如何和政府打交道,包括我现在从事开发也是在向这方面努力.所以我希望你们不要埋怨,勇敢面对,生活还是美好的,不要把自己的不如意成为社会的负担.

**Comment by YuHuaB** [comment]
维稳知道吗

**Comment by dp199313** [comment]
哥们，讲道理讲不通的，我们把他们倒流出去，才能有清静

**Comment by grasscase** [comment]
打字要分段，才好看。

**Comment by boogoobird** [comment]
至于某些评论的不当言辞,我想知道二十几年的学白上了吗?是谁给你灌输的这个XX思想,XXX做的是不够好,但至少比资本主义剥削你要强太多了,XX管制严,但安全很多.得到什么,总要失去什么,生活不会处处如意.

**Comment by dp199313** [comment]
像我在学校那会，从早忙到晚。现在的学生真是悠闲。

**Comment by FanWuTuoBang** [comment]
朋友，都21世纪了，都互联网时代了，你眼里的资本主义还是18世纪的资本家剥削么？

**Comment by zzjas** [comment]
> 可以诉诸法律,一味的争吵是解决不了问题的
有法可依还有这种事？
>不要把自己的不如意成为社会的负担
如果自己的不如意是社会的畸形带来的，为什么不能去争去闹去反抗？
>至少比资本主义剥削你要强太多了
不好意思资本主义没经历过，“社会主义核心价值观”倒是背了不少

**Comment by boogoobird** [comment]
是真闲,做事情都不动脑子.如果他们要真有苏秦和张仪的"三寸不烂之舌",我倒还真佩服他们,看到他们我就想到我老家的那些村民,只是为了自己利益叽叽喳喳,但从不会从长远考虑问题.总是觉得别人伤害了他们,却不会想怎么达到双赢.

**Comment by Vargnatt** [comment]
> 我一直有一个想法,我想改变教育体制,十年前我甚至想到北京去陈述我的想法,但我的想法是不能被认可的,后来我一直在学习如何与人交流相处,如何和政府打交道,包括我现在从事开发也是在向这方面努力.所以我希望你们不要埋怨,勇敢面对,生活还是美好的,不要把自己的不如意成为社会的负担.

从这些话可以看得出，你的智力发展水平让你依旧还是这个社会的负担，只不过你闭嘴的时候社会的负担更少一点。

**Comment by Vargnatt** [comment]
> 像我在学校那会，从早忙到晚。现在的学生真是悠闲。

专科学生再不忙就要饿死啦！

**Comment by firogh** [comment]
不是有意嘲讽, 如果能诉诸法律, 还有我们在这废口舌,  怕是失了智.

**Comment by boogoobird** [comment]
是的,所以我要努力学习提高自身能力呀@Vargnatt

**Comment by boogoobird** [comment]
那就是没证据了@firogh 凡事都要摆事实,讲道理嘛

**Comment by dp199313** [comment]
开玩笑，上一辈的积累，改革开放的成果。我们这些高材生还用努力。我们打打游戏闹闹事，他们就得妥协。乖乖供着吃喝。我们高材生要努力，这辈子不可能

**Comment by firogh** [comment]
实在不敢苟同, 版眼强调太死, 此事本就是执法机关该管的事, 正是因为他们的不作为, 才有此处民间声音.

**Comment by cizezsy** [comment]
@dp199313 这位同学，你好意思在这里说讲不通道理？我和你讲道理了啊，你回应了吗？

**Comment by aminic** [comment]
法律要有用，就用不着那么多上访的了，法律要有用，也用不着维稳了，法律要有用，党应该在法之下。

**Comment by boogoobird** [comment]
@firogh 我很赞成民间发声,我一直有一个想搞一个自由交流的平台.我本人也遭遇过不公,心里也愤慨过,但问题最终没有解决.所以我的态度是解决问题,而不是争论问题

**Comment by FanWuTuoBang** [comment]
@aminic   法律是有用的，但是法律的执行者不一定会履行，而且公权力得不到有效监督！法律再完备也只是白纸黑字，还是要人来执行

**Comment by FanWuTuoBang** [comment]
@boogoobird 对啊，你自己也曾经是受害者。你希望自由交流的平台，也是这次是一次契机呢？

**Comment by boogoobird** [comment]
@aminic 这个问题我知道,但是目前这个问题没办法解决,可能只有等到我们这代人上台主政的时候,这个问题才能解决,XXX有自己的执政方针,有自己的布局和规划.要改变是很难的.

**Comment by SakuraLove** [comment]
大家这样争来争去也没意思，不如多为岳昕同学整理下资料，关注下发展。
鹬蚌相争，渔翁得利。
居然连y2b的min运党都给炸出来了，这就已经不是我们所有人的初衷了。
也发展自己吧。

**Comment by SakuraLove** [comment]
其实自己也很苦恼，一遍是政府的宣传，另一边就是min运党的洗脑。
只有自己多去了解真相，多用自己脑子思考才能明辨是非
发到github其实也说大不大说小不小，但大家吵起来真的就是乌烟瘴气了

**Comment by SeaHOH** [comment]
家家有本难念的经，没有完美的社会。

请关注于一个主题，这样才能讨论出结果。

不然跟吹牛闲聊没有区别，没有任何用处。

**Comment by FanWuTuoBang** [comment]
@boogoobird  哥们你还是太单纯了。
等咱们这一代？
你知道红色传承是有专门的培养么？目前这这位就是第三梯队，未来接班的第四梯队，第五梯队都在逐步的培养中呢。

**Comment by zhangn1985** [comment]
@FanWuTuoBang 这个是真的，党培养的队伍就是接班用的。最早的论述可以看“古田会议决议”。

**Comment by tme-wl** [comment]
你就先回答一个事儿，为什么你用半角的标点？

**Comment by JourneyofRock** [comment]
@boogoobird @FanWuTuoBang 下面梯队里是胡锦涛儿子胡海峰，邓小平孙子邓卓棣，叶剑英孙子等等，目前在各县市任职，等待接班，欢迎补充。

阎淮在《进出中组部》里也多次提到他的好友、陈云的长子陈元的一句话：“统治阶级要有统治意识。”

阎淮披露，陈元还说过：“对干部子女政策的出发点应是阶级利益，它是阶级政策的一部分。”

赵家人希望江山世世代代都是红色的。龙生龙，凤生凤，再不发声咱们都只是世世代代打洞的老鼠。

**Comment by ky0ncheng** [comment]
連中文符號排版都不會，還提醒別人好好學習，笑死我了

**Comment by beyondxuxingwang** [comment]
有趣，开眼了，平常课看不到这么思想碰撞
