### ISSUE TITLE
我不反对将这种事挂到github上来

### ISSUE THREAD

**Issue by Archaeoraptor** [sikaozhe1997/Xin-Yue#507]
人民对自由的追求谁也没有理由阻挡

**Comment by boogoobird** [comment]
挂吧,挂吧,大不了以后翻墙搞代码吧

**Comment by GabrielKidd** [comment]
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
