### ISSUE TITLE
[proposal] Suggest using English

### ISSUE THREAD

**Issue by 6ziv** [sikaozhe1997/Xin-Yue#511]
Why do we only discuss it but not spread it?
Personally I suggest using English, to spread it ,and also to show respect for the platform.

Also.I personally recommand those resources(for example videos on YTB) also be collected..

**Comment by UpJunior** [comment]
you are right.

**Comment by GabrielKidd** [comment]
I18N is necessary.

**Comment by SniperChen** [comment]
I agree with ,and I have another idea of translating this articles into English.

**Comment by 6ziv** [comment]
@SniperChen Well...there are so many of them that we may need dozens of volunteers....

**Comment by chengdong0421** [comment]
啥？

**Comment by 6ziv** [comment]
就是说建议用英文啦…毕竟这个平台不只有汉语种人员……
I just recommend using English, for there are still people speaking other languages here.

@chengdong0421

**Comment by chengdong0421** [comment]
这好像是家事吧。。。

**Comment by JourneyofRock** [comment]
we need to spread the word and get western media's attention. "Xi's not my president" https://twitter.com/stopxijinping?lang=en was covered by new york times https://www.nytimes.com/2018/03/09/us/xi-student-protest-china.html.

**Comment by 6ziv** [comment]
@JourneyofRock ...Well...Can I refuse to attend political discussions. Political issues cause too many conflicts...

**Comment by 6ziv** [comment]
@chengdong0421  I mean..yes, you are right. But in fact it is nothing that should be kept secret. Then talking in mother tongue where there may be foreigners may be considered impolite by some people...
