### ISSUE TITLE
[Proposal]希望有人可以帮忙改善一下gitpage

### ISSUE THREAD

**Issue by Homer-G** [sikaozhe1997/Xin-Yue#513]
大家不要在issues争论github的用法问题了

这个项目目前有较多材料，但缺少维护。
1. 很多Markdown和图片文件没有生成静态页面
2. readme.md里面的链接也比较混乱，有链接到chuantu.biz也有链接到gitpage的

我建议在issues里讨论一下链接规范和gitpage静态页面的统一生成方式

@zhaobenx

**Comment by dp199313** [comment]
请关掉issue自建评论，现成的评论插件有很多github也有。

**Comment by SniperChen** [comment]
建议关闭无用issues.

**Comment by dp199313** [comment]
真心想做这件是的，找个人出来维护一下评论。过滤掉偏激谩骂，让事情步入正轨。

**Comment by SakuraLove** [comment]
无用的争论issue特别是min运的issue就麻烦删了吧。争论打内斗只会削弱自己的力量，被别人拿去当笑柄

**Comment by cizezsy** [comment]
@dp199313 所以说是谁偏激漫骂？

**Comment by dp199313** [comment]
清华北大，见识到了。

**Comment by cizezsy** [comment]
自己都行不端，坐不直的人，就别站在自认的道德高地上了。

**Comment by SniperChen** [comment]
@GameBunring 统一一下规则，然后按规则来撰写。我觉得也可以让更多人发起merge请求，专门如果可以，找几个人来专门审核求情。这样会不会好一些？

**Comment by cizezsy** [comment]
@dp199313 得了，我也不在这说了，没意义。呆会我就把评论全删了，前面言语有冒犯之处，见谅。

**Comment by GameBunring** [comment]
@SniperChen
pull request都是 @sikaozhe1997 处理的，我觉得处理的很好
现在主要是缺少这个repo的规范说明文件

**Comment by dp199313** [comment]
@cizesy 先喷的是谁？

**Comment by SakuraLove** [comment]
大佬们加油，希望自己也能出点微小的贡献

**Comment by cizezsy** [comment]
@dp199313 你问问你自己啊，你造谣这违反社区条款也没个回应，你说别人不和你讲道理，我讲了，你也没个声响。我们也别在这干扰别人的正常的issue了行不？都删了，该干嘛干嘛去吧。

**Comment by Vargnatt** [comment]
@dp199313 
> 清华北大，见识到了。
天津电子信息职业技术学院，见识到了。问下阁下投身前端两年工资多少了啊？有没有抄的代码行数多啊？抄人代码连注释都不改的咯？

**Comment by cizezsy** [comment]
@Vargnatt 说真的，我是友军。但是我觉得在这里用他人的学历做攻击，不太恰当。（十分钟后，我就把评论全删了）

**Comment by Vargnatt** [comment]
@cizezsy 我从来不拿这些说事的，但是这个家伙蠢而不自知的行为真是惹到我了。
整个issue里面都是他的babyrage般又不尖又不刻薄的酸臭味。缺乏交流的能力、顾左右而言它，从借着一个貌似伟岸的理由表达“我不喜欢的都应该去死”到无差别乱喷。唯有毫不自省这一点是不变的。
遇到这种好为人生导师的人，我一般都会打听一下能不能教我赚钱。

**Comment by cizezsy** [comment]
@Vargnatt 明白你的意思。他的行为确实有点出格而不自知。明明自己在喷人，自己在尖酸，自己完全不讲道理。不知道为什么还有底气这么趾高气昂。就别和这种人计较了，没什么作用的。这是个讨论技术的issue，待会我们把评论都删了吧，不打扰他们正常的讨论了。（十分钟后删除此评论）

**Comment by Vargnatt** [comment]
@cizezsy 
deal.

**Comment by zhaobenx** [comment]
感觉很好呀，但是得把repo的所有者 @sikaozhe1997 请来才能更好的维护嘛。 而且如果建立gitpage的话可以用一个利用issue进行评论的插件，这样看起来也会整齐很多

**Comment by vzxxbacq** [comment]
@zhaobenx 个人建议在docs内添加 README.md 用来规定整个页面代码的编写规则（代码风格、文件结构之类），如果有新信息，大家就能够根据这个规则添加页面。

**Comment by zhaobenx** [comment]
[**@vzxxbacq**](https://github.com/vzxxbacq) commented on [2018年4月25日 GMT+8 下午8:02](https://github.com/sikaozhe1997/Xin-Yue/issues/513#issuecomment-384262241 "2018-04-25T12:02:06Z - Replied by Github Reply Comments"):
> @zhaobenx 个人建议在docs内添加 README.md 用来规定整个页面代码的编写规则（代码风格、文件结构之类），如果有新信息，大家就能够根据这个规则添加页面。

我已经发起了个pr #584 ，如果通过的话所有的md文件都会被收录进那个静态网页。至于页面风格的不知道你有没有什么想法？（我只是技术方面的活计，内容格式什么的可以和其他几位探讨）

**Comment by gaocegege** [comment]
@daniel-lij 现在我们有了一个解决方案，欢迎提 PR 优化。

**Comment by gaocegege** [comment]
现在可以关闭这个 issue 了么，我们已经有了比较美观的静态页面，只是，现在还没有 enable

Ref #618

**Comment by vzxxbacq** [comment]
agree
