### ISSUE TITLE
所以在一个码农社区讨论这件事有什么用吗？

### ISSUE THREAD

**Issue by skriany** [sikaozhe1997/Xin-Yue#514]
其实大部分人喜欢在这叨逼还不是因为不需要翻墙……
可是看很多聚聚的言辞他们又不是没有VPN。
谋求热度关注去推特有用多了，
你说存档……推特也行啊……

**Comment by UpJunior** [comment]
嗯，睿智啊你

**Comment by chengdong0421** [comment]
疯了呗，其实只是为了发泄。具体有没有用他们才不管呢。“反正我发声了，我对这件事做贡献了，你没做，你就是跪着的”

**Comment by wmxl** [comment]
第一，这个地方可以不用翻墙就能看到，所以可以方便地转发给别人看，从而让更多的人知道
第二，保留一些这个事情的信息资料而已，没让非要关注啊，你觉得不关你的事，你可以不理啊，也没必要酸别人想关注这个事的

**Comment by skriany** [comment]
@wmxl 按照这趋势被墙了不奇怪，所以以后看这事还不是要翻墙。2333333

**Comment by dp199313** [comment]
第一，我们清北高材生想去哪就去哪
第二，我们穷，我们弱势，我们在干正义的事

**Comment by 6ziv** [comment]
For letting others know.
Yeah, I have VPN, and I can discuss it on Twitter, and only a few people behind the Wall will see it if so. Now someone posted it on github, and people concerned about it can view the repo, speaking out their opinions. Is it useless?I do not think so.

**Comment by wmxl** [comment]
@skriany 如果真的因为这个事情github被墙了，哪我们的政府也太脆弱了，我觉得不至于，其实本来就不是多大的是，只不过上面想遮丑而已，至于为了一个老师的丑事让广大程序员都不方便吗？这不是个划算的买卖

**Comment by juliosueiras** [comment]
@6ziv just a reminder, Github is a company in the end of the day(unlike WikiLeaks), so any action that Github takes is not suppression of any kind, but rather its being a company P.S. also most people don't like politics, and Github is mostly neutral of any kind of politics(even government's repos are law draft, code, proposal, etc)

**Comment by skriany** [comment]
@6ziv 讨论来讨论去，对当事人一点实质性的帮助都没有。你真有这心还不如给当事人打钱，最后假洋鬼子guna

**Comment by skriany** [comment]
@wmxl 算了吧，反正这事没多大事，可是你又不能保证其他人会不会讨论别的敏感政治事件……

**Comment by liyi1008** [comment]
这是污染社区，虽然社区好像并没有规定只能弄技术相关的东西，但是这是大家公认的惯例。这种有高尚理由就公然藐视规则的事，不正是大家现在所反对的吗？既然如此，这不是很幼稚可笑么？

建议大家还是国内发，删多了它们才知道你们的意思，如果认识不到这一点，那么比起百年前，你们不但没有长进，反而大有不如了。

**Comment by Vargnatt** [comment]
归档归归档，讨论归讨论。
你要看到所有讨论都是自发的，这件事情（尤其它之后的发展）值得这么多讨论。
repo的一个人建的，讨论是每个人参与的。这不是污染社区，这就是刚好在github上有了这么个repo

**Comment by 6ziv** [comment]
@skriany Well I am just saying in English because github is a global website..You think I love typing English on a cell phone?enmmmm..if you want I will try to.speak in both English and Chinese..
I admit that discussion here does little help. But the repo is good, collecting infomation about this, right?Also someone referred to a  video on youtube about this is Issues. And discussion here really arised some people's awareness...

额…说英文还真是不好意思了…只是出于对平台的尊重输入英文也很累的……那我还是双语吧…………
首先是在这里讨论用处不大并不代表这个仓库没用啊…整理了大量的资料，话题里其实也有大佬贴油管视频，确实帮着梳理了事件啊……接下来是我们讨论有没有用的问题…打钱并没有什么用吧…不管真相如何这个事件更多的需要人们知情需要舆论啊…而这里的讨论…至少把它弄得很热了不是嘛…

**Comment by juliosueiras** [comment]
@6ziv 建repo为了整理文件没问题（很欢迎），。。。。。可以issues太多无语的。
比如用travis来弄自动找错别字

**Comment by 6ziv** [comment]
@juliosueiras Thanks for the reminder. But still I think being neutral of politics does not mean banning politics..(In fact I do not think the whole thing has anything to do with politics..For every country and every state hates power abuse...)

**Comment by juliosueiras** [comment]
@6ziv what I mean by neutral politics not in banning, but using repo as jumping point, for discussions, for example, issues, is not a good places for discussions(like the name suggest, is for issues), for discussions, something like gitter can work. I am just saying , posting politics sensitive repo in github is fine , just do it in a neutral format(like not starting a flame war). The point I am just saying is the repo can be use for the material reside(with update files, website link, youtube link, maybe even use automatic tools like headless chrome to do automatic backup of certain website that might be taken down), but discussions regarding the matter can be jump to platform that may connect to github like HipChat, Gitter, Slack, etc

**Comment by GabrielKidd** [comment]
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。

**Comment by grasscase** [comment]
还有很多人不知道嘛。

**Comment by MAYDAYHAO** [comment]
还是你睿智啊。在这个地方物尽其用存个档不好？没人逼着你看吧，进来找喷图什么。

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
