### ISSUE TITLE
真是看到了人性的自私

### ISSUE THREAD

**Issue by wmxl** [sikaozhe1997/Xin-Yue#515]
唉 其实真的能影响到你们多少吗？ 哪怕有一丝丝可能对你的利益损害，都要极力反对。为什么不想远一点，今天别人遭受的困难，可能有天你也会遭受，难道你希望那时候人人都对你避而远之或者跟甚者落井下石吗？

**Comment by nbwuzhe** [comment]
别人没有义务要被你影响。你的想法很可笑。

**Comment by 6ziv** [comment]
@nbwuzhe And we have no responsibility to quit. You can say that you are against it, but it is a suggestion, not an order, and we can choose to take it or not.
What really makes things worse is that some so-called 'programmers' poured their anger on Yue, and said something cold-blooded, or even some rude words...

**Comment by nbwuzhe** [comment]
@6ziv Actually I think the content is worth supporting. What I despise is the way these guys are doing and thinking.  First, they come to a totally wrong place, and I strongly suggest that they go to FB or Twitter to discuss such kind of issues. Second,  their thoughts are ridiculous, saying "其实真的能影响到你们多少吗". We can offer help, and we are happy to, but it is unreasonable to regard the help from GitHub community as an obligation.

**Comment by 6ziv** [comment]
Well..But the best way to handle it is to mail to the supporting team of github, or just writting down reasons, but not to mess things up. On both sides there are ridiculous people, pouring some.. some f-words on each other...
Well, I just mean that discussion is welcome but it should be gentle and reasonable, not calling names.
In fact I think no side should be wholly blamed.But those offensive speakers should be looked down upon...

**Comment by MAYDAYHAO** [comment]
@nbwuzhe 当别人都在密切关注事件进展的时候说两句反话表达所谓的睿智观点，就能表现得自己与众不同？“看我吃屎多帅呀！”怎么办，我难道还要给你亲亲抱抱举高高吗。

**Comment by nbwuzhe** [comment]
@MAYDAYHAO 您的内心戏好足，佩服佩服。

关不关注事情发展是一方面，该不该往GitHub上发是另一回事。我说的是后面一回事，而你非要把两者混成一坨。同时也很好奇把您那么大一坨拉出来的人会是什么样的，一个动不动一上来就满嘴屎尿屁的混迹在GitHub社区，真的是件很呵呵的事。

看看你的repo和activity本来是懒得理你这种把GH当贴吧用人的，但既然你已经开始喷米田共了那就不妨遂了你愿，让大家看看清你的嘴脸。

**Comment by MAYDAYHAO** [comment]
@nbwuzhe 别人没有义务要被你影响。你的想法很可笑。我把gh当什么用，跟你有什么联系吗。既然你对号入座，那你开心就好。让大家看清楚你是什么嘴脸咯。码云也好用，我还能当私人仓库，你这么睿智把公司代码贴到这里吗？
