### ISSUE TITLE
怅然泪下

### ISSUE THREAD

**Issue by Shuo-Jia** [sikaozhe1997/Xin-Yue#516]
遥想当年大学之自由精神，以为中国再不会有这种人！读罢整个事件，竟然恍然犹如穿梭到民国大学那个年代，然而回到现实看罢周遭浮躁喧嚣，不禁怅然若失。但是又能怎样？我不想谈论他们做得对与否，也许真的不妥当，但是这种精神，这种担当是我们该仰望的！

**Comment by JourneyofRock** [comment]
有些话总是有人要说的，有些事总是有人要做的。挺直脊梁，拒作犬儒。

**Comment by wmxl** [comment]
有的人就是自己跪着， 还看不惯别人站着，  还要酸一下别人
