### ISSUE TITLE
坚决支持！

### ISSUE THREAD

**Issue by zhangjinxue** [sikaozhe1997/Xin-Yue#519]
那些说关闭issues 自建讨论区的麻烦动动脑子！你能保障不被封吗？ 还有反对把这种事情挂到github的人，告诉你们，反对没用！github是你家的吗？你能控制了吗？既然能发上来就说明github规则允许！就是可以发出来！真是气晕了！

最后说一句：在这个充满谎言的世界里感谢说真话的人！坚决支持岳昕！

**Comment by GabrielKidd** [comment]
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。
