### ISSUE TITLE
github是我程序员的圣地，发这种，容易被政府封啊

### ISSUE THREAD

**Issue by oldshipmaster** [sikaozhe1997/Xin-Yue#520]

**Comment by GabrielKidd** [comment]
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。

**Comment by wydwww** [comment]
Duplicated with many previous issues https://github.com/sikaozhe1997/Xin-Yue/issues/13 https://github.com/sikaozhe1997/Xin-Yue/issues/83 https://github.com/sikaozhe1997/Xin-Yue/issues/50 https://github.com/sikaozhe1997/Xin-Yue/issues/187
Please close.

**Comment by zhangsen1992** [comment]
if a programer can not break through the GFW,he isn't a qualified programer~

**Comment by Mason-Xu** [comment]
一个公民的人权,自由被压迫,在 某些人看来还远远没有一个网站被封重要, 我感到悲哀

**Comment by dadadaheiguo** [comment]
想知道外国语学院的怎么会想起来在github上发表？不过为了能有个被侵权后发声的机会，顶一下

**Comment by wangduheng** [comment]
你可以把github搬到你家里去，别人就发不上去了

**Comment by Etamin** [comment]
这个网站本身就不“合法”啊，没有在大陆注册，没有把服务器放在大陆，能够访问本来不过是一种“施舍”罢了

**Comment by grasscase** [comment]
美国网站，不是要抵制美国吗？封了就封了吧

**Comment by kribeel** [comment]
你们是不知道，github对大陆程序员有多重要。你们需要的自由，跟长城防火墙去讲道理啊！

**Comment by MAYDAYHAO** [comment]
圣地就是让你来当个小仓库然后考个别人代码的？如果没有贡献请你闭嘴安静的用就行。

**Comment by lazycatzh** [comment]
什么圣地不圣地，这里是开源社区，是代码仓库，在自己的仓库存放什么格式的文档是自由的，文档有没有BUG，你可以提,  封不封关你什么事。

**Comment by blacklisten** [comment]
这个是让世界人看笑话么？

**Comment by gamesover** [comment]
这个楼主真是我们程序员之耻。连基本公平公正公理都讲，你还编什么程序？

这是做人的基本道理。

**Comment by kilobtye** [comment]
类似的issue太多了，请到 #530 进行讨论，谢谢~
duplicate of #530

**Comment by tomfly-connectThesource** [comment]
最后起码的，希望你能把这句话中的“程序员”三个字删掉！
