### ISSUE TITLE
學醫救不了中國人，學技術也一樣。

### ISSUE THREAD

**Issue by GabrielKidd** [sikaozhe1997/Xin-Yue#521]
Lu Xun said that medicine cannot treat Chinese people. Now the technology cannot either.
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。

**Comment by wql7013** [comment]
因为对于大多数人，互联网是用来挣钱的，“互联网+”就是一个商业概念。

**Comment by dp199313** [comment]
嗯，对学技术救不了中国。但是我们清北高材生。就可以。我们现在就在github治国。哦，那你倒是别在技术社区发。哦不，其他社区也是程序员搭的

**Comment by liyi1008** [comment]
遵守规则，以法治国才是唯一之路，所以希望大家尊重此地不成文的惯例。

**Comment by dp199313** [comment]
有才有平等自由，没有你平等自由个毛线。这么多高材生，自己搭网站去宣扬你们主义呀。

**Comment by chengdong0421** [comment]
学技术好像也不是为了救中国吧。。。为了混口饭吃。。

**Comment by phdsky** [comment]
中国人的脊梁骨已经被压弯了，比以往任何时候更甚。

**Comment by shanezhiu** [comment]
有人说不能靠这靠那，只说一句，学技术为了生活？你不要生活，难道你脑子每天想着，阿，我要拯救中国？不要这样悲天悯人。很反感。

**Comment by GabrielKidd** [comment]
某些人根本不懂什麼叫做生活，就像他們不懂互聯網精神，不懂GitHub精神一樣。

**Comment by roberning** [comment]
先救自己吧

**Comment by chenchongsong** [comment]
学医学技术都不行 那您觉得要学什么

**Comment by chenchongsong** [comment]
学医学技术都不行 那您觉得要学点什么好呢？

**Comment by chengdong0421** [comment]
@GabrielKidd 看你头像怎么感觉你是做鸡的啊。。。。

**Comment by GabrielKidd** [comment]
@chengdong0421 Why beholdest thou the mote that is in thy brother's eye, but considerest not the beam that is in thine own eye? Or how wilt thou say to thy brother, Let me cast out the mote out of thine eye; and lo, the beam is in thine own eye?

**Comment by aminic** [comment]
真正的医者，看到病人肯定会问诊施救的，而不是看着不就就算了。
真正的医者，医术高低在次，仁心在上。
所以真正的医者，并不会因为看着不行就算了，能医的，会尽力医的。
医者仁心，医术&IT 无非都是技术，重要的是人心仁心，决绝的不放弃。
不要小看普罗大众的觉悟。

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
