### ISSUE TITLE
所以发在github是什么鬼？

### ISSUE THREAD

**Issue by mzbac** [sikaozhe1997/Xin-Yue#522]

**Comment by GabrielKidd** [comment]
互聯網的技術特徵使得網民的「結網行為」呈現出以下特徵：極低的准開放、平等、協作、分享，這就是所謂的「互聯網精神」，是一種「追求自由與平等」、「拷問人性和社會」、「喚醒真我和愛欲」的精神。
如今有越來越多人正在玷污互聯網，玷污互聯網精神。這是我以及每一位互聯網工作者的恥辱。如果說北大已經失去了靈魂，請不要讓互聯網再失去它的靈魂。

**Comment by zhangjinxue** [comment]
还有别的地方可以发吗？还有哪个平台不会被封？

**Comment by dp199313** [comment]
别的平台，我们也不知道，也不会呀。毕竟我等清北高材生不了解这么基础的东西的

**Comment by Homer-G** [comment]
[Seven Ways To Use GitHub That Aren’t Coding](https://readwrite.com/2013/11/08/seven-ways-to-use-github-that-arent-coding/)
如果你真的想维护Github，请把这个duplicate issue删掉

**Comment by mzbac** [comment]
对牛弹琴..

**Comment by zhaobenx** [comment]
# 530
