### ISSUE TITLE
能否将讨论集中在几个issue中？

### ISSUE THREAD

**Issue by karkenhavedream** [sikaozhe1997/Xin-Yue#524]
关闭掉其它的issue，将不同的主题讨论集中在几个issue中，避免现在这种散乱无序的局面。

例如，"[Discussion]该repo发在GitHub上是否合适"，“[Discussion]该repo能为这个事情带来什么帮助”。

（这是小号，大号不想发这种政治相关的issue）

**Comment by goldimax** [comment]
同意 @sikaozhe1997

**Comment by Zheaoli** [comment]
同意
