### ISSUE TITLE
这不是一个政治论坛

### ISSUE THREAD

**Issue by NeuronWade** [sikaozhe1997/Xin-Yue#527]

**Comment by JourneyofRock** [comment]
@chengdong0421 至少有几千个人能看到，至少有几千个人知道有同伴和他们在一起

**Comment by chengdong0421** [comment]
@JourneyofRock 那又怎样，在这里骂得再解气，你要骂的人又听不到。。。

**Comment by chengdong0421** [comment]
@JourneyofRock 听不到又怎么会害怕？

**Comment by JourneyofRock** [comment]
@chengdong0421 能在有一定人气的公开场合自由地说自己想说的话本身就意义重大，同时也能让志同道合的人鼓起勇气。而且人多了就会有媒体关注报道。

**Comment by chengdong0421** [comment]
@JourneyofRock 你傻了吧，各大媒体都已经知道过了，只是他们也没办法。。。在这里喊，他们还是没办法。。

**Comment by liyi1008** [comment]
贴大字报吧，被撕没关系，不断搞就是了。躲在这种小众的技术社区声张正义，那不过是自我安慰。

现在的学生比起29年前和99年前差很多。

**Comment by zhangn1985** [comment]
29年前也是被人利用了，颜色革命。99年前，也烧错了房子。

**Comment by DanteAndroid** [comment]
也请你别把这里当贴吧一样，乱发issue。

**Comment by chengdong0421** [comment]
@DanteAndroid 什么叫乱发？这不是言论自由的吗？

**Comment by JourneyofRock** [comment]
@liyi00000 贴大字报和网上发声的目的都是让更多的人看到。小众的技术社区目前看上去像亚文化，但很可能会在将来变得流行，就像b站当年也很小众，如今也进入了主流的视野。

当年没有监控，摸黑贴大字报和现在在网上发帖是一个性质。国内现在到处都是监控密布，出门贴大字报一查就能知道是谁干的，和帖实名大字报有什么区别。

**Comment by zhangn1985** [comment]
@chengdong0421 我们刚刚体会到了无序发言的害处，言论自由也要注意方法。
