### ISSUE TITLE
来赌一下，清北高材生们多久能搞定gitpages平息混乱？

### ISSUE THREAD

**Issue by dp199313** [sikaozhe1997/Xin-Yue#528]
我赌半天。大家宽容点，不必对这群孩子这么苛刻。

**Comment by 6ziv** [comment]
问题不友善，建议修改。
我也瞧不起那些仗着自己TP就瞧不起别人的人…但是这么开地图炮不好吧…
我好像没见到那种有迷之优越感的人啊…有的话帮忙圈一下…
倒是您这技术优越感…讲真的有点强…

Offensive words. Suggest adjusting. 
I also look down upon those who have a sense of superiority over others, but please do not judge a group of people by some of them.
By the way I see nobody else looking down on others.
But in fact i consider you with a sense of superiority over others for your ability of coding..

**Comment by Homer-G** [comment]
参考 #524 的建议，请修改issue格式

**Comment by dp199313** [comment]
我友善帮你们解决问题的时候。各位高才可说的是，这里是清北的人，干我屁事这种言论。我以为你们很喜欢清北高材生这样的称谓
