### ISSUE TITLE
请不要污染github

### ISSUE THREAD

**Issue by flasco** [sikaozhe1997/Xin-Yue#529]
被墙了你们才开心？

**Comment by guider** [comment]
如果你是当事人你就不这么说了吧?

**Comment by shellv** [comment]
如何作为一位技术人员能被防火墙墙住，说明要不你自己技术不行，不要就是你公司不行。
自己技术好的随便怎么都不会墙住，公司好的梯子已经给你搭好。
如果你是技术人员还是转行吧，你不适合做这行。
