### ISSUE TITLE
[Discussion]@dp199313这个id真的很活跃哦

### ISSUE THREAD

**Issue by 313991pdkcuf** [sikaozhe1997/Xin-Yue#531]
这是个什么人，希望大家心里有数吧。专门发个issue，大家避而远之，免得浪费时间。
![image](https://user-images.githubusercontent.com/38715332/39229989-7c6ff392-4897-11e8-918d-8c613d8427c4.png)

**Comment by dp199313** [comment]
是不想看到你们的人。

**Comment by JourneyofRock** [comment]
在google上搜这个id就能看到他在cnode上发的帖和他本人照片

**Comment by leciel-guo** [comment]
@dp199313 不想看就别看啊，赖在这里，所以你是智障呢还是智障啊

**Comment by dp199313** [comment]
呵呵，贴吧的那一套学得挺快，来人肉我。把这个社区反对你们的人都人肉出来你们就能赢得胜利

**Comment by leciel-guo** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/35631258/39229576-e8ab2f60-4895-11e8-9331-93883c33d367.png">
我来备份一下

**Comment by karkenhavedream** [comment]
@leciel-guo 涉及到人肉就过分了，麻烦删除这个comment。你这样的行为和我们所反对的行为性质是一样的。

**Comment by SniperChen** [comment]
@leciel-guo 请停止你的行为。

**Comment by SniperChen** [comment]
@dp199313 请停止你的行为。

**Comment by JourneyofRock** [comment]
@dp199313 
你要是正常参与讨论没人会说你。你上蹿下跳阴阳怪气当搅屎棍就不对了。

**Comment by lilewis** [comment]
@leciel-guo还是撤掉吧
<img width="741" alt="123" src="https://user-images.githubusercontent.com/7970836/39229765-8e9342f0-4896-11e8-9184-5d44392318af.png">

**Comment by Chandelier309** [comment]
@JourneyofRock 虽然很烦他，但是不建议使用这种方法拓展攻击。这样不好

**Comment by fuckdp199313** [comment]
@leciel-guo 撤掉吧，他是什么人大家都懂，没必要这样攻击。

**Comment by Vargnatt** [comment]
他可能在智力发展上存在那么一些障碍，给自己竖了个稻草人疯狂输出。
我曾经想怼他的学历或者代码抄袭甚至语文水平，不过终究没必要。他毕竟只是傻，还不算坏，因为他没法跟你有来有回，只能疯狂虐待稻草人。

**Comment by dp199313** [comment]
首先谩骂不是我带头的。是你们的人，其次和我好好说话的人，我都礼貌回答

**Comment by FanWuTuoBang** [comment]
@leciel-guo   虽然我不喜欢这个人，但请不要搞人肉搜索，用网络暴力对待人家。我们就和打压岳同学的北大老师一样了。

虽然持有不同观点，但希望彼此都能遵守一个道德底线，不要发展成为网络暴力。

**Comment by karkenhavedream** [comment]
@dp199313 反对。你并没有礼貌回答，我用大号回复你，被你骂了。

**Comment by JourneyofRock** [comment]
@Chandelier309 但如果在一个没有管理员的讨论区，没法封禁id的话，对于少数品行低劣的人该如何处置呢。总有新加入的人被这个人的搅屎棍言论吸引，浪费时间和他撕。至少也得有个这种人的名单广而告之，新人也不用浪费时间看他们的小丑言论了。

**Comment by UpJunior** [comment]
@dp199313  不要装无辜。

**Comment by JourneyofRock** [comment]
@karkenhavedream 哈哈哈，这脸打得啪啪的

**Comment by dp199313** [comment]
请截图在你谩骂我之前我主动骂你

**Comment by Vargnatt** [comment]
我真是不知道谁第一个满口社区大义满口人生经验的发issue嘲讽的，以为自己把自己的issue关了别人就不记得了？
分明是一边正常地贴出ToS和相关说明，然后这个d开头的id只能顾左右而言他，之后狗急跳墙地开了不知道多少阴阳怪气的issue。

**Comment by JourneyofRock** [comment]
@dp199313 你这是想钓别人大号吗，你以为都和你一样脑残

**Comment by dp199313** [comment]
开小号各种带节奏，敢做不敢当，你们不过就又想闹事情又不想承担

**Comment by Vargnatt** [comment]
真把自己当做管理员了。你是不是还要给别人扣一个僭越的帽子？

**Comment by JourneyofRock** [comment]
@dp199313 你是不是日常生活中心理自卑，逮到个机会就上蹿下跳找存在感。你在贴吧被封的原因可见你本来就一屁股屎到处咬人。

**Comment by dp199313** [comment]
你们别给们扣奴性自私的帽子已经很不错了。我敢给你们扣帽子。毕竟你们开小号躲在网络后面无所畏惧。

**Comment by poholo** [comment]
看到ETH的妙用了~

**Comment by Vargnatt** [comment]
对你需要扣帽子吗？实事求是地指出你蠢而不自知还不够吗？你是不是那种寻求被羞辱体验的抖m啊？

**Comment by karkenhavedream** [comment]
@dp199313 抱歉，我开小号是担心我的工作会受到影响。我可能确实不够无私，没有岳昕同学有勇气，这点我不否认。

**Comment by 6ziv** [comment]
@fuckdp199913 
Please change another id.
None of us want the disscussion to become calling names..

请修改id……
发展成互相谩骂互相人身攻击就不好玩了……

**Comment by lazycatzh** [comment]
![wechatimg1](https://user-images.githubusercontent.com/8511571/39231942-477514f4-489e-11e8-81ae-871523d43469.jpeg)
这个dp199313 看起来在哪都是个老鼠屎，真恶心

**Comment by Himself65** [comment]
第一次想知道GitHub怎么屏蔽人

**Comment by DayChan** [comment]
@gaocegege Plz close this issues. It's not appropriate to discuss a specific people, and it's not good for freedom of speech. 类似于批斗式地批评与人肉一个具体的普通人不合适，并无益于言论自由
