### ISSUE TITLE
[Discussion]关于解决目前issues 混乱的建议

### ISSUE THREAD

**Issue by SniperChen** [sikaozhe1997/Xin-Yue#532]
为了解决目前issues混乱的问题。
本人提出几点建议

请各位issues 发布遵循以下规则
1. 发布issues 请使用同一格式的前缀：
[Discussion]：问题讨论
[Bugfix]：项目问题修复讨论
[Proposal] : 建议类倡议
......(待补充) 

2. 请各位不要随意发布issues，可以先搜索以下有没有和自己相同的issues，他家统一到里面讨论。

一些讨论区：
**讨论该repo是否适合发在GitHub上**  #530。

关于政治是否应该在github讨论的各种观点，我都觉得没有错。我尊重所有人的观点，也尊敬22位contributors 的行为。不过，当下，我们为什么不可以把这个项目当做一个要建设的网页，去先把里面的技术问题解决呢？

**Comment by wql7013** [comment]
另外提议，大家不要只顾着看issues，还要多关注code里面的文档，一直在更新，也可以关注Pull requests

**Comment by firogh** [comment]
@sikaozhe1997 建议临时关闭issues 区.

**Comment by karkenhavedream** [comment]
同意，希望大家能理性思考，不要相互攻击了。

**Comment by wmxl** [comment]
同意 理性支持

**Comment by larvata** [comment]
目前在没有办法阻止创建恶意issue的情况下 
contributors对有价值的issue打tag 
我认为是更可行的办法

这样对issue的评价可以有一个相对统一的标准
有了tag也便于搜索

那些无意义的issue就随他去吧

**Comment by UpJunior** [comment]
tongyi

**Comment by zhaobenx** [comment]
[**@larvata**](https://github.com/larvata) commented on [2018年4月25日 GMT+8 下午3:00](https://github.com/sikaozhe1997/Xin-Yue/issues/532#issuecomment-384181101 "2018-04-25T07:00:55Z - Replied by Github Reply Comments"):
> 用户主动写前缀没办法防止恶意开issue
> 
> 目前在没有办法阻止创建恶意issue的情况下  
> 
> contributors对有价值的issue打tag  
> 
> 我认为是更可行的办法
> 
> 这样对issue的评价可以有一个相对统一的标准  
> 
> 有了tag也便于搜索
> 
> 那些无意义的issue就随他去吧

打tag+1

**Comment by chengdong0421** [comment]
GitHub贴吧吧规！赞

**Comment by zhaobenx** [comment]
同时 @sikaozhe1997 可以添加 ISSUE_TEMPLATE.md嘛，这样也可以方便规范issue。
以及可以的话可以多找几个人合作管理这个repo，也方便及时进行消息管理

**Comment by chengdong0421** [comment]
你们现在真像一个组织

**Comment by JourneyofRock** [comment]
@chengdong0421 哈哈哈，其实有些贴吧和虎扑的管理经验可以吸取借鉴。github贴吧主要是账号太容易申请，发帖没有门槛限制，又无法对有些id进行一定时间的封禁。

**Comment by SniperChen** [comment]
@zhanggenex 
同意！
撰写相关的管理规范文档+1

**Comment by dogbeiqing** [comment]
@chengdong0421 机智

**Comment by karkenhavedream** [comment]
@chengdong0421 因为**不友善行为**被封禁，和因为**行为**被封禁性质是不一样的。

**Comment by SniperChen** [comment]
@karkenhavedream 
统一tag 和 issues 发布规则的定制你有什么想法和建议吗？

**Comment by dogbeiqing** [comment]
@karkenhavedream 不友善的行为现在是你们在定义,别人反对你们的行为即不友善.你们谩骂别的人行为就是友善

**Comment by zhaobenx** [comment]
添加 pr #544 希望大家可以去讨论讨论具体添加的内容

**Comment by karkenhavedream** [comment]
@dogbeiqing 请你举出从这个Issue创立时开始，你们觉得友善，因为反对我们被定义为不友善，以及我们漫骂其它人，被定义为友善的例子。

**Comment by karkenhavedream** [comment]
@SniperChen 我得工作去了，划了一下午的水，再不敲代码就要倒霉了哈哈。晚上再来讨论。

**Comment by karkenhavedream** [comment]
@dogbeiqing 那位dp同学，被别人爆照人肉，我们都第一时间进行了反对。而dp同学指责我们（当然我们也指责他了）并没有任何类似封禁的事情发生。（谢谢讨论，我得工作去了）

**Comment by JourneyofRock** [comment]
@karkenhavedream @SniperChen 谢谢你们的工作。有些小号无理取闹就别理他们了，不值得浪费时间解决他们的胡搅蛮缠。

**Comment by dp199313** [comment]
北大是全中国第一名校。不会有错的，该删哪些，该留那些，该怎么导向舆论，岂是我们能批判的，大佬要占领github顺便摩擦一下我们的人格，有何不可。

**Comment by SniperChen** [comment]
@dp199313 你好，请你到 #530 讨论本话题，已经设立了专门讨论区。感谢配合，谢谢！

**Comment by weihuang0908** [comment]
谢谢你们的工作，清理了之前乌烟瘴气的issue区，从互撕往规范合作的方向发展，干得漂亮！

**Comment by hunt978** [comment]
你们也在删留言啊，牛气！

**Comment by SniperChen** [comment]
@gaocegege 
Yes，this issues is just a temporary  template.
