### ISSUE TITLE
[Proposal] Using Git-LFS for Hosting Videos

### ISSUE THREAD

**Issue by juliosueiras** [sikaozhe1997/Xin-Yue#533]
English:

Since youtube itself is block in china, possible solution would be using git-lfs to save the videos, and use html5 player on the result git-pages

Chinese:

因为Youtube在中国被封，可以使用Git-LFS（Git大型文件）来存，然后用<video>在Github Pages来看

TodoList：
- [ ] Implement git-lfs to the repo
- [ ] Save related videos
- [ ] Implement <video> on the github page

**Comment by SniperChen** [comment]
你好，给个小建议，是否可以把前缀改为[Proposal],这样简洁，也比较好检索。十分感谢你的建议！

**Comment by juliosueiras** [comment]
@SniperChen 好了

**Comment by gaocegege** [comment]
如果有视频的需求自然这个 feature 是很合适的，谢谢你的建议。

BTW，目前没有任何视频内容
