### ISSUE TITLE
真心可以去Facebook、Twitter啊，我真的不知道为啥要在git上写啊

### ISSUE THREAD

**Issue by Hujunjob** [sikaozhe1997/Xin-Yue#534]
很多评论就说什么五毛啊、跪久了啊、不负责任啊什么的。
可是我真的就只是用github来关注世界上各个优秀的程序员写的代码，
我真的只是想用自己的一点点力量去让中国至少在互联网上一点点能接近美国
发泄能有什么用啊？
要改变什么就用合理的方式，用自己的行动去解决

GitHub is a web-based hosting service for version control using git. It is mostly used for computer code. 
--Wikipedia

hello world

**Comment by SniperChen** [comment]
你好，请在你的标题改为[Discussion]+标题内容，或者去搜寻相同内容的issues参与讨论。感谢你的配合谢谢！

**Comment by karkenhavedream** [comment]
请去相应的Discussion讨论该repo是否适合发在GitHub上，[https://github.com/sikaozhe1997/Xin-Yue/issues/530](https://github.com/sikaozhe1997/Xin-Yue/issues/530)。

**Comment by 6ziv** [comment]
Please add '[discussion]' tag to the issue. Thanks.
@Hujunjob

**Comment by liyi1008** [comment]
那些平台才常见了，发到这里显得比较高端比较有技术含量一些，给人感觉牛一点。

**Comment by JourneyofRock** [comment]
请去相应的Discussion讨论该repo是否适合发在GitHub上，#530。

**Comment by UpJunior** [comment]
请去相应的Discussion讨论该repo是否适合发在GitHub上，#530。

**Comment by SniperChen** [comment]
请去相应的Discussion讨论该repo是否适合发在GitHub上，#530。

**Comment by Homer-G** [comment]
请去相应的Discussion讨论该repo是否适合发在GitHub上，#530。

**Comment by chengdong0421** [comment]
跟失去理性思考的人没法讲

**Comment by CreeperGo** [comment]
真心您免费提供一个无限制上fb的方法估计这里的人会少很多吧 :D
