### ISSUE TITLE
作为程序员不喜欢这种事上 Github

### ISSUE THREAD

**Issue by helloli** [sikaozhe1997/Xin-Yue#536]
毕竟 Github 是程序员很重要的开源地带，万一因为这种事被墙，是非常可惜的事情！

**Comment by JourneyofRock** [comment]
请去相应的Discussion讨论该repo是否适合发在GitHub上，#530。

**Comment by Homer-G** [comment]
参考 #524 的建议，请修改issue格式

**Comment by chengdong0421** [comment]
原来这里也不能自由的发言，这关issue的手法和删帖真是如出一辙

**Comment by jerzygao** [comment]
作为程序员我很讨厌你的这种说法

**Comment by StepOITD** [comment]
我不喜欢的东西多了，我不喜欢你的观点，但是并不妨碍你表达出来，你不喜欢这个东西出现在github上，但是github表示ojbk，完全没问题。
这跟你程序员的身份没关系，你代表不了所有的程序员。

**Comment by fortyMiles** [comment]
@helloli 你无权代表程序员

**Comment by qidaping** [comment]
那是因为这种事没有发生在你的身上。当发生在你的身上 看着媒体 的报道都被删除  你为什么不换位思考一下

**Comment by podiumdesu** [comment]
啧，身为程序员，不能学习一下翻墙吗？在这里找什么存在感。

**Comment by clong365** [comment]
我是那每天都会上github看看Trending的人，很早就看到这个项目了。就从项目维护的角度说吧，维护的不怎么样。我看了半天也没看出个清晰的来龙去脉。最后还是维基百科管用...
https://zh.wikipedia.org/wiki/%E5%8C%97%E5%A4%A7%E5%B2%B3%E6%98%95%E4%BA%8B%E4%BB%B6
建议readme.md加上维基百科的链接。
