### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Cody1988** [sikaozhe1997/Xin-Yue#538]
这个放在这里不知道合不合适，
但是北大这样的学府，我一直应该是站在法理最前端的地方，看到这样的事情还是挺失望。
难道直面错误有那么的难么？

**Comment by Homer-G** [comment]
请参照 #524 的建议修改issue格式

**Comment by karkenhavedream** [comment]
请加上[Discussion] Tag，并修改成更有说明意义的标题。（维护讨论氛围从你我做起，谢谢！）

**Comment by Cody1988** [comment]
OK，应该的，确实需要好好的组织一下讨论的
