### ISSUE TITLE
Wiki 词条，欢迎大家来编辑

### ISSUE THREAD

**Issue by Hexixixi** [sikaozhe1997/Xin-Yue#54]
[北大岳昕事件](https://www.wikiwand.com/zh/%E5%8C%97%E5%A4%A7%E5%B2%B3%E6%98%95%E4%BA%8B%E4%BB%B6)

**Comment by FoxerLee** [comment]
好像被封掉了？

**Comment by iBug** [comment]
直接上维基百科啊，这个网站我都没听说过。。。

**Comment by Hexilee** [comment]
现在是这个 url 了 https://www.wikiwand.com/zh/%E6%B2%88%E9%98%B3%E4%BA%8B%E4%BB%B6

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
