### ISSUE TITLE
[Proposal]能否把repo里的文档每个都建立一个相应的thread供大家讨论？

### ISSUE THREAD

**Issue by JourneyofRock** [sikaozhe1997/Xin-Yue#540]
建立这个repo的目的是大家对这一事件进行关注和讨论，但由于code和issues的分离导致很难集中对一些公开信的内容进行有深度的探讨。不知管理员怎么看？

**Comment by Homer-G** [comment]
我只是来分担一点维护工作，这个repo的定位问题还是由 @sikaozhe1997 来决定。
根据之前issue的情况，我个人不建议在Github上进行探讨，未名BBS之类的是更好的探讨平台。

**Comment by JourneyofRock** [comment]
@Homer-G 我没用过未名BBS，不过既然是官方控制的论坛上面会不会把大家的讨论删帖？那样的话多高的楼也容易朝不保夕。

**Comment by gaocegege** [comment]
We support GitTalk now, so closing the issue soon.
