### ISSUE TITLE
请滚出Github!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by FreedomOfSpeech** [sikaozhe1997/Xin-Yue#541]
Issues 太多，这只是个吸引眼球的标题，大家看到肯定想进来骂我。

我只是想说可以去
https://anonymous-xinyue.github.io

这个 gitpage 网站下面评论， 不要在这里发Issues 了。点赞高的评论会自动置顶，没用的评论会自动沉掉。

**Comment by FreedomOfSpeech** [comment]
可以用disqus 账号评论

**Comment by alwxkxk** [comment]
皮

**Comment by zhangn1985** [comment]
对不起，不去。看你的名字就知道你的目的。

**Comment by FreedomOfSpeech** [comment]
真是一脸懵逼啊.... 你们继续吧，不管你们的闲事了。

**Comment by zhangn1985** [comment]
本来就不是你们外人该管的事。
