### ISSUE TITLE
[Discussion]关于建立使用issue的规则和清理issue

### ISSUE THREAD

**Issue by zhaobenx** [sikaozhe1997/Xin-Yue#542]
有些重复讨论的话题建议集中到一个issue里，如是否该使用github等。
以及说明哪些不符合规定的issue会被关闭，如漫骂、人身攻击、不符合格式#532等。

**Comment by SniperChen** [comment]
issues 发布规则（草稿）：
1. 发布前请检索是否有相同内容的issues, 如果不存在相似内容的issues，才可以根据 #532 的规则创建新的issues 
2. 为规范讨论，请勿在发布抨击、诋毁、辱骂他人的issues, 否则将面临issues 关闭。
3. 我们更不允许出现人肉等恶劣行为的发生。
4.待补充

**Comment by gaocegege** [comment]
SGTM. 建议只保留几个互相不重复的 issue 即可（目测不超过 10 个），其余没有 open 的必要。

WDYT

**Comment by zhaobenx** [comment]
感觉可以增加几个 issue专门用来讨论特定问题，如是否该使用 Github等。
我已经建立 pr #544 ，制定好了就可以将内容增加进去

**Comment by zhanggenex** [comment]
@SniperChen
泻药
补充一点，那种什么有没有一起打王者荣耀的issue也不要纳入里面 哈哈
另外，可不可以这样设置，发一个issue需要管理员同意才能发？就是不能随随便便的发起issue的意思

**Comment by chengdong0421** [comment]
SVNhub

**Comment by gaocegege** [comment]
@zhanggenex GitHub 没有这个 feature

**Comment by kilobtye** [comment]
我计划清理一下现有的issue, 首先把无意义的issue关闭。另外重复的讨论也考虑关闭并引导到同一个issue里。

**Comment by zhaobenx** [comment]
github只有限制新注册用户提issue的功能

**Comment by gaocegege** [comment]
Could we close the issue?

**Comment by zhaobenx** [comment]
Agree
