### ISSUE TITLE
你们又有什么资格去为一个本来就不应该能访问的网站被封掉而忿忿不平

### ISSUE THREAD

**Issue by Etamin** [sikaozhe1997/Xin-Yue#547]
GH在大陆备案了么？在大陆安置服务器了么？向大陆提供服务器是合法的么？
不能用才是正常的，能用反而是不正常的。你访问这个网站的权利既然不受法律保护，谁又侵犯了你的权力呢？
该被封掉就让它封掉，这一天迟早会来，又苟延残喘些什么呢

**Comment by Homer-G** [comment]
请参照 #532 修改格式，不要发duplicate issue
