### ISSUE TITLE
[Request]建议所有帐号中带有真实身份的贡献者们注意隐藏真实信息

### ISSUE THREAD

**Issue by vzxxbacq** [sikaozhe1997/Xin-Yue#556]
看了一下几位主要贡献者，个人信息太详细了，希望您们暂时隐藏个人信息，如果您们暂时还在大陆的话。
@zhaobenx zhao @SniperChen sniper

**Comment by vzxxbacq** [comment]
把学校信息邮箱信息撤掉吧，撤完我把这个issue关了

**Comment by zhaobenx** [comment]
哇 太谢谢关心了，但是我只是提供了技术方向的支持，所以我想应该不会只是我搞了gitpage的配置而对我怎样吧

**Comment by JourneyofRock** [comment]
@zhaobenx 多加小心，保护好自己，从前三十年的历史来看别高估当局的下限。

**Comment by Shadesoul** [comment]
@zhaobenx 楼主说的对，首先保护好自己，不要有侥幸心理。

**Comment by vzxxbacq** [comment]
Issue里有多少水军呢，昨晚看下来我觉得挺多的。您们现在成功组织起这个repo他们可不愿意看到，请保护好自己。 @zhaobenx

**Comment by vzxxbacq** [comment]
@sikaozhe1997 希望能转达给所有Collaborator，望大家平安.....

**Comment by IWSR** [comment]
想想当年shadowsocks的作者 @Clowwindy 被警察请去喝茶，回来后就把项目删了。@zhaobenx @SniperChen 两位请注意人身安全。

**Comment by vzxxbacq** [comment]
@IWSR 他们两个已经改了23333，不过还我看到一些其他高校的学生挂着详细的信息和Collaborator头衔，有些担心他们。

**Comment by zhaobenx** [comment]
谢谢各位关心呀！这点小事情是没问题的

**Comment by IWSR** [comment]
@vzxxbacq 改下标题吧，感觉不醒目，建议所有帐号中带有真实身份的贡献者们注意隐藏真实信息。这个issue很重要！

**Comment by lfq7413** [comment]
各位，勇敢点好不好？不要怕死，公开自己的信息，这样我还能佩服你们。
GitHub 因为你们被封了，影响了多少人？
别一副 “我不管，影响多少人无所谓，反正别影响我，我怕死” 的嘴脸好不好？

**Comment by tubu-long** [comment]
@lfq7413 不是应该保护同志么？  斯德哥尔摩症？

**Comment by boogoobird** [comment]
敢做敢当才是男儿本色

**Comment by boogoobird** [comment]
20年前的事才叫轰轰烈烈,你们太娇气了,希望你们和我不是同年代的人

**Comment by vzxxbacq** [comment]
- 一切如上言论希望大家视为有关部门钓鱼

- 各位讨论合理性请前往#530（无关信息全部Report）

- 如果看到那位Collaborator信息太全面请来这个issue @ ta。

**Comment by autodataxx** [comment]
@SniperChen your personal page "SniperChen.github.io" has the link of your LinkedIn profile which contains your working and education info. beware of the dog

**Comment by SniperChen** [comment]
感谢各位，我就是负责维护一下issues，也呼吁北大勇敢一点。爱国心，我不比谁差。❤️

**Comment by gaocegege** [comment]
先 close 了，有问题可以继续反馈，谢谢你的提醒。
