### ISSUE TITLE
[Bugfix] Wikilink on 沈阳事件.md

### ISSUE THREAD

**Issue by juliosueiras** [sikaozhe1997/Xin-Yue#557]
English:
it look like the file 沈阳事件.md is markdown version of the wikipedia article, so the the link retain with "wikilink", is this something that the site generator acknowledge?

Chinese:
在沈阳事件.md文件里有很多“wikilink“的地址（好像是markdown版本的维基文章），这个wikilink在自动网页搭建器能用吗？

**Comment by vzxxbacq** [comment]
It seems we already have link-checker. Should we close this Issue?
@juliosueiras
