### ISSUE TITLE
[Discussion]Administrator warning forced shutdown

### ISSUE THREAD

**Issue by 80k** [sikaozhe1997/Xin-Yue#558]
#

**Comment by MAYDAYHAO** [comment]
炒作能让人正视一下在光鲜外表下的脏事也未尝不可吧。总比有些职业喷子眼见洗不白就丧心病狂喷人强。点名1993。

**Comment by wql7013** [comment]
作为女生，可以以志愿者的身份进行青少年性教育，我觉得这种勇气可嘉。
从多个渠道了解一下岳昕就知道了，可以看看她以前在知乎的回答。

**Comment by YuzhouZhang** [comment]
@wql7013 给个她的知乎链接谢谢

**Comment by vzxxbacq** [comment]
@YuzhouZhang https://www.zhihu.com/people/pinkguor/activities 更新停在了四天前，很悲伤。
