### ISSUE TITLE
[Resource] 事件发展的时间线--1月8日至4月24日，完结，缺20日下午，21、22日。

### ISSUE THREAD

**Issue by zhangn1985** [sikaozhe1997/Xin-Yue#562]
日期|参与者|事件|相关人的评价|来源
------|---------|-----|------------------|---
1月8日|顾华盈+14名联署| 联名信 北京大学学生实名要求建立校园性骚扰防治机制的公开信 和 《校园性骚扰防治规范建议稿|转自： PKU的北门静悄悄 公众号|[联名信 北京大学学生实名要求建立校园性骚扰防治机制的公开信](http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed4fece763105392230e54f72867818b46239cc802d4384c413037bee43a715042889422301cad325be1ad65317d1765eadb9e875dabbd85592d9f5047676cf25612a20edfcc5154b137912afed918f0cd8725e4ddc5a3af&p=b434d215d9c043ad0db3c7710f0592&newp=81759a46d4c117e91eb1c7710f0a94231610db2151d7d5106b82c825d7331b001c3bbfb423251601d3c67e6606ad485fe0f73c733d0523a3dda5c91d9fb4c57479de61722c&user=baidu&fm=sc&query=%D4%C0%EA%BF+%B5%CB%D3%EE%EA%BB&qid=f4ece31000004f67&p1=4)
清明|李悠悠等高岩同学20多人|公开举报，称沈阳性侵自己同学高岩并致其自杀身亡，此事立即引发广泛关注。||[声援勇士岳昕：两个北大之间的斗争](http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed4fece763105392230e54f7357b9c834968d4e419ce3b4c413037bfa666784d41c4c50a6d04b8492ae9f23676370037b7edcb9f4aaae1d477719c6269304a895664d50edec95152b237e02efeaf68f0caf725e2dec5d2af4325cb44720d9787f84d7064&p=80769a47cc9609ff57ea9366425c&newp=9874de0385cc43f108e29379534492695912c10e3ad6c44324b9d71fd325001c1b69e3b823281603d4c6786c15e9241dbdb239256b557e&user=baidu&fm=sc&query=%D4%C0%EA%BF+%B5%CB%D3%EE%EA%BB&qid=f4ece31000004f67&p1=2)  ;    [沈阳事件](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E6%B2%88%E9%98%B3%E4%BA%8B%E4%BB%B6.md) ;    [北大邓宇昊同学申请校方公开“沈阳事件”处理文件被约谈全貌](https://www.00ke.net/v/view.php?vid=oMnu8yKPa2Zzx1wU5Oye8MAj)
4月5日下午|沈阳|通过短信回覆新京报记者，称“当时北大中文系党委和北京海淀警方均有调查和明确结论，根本不存在上述事实”，“上述‘指责’实均为恶意诽谤”，“为此我将保留控告的权利”。在电话采访中，沈阳表示与高岩没发生过性关系，也没谈过恋爱||[沈阳事件](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E6%B2%88%E9%98%B3%E4%BA%8B%E4%BB%B6.md)
4月6日|北京大学、南京大学|北京大学的说明称，经查阅相关材料，二十年前，即1998年3月，北京市公安局西城分局对这一事件作出事实认定，给出调查结果，1998年7月，北京大学对沈阳做出了行政处分；南京大学回应称正在进行研判、密切关注事件进展|当年参与处分的北京大学中文系主任费振刚，接受采访时表示，“我是一个老人，对这个事情有我自己的判断。当年，他是个年轻人，但是从师德讲，这个年轻老师是有问题的。”|同上
4月7日|南京大学文学院|根据说明，沈阳处于等待核查和调查阶段，在此阶段，停止沈阳从事南京大学文学院的教学工作；另外，沈阳在调动工作中隐瞒事实，相关议论已经严重影响南京大学文学院正常的教学科研秩序和学术声誉，为此南京大学决定，建议沈阳辞去教职|网络消息则称，南京大学本想“维稳”，杜绝负面影响，而文学院院长徐兴无和文学院领导班子以先斩后奏的方式通过建议沈阳辞职的决议。之后，上海师范大学也于同日发表声明，决定即日起终止2017年7月与沈阳签订的校外兼职教师聘任协议|同上
4月7日|邓宇昊等|邓同学申请信息公开，并将这一申请提前发到网络上，引起广泛关注。这一行为是否合理？C同学回答是：行为合理，应该得到支持。因为：如果单独一个人悄悄提交了信息公开申请，得到回复的可能性很低。晚21时许，数院辅导员刘老师在朋友圈看到了邓同学发的文章《沈某事件,周一上午9：00我将前往校办申请信息公开》， 21:58邓宇昊回复消息，刘老师表示希望邓宇昊同学到办公室聊聊，邓宇昊同学同意。22:30，邓宇昊同学到了学院，学院辅导员刘老师、董老师和邓同学在学院进行谈话，学院邀请了熟悉网络信息相关工作的张老师（也是学校辅导员）一起参加 ，邓同学表示同意联系公众号删除该文，00:06公众号回复消息：“我都睡了，考虑一下删不删吧，明天再说”，邓同学再次表达作为原作者要求删帖愿望，虽然运营者在线并管理该文的回复，但该文一直未撤下。1:10许，10余位关心邓同学情况的同学，找到谈话教室了解情况，约1:15，燕园派出所民警到达谈话现场，称接到报警说邓同学被限制人身自由，警方前来核实情况后离开。在警方离开后老师们建议时间太晚，请同学们先回宿舍休息，但到场的同学们坚持继续沟通，持续到约3:30结束。老师们事后才得知BBS上发布了关于邓同学22:30分被辅导员约谈未归的帖子，引起关注|。|[声援勇士岳昕：两个北大之间的斗争](http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed4fece763105392230e54f7357b9c834968d4e419ce3b4c413037bfa666784d41c4c50a6d04b8492ae9f23676370037b7edcb9f4aaae1d477719c6269304a895664d50edec95152b237e02efeaf68f0caf725e2dec5d2af4325cb44720d9787f84d7064&p=80769a47cc9609ff57ea9366425c&newp=9874de0385cc43f108e29379534492695912c10e3ad6c44324b9d71fd325001c1b69e3b823281603d4c6786c15e9241dbdb239256b557e&user=baidu&fm=sc&query=%D4%C0%EA%BF+%B5%CB%D3%EE%EA%BB&qid=f4ece31000004f67&p1=2); [北大邓宇昊同学申请校方公开“沈阳事件”处理文件被约谈全貌](https://www.00ke.net/v/view.php?vid=oMnu8yKPa2Zzx1wU5Oye8MAj)
4月8日|北京大学|教师职业道德和纪律委员会召开会议，出示了当年对沈阳予以警告处分的决定，文件称，1997年1月高岩到沈阳住处，要求与他确立恋爱关系，沈阳然后与高岩拥抱、接吻，对高岩说“那你就算是我女朋友吧”，数月后又宣布与高岩终止交往，高岩于次年自杀|南京大学文学院前任院长丁帆接受采访表示：沈阳在自传中提及的关于调入南大的过程有多处美化，是“自我标榜”，并不存在“撤下其他人”优先让沈阳申报长江学者一说，也不存在以申报长江学者“挖角”一事|[沈阳事件](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E6%B2%88%E9%98%B3%E4%BA%8B%E4%BB%B6.md)
4月9日上午10点整|十名同学（实际到场八名）包含岳昕，张震林|向北京大学提交关于1998年7月前后讨论沈阳‘师德’问题的系列会议记录的信息公开申请| |[申请公开信息事件经过（量产基地）](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E7%94%B3%E8%AF%B7%E5%85%AC%E5%BC%80%E4%BF%A1%E6%81%AF%E4%BA%8B%E4%BB%B6%E7%BB%8F%E8%BF%87%EF%BC%88%E9%87%8F%E4%BA%A7%E5%9F%BA%E5%9C%B0%EF%BC%89.md)
4月9日|张震林|院系辅导员曾给他打电话，表示学校学工部曾找自己了解学生情况，被她“挡回去了”。辅导员随后联系了张震林的同学|| 同上
4月10日|张震林|同学转告张震林，称提请信息公开一事背后或有境外势力支持，让他谨言慎行|张震林“感到害怕”，于是主动联系辅导员|同上
4月10日|岳昕|学工老师不断给她打电话，她因忙于毕业论文的缘故未能接听，回复短信表示已经收到消息|| 同上
月11上午9点|张震林和辅导员|张震林和辅导员见面谈话。辅导员提出了3个指控：有组织，有境外势力，张震林联系了境外势力，张震林对外媒不知情，自认不活跃。但辅导员对此不信任，因为他“说话吞吐且前后不一”“当提到有外媒时表现得很镇定，像是早已经知道了一样”，张震林录了音|岳昕： 不是统一着装，确实有境外媒体。|同上
4月11日晚上10点|岳昕、学工老师|约谈，得知张震林被约谈，接到母亲关于此事的电话。她开始同朋友商量“最坏的可能性与对策”||同上
4月12日|张震林和辅导员|微信联系，具体未知 ||同上
4月13日|张震林父亲和辅导员|辅导员给他的父亲打去电话，告知相关情况并希望他来学校。当晚八点左右，父亲到达张震林宿舍楼下，但张震林已因害怕辅导员来宿舍找自己的缘故，选择去北京八中附近的一家宾馆住宿。父亲和辅导员及张震林所在院系的党委副书记老师见面。||同上
4月14日|张震林和张震林父亲|父亲不信指控，试图调和，失败，张震林认为父亲怕了||同上
4月14日|公众号：深约一丈|发表《沈阳事件近期情况汇总》，被禁言7天||同上
4月15日|张震林和熟识的同学|聊起此事，向公众号“深约一丈”讲述了这件事||同上
4月15日下午|岳昕|社会学系的一位老师发来邀请，希望她能列席参与次日的“反性骚扰暂行规定学生意见征集会”，晚上10点，她收到了具体的时间地点信息。||同上
4月16日|学生和老师，包含岳昕及张震林|反性骚扰暂行规定学生意见征集会，岳昕及张震林作为列席成员，提出许多问题，主持人不希望会议内容外泄||同上
4月17日下午|校领导等|学校召开第935次校长办公会议，专题研究反性骚扰暂行规定。||同上
4月17日晚上|张震林|在未名BBS“三角地”板块和自己的公众号“境外事例”上发表了会议内容记录，并在未名BBS“校长信箱”板块提出自己的8条建议，校方回复说：“同学，你好！学校专家组会对你的意见进行研究， 感谢你的建议。”北京大学学生会常代会回复了BBS的会议内容记录帖子：“有网友未经会议主办方确认，自行在互联网上发布本次会议‘记录整理’，我们对此表示遗憾。”||同上
4月19日|老师、张震林|询问BBS的帖子是否由他发布。张震林认为他“管不着”，但又不想撒谎，于是拒绝回答||同上
4月19日下午16时44分|岳昕和校工老师|她们在未名湖边聊了四个多小时。老师不断劝说她考虑家人的感受，“不必走到申请信息公开的最后一步”“反正最后也会告诉你”。岳昕暂时没有回复她。||同上
4月20日|提交申请的同学们，及其余十五名通过邮件申请信息公开的同学均|收到了来自北京大学信息公开办公室的答复。岳昕和另一同学保留了纸质答复函。||同上
4月20日|老师、张震林|约谈，随后收到了11天前，关于信息公开申请的回复函。院长、党委书记和副书记及其他学工老师均在场。张震林认为，整个学院“精锐部队”全部出动的阵仗，可能会让很多同学觉得“压力非常大”。||同上
4月20日5时33分|岳昕|向老师发信息，表示仍希望走完信息公开的整个流程。收到短信回复：“你真的想清楚了吗？还是再想想吧。”||同上
4月22日晚上十一点左右|岳昕|辅导员突然给我打来电话，但因为时间已晚，我并没有接到。凌晨一点，辅导员和母亲突然来到我的宿舍，强行将我叫醒，要求我删除手机、电脑中所有与信息公开事件相关的资料，并于天亮后到学工老师处作出书面保证不再介入此事。有同楼层的同学可以作证。随后，我被家长带回家中，目前无法返校。 我和母亲都彻夜未眠。学校在联系母亲时歪曲事实，导致母亲受到过度惊吓、情绪崩溃。||[岳昕：致北大师生与北大外国语学院的一封公开信](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E5%B2%B3%E6%98%95%EF%BC%9A%E8%87%B4%E5%8C%97%E4%BA%AC%E5%A4%A7%E5%AD%A6%E5%B8%88%E7%94%9F%E5%92%8C%E5%8C%97%E5%A4%A7%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%AD%A6%E9%99%A2%E7%9A%84%E4%B8%80%E5%B0%81%E5%85%AC%E5%BC%80%E4%BF%A1.md)
4月23日下午12时57分|公众号“深约一丈”|刊载岳昕的公开信；13时18分，公众号显示“此内容因违规无法查看”。||[申请公开信息事件经过（量产基地）](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E7%94%B3%E8%AF%B7%E5%85%AC%E5%BC%80%E4%BF%A1%E6%81%AF%E4%BA%8B%E4%BB%B6%E7%BB%8F%E8%BF%87%EF%BC%88%E9%87%8F%E4%BA%A7%E5%9F%BA%E5%9C%B0%EF%BC%89.md)
4月23日|北京大学外国语学院|回应岳昕的公开信|| [外国语学院-情况说明](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%AD%A6%E9%99%A2-%E6%83%85%E5%86%B5%E8%AF%B4%E6%98%8E.md)
4月23日晚|匿名|匿名者声援岳昕字报||[匿名者声援岳昕字报](https://github.com/sikaozhe1997/Xin-Yue/blob/master/23%E6%97%A5%E6%99%9A%E5%8C%BF%E5%90%8D%E8%80%85%E5%A3%B0%E6%8F%B4%E5%B2%B3%E6%98%95%E5%AD%97%E6%8A%A5.md)
04月24日| 郑厚哲 清律| 发表《让高校信息公开与学生管理回归法治轨道》||[让高校信息公开与学生管理回归法治轨道](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E8%AE%A9%E9%AB%98%E6%A0%A1%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%E4%B8%8E%E5%AD%A6%E7%94%9F%E7%AE%A1%E7%90%86%E5%9B%9E%E5%BD%92%E6%B3%95%E6%B2%BB%E8%BD%A8%E9%81%93.md)
04月24日| 雷雨 人民日报评论| 发表：《如何聆听“年轻的声音”？》||[《如何聆听“年轻的声音”？》](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E4%BA%BA%E6%B0%91%E6%97%A5%E6%8A%A5%E8%AF%84%E8%AE%BA%EF%BC%9A%E5%A6%82%E4%BD%95%E8%81%86%E5%90%AC%E2%80%9C%E5%B9%B4%E8%BD%BB%E7%9A%84%E5%A3%B0%E9%9F%B3%E2%80%9D%EF%BC%9F.md)

**Comment by THUcqb** [comment]
- 建议附上各时间点的参考资料。如果没有请注明

**Comment by LorrrTor** [comment]
反对。我认为正确的时间线应该是只有文章及文章发表时间的时间线。

**Comment by shanezhiu** [comment]
需要附带来源。

**Comment by gaocegege** [comment]
I do not think we should maintain such a timeline since some of them are just articles and the date when it is published does not matter.

**Comment by gaocegege** [comment]
I am closing the issue, again. But feel free to maintain the timeline here if you like. :ok_hand:
