### ISSUE TITLE
雪崩之下每一片雪花都认为自己是无辜的，然而每一片雪花都有责任。

### ISSUE THREAD

**Issue by ygren** [sikaozhe1997/Xin-Yue#564]
关于是否能不能使用Github的问题，很多程序员的表现一方面自视清高，另一方面担心被墙，我表示一方面理解技术需要独立性，如果大家有正常的途径怎么可能会来这样一个社区呢？套用科学是无国界的，单科学家是有祖国的。技术技术是无国界的，但工程师是有信仰、有态度的。互联网科技发展到现在，网络上想屏蔽谁就屏蔽谁，没有程序员的技术贡献么？我相信这并不是广大程序员愿意看到的，但事实上这就是广大的工程师的付出才出现了今天这样一个互联网世界。我们当然有责任，有属于自己的态度，而不是自视清高，Github被墙了又会怎样，只会说更进一步推进社会矛盾罢了，到时候自然还会有相应的技术产生来推进互联网技术的进步。
今日的你我，就是今日之中国，很多人以为自己束之高阁，就会等着社会变好。怎么可能呢？你不去做，我不去做，还会有人去做么？在国内能够在211 985 毕业的，能够读完硕士的，能够读完博士的，这一部分人，永远都属于少数人。我们的态度并不一定是社会的主流，但一定要相信自己是时代的先锋。这一群人发出自己的声音，怎么会反对。另我想说的是国内顶尖公司的程序员都公司常被翻墙的梯子的，那么宣扬技术独立性的总不会是多少大牛了。对于他们来说github墙与不墙，没什么影响，我身边进BAT这些公司的朋友整体都还是支持的。
社会问题和技术相结合，是能够促进技术的进步的，每一次技术的进步都是存在一定过的刚需的，不过在目前看来很多人觉得表达自己的权利诉求不是刚需，互联网的很多技术都还是靠色情需求驱动的，这里说这个总感觉哪里不对。
我是支持岳昕的，她代表的是我们这一代年轻人的勇气，我们更关注社会问题，更是清晰认识到这个社会的问题存在。而既得利益的官僚们，总是讳疾忌医， 不到崩溃的最后一刻，是不会妥协的，好像在中国任何问题都是不破不立一样。然而我们只是想一点点的把这个世界变好，每个人各司其职，做自己该做的事情，而不是尸位素餐，为什么区别就这么大呢？百亿公司跨省抓人近在眼前，千亿公司国会道歉也在眼前，难道我们就真的比别人差？正常的程序，表达自己正常的诉求，这有问题？利用技术和自己的影响力全网封杀，这也是北大对一个普通人正常诉求的回答？什么时候我们才能学会好好去解决问题，而不是解决提出问题的人？不是我们总是不接受，但是各打五十大板，弱化矛盾真的不是一个好策略。一个人如果生病了，当然是越早治疗越好，难道一直吃治表的缓解药，对根本病因不管不顾，等最后绝症了救不了？我相信我们都不愿意自己的国家这样。
利用技术无限制的屏蔽用户内容，限制舆论自由，这个我真的不知道有些官僚是真的爱党爱国，还是打着爱党爱国的旗帜，行着什么样的勾当呢？毛泽东同志说过“如果这样的共产党不是为人民服务，而是挂着羊头卖狗肉，那么人民就要自发组织起来，以武装的革命坚决打倒假共产党！推翻其在中国的罪恶统治！并全部、干净、彻底地消灭一切附着在这个奸伪集团上的官僚买办汉奸势力！”  最后科学技术虽然没有国界，但是工程师是有信仰，有态度的。我信仰的是共产主义，不是哪些官僚，哪一个个人的共产主义；我热爱的是我的祖国，不是哪一个小群体的祖国，而是代表最广大工人农民群众利益的祖国。
综上，如今的互联网环境，如果还说什么跟技术无关，不是蠢就是坏，大数据杀熟、定向屏蔽，哪一个不会技术干的？科学技术是无罪的，关键看掌握在谁的手中。
今日的你我，就是今日之中国。如果年轻人没有热血，没有担当，这一代人的焦虑将会一直存在。

**Comment by YgRen** [comment]
收到。。
