### ISSUE TITLE
[Discussion]如何用Github做信息整理的一点思考

### ISSUE THREAD

**Issue by qfeudal** [sikaozhe1997/Xin-Yue#568]
目前我们用Github主要是公示，并用它的pr功能做公共编辑。但这个功能同其他维基类站点的区别是什么？更具体的说，相比相关事件的维百页面，这个仓库能提供多少额外的价值？

放远来说，面对近来网络上的公共事件，始终有两种声音：一种是争，一种是等。前者不断争取、挖掘信息，后者等待权威部门的答复。反对前者的人，会说那是捕风捉影、传播谣言，反对后者的，则压根就不相信权威部门（至少不相信他们会主动公开真相）。在这种极端对立的情况下，共识成为奢侈，真相更是遥远。而维基类站点的前提就是共识，如果用维基的公共编辑模式，最终会陷入不断“反转”“实锤”的编辑战、口水战。

因此我想，是否可以用Git的版本控制功能，为不同视角的文件（如公安、学校、学生）建立不同的branch，然后在不同branch中各自维护一个时间线文件，用一定标准的格式（如每行为，某年某月某时某事发生）记录该视角下整理得出的“真相”。最终，当信息达到饱和，各个branch的时间线文件收敛到一致，就可以进行merge，得到相对全面、可信的真相。

当然，上述是一个高度简化的模型，需要实践尝试，但希望能抛砖引玉，提供一些思考，帮助大家更好的使用Github来整理公共事件的相关资料，以求真实。

**Comment by longqiany** [comment]
暂时没有必要创建分支吧，直接提pr。
2、如果是小范围主题讨论，trello可以试一下。

**Comment by lazycatzh** [comment]
开了分支估计永远merge不到一起了，冲突太大，解决不了

**Comment by findNextStep** [comment]
在我看来产生新的branch并不能解决您说的问题，反倒有加大事件整理难度的风险

倒不如直接在不同的文件夹中编写，反正不同视角结果多半不同

**Comment by mrg123** [comment]
我也一直有这样的想法

**Comment by wql7013** [comment]
基于Git的web信息库应该推广开来，有朝一日希望也能推广到其他的学术领域，实现“学术开源”，摆脱出版社知识垄断。

**Comment by suruoxi** [comment]
这个repo里有很多人，明显是最近才加入github的，并不都是开发者。
branch、git对非开发者成本太高了。 
现在这样也好。

**Comment by boogoobird** [comment]
@suruoxi@tubu-long@qfeudal 果然都是学生.......这个平台就是给开发人员用的

**Comment by boogoobird** [comment]
Issues是提需求的, Pull requests是合并代码请求的, 我们平常讨论问题用的gitter,希望这次事件能让你们喜欢上github  另外像这种大段的说明都是用github Page处理的,有的项目会把项目说明部署到自己的服务器

**Comment by vzxxbacq** [comment]
就现在的情况来说，个人认为，添加branch不如优化文件的存放结构。

**Comment by leosongwei** [comment]
Git的最大好处就在于，数据在每个人的电脑里面，可以严防原上传者由于各方面的压力而执行`git push --force`

**Comment by gaocegege** [comment]
讨论下来的结果是目前不需要这么复杂的模型，因此先 close 了，不过欢迎继续讨论。

**Comment by lzrzwz** [comment]
搞不懂，我就是来围观的。
