### ISSUE TITLE
[Discussion]关于"此类问题是否会导致GitHub被墙"的问题

### ISSUE THREAD

**Issue by niminga** [sikaozhe1997/Xin-Yue#570]
**事实证明，GitHub会针对不同地区对某些repo进行屏蔽。**

以这个repo为例：[programthink/zhao](https://github.com/programthink/zhao/)，使用同一个用户ID、不同的IP进行访问该GitHub网址，响应的页面不同：

* 这是使用中国大陆IP访问后的截图：
![snipaste_2018-04-25_16-40-18](https://user-images.githubusercontent.com/38719333/39236917-a730fc1a-48ac-11e8-8ef3-a49917198af3.png)

* 这是使用美国IP访问后的截图：
![snipaste_2018-04-25_16-41-00](https://user-images.githubusercontent.com/38719333/39237026-f09c1d30-48ac-11e8-97fc-537c54f26ba5.png)

> 开这个Issue的目的只是希望各位不要再争执**是否应该在GitHub上讨论这类问题**，因为有关于这种话题的讨论很早就有了，可以参考下[programthink/zhao](https://github.com/programthink/zhao/)的Issue。

> 希望大家回归事件的本身，不要将话题带偏。

**Comment by UpJunior** [comment]
支持，有些喊着要敲代码的，自己也没几个高star的项目，只是怕自己没地方抄代码而已。有高star的说这话我不反驳，但没有的还是请不要再秀逗。谢谢。

**Comment by gaocegege** [comment]
Ref #530

**Comment by xinmu99** [comment]
> ”GitHub会针对不同地区对某些repo进行屏蔽“

programthink 那里是政府和github交涉，并且是给出了诽谤的理由。
这个repo 我看拿不出理由。
