### ISSUE TITLE
怎么越看越感觉像是法轮功之类的了？连个图都没有，文字能说明一切？  眼见为实吧还是

### ISSUE THREAD

**Issue by xx7777** [sikaozhe1997/Xin-Yue#574]

**Comment by xx7777** [comment]
这个图略有深意![image](https://user-images.githubusercontent.com/38721431/39240349-1924251e-48b6-11e8-9338-c1a3ea478d24.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39241199-a14f359e-48b8-11e8-9a5b-9476355a3883.png)
