### ISSUE TITLE
[Discussion] 如何保证信息来源真实性

### ISSUE THREAD

**Issue by Anon02** [sikaozhe1997/Xin-Yue#578]
我想知道，既然这是一个学生和学校的矛盾，那么应该由本校学生来进行处理吧？
北大学生没有向各位提出援助请求，反而为什么Contributors中似乎没有北大学生呢？
为什么要由清华学生，复旦学生和其他已经步入社会的人士来控制发生在北大的事件的信息来源呢？
这些信息来源的可靠性是由谁保证的？

replace #574.

**Comment by longqiany** [comment]
一个历史事件
学生的诉求是公开合法合理的文件内容
所有信息公开在github上面，你有不同消息来源可以提pr
合理合法的讨论，言论自由欢迎任何人来参与

**Comment by Anon02** [comment]
@longqiany 我不关心诉求的内容，我只关心事件经过是否真实，有没有证据和目击证人。如果有，请详细举出。如果没有，我就不得不怀疑这个repo的动机到底是什么了

**Comment by aminic** [comment]
一个重要事件，肯定会引发各方震动的，而不是在于北大学生的多寡。

**Comment by xx7777** [comment]
同问，我也很好奇这个问题。 #574

**Comment by Anon02** [comment]
@aminic 但是这个事件是北大学生和北大校方的矛盾，理应由北大学生**亲自**解决。何况非北大学生掌握的只是三手消息源，可信度无法保证。

**请正面回答我的问题。**

**Comment by Anon02** [comment]
根据你们的回复速度，我可以认为你们可以在接下来的10分钟内给出**正面**答复。

有，还是没有，很简单。有，明示。没有，就有传谣的_嫌疑_。

**Comment by vzxxbacq** [comment]
- 这是大家的权力，北大是副部级行政单位。而且校方各个平台把控舆论，是校领导个人的力量吗？

     >中华人民共和国公民对于任何国家机关和国家工作人员，有提出批评和建议的权利；对于任何国家机关和国家工作人员的违法失职行为，有向有关国家机关提出申诉、控告或者检举的权利，但是不得捏造或者歪曲事实进行诬告陷害。

- 很多contributor并没有添加内容，只是更改排版，引用权威信息或校内信息

- repo现在收集的信息都是曾经公开的，而且维护的同学们都没有偏袒。这里既有人民日报的信息，也有未名BBS上的信息。相信与否我个人觉得是你自己的事情。

**Comment by yyong119** [comment]
有北大认识的同学，人家怕被刚，让其他学校的高中同学发貌似有问题哦？（人家至少不像你那样挂个小号在这里唧唧歪歪

**Comment by Anon02** [comment]
@vzxxbacq 

1. 我认为这种行为存在干涉北大内部事务的嫌疑。
2. 那么也就是没有实际证据了？那么如果这个repo连给出令人相信的证据都做不到，我不知道这个repo是不是辜负了所有期待着真相的大家。北大BBS上的内容一直都存在，都有人转发，我不认为这个repo有存在的必要。

**Comment by laazy** [comment]
岳同学已经请求社会的帮助了，那么现在社会就在帮助他。
还有，你这个说法本身也不对，为什么北大学生和北大校方的矛盾只能由双方来解决，其他人无法插手？你是认为北大对其所属学生具有完全执法权吗？或者北大相关人员能够完全决定其校内所有事务吗？那是不是首先应该批判一下人民日报的相关报道？
最后，我觉得你所提的三个问题没有任何意义，或者说答案显而易见，仅有最后一个问题可以称得上是值得回答与讨论。而我给出的答案就是，没有人能提供完全客观的信息来源，因此，我们只是保证所有的信息都在此处。

**Comment by Anon02** [comment]
@yyong119 人身攻击是违反GitHub ToS的行为，我有充足的理由举报你，请您好自为之。

**Comment by wql7013** [comment]
我建议项目贡献者不要透露个人信息。
因为这件事不是个例，所有能引起广泛关注，希望给其他事件有一个指导性的处理方式。

**Comment by Anon02** [comment]
@laazy 

好，既然您认为人民日报的相关报道是可信的，**我相信您也明白人民日报的说法本质上就是该事件属于高校的内部矛盾**。
您的话存在逻辑上的矛盾，我无法回答您。

**Comment by vzxxbacq** [comment]
- 她最后一次在社交媒体上传出的消息就是向校友、社会寻求帮助。虽然我不是校友，但我是社会的渺小一员

- 这个repo本来就不是证据，在我看来它是一个记录。里面有岳同学学院的发言，有辅导员的发言，有这位同学自己的发言。这个repo只是在记录着一切罢了，Owner与Collaborator都没有在仓库添加任何与自己编造的言论和情绪。假如Owner和Collaborator夹带自己的私货，也就不会有这么多人帮助他们了，当然，我也不会。

**Comment by aminic** [comment]
@aminic 如果北大学生能亲自解决会弄到这里么？如果校方起先能解决问题的诚意，会弄到这里么？如果官方有解决问题的诚意而不是遮遮盖盖，会在墙内所有可访问本项目地址的提示全部标识禁掉？如果那么多问题可以在公开媒体播发讨论，会有那么多不幸的事情发生么？会有谣传继续散播么？再扩大一点说，北京上访的人群那么多，只有这样才能充会体现社会主义制度的优越性？
哦，差点忘了，墙内所有的媒体都是没有相对独立性的，随时都能变成党的喉舌，时刻霸占舆论话语权。
那怕，到了墙外也还要霸占话语权。人报是媒体权威，新华社是媒体权威，那一个党政媒体不是媒体权威？
追根溯源，遮遮盖盖这么多年，官僚们通常的习性如此，都是官僚权力没有公开有效的监督，权力不是直接来源于公民，红色的顶子来源于上级委派，唯上，所以，上边的老爷们，如果要点脸的话，才有可能比较合适正确的处理相关事件相关人等。

**Comment by Anon02** [comment]
@aminic 

重申一遍，**请正面回答我的问题**，目击者证据是有还是没有，来自何方。

另外，请不要使用带有偏见的含有政见的语言回复。这个repo的作者是清华大学学生，与北京大学无关。

**请您不要擅自代表北大学生。**

**Comment by RumbleJack** [comment]
fork一下表示支持 = =。

**Comment by Anon02** [comment]
@aminic

每个人都能正常表达他的所思所想，就像独人13一样。

**Comment by boogoobird** [comment]
北大很叼吗,清华复旦又如何,在我眼里都一样.不要以为上个好学校就自以为了不起.你们并没有比别人了不起多少,除了愤青,还是愤青.北大清华就应该关注,其他的学校的就不是事吗?不要拿学校压人.

**Comment by xx7777** [comment]
越来越精彩了  让它走出中国的大门，迈向世界吧

**Comment by Anon02** [comment]
@boogoobird 

我本人不是愤青，北大内部也有很多不是愤青的人，北大内部也有很多愤青。

请您回避这个问题，在北大学生未集体请求外界援助之前，这是一个内部事务。

**Comment by wql7013** [comment]
@Anon02 我觉得这不只是学校内部的事，就像韩春雨事件一样，不只是河北科技大学的事。

**Comment by laazy** [comment]
@Anon02  请不要预设立场，我只是指出人民日报作为非北大相关人员评论了该事件，而基于一般的常识判断，其对该事件的评论是合理的，即其评论的行为并非不被允许，所以归谬了你的说法而已。

**Comment by tubu-long** [comment]
请移步 https://zh.wikipedia.org/wiki/%E6%B2%88%E9%98%B3%E4%BA%8B%E4%BB%B6   
此件事是因为ME TOO运动而起，大家的诉求是公开合理合法的文件
你所说的目击者跟此repo的合理性并没有什么必然关系。

**Comment by xx7777** [comment]
但是目前为止并没有确凿的证据摆出来不是么？这样制造舆论真的好么？

**Comment by laazy** [comment]
另外说一句，如果你觉得这个repo不应该存在，那么请联系相关作者删除。

**Comment by boogoobird** [comment]
@Anon02 为人师表敢作恶,就应该收到严惩.既然这事已经公开,作恶者就应该接受审判.

**Comment by ZeroneCat** [comment]
1. 非北大同学也可以参与讨论、维护repo；此外，北大作为教育部直属高校，中国公民有权对其进行监督。

2. repo只存储相关信息（包括直接来源于当事人的信息与第三方报道评论），来源不受控制，可靠性、可信性自行判断；内容在此期被修改可自行查看历史版本。

3. 非亲历者的任何人都不能提供非「三手消息源」，不必要强调北大学生。

**Comment by Anon02** [comment]
@lazzy 

好的。如果有必要，我会联系这位同学。由于回复过多，我将稍后回答您的疑问。

**Comment by moonwater** [comment]
楼主今天刚注册就来给人下套了

**Comment by Anon02** [comment]
@tubu-long  @boogoobird 

沈阳事件仅作为此事件的直接原因，此事件的诉求并非沈阳事件的诉求，沈阳事件理当联系南京大学处理。

**Comment by Anon02** [comment]
@moonwater

我保留一切report您的权利。您的人身攻击行为已经违反GitHub ToS。

**Comment by boogoobird** [comment]
@北大学霸 能顺带脚的提一下"教育改革"的事吗?

**Comment by vzxxbacq** [comment]
- 在我看来岳同学代表不了北大，你也代表不了，这是她个人的求助

- 北大不是一个独立的政治实体，没有外交自主权233333，不需要你们来请求我们的帮助

- 尽管我不是Owner和Collaborator，但我同意除了亲历者没有资格添加内容。

说一下我对这个repo的看法吧，我希望这个repo能成为这个事件的记录，至少，不应该被遗忘。就像写史书一样，默默记录历史。你能说史书全是真的吗，全是证据吗？我们只需要把整个事件，关键的发言记录下来就好。相信您作为北大的同学能明白这件事的意义。

**Comment by aminic** [comment]
@Anon02 即然是在公开网络上，除非项目负责人或者社区管理者，以及法定执行人，没有任何人应该有能力对别人的言论有管制能力。
言论的自由表达正在墙内所欠缺的，在墙外还自我设限么？我觉得还是站着说话硬气。
@Anon02 应该在墙内新华福人报以及央视发起这样的问话。

**Comment by UpJunior** [comment]
@Anon02 看了你的言论，我表示理解。作为非北大学生，在看了rep上的东西之后觉得确实没有提供你提的**所谓证据**，但是校方对于学生和外界的质疑也并没有做出回应反驳，以及给出证据证据支持此rep有问题属于造谣。所以，你有表达的你观点的权利，他们也有发表言论的权利。
**因为无论是支持还是反对都要有证据，你所质疑的确实属实，对方无法提供证实rep真实性的证据，但你或者校方也并未给出证明对方rep有问题的证据！是吧?**
**所以，最后支持或者反对的证据没有浮出水面之前，此事就是可以讨论的。欢迎反驳！**

**Comment by vzxxbacq** [comment]
联系Owner不必了吧，Owner很明显在隐藏自己的身份，为什么要让你联系呢？古代焚书还要找到书生家里去呢，哪有书生捧着书让你烧的道理。哈哈哈。

**Comment by boogoobird** [comment]
我到是觉得你们这些学霸,将来可以从政,将来好好施展下你们现在的报复.

**Comment by Anon02** [comment]
@boogoobird

抱歉，您所提出的事情和本事件无关。

**Comment by boogoobird** [comment]
匿名很重要,要不然会查水表的,让爆ID的,都是警察派来的卧底.

**Comment by Anon02** [comment]
@bbtmcat

您问到关键点上了。待我详细说明。

**Comment by blacklisten** [comment]
@aminic 请不要带上你们这两个字，我只是站在个人的角度，并不代表任何一方。我希望大家都可以正确的看待问题，讨论归讨论，但不要影响社区的宁静。用star把舆论送到热门?我想这并不是大多数人想在github上看到的(类似头条的内容?)。他(她)第一眼想看到的是和自己工作，自己规划有关的，而不是这些...

**Comment by vzxxbacq** [comment]
@blacklisten 可以前往#530 讨论Repo存在是否违反Github条例。如果不存在违反条例，您就没有资格决定这个Repo是否存在。不过为污染您的眼睛抱歉。

**Comment by Anon02** [comment]
_Closed and backuped._

**Comment by wql7013** [comment]
@Anon02 这并不涉及到北京大学学生的切身利益，如果考虑自身利益的话，大家都会选择沉默，北大学生也不例外。这是社会热点事件信息公开的问题。

**Comment by aminic** [comment]
@blacklisten 我确实应该去掉你们这两个字，这是我的疏忽失误，报歉。
github做为全球第一大内容协作平台，应该不是大教堂式的社区，大概应该是集市式的社区，既然是集市，必然会有纷扰，必然会有热闹。
如果他（她）第一眼想看到的是和自己工作规划密切相关的的内容，那么大致上应该不会查看trending相关信息的，也不会给他（她）带来任何纷扰。
通常我也是不会看trending的，不管是github或者是其它网络社区的热度排行，通常只会找寻需要的相关信息，而不是追着热度。

**Comment by Anon02** [comment]
@wql7013  北大学生对和学工相关的自身利益的保护是非常热心的，这也是大部分学生对该问题的诉求，即学工和青研的工作太糟糕。而不是您现在看到的这样鱼龙混杂，谁都想代替北大学生发个声。这点可从未名BBS上的言论得到佐证；这点我相信我比您更有一些发言权。

**Comment by lengyanyu258** [comment]
@blacklisten #308

**Comment by gaocegege** [comment]
你好，之前因为回复太多被 GitHub ban 了。就信息来源的可信度问题，请您移步 #585 

如果您觉得这个 repo 本身有违 GitHub 社区规范与用户条款，请移步 #530 

个人赞同你关于信息的可信度的质疑，我们也在探索如何解决这一问题。另外，contributor 来自哪里就我个人而言并不特别重要，只要解决版权问题，同时信息来源是可靠的，谁来贡献并不重要。

**Comment by xx7777** [comment]
emm....鱼龙混杂，留给时间来见证真想吧

**Comment by vzxxbacq** [comment]
@Anon02 
Github会对太多回复的Issue进行关闭处理，希望你我现在都认同这个repo存在的合理性。何为野史何为正史怎么确定的问题您可以前往#585 讨论。

**Comment by bbtmcat** [comment]
@Anon02 
首先，我认同“北京大学学生的利益诉求（不）需要其他人员代为提出”。
但此次事件如许多网友所说，已经成为了一件公共事件。即北大行政行为的合理性，不仅仅涉及到北大学生的利益诉求，也与许多非北大公民相关。理由如下：
1.北大的行政行为可能具有重复性，能够影响到北大未来的学子。
2.北大的行政行为具有社会效应，能够作为其他学校处理类似事件的参照，从而影响到其他学校的学生。
3.北大作为被授权的行政主体，社会对此有监督权。其行为有义务向国家机关负责，对国家机关的责任，最终是来源于对本国公民的责任。
以上，我认为非北大学生参与此次事件发布信息、讨论并目的合理。
其次，反对“北京大学学生比其他人员有更高优先级。”
理由：
对于公民遭到类似行政处理的风险评估，不仅在于TA否是北大的学生，更在于TA的人格以及经历。即如果TA是一个与岳昕类似的人，即便TA不是北大的学生，相比于其他不同于岳昕的北大学生，也可能具有更高的遭到类似待遇的风险。因此而具有参与事件、图求改善所处环境的迫切性。我相信他们不会比北大学生的优先级更低。 
最后，我支持对信源进行确认，目前为止直觉上相信这个repo的动机是善的。
