### ISSUE TITLE
[Discussion]疑似MIUI已从系统层面封锁GitHub全域网站

### ISSUE THREAD

**Issue by Yanstory** [sikaozhe1997/Xin-Yue#582]
使用的机型以及系统环境为小米MAX2，MIUI9 8.2.1 Based on Android  7.1.1，并非该机型的最新MIUI版本。
通过任何浏览器（无论是MIUI系统浏览器还是第三方浏览器）直接访问github.com返回Connection Refused，但在电脑端无此异常。

**Comment by aminic** [comment]
《厉害了，我的国》

**Comment by zhangjinxue** [comment]
亲测，并没有！MIX 2    MIUI 9.5

**Comment by vzxxbacq** [comment]
实测没有，Miui 9， 请关闭这个issue

**Comment by lengyanyu258** [comment]
未复现：小米Note MIUI 9.2.3.0 Android 6.0.1

**Comment by tubu-long** [comment]
刚测试没有

**Comment by Yanstory** [comment]
那可能是网络运营商问题吗？例如我的是移动数据网络。

**Comment by shanezhiu** [comment]
没有。

**Comment by huoqiangf** [comment]
你没事儿用手机上github? 神人神人

**Comment by FenixZhu** [comment]
MIUI9.5.2.0未出现此种情况。

**Comment by Yanstory** [comment]
已确认不是MIUI的问题，可能是运营商网络针对。

**Comment by wydwww** [comment]
此[推文](https://twitter.com/__Crazy_Kid__/status/988612992869662721)回复中有很多宣称复现。
