### ISSUE TITLE
[Discussion] 如何对信息进行可信度分类

### ISSUE THREAD

**Issue by vzxxbacq** [sikaozhe1997/Xin-Yue#585]
岳同学现在还没有消息，北大校园内不平静却传不到校墙外。相信未来信息会更加繁杂，对于未来可能出现的信息是否需要进行可信度的标注呢？
#578

**Comment by DayChan** [comment]
我支持，但首先要制定一个评判标准

**Comment by shanezhiu** [comment]
支持，需要一个评判标准

**Comment by wql7013** [comment]
建议在引文末尾增加文章发布者简介，通过发布者同意的情况下，以便大家验证信息可靠性。

**Comment by ZeroneCat** [comment]
可以在文档开头增加yaml表头，提供作者信息与来源网址（即便已被删除）。

**Comment by gaocegege** [comment]
目前新的投稿都会带上来源，暂时缓解了这一问题，先关闭了，如果有任何问题请再 open 它。
