### ISSUE TITLE
一个沉默者的第一次发声

### ISSUE THREAD

**Issue by upofpurple** [sikaozhe1997/Xin-Yue#589]
我和许多人一样已经沉默了很久，每天看着新闻，却从不发表任何评论。因为我知道键盘上敲几个字并不能解决任何问题，那只是作为一个喷子在发泄。这个国家无时无刻不在发生比岳昕同学家庭破裂更凄惨的事情。创业，理财产品，网上借贷，股票，虚拟货币，赌博……这些每天都在摧毁一个个人，我看在眼里，内心毫无波动。但是发生在岳昕同学身上的事确实是不一样的，让我久违地感到不说点什么不行。
那么是什么地方触动了我呢？对于我来说，约谈，叫家长，关禁闭只是让我感慨北大也和中国其他的大学一样，没什么了不起的。岳昕同学的公开信让我见识到了一个年轻人可以在如此悲愤难当的心情下依旧理性从容地提出自己的要求，捍卫自己的权力，让我反思自己当年应该做的更好，但也就只是这样。真正让我气愤的是北大不仅删掉了有关这件事的文章，是，你北大牛逼，微信，微博，知乎没有你搞不定的，家事不想外扬我也能理解，但谁给你的权力删掉岳昕这些年走过来的心路历程。
我点进岳昕同学的公众号木田无花只是基于好奇，在那个时间点的我还是那个沉默的我，只是看看这个事件的当事人是个怎样的人，然后我震惊了，并不是因为看到了什么，而是什么都看不到。这个热心公益的女孩在这些年留下的点点滴滴全部被抹去了。内容违规被删除？究竟是谁以怎样的标准来判断这些文章违的哪门子规？关于岳昕同学写的一个北大既得利益者的自述，也许文笔一般，但确实透露出了深刻的思考和责任感。这篇文章如今已被删除，可能不会有重见天日的一天了。
我能理解具体操作的人的心态，哎呀，她公众号写了这么多文章，谁有时间一篇篇看啊，全都删了得了，万一涉及什么话题呢。但是我不能接受。
我可以接受那些因为约谈而沉默的同学，因为这个社会从古至今一直在摧毁鲜活的灵魂，所谓磨平棱角，成为一个成熟的人，但是我不能接受就这样随意抹杀掉这个鲜活灵魂留在这个世界上的痕迹。
扪心自问，如果有人这样对我，我大概就疯了，相比之下把我写的毕业论文删了都不算什么。
仅在此求有心人将此文传到未名bbs上，我既不是北大校友，也不是什么名人，只是一个沉默的大多数第一次想发出声音。

**Comment by gaocegege** [comment]
谢谢理解，因为与 repo 内容无关，先关闭了
