### ISSUE TITLE
[Request] 明确项目的目标

### ISSUE THREAD

**Issue by findNextStep** [sikaozhe1997/Xin-Yue#590]
鉴于[当前](https://github.com/sikaozhe1997/Xin-Yue/tree/3c5821a71cc7925c6712caceb281e3d0ca4a71d5)的[README.md](https://github.com/sikaozhe1997/Xin-Yue/blob/master/README.md)提供的是《岳昕：致北大师生与北大外国语学院的一封公开信》的内容，个人认为造成了这个项目的目标不明确。且在一定程度上导致了issues上的混乱。

建议将公开信的内容放到单独的文件里（事实上是有[这个文件](https://github.com/sikaozhe1997/Xin-Yue/blob/master/%E5%B2%B3%E6%98%95%EF%BC%9A%E8%87%B4%E5%8C%97%E4%BA%AC%E5%A4%A7%E5%AD%A6%E5%B8%88%E7%94%9F%E5%92%8C%E5%8C%97%E5%A4%A7%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%AD%A6%E9%99%A2%E7%9A%84%E4%B8%80%E5%B0%81%E5%85%AC%E5%BC%80%E4%BF%A1)的），并在readme中说明项目的目的和作用。并起到记录变化的效果

**Comment by boogoobird** [comment]
README中写清楚这个项目的意义在哪儿,这个事件的说明链接,以及如何维护这个项目

**Comment by gaocegege** [comment]
我觉得我们应该就 repo 的 scope 达成一致。个人认为，所有关于事件本身的讨论，思考，分析，都不应该以任何形式出现在 issue, PR, 内容中。Repo 的本意应该不是开拓一片论坛，而只是记录事件本身的发展。

WDYT @SniperChen @zhaobenx @kilobtye

**Comment by zhaobenx** [comment]
#581 讨论出来的结果都可以放到这个里面，让人想发issue前阅读

**Comment by vzxxbacq** [comment]
个人希望这个repo用于记录这件事情的过程，issue用于维护。（或许我们可以在gitpage里加入讨论模块？）

README.md 是不是可以作为一个让人们了解这个repo的手册呢？是不是可以加入这些呢？
- 指导有消息的人如何PR
- 提供信息存放结构用于维护
- Gitpage使用指导于链接

个人一些浅见

**Comment by zhangn1985** [comment]
本人同意 @findNextStep 的观点，应该要在Repo的ReadMe中阐述本项目的目标和观点，存在的价值。

**Comment by zhangn1985** [comment]
对于岳昕本人已经不是本项目的重点。

我建议本项目
1, 收集沈阳事件的真实内幕
2, 把岳昕移除主要讨论，因为她不是问题的核心，她只是事件的爆发点，基于其脆弱性，减少对其关注，以保护她。
3, 可以适当挖掘“深约一丈”和作为媒体的“张震林”

**Comment by kilobtye** [comment]
我认为在 issue 中对这个事件进行理性的讨论没有什么问题。因为目前不被删帖而且墙内可以正常访问而且有人气的可以讨论这个事件的地方确实找不到了，所以大家才会聚集在这里发 issue。大家因为关注这件事才来到这里，汇聚成一个社区，想发出自己的声音。

所以我希望这里有一个较为自由轻松的环境，不必局限在程序员视角，对不懂 Github 这一套的人也要有包容的态度。既然 issue 可以当博客来用，当论坛来用也可以。当然有讨论就会出现各种人身攻击嘲讽撕逼之类的，需要严格的规范才能有良好的讨论氛围，这个还是挺难做到的。。

**Comment by SniperChen** [comment]
@vzxxbacq 
同意你观点，还可以再加README.md中还可以加上，issues发言的规则，和具体讨论板块的传送。类似于以前贴吧的汇总帖。你们觉得怎么样？

**Comment by findNextStep** [comment]
@kilobtye 我不太认同将issues作为论坛或者博客的做法。
就现在closed的issues来看，大多数人难以认同不同的观点，才此处的讨论往往导致不可控制的后果。
讨论需要全力避免意识上的讨论，因为一定不会有结果。
并且我认为这个事件已经发生，北大难以接收公开信息的后果才是事件的主要原因。
与其讨论这个事件的真相（且不说讨论能有何作为）不如讨论如何让大学能够接受认错的后果（当然，这似乎与这个工程主题不符）

**Comment by vzxxbacq** [comment]
@SniperChen 写了个大概，等到文件结构确定我再pr。

@kilobtye 个人认为可以在Gitpage中添加评论功能用于讨论。Issue的权限还是太小了，有些言论应该避免（可以说为了保护Owner和Yue-Xin同学）。当然我们可以提前约定发言规则，按规则来删除。

**Comment by SniperChen** [comment]
@findNextStep 
赞同。我觉得，反对的人，也不是不可以理解。他们也有发声的权利。不过，发布issues 要规范起来。像今天早上那样，每个人都发，太混乱了。

**Comment by zhangn1985** [comment]
@vzxxbacq 我觉得可以先把ReadMe先改了，让大伙看看新气象。

**Comment by findNextStep** [comment]
@SniperChen 我在考虑是否添加一个issues讨论如何让高校接收自己的`黑历史`
无论是本次事件还是其他XX事件，高校隐瞒、删除真相本质上是因为公布真相不利于高校自身。
这里有社会认同的问题也有社会现状的问题。
就是不知道是否适合在这个工程下讨论

**Comment by gaocegege** [comment]
我个人觉得之前所有 issue 里的讨论最后都会往极端的方向发展，这对项目本身毫无帮助。不过我接受以 GitHub Pages 上的评论方式来进行

**Comment by SniperChen** [comment]
@gaocegege
恩恩，最理想的状态是这样的，在GitHub page上以评论的方式出现。目前会去讨论issues,是因为，许多人都选择了这种方式来发声。可能需要我们后期提供合适的方式。

**Comment by FormotherChina** [comment]
@gaocegege 
关于该项目下一步该怎么做，我再提一些建议。
1.考虑尽快和[端点星计划](https://github.com/Info-cn/Terminus)、[时代先锋网](https://www.shidaixianfeng.tk)、[陶崇园事件永久档案库](https://github.com/lonufate/ArchivesOfTaoChongyuan)和[墙与书博客](https://wallsandbooks.wordpress.com)达成合作（或添加友情链接），避免重复劳动。
2.如果本repo被像[zhao](https://github.com/programthink/zhao/)一样被451，建议几位Collaborator各自fork，明确下一个阵地，比如在@gaocegege或者其他人的repo里继续作贡献。

**Comment by gaocegege** [comment]
如果被 451，那么我觉得应该做的是 argue 而不是打游击。

**Comment by xinmu99** [comment]
希望她能平安，毕业不受影响。

再往深一步发展，对抗的那就不是仅仅 北大信息公开公开制度了，后面的体制问题的根本原因在哪，两个月前我想你们应该也知道了。 这个问题也不是你们北大仅有的，不仅仅是你们北大人的事，也是中国人的事；只是你们影响力大，同时领导能耐也大。能谈到什么程度，最好联系一个可靠的调解员。

这个体制*到什么程度，来到墙外面应该清楚；至于要求的太多很可能无法达成妥协，反而使得岳昕得罪的人更多。

如果是为了保护岳昕不受伤害，建议可以考虑政治庇护作为最后手段；你们自己也要妨止社工，防举报的叛徒，被发现 你们自己也会有危险。

建议去编程随想那里 取经匿名手段；无关的政治讨论可以去品葱--自由无审查的问答社区。

**Comment by zhangn1985** [comment]
zhao这个项目本来就是湖边乱造的，早就被国内的程序员批判过无数次，建议不要喝他们合作。编程思想这个家伙是个铁杆反华分子。

**Comment by FormotherChina** [comment]
@sikaozhe1997 请问你们有匿名邮箱（或其他通讯手段）吗？我有些事情不方便在issure里说，github上又没有私信的方法，麻烦你们给我发一下吧，非常感谢。

**Comment by zhangn1985** [comment]
他们说得多危言耸听，政治庇护都出来了，中国共产党居然要去迫害一个还未毕业的学生，你们的思想也真是太下作了。

**Comment by zhangn1985** [comment]
跟他们合作真是坐实了有境外势力的介入，那个是实锤。

**Comment by zhangn1985** [comment]
保持清醒，@sikaozhe1997 @gaocegege

**Comment by xinmu99** [comment]
> ”他们说得多危言耸听，政治庇护都出来了，中国共产党居然要去迫害一个还未毕业的学生，你们的思想也真是太下作了。“

恐吓父母、威胁毕业、已经限制人身自由，这还不算迫害？ 什么样才叫迫害。
有技术自己不去学，是你们自己的事情了，谁在说假话，# **_大学生都应该有自己的脑子，凭逻辑、证据自己去思考_**
《历史的先声》 人民日报 新民主主义时期说的话，恐怕你也是装不知道，

**Comment by xinmu99** [comment]
@FormotherChina telegram  有临时邮箱 tempmail bot； 或者，你重新注册新的邮箱，mail.com 或者protonmail 用gmail注册不用手机

**Comment by zhangn1985** [comment]
看到没有，瞎话连篇，你在哪里看到有人被限制自由，谁恐吓了家长，哪里说了不让毕业？

**Comment by JourneyofRock** [comment]
@zhangn1985 repo里岳昕的公开信里把这些说得清清楚楚。你为何在这胡搅蛮缠，浪费别人的时间。

**Comment by zhangn1985** [comment]
好好读一读原文，岳昕是被接回家了，没有限制自由吧，岳昕自己的感受是毕业受到威胁。每个学生跟学校发生这种不愉快，都有这种感觉吧。岳昕自己没说母亲被恐吓了吧？

**Comment by JourneyofRock** [comment]
@zhangn1985 
岳昕公开信原文

“凌晨一点，辅导员和母亲突然来到我的宿舍，强行将我叫醒，要求我删除手机、电脑中所有与信息公开事件相关的资料，并于天亮后到学工老师处作出书面保证不再介入此事。有同楼层的同学可以作证。随后，我被家长带回家中，目前无法返校。

我和母亲都彻夜未眠。学校在联系母亲时歪曲事实，导致母亲受到过度惊吓、情绪崩溃。因为学校强行无理的介入，我和母亲关系几乎破裂。学院目前的行动已突破底线，我感到恐惧而震怒。

申请信息公开何罪之有？我没有做错任何事，也不会后悔曾经提交《信息公开申请表》，行使我作为北大学生的光荣权利。

二十年孺慕情深，我爱我的母亲。面对她的嚎啕痛哭、自扇耳光、下跪请求、以自杀相胁，我的内心在滴血。在她的哀求下我只能暂时回到家中，但原则面前退无可退，妥协不能解决任何问题，我别无他法，只有写下这篇声明，陈述原委。情绪激动，请大家原谅我的语无伦次。”

**Comment by JourneyofRock** [comment]
@zhangn1985 “导致母亲受到过度惊吓、情绪崩溃。” 还不算恐吓吗

**Comment by zhangn1985** [comment]
她也只说了母亲受到惊吓，不是恐吓，一字之差，好不好。她被接回家，没有限制自由吧。

**Comment by zhangn1985** [comment]
所以那些境外反华势力是不是很会挑拨，还用的是共产党否定共产党。

**Comment by zhangn1985** [comment]
但他们的证据确是伪造的。

**Comment by JourneyofRock** [comment]
@zhangn1985 "学校在联系母亲时歪曲事实，导致母亲受到过度惊吓、情绪崩溃。"

 "面对她的嚎啕痛哭、自扇耳光、下跪请求、以自杀相胁，我的内心在滴血。在她的哀求下我只能暂时回到家中."

这就是恐吓，没得洗。

你在这里给其他讨论问题的人扣各种帽子，挑动不和；又无理辩三分，强行洗地。做一个抖m搅屎棍很开心是吗。大家不要搭理他，不要在这种搅屎棍身上浪费时间。

**Comment by zhangn1985** [comment]
普通人怎么会去读党的文献，让你读你会去读吗？所以他们不简单，动辄引经据典，大有准备咯。有组织有来头。

**Comment by zhangn1985** [comment]
你估计没有和爸妈闹矛盾，至少我妈妈是那样，我不停她话的时候，她就是这样，声泪俱下，自责。

**Comment by zhangn1985** [comment]
就算是恐吓了，也不要和编程随想合作，他真是铁杆反华。

**Comment by JourneyofRock** [comment]
@zhangn1985 “面对她的嚎啕痛哭、自扇耳光、下跪请求、以自杀相胁” 

你不听话你妈妈会给你跪下自扇耳光？辅导员要怎样歪曲事实恐吓家长才能把人逼到这份上。

**Comment by zhangn1985** [comment]
不争吵，这个恐吓与否没意义，千万别和编程随想合作，真反华呀。

**Comment by JourneyofRock** [comment]
@zhangn1985 你刚开始罔顾事实，信口开河。然后咬文嚼字，无理辩三分。最后词穷，又说没有意义，然后来转移话题。你要是个成年人就要为自己说过的话负责，别像放屁一样臭不可闻。

**Comment by xzhu70** [comment]
@zhangn1985 反共不是反华。请认清基本事实。

**Comment by zhangn1985** [comment]
你居然承认了，@Peiyang @TinaHongBu @xzhu70 

你知道他们居然还同时和疆独，藏独，台独，港独结盟，何以做到反共不反华！！他们是同时反共反华。

**Comment by zhangn1985** [comment]
需要看清楚他们的真实面目，是肢解，肢解中国。

**Comment by FormotherChina** [comment]
@xinmu99 谢谢你，我的GitHub小号就是用protonmail注册的。但是我的意思是让本repo的负责人给我一个他们的匿名邮箱，我通过邮件和他们交流。issue里现在鱼龙混杂，恳请Collaborator们适当管理。

**Comment by vzxxbacq** [comment]
@FormotherChina #556 Owner和Collaborator也只是一些普通人，不管您出于什么目的，我都不希望您能联系上Owner。

**Comment by ryanaltair** [comment]
@zhangn1985 我把你点名的人的info 查看了一下 这里做个总结 
pc848 2 repo 3 star
tina bu 14 repo 14 repo
journeyofrock 0 repo 1 star 
thinkpeace 0 repo 7 star
formotherchina 1 repo 1 star

意味什么？

**Comment by FormotherChina** [comment]
@vzxxbacq 不要误会，我请求的联系方式是匿名邮箱或一次性的通讯方式，是想在充分保护你我的情况下进行交流。除了邮箱，twitter私信、telegram、signal等等都可以，请考虑一下。

**Comment by xzhu70** [comment]
@zhangn1985 把“疆独，藏独，台独”当作反华是中共的愚民操作。凭什么他们对自己的家乡不能有自由的选择？你自己在中国没有基本政治权利，还反对给别人政治权利？谁说统一就是对华人好了？真正剥夺华人自由、压迫华人的是中共。中共才是反华。

**Comment by zhangn1985** [comment]
给位呀，你们还敢和@xzhu70 合作吗？ 先不说共产党的成绩，就是想把新疆西藏台湾分裂出去，就要和他们彻底决裂！！ 不要和他们交流，不要使用他们提供的工具。他们说的要旗帜鲜明的反击，这样我们手握真理的大多数的正确发声方式。

**Comment by xzhu70** [comment]
@zhangn1985 搞笑。手握真理的大多数？说个政治都敏感，怎么会有真理？

**Comment by zhangn1985** [comment]
突然想起，GFW在阻碍交流的同时，也在保护我们，这些思想太可怕了，要分裂我们的祖国，还那么振振有词。

**Comment by xzhu70** [comment]
@zhangn1985  品葱上在讨论你是不是五毛。：） https://www.pin-cong.com/p/74252/?s=74252&c=74258#cmt_area_74252

**Comment by zhangn1985** [comment]
我都说了，我是自干五呀。不用讨论。

**Comment by xzhu70** [comment]
@zhangn1985 你的思想被党保护得太好了。你喜欢党保护你的思想吗？那就应该不要出墙，不要碰任何党妈敏感的话题。你已经犯忌讳了。：）

**Comment by zhangn1985** [comment]
我是在保护党不受你们的侵害，这里的大多是年轻的学生，还不懂，但是他们是党的未来，我在这里战斗，就是保护党，保护党的未来！

**Comment by TinaHongBu** [comment]
我...被点名成藏独了??? LOL 笑死了

**Comment by xzhu70** [comment]
@zhangn1985 战斗？在评论区叫骂扣帽子，有多少说服力？算是战斗？就邀请你回答品葱这个问题吧。看你能不能说出些道理，把观点阐述清楚，到底有多少战斗力。

如何评价 在 github 放置 ”北大岳昕事件“，以及反对声音？https://www.pin-cong.com/p/72818/?s=73794

**Comment by gaocegege** [comment]
目前达成的共识：以评论的方式支持讨论，issue 只做与 repo 内容有关的维护用途。如果有任何问题可以继续回复。

另外在当下北大认为 Xin Yue 与境外势力有染的情况下，我不认为这些讨论对事件的解决有帮助，还请就事论事，言之有物。
