### ISSUE TITLE
[Discussion]让岳昕同学正常完成学业

### ISSUE THREAD

**Issue by boogoobird** [sikaozhe1997/Xin-Yue#591]
1. 我认为最重要的事情是帮助岳昕同学完成学业,这么一闹岳昕同学是受伤最重的一个人,你们和岳昕同学生活在同一个校园和岳昕一同经历了事情的始末,你们应该去安慰岳同学,岳昕让我想起了二十多年前的那个女生,你们父辈那代人受的委屈要比你们多得多.我希望你们能携起手来平息掉这件事,让事情有一个圆满的结局.
2.信息公开这件事很难,如果你们真的有心,希望你们可以坚持下去.

**Comment by gaocegege** [comment]
这当然是肯定，不过与这一 repo 无关了，我们也无法决定这件事，先关闭了

**Comment by zhangn1985** [comment]
其实我觉得岳昕是最大的受害者。她不能承担压力，而且现在又在舆论的中央，但是她又不是核心参与者。
