### ISSUE TITLE
[Discustion] 民主的进步： 从西方民主到协商民主

### ISSUE THREAD

**Issue by zhangn1985** [sikaozhe1997/Xin-Yue#592]
我是在比较晚才知道有这个事情的。在这个Repo已经讨论，发酵很久，里面吵吵闹闹。大家各抒己见，好不热闹。但是讨论出了结果吗？

没有，没有。甚至出现了人身攻击，开始了谩骂，还有人肉。。。

在这里大家真的能够绝对自由的发言。这像极了西方议会。

但不愧是高等学府的学生，很快意识到，漫漫散散的讨论，完全不会有任何结果，还会导致恶劣的后果。

一些最早意识到的同学，就开始讨论，哪些话题是应该在这里讨论的，哪些是我们在这里的任务，以及如何甄别信息的真伪。并且开始关闭不应该在此讨论的话题。

然后整个社区，清净了，我们终于可以开始做正确的事情。这难道不是两会的缩影吗？

**Comment by zhangn1985** [comment]
共产党就在你们心中，你们的骨髓里面。

接受它，并成为它。

**Comment by vzxxbacq** [comment]
@gaocegege 
个人不希望这个repo成为政见的发表场所，所以@ collaborator了，抱歉

**Comment by zuoge85** [comment]
@zhangn1985 含住

**Comment by DayChan** [comment]
这不是两会的缩影，这是西式democracy的缩影。之所以你认为西方民主不是这样的，那是因为你未曾仔细了解过它

**Comment by DayChan** [comment]
西式民主（已发展健全的社会）最优的一面，并非体现在总统大选中，而是体现在国会以及一下各级议会中。体现在对民权对公共权力的制衡，如警权与类似的权力，以及媒体的权力。一切有一套规章制度来约束，公权均不能越线，民权亦不能越线
其实在民主社会，也不一定是民主社会，法治社会吧（比如新加坡，就是不民主但法治的社会），都可以很容易看到示威中的公民与警察对质，这是因为公民与警察都明白有条线，警察不能随意抓人。但在不一定法治的国内，恐怕99%的人都不敢惹警察
有空去了解一下深中民主（深圳中学），可以去谷歌查一下他们的校园媒体：涅槃新闻（百度可能查不到）。其实说是深圳民主，其实模仿的是香港议会的程序和香港社会对权力的制约。其实了解深圳民主就大概可以了解到香港民主真正的样子，而不是看国内媒体的报导

**Comment by DayChan** [comment]
而两会就不多说了，所谓充分讨论达成共识在我个人看来无非就是沆瀣一气罢了。最容易想到的问题就是人大代表的选举尚不明了，多少人根本没有接触过最低一层代表的选举。简单的问吧：哪个国家的宪法修正案能有99%的通过率，并且从公众知情两周内就通过了，并且还是有争议的修正案？

**Comment by zhangn1985** [comment]
恐怕有些事情，不是这样哦。

至少你举的警察的例子已经不恰当了。

外国的警察，至少美国的警察开枪是随意的，打死多少黑人！

国内的警察，真的是被舆论搞的死死的，我亲历的一件事，警察在地铁站查身份证，有个小伙子没带身份证，然后一直在说你有什么权利查我的身份证，我又没有犯法，屡次拒绝配合。
警察无奈，仅仅是威胁口头传唤。也没拿他怎样，只好放他通过。

网上太多这样类似的事件，警察现在已经不知道怎么面对舆论，被舆论压得抬不起头。

**Comment by zhangn1985** [comment]
你又不懂法律（猜的，万一你懂，就抱歉啦），给你讨论有啥意义呢？

一个法国的例子，欧洲宪法草案投票通过，法国就搞全民投票，结果被否了。
欧洲宪法草案没通过，就搞了一个轻量版的，啥啥条约的，法国学聪明了，就搞议会讨论投票就好了，
结果就通过了。

**Comment by DayChan** [comment]
其实从你说的欧洲的例子就可以看出你其实对民主有误解，法国全民投票还是议会议事的选择取决于法律，而不是”法国“，从你的话中我好像感觉你把”法国“当成一个可以决定的个体，我感到疑惑
再者，你的警察的例子，这种情况不正可以说明警察根本无法举出法例来解释为什么要查身份证？威胁口头传唤，随意威胁怕是不合法例哦。难道警察是想抓就抓想查就查，口头威胁还算是让步了？在台湾，警察在抓捕的第一刻都会宣读是什么法律法例允许下执行，以及嫌疑人有什么权利拒绝回应与上诉
美国的情况我不了解，我知道确实有很多人被枪杀，但是具体的程序与缘由不清楚。但是香港的情况我了解，在香港，警权与民权的平衡真的是做到一个很好的平衡，每个动作都有程序或者法例来规范，但是就算是这样，警察在香港还是受到大量舆论的批评，至于为什么，这就话长了，得你自己去了解

**Comment by DayChan** [comment]
还有我说的警察的意思是，不是说所有多小的任务你都得宣读法例，但是至少别人反问时，应该脑子里清楚、能回答吧。不然做警察连自己为什么有这个权力执行这个行为还不知道，那怎么做警察。

**Comment by zhangn1985** [comment]
所以香港出现了港独不坐牢，维持秩序的警察坐牢了，很好的平衡。

再回来法国的例子，欧盟宪法已经在欧盟谈判通过了，但需要成员国批准。

法国的民主是这样的，全民投票是民主，因为议会也是代表人民，所以议会投票也是民主。

最初法国举行全民投票来表决欧盟宪法，结果否决了。

欧盟没办法，只好重新谈判，搞了个大同小异的里斯本条约。

法国这次不搞全民投票了，议会投票同样是民主，这次就通过了。

那么全民投票否决的欧盟宪法，议会却通过了类似的里斯本条约，哪个才是民意，哪个才是真的民主。

回到我国宪法修正案，是人民代表大会批准的，这个跟议会批准里斯本条约有何区别？

**Comment by zhangn1985** [comment]
所以香港出现了港独不坐牢，维持秩序的警察坐牢了，很好的平衡。

再回来法国的例子，欧盟宪法已经在欧盟谈判通过了，但需要成员国批准。

法国的民主是这样的，全民投票是民主，因为议会也是代表人民，所以议会投票也是民主。

最初法国举行全民投票来表决欧盟宪法，结果否决了。

欧盟没办法，只好重新谈判，搞了个大同小异的里斯本条约。

法国这次不搞全民投票了，议会投票同样是民主，这次就通过了。

那么全民投票否决的欧盟宪法，议会却通过了类似的里斯本条约，哪个才是民意，哪个才是真的民主。

回到我国宪法修正案，是人民代表大会批准的，这个跟议会批准里斯本条约有何区别？

**Comment by zhangn1985** [comment]
法国可以，我国不可以，那就是明显的双标了。

再从人大代表的组成上来看，你就会知道人民代表大会的全面性。
[一图看懂人大代表的构成](http://t.m.china.com.cn/convert/c_kBtiwwDD.html)

**Comment by DayChan** [comment]
维持秩序的七个警察把一个人拖到暗角拳打脚踢，很好的维持秩序
港独不坐牢，涉及到一个言论自由与港独定性的问题，因言入罪是一个很敏感以及很难界定边界的问题，所以是不可能坐牢的。并且港独不是杀人放火，而是香港人在讨论自己香港地的问题，又为何要坐牢？香港在被殖民前是大清的属地，中华人民共和国从未拥有过主权，甚至中华民国也没有。如果说以前朝代有主权的土地现在政府就自然拥有其主权，唐朝时地图才大呢，怎么不说那都是中国的土地。再者每个英殖民地在现代去殖民化时都有独立的选项，只有香港是通过谈判直接主权移交，英国人和中国人不允许香港人参与谈判，香港人表示很受伤并严正抗议。所以为何讨论独立要入罪？
仔细了解过里斯本条约后，我认为这确实是完全民主的弊端
但是看回两会，我看不到协商民主的影子和证据，看不到其讨论的严谨，看不到法律在其中的制衡与保障。只看到了法律想制定就制定，宪法想改就改。

**Comment by DayChan** [comment]
你所说的全面性我看是只是地区和族群和功能组别的全面性吧，这个全面性哪个议会没有呢，但更重要的政治取向的全面性呢，我看两会是99%持相同政见吧

**Comment by zhangn1985** [comment]
不同政见的人一起执政，肯定是吵架呀，这就是西方议会。看过纸牌屋吗，不同政见的执政，实质是什么，交易，懂不！

**Comment by zhangn1985** [comment]
在来说你港独的实质，你有没有好好学习南京条约，有没有学习溥仪的退位诏书。

**Comment by DayChan** [comment]
相同政见的人执政的结果是什么，权力遮天，执政不透明，这也是这个repo出现的原因。我宁愿牺牲一点执政效率确保程序正义

**Comment by DayChan** [comment]
港岛已经其他小岛是割让，新界是租借。租借就涉及到主权属于大清，但是，退位诏书指的大清土地主权移交给中华民国，不是中华人民共和国，这个中华民国至今仍存在，所以新界主权与中华人民共和国何干，港岛更别论

**Comment by zhangn1985** [comment]
为了推行一个法令，而做的交易，甚至不惜牺牲国内另一团体的利益，这就是你要的程序的正义。结果呢，不过是一个利益团体侵占另一个团体的零和游戏。这样的小团体民主有何意义呢？

**Comment by zhangn1985** [comment]
不仅是港独还是台独，中华民国早就亡了。

**Comment by zhangn1985** [comment]
拿美国的民主党共和党，他们一个保守一个自由，看上去政见不同，其实他们都是维护资产阶级统治的政党，他们在这个基本面上是完全一致。所以他们们是大同小异，这下是他们能坐下来交易而不打起来的基本。

**Comment by zhangn1985** [comment]
再说你的港独，我先抛弃我的原则，如果你说香港不属于中国，也不属于英国，也许我还会赞你有骨气。你知道港英政府根本没有把你们这些黄皮肤的人当人看，是你们的爷爷，父亲几代人的斗争才有了你们的地位。香港回归后，立刻就有了港人治港的权利，白给你们的权力。你不要反而要去英国摇尾乞怜，真是可悲，他们你有彻底把你们当作狗。香港的确有很多困难，但你们不努力解决困难，异想天开的以为，换个政府就能解决问题。还是名言送给你，图样图森破，上台那衣服。

**Comment by cnrpman** [comment]
你这是把repo的基本管理污蔑成民主集中制。
在这里，closed了的话题依旧能继续讨论，好比你虽然和大部分人的意见相左但依然可以自由发声。
不要把你眼中的常识当做事实。

**Comment by blueabysm** [comment]
@DayChan 且不论观点内容，单看措辞和逻辑水平，他和你就远不在一个水平线上。很佩服你举证说理的耐心，给个赞。

**Comment by blacksong** [comment]
@DayChan 看完你的见解，让我真的很佩服，逻辑清晰，心平气和，不用道德制高点去压制别人，这场辩论你赢了！很强

**Comment by ge8528** [comment]
@DayChan 你的见解很好，哈哈我只是不想和@zhangn1985 这厮辩论，哈哈，所以直接开骂了，大号被封，用小号。哈哈

**Comment by DayChan** [comment]
@zhangn1985
如果中华民国已经灭亡，世界上就没有地方连续飘着中华民国的国旗106年了
认同中华民国存在不是台独，认同台湾国存在才是台独。
除非你说国民党也是台独

**Comment by DayChan** [comment]
@zhangn1985
事实上我没有说香港属于英国
我说的是香港中的港岛区在1997以前法理上属于英国

**Comment by zhangn1985** [comment]
@DayChan 一中各表也是台独。

**Comment by DayChan** [comment]
@zhangn1985
那么你愿意把共产党带给你的东西在你脑海里生根发芽固然也是极好的
