### ISSUE TITLE
[Request] 需要把校方的公开的资料收集起来。

### ISSUE THREAD

**Issue by zhangn1985** [sikaozhe1997/Xin-Yue#593]
校方公开了沈阳事件的部分资料，这部分加进来，可以让我们知道更多。

建议如下组织项目：

沈阳事件/校方公开资料/
学生申请公开/事件内幕
                    /媒体评论

**Comment by klwz** [comment]
维基百科欢迎你们
https://zh.m.wikipedia.org/zh-tw/%E5%8C%97%E5%A4%A7%E5%B2%B3%E6%98%95%E4%BA%8B%E4%BB%B6

**Comment by zuoge85** [comment]
@zhangn1985 你这样的狗逼含住别说话就对了。
