### ISSUE TITLE
[Request] 需要把当年事件报道收集起来，如果有

### ISSUE THREAD

**Issue by zhangn1985** [sikaozhe1997/Xin-Yue#594]
一般学校图书馆都有期刊报纸的存档，看看是否有这样的报道。有助于理解沈阳事件。

**Comment by zuoge85** [comment]
@zhangn1985 你这样的狗逼就不要在这儿讨论了吧，你还是专心跪好，然后含住别说话

**Comment by zhaobenx** [comment]
Duplicate of #593
