### ISSUE TITLE
[MMMM] 很烦呢，人身攻击！！！@zuoge85 

### ISSUE THREAD

**Issue by zhangn1985** [sikaozhe1997/Xin-Yue#595]
这个用户老是攻击我，很烦啊，能不能ban掉他

@gaocegege @sikaozhe1997

**Comment by ayaservice** [comment]
@zhangn1985 谁让你的言论太共匪呢？

**Comment by vzxxbacq** [comment]
Report to Github

**Comment by zhangn1985** [comment]
@gaocegege 喂喂，这就是你处理问题的方式？？？

**Comment by zuoge85** [comment]
@zhangn1985 狗逼，你含住就是了，说话做啥

**Comment by gaocegege** [comment]
@zhangn1985 可以选择 report user，因为这一问题与 repo 主题无关

**Comment by gaocegege** [comment]
我查看了一下 GitHub Help，由 @sikaozhe1997 block，才会起作用

**Comment by zhangn1985** [comment]
我看了一下我自己的项目，似乎也找不到哪里能Block 用户，误会你了。

**Comment by zhangn1985** [comment]
Limit to existing users

Users that have recently created their account will be unable to interact with the repository.

只能block 24小时。

**Comment by gaocegege** [comment]
嗯，GitHub 本身对 block 的支持很差

**Comment by shanezhiu** [comment]
心疼你

**Comment by ayaservice** [comment]
@gaocegege 你们都是太监们 这么喜欢自我阉割

**Comment by gaocegege** [comment]
你看过他的 comment 再说

**Comment by sikaozhe1997** [comment]
我block他了···哎大家观点不同可以文明的沟通交流···真不知道他这样是为什么···发泄情绪么··

**Comment by zhangn1985** [comment]
其实我只是说了我是自干五，他就开始人身攻击。
我是真的信“没有共产党就没有新中国”的，1000%信。
我也当然知道共产党有很多问题。

大家可以和而不同嘛，为了共同的部分奋斗。
