### ISSUE TITLE
[Discussion]交大类似事件&最新处理结果

### ISSUE THREAD

**Issue by YUEXINFIGHTING** [sikaozhe1997/Xin-Yue#596]
为了保护隐私注册了小号参与讨论，上海交大媒设学院副院长涉嫌性侵而且被实锤了，现在已经公开处理，进一步调查处理后续还在进行中。
https://www.wukong.com/answer/6548340873615114509/?wxshare_count=7&from=timeline&isappinstalled=0

**Comment by ayaservice** [comment]
### **__ **
