### ISSUE TITLE
请贵驾另觅他处，莫要折腾程序员社区！！！

### ISSUE THREAD

**Issue by hunt978** [sikaozhe1997/Xin-Yue#597]
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！
请贵驾另觅他处，莫要折腾程序员社区！！！

**Comment by vzxxbacq** [comment]
ref #530

**Comment by SniperChen** [comment]
你好，此问题有专门的讨论区 #530 ,此问题会被关闭。原因：内容重复。希望理解。谢谢！

**Comment by hunt978** [comment]
我看了，你们在强词夺理。
