### ISSUE TITLE
[Discussion]是否有必要分享这个repo或者该如何让更多人关注这一件事并引导其去思考

### ISSUE THREAD

**Issue by SakuraLove** [sikaozhe1997/Xin-Yue#598]
考虑到直接转发宣传这个repo有可能对GitHub或者repo主会造成某些不必要的麻烦。
但这种维权事件，我们大部分吃瓜群众能做到的也就是保持关注和保持其热度，不能让其再像以前被后事埋没。
所以就有了这个discussion，是否应该分享这个repo或者该如何让更多人知道这件事并引导其去思考。

**Comment by SniperChen** [comment]
我想目前，这个仓库的存在不是为了宣传，仅仅是为了记录。因为，如果要是去宣传，我们有微博等更有效快速的平台。

**Comment by wql7013** [comment]
可以引用此repo，毕竟资料比较齐全。

**Comment by zhangn1985** [comment]
不必要，这个会给岳昕更大的压力和伤害。

**Comment by ayaservice** [comment]
袁腾飞老师曾经说过：满街假大空，天天粉太平。我本教书人无意惹权柄，天生真性情，反被小人用，宁做大嘴巴，不当马屁精。
这世界上最大的危险，莫过于真诚的无知和认真的愚蠢，以及无畏的自以为是。一个社会越是偏离真相，越是憎恨那些讲出真相的人。

**Comment by ayaservice** [comment]
@zhangn1985 跪久了忘记如何站立了吧，你还是继续跪着吧

**Comment by zhangn1985** [comment]
@ayaservice 你这个藏独！

**Comment by vzxxbacq** [comment]
或许Repo作为记录好一些，等到完善Gitpage后，您可以引用Gitpage中文章的url作为您观点的引申，可能比直接宣传这个Repo好一些？

**Comment by ayaservice** [comment]
@zhangn1985 最后回复你，我不同意你的观点,但我誓死捍卫你说话的权利，藏不藏，独不独，历史会证明一切

**Comment by moonwater** [comment]
> 我想目前，这个仓库的存在不是为了宣传，仅仅是为了记录。因为，如果要是去宣传，我们有微博等更有效快速的平台。
如果微博微信能正常发帖，　这个repo就不会火了，　这是基本的常识．

**Comment by zhangn1985** [comment]
@ayaservice 我说话的权利不需要你来捍卫，我自己有手有脚，不要拿这种冠冕堂皇的话来说，宣传藏独，不是言论自由。如同你在德国宣传纳粹一样。

**Comment by xlfsummer** [comment]
我建议完善 gitpage 之后再分享链接，直接分享 repo 可能对大多数普通人不太友好

**Comment by shanezhiu** [comment]
gitpage也会被封

**Comment by UpJunior** [comment]
#@ayaservice 警告别有用心之人离开，尤其是藏独分子，别想混淆视听。

**Comment by ayaservice** [comment]
@UpJunior 爱国主义是流氓最后的庇护所，你国厉害了，你国gfw会把你等粪青赶回大中国局域网的，我在自由之国拭目以待

**Comment by ayaservice** [comment]
@aminic 谢谢你的观点， 言论自由是一种基本人权，指一个国家公民，可以按照个人意愿表达意见和想法的政治权利，这些意见表达不用受政府的审查及限制，也无需担心受到政府报复。

**Comment by shanezhiu** [comment]
畸形的

**Comment by ZeroneCat** [comment]
@ayaservice 你可以保有你的观点，但是不要在这个repo的issue里讨论无关话题。

**Comment by zhangn1985** [comment]
你知道在美国不能宣传共产主义吗？美国言论多自由啊。

**Comment by JourneyofRock** [comment]
@zhangn1985 美国是有共产党的，现在也有。我在纽约上学的时候就在校图书馆门前收到过他们的传单。美国共产党总部就在纽约的20几街。美共的wiki在这里 

https://en.wikipedia.org/wiki/Communist_Party_USA

发言前多查查事实没坏处，别凭空信口开河。

**Comment by zhangn1985** [comment]
有一个西点军校的学生在毕业的时候，拍了一个照片，他的帽子里面写了社会主义，当即被取消了军人福利。美国有共产党不奇怪，但是宣传共产主义在美国就是会遭到打击。

**Comment by zhangn1985** [comment]
http://bbs.tianya.cn/m/post-333-1237558-1.shtml

**Comment by JourneyofRock** [comment]
@zhangn1985 首先，他受到批评并不是因为言论自由，而是穿军装宣扬自己的政治观点，辱骂上级，违反了军队条例（Uniform Code of Military Justice）。其次，你引的文章只是写他**可能**被取消军人福利，但我没有查到任何他**真正**受到处罚的报道。

而且你引得是环球屎报的文章，这个跪舔的报纸没有所谓新闻公正是有目共睹的。

**Comment by zhangn1985** [comment]
那你就找fake news CNN咯。

**Comment by JourneyofRock** [comment]
@zhangn1985 你活在新闻联播的世界里还好意思给cnn扣帽子，你举一下cnn有哪些不实报道。

环球屎报劣迹斑斑，自打脸的事都干过不少。当年还给ISIS洗过地。
http://news.sina.com.cn/pl/2014-09-17/072030869585.shtml

**Comment by shanezhiu** [comment]
能把issue关了吗，感觉他妈的越来越像Twitter了。越来越多人来这里并不是为了关注事件本身，而是宣扬什么主义，很反感。你们能不能不要舔着脸大义凛然的?不是说了这个文档只是在记录事件本身吗？但是issue存在是不是改变这个目标了?
