### ISSUE TITLE
[Proposal] 建议把此事件，存到ZeroNet，和到ZeroNet讨论

### ISSUE THREAD

**Issue by funny110** [sikaozhe1997/Xin-Yue#600]
Repo主应该去ZeroNet建个网站备份。
https://zeronet.io/zh
https://github.com/HelloZeroNet/ZeroNet
可以在ZeroNet里的推特(ZeroMe)讨论。
ZeroNet里，自己建的网站，节点多了，可以永存于网络。无人能删。只有你自己能删改。

**Comment by funny110** [comment]
@vzxxbacq 我不会用github，能看到就好。我发此issue只是想让看到的人知道有个叫ZeroNet的开源，免费，易用。不怕任何人审查，删贴，免费自由建站，你站点节点多后可以永存于ZeroNet网络的这么个自由之地。

**Comment by xinmu99** [comment]
zeronet 最近都找不到节点，，，，

**Comment by xinmu99** [comment]
@funny110 用了代理上的，，也找不到节点。。

**Comment by funny110** [comment]
@xinmu99 代理全局。我的正常。
或者你可以让zeronet使用tor
always。

**Comment by xinmu99** [comment]
@funny110 是ssr全局+tor啊，，只有一个月前刷出来的。。。

**Comment by funny110** [comment]
@xinmu99 那你全局ssr代理后，`关闭tor always` 试试。我使用没问题。

**Comment by eaglexiang** [comment]
无耻发个推广🌚，需要代理工具的可以试试我开发的https://github.com/eaglexiang/eagle.tunnel.dotnet.core，功能上和ss差不多，自己做了新的协议

**Comment by xinmu99** [comment]
@funny110 连上了。好像是端口被我换了。。

**Comment by zhangn1985** [comment]
完了，跟这些人合作，坐实了和境外势力勾结了。

**Comment by zhangn1985** [comment]
知道什么是境外势力了吗，他们并不是白皮肤，金发碧眼。扎扎实实的黄皮肤黑头发，说汉语。迷惑性很大。

**Comment by zhangn1985** [comment]
过去我们把他们称为汉奸。

**Comment by zhangn1985** [comment]
境外势力：@fanny110 @xinmu99 @Peiyang @patrick330602

看他们出现的时区都不一样！

**Comment by patrick330602** [comment]
@zhangn1985 首先第一点，我不是什么你所谓的境外势力。我在香港科技大学读书，目前在美国交换，仅此而已。我也觉得那些所谓“港独”，“台独”恶心，也对你们这种遇事不决就说别人是境外势力的人恶心。第二点，ZeroNet本身与境外势力无关。ZeroNet诞生于匈牙利，为了一个开放，自由和不被屏蔽的互联网而存在（引用自https://github.com/HelloZeroNet/ZeroNet）。不得不承认，ZeroNet上确实有你所说的“境外势力”，但是，你对一个平台的使用方法决定了你接触的内容。这只证明你经常接触这些你所谓的“境外势力”而产生这个平台上只有这些人的幻想。

**Comment by zhangn1985** [comment]
我只是点名，你也许是误伤，因为你老是和他们一起来。分不清呀。

**Comment by funny110** [comment]
@zhangn1985 你这人不正常，脑子有问题。

**Comment by XhstormR** [comment]
@zhangn1985  扣帽子技术一流啊

**Comment by fuzheng1998** [comment]
为了repo拥有者的安全，建议大家转移内容到Facebook，或者twitter等其他境外网站。毕竟SSR创始人被强制删库并喝茶就是最明显的例子，翻墙软件大家可以使用GitHub的蓝灯

**Comment by aminic** [comment]
一万个境外反华势力都没有一个PKU的官僚对世道人心的荼毒厉害。
强化境外反华势力的概念正是吃维稳狗粮的命根所在。

**Comment by leinue** [comment]
你们这样不怕github被封吗  :(

**Comment by XhstormR** [comment]
@leinue 这个问题已经讨论很多遍了，自己去 issues 翻看吧

**Comment by leinue** [comment]
@XhstormR 我看了，我担心的是一旦github被封 会影响很多软件系统的部署，不是每台服务器都自带梯子的

**Comment by kehao95** [comment]
建议大家不要离题，balabala的人无视即好。
----
支持将此事搬运至ZeroNet，ZeroNet就是为了这个而出现的。不过目前ZeroNet的Tracker还处于被屏蔽状态，直到有合适的初始补种方法出现前对于新用户来说处于不可用状态。

**Comment by funny110** [comment]
@leinue 墙不敢封GitHub，封了还怎么网络强国。封了github，党更怕你们程序猿集体翻墙。

**Comment by MARESFAC** [comment]
封了才好，封了某些生物就不会在上窜下跳了，封了他们让这些生物去用码云，直连github的速度怕是只有某些生物能接受。

**Comment by Godzillas** [comment]
什么 叫百度能方方面面代替谷歌 ...

**Comment by hiliyi** [comment]
封了好，免得有些蠢货说什么别的平台被封了云云，借口太拙劣。

**Comment by funny110** [comment]
@Godzillas 对于绝大部分中国人，是够了。

**Comment by Chandelier309** [comment]
如果你有SSR，或者SS或者V2Ray代理，那么通过设置Tor的Socks前置代理，可以网速很快的使用Tor（我觉得几MB/s够快了）。
然后设置ZeroNet 使用 always Tor，还可以保证匿名性。（因为ZeroNet不默认实现匿名，有点点危险）

**Comment by gaocegege** [comment]
目前建议比较可行的是 GitBook，所以先关闭这个 issue 了，谢谢您的提议。

**Comment by Ghostineuro** [comment]
@zhangn1985 境外势力哈哈哈哈哈，老铁，马克思是哪国人？

**Comment by ChandelierX** [comment]
@Ghostineuro 说实话，反华主要还是靠这些境内反华势力：四处扣帽子，希望他不要继续使用境外势力提供的Github了，有勾结境外势力的嫌疑。
