### ISSUE TITLE
[Proposal]关于修改README.md

### ISSUE THREAD

**Issue by vzxxbacq** [sikaozhe1997/Xin-Yue#603]
根据#590 的讨论，或许我们应该把README.md改为一个简单的tutorial。

**Comment by FormotherChina** [comment]
同意修改，这个repo的名称和目的应该更明确一点。我想 @sikaozhe1997 建立这个repo的初衷是为了让岳昕的公开信以及其他声援的文章不被gfw从网络上抹除，所以本repo不如叫**“反抗404计划”**怎么样？

**Comment by zhangn1985** [comment]
@FormotherChina 反贼闭嘴。

**Comment by vzxxbacq** [comment]
@zhangn1985 能否不要带情绪话发言，我丝毫不赞同上面那位的说法，但是不代表他要闭嘴。已report。

**Comment by zhangn1985** [comment]
OK，了解，我也是揭露他们的真面目，怕你们不清楚，既然清楚了，我也不必进一步纠缠。谢谢。

**Comment by FormotherChina** [comment]
我为自己辩护一下。在 #590 里我提到的仅仅是其他几个为高校学生鸣不平的项目，
>1.考虑尽快和端点星计划、时代先锋网、陶崇园事件永久档案库和墙与书博客达成合作（或添加友情链接），避免重复劳动。
因为我觉得诸位的目的没有根本性的差异，zhangn1985因此给我扣上反贼的帽子是何居心？

**Comment by shanezhiu** [comment]
最为担心的事情还是发生了。Twitter上的那群人闻风而动，蜂拥而至，一掺沙子，repo本来的目的就已经淡化了，上身到了政治层面。

**Comment by zhangn1985** [comment]
@shanezhiu 其实呢，这些事情出来了之后，境外势力不是请过来的，是自己闻着味过来的。
然后就抬杠到政治制度，党，政府。

加之确实国内是有不少人对我国的制度，党，政府不满。在境外势力的推波助澜下形成共振。

这些事情放到Github上，你是控制不住的，你想控制别人发新issue，不可能，这是个自由社区。

你想平平静静的做自己想做的事情，共振已经起来了，无法停止。

我们在这里关闭issues，和学校政府删帖有啥区别呢？都是在控制事态， 平平静静的处理这些事情。
