### ISSUE TITLE
[Proposal] 请求声明立场和境外势力划清界限

### ISSUE THREAD

**Issue by hsz1273327** [sikaozhe1997/Xin-Yue#606]
看这边工单基本上明眼人都能看明白有人目的不纯了吧,学生发声没啥的也是好事,但是如果让那些目的不纯的把项目带歪了,想象下还有好事么?不说别的倒霉的肯定是XIN_YUE小朋友,,这几个项目作者,包括那些带节奏发表反动言论的有谁会给她背锅?

还有人说这事件XIN_YUE小朋友已经不重要了,不要借题发挥带节奏,这边聚集过来的人都是同情小姑娘才来的吧.
同时建议block 掉那几个明显的反动份子,很好查的,看他们有几个仓库star过几个项目就知道了.

**Comment by eaglexiang** [comment]
有几个ID一看就知道不对头的。

**Comment by FormotherChina** [comment]
>看他们有几个仓库star过几个项目
不能作为判断依据，因为很多人为了避免泄露个人信息用的是小号的。例如本仓库的创建者@sikaozhe1997 有几个repo？star过几个？

**Comment by cameled** [comment]
If you have any other purpose, please fork this project. Then you can do want you wanna do.

**Comment by wallpusher18** [comment]
支持，朝毛主席像泼墨的必须扭送：https://zh.wikipedia.org/wiki/%E5%A4%A9%E5%AE%89%E9%97%A8%E6%AF%9B%E6%B3%BD%E4%B8%9C%E5%83%8F%E6%B1%A1%E6%8D%9F%E6%A1%88

**Comment by hsz1273327** [comment]
@FormotherChina 所以说既然都怕担责任,那为什么不先明确边界,这边的都只是账号,背后的是人是鬼鬼知道,到时候被带偏请喝茶的肯定是XIN_YUE,举着个小姑娘当挡箭牌好意思么?我只是提个建议

**Comment by eaglexiang** [comment]
@hsz1273327 我认为他并不反对你的意见，只是指出仅“依据repo和star数目”有些不妥。

**Comment by zhangn1985** [comment]
既然被点名了就来看一下。

首先啊，@JourneyofRock 就是一个小号，缩头乌龟，然后跟那些个 xzhu70 之流沆瀣一气， xzhu70是个明反， 给你戴个帽子太正确了。

**Comment by hsz1273327** [comment]
@JourneyofRock 是不是境外势力明眼人都看得出来,谈不上扣帽子.

另外这边没有讨论到自干五请不要乱带节奏,你觉得自干五也该block的话可以自己开个工单提意见哇,不要在这边讨论不相干的东西

**Comment by zhangn1985** [comment]
@hsz1273327 怎么对政府，党不满，都是咱自己的事，跟境外组织一点关系没有。在对外这件事情上，我们是一条战线的。

**Comment by hsz1273327** [comment]
@JourneyofRock @zhangn1985 这边没讨论自干五也没讨论小号,不相干的议题,,吵架可以外面另开个工单.

另外是不是境外势力应该明眼人都看得出来,不用我扣帽子.

评判的维度从低到高排的话:

1. repo和star数目和内容可以被参考,因为起码不用小号的人基本可以看得出研究从事的领域和参与研究的时间,相对来说会可信些
2. 活跃程度 不安好心的肯定很跳
3. 言论本身,这没啥好说的,字里行间就可以看出来

**Comment by FormotherChina** [comment]
@hsz1273327 我同意大部分人都是同情岳昕才关注这个repo的，但是我们要想一想，怎么做才能更好的保护岳昕。一种选择是息事宁人，把这个repo**删除**无疑是最好的方法。另一种就是依靠GitHub的影响力，以舆论的压力关注并保护岳昕，那么本repo就要考虑怎么扩大影响力了，可能需要适当的联系媒体。

**Comment by hsz1273327** [comment]
阶级矛盾,人民内部矛盾人民内部解决,不要让事情变质

**Comment by JourneyofRock** [comment]
口口声声又是阶级，又是人民。这些自干五才是最祸国殃民的。以保护岳昕的名义对不同的声音进行打压，还帮着洗地。

**Comment by gaocegege** [comment]
首先，Xin Yue 并没有请求任何来自外部的帮助，我们的 repo 目前还没有解决版权的问题。媒体不是我们有权利决定的，请联系 Xin Yue 本人。

其次目前 repo 的定位只是对事件的发展的记录，具体可参考 https://github.com/lonufate/ArchivesOfTaoChongyuan 的做法。

**Comment by tubu-long** [comment]
就事论事的讨论，和扩大scope（前面都用的scope）的讨论都是没问题的。
但是上来就**扣帽子**和**占边**的回复都是混淆视听，搅乱正常讨论思考的套路，请不要被带节奏。
我们的目的是讨论问题，跟阶级立场不对立，不管什么立场只要能把别人说服，就是好论点。

**Comment by hsz1273327** [comment]
@JourneyofRock 你觉自干五的问题有必要讨论请自己另开一个工单,谢谢.请不要在这个议题下讨论不相干的东西,谢谢
