### ISSUE TITLE
请你删除此贴

### ISSUE THREAD

**Issue by anicething** [sikaozhe1997/Xin-Yue#607]
同学，很理解你的心情，但是GitHub不是发表此类文章的地方，这是个程序员交流的地方，您的行为可能导致广大的程序员无法访问这个网站，对程序员是莫大的损失。谢谢！

**Comment by gaocegege** [comment]
Ref #530

**Comment by AnyWAT** [comment]
🤣不识代码的听说，强加13亿人的GFW貌似程序员的莫大功劳？

**Comment by DanteAndroid** [comment]
"删除此贴" 已暴露你的智商就是貼吧水平

**Comment by qidaping** [comment]
如果连着 都被封了 那你真正看清了你所信仰的东西的真正面目  倘若有一天这样的 事发生在你自己身上 你希望有人为你发声吗？ 五四运动的时候 真正敢发声的 又是什么人 没有尝试 一切 都会止步不前
