### ISSUE TITLE
[Discussion] （网传）岳昕：目前我已回到学校

### ISSUE THREAD

**Issue by Homer-G** [sikaozhe1997/Xin-Yue#614]
![image](http://chuantu.biz/t6/296/1524714864x-1404755624.jpg)

来源：https://www.douban.com/people/hejinghui1989/statuses

repo主的初衷就是帮助岳昕，这算是阶段性的好结果。

**Comment by JourneyofRock** [comment]
希望岳同学顺利完成学业

**Comment by tubu-long** [comment]
![image](https://user-images.githubusercontent.com/2630303/39284583-948a76b4-4946-11e8-9fd1-8cdeacbe1bed.png)

**Comment by gaocegege** [comment]
403

**Comment by FormotherChina** [comment]
[目前我已回到学校](https://i.loli.net/2018/04/26/5ae1403530b8c.jpg)

**Comment by JourneyofRock** [comment]
不过看豆瓣的帖子有人评论字迹和以前的不一样，望有人能证实

**Comment by vaxcert** [comment]
http://i.imgur.com/TvCchmW.jpg
有幸打开了链接

**Comment by crescendo007** [comment]
这是不是她写的？

**Comment by Homer-G** [comment]
修改了链接，我是在豆瓣上看到的，但这个出处可能不是豆瓣。所以我还是把名字改一下防止误解。

**Comment by AnyWAT** [comment]
转：她的手機被限制，微信、公衆號都不能上，在哪寫的，只能想象。

**Comment by AnyWAT** [comment]
转：中國人民大學有一個成立六年的致力于服务校内外来务工人员的公益社团——新光平民发展协会，該社成員多年勤勤恳恳、踏踏实实地竭尽所能，为人大后勤职工开展夜校、文艺队、晚会、义诊等活动。最近也被校方約談，詆毀該社團的聲譽，该协会會長陳可欣23日，25日連續給校長劉偉發公開信，問題還沒有解決。（2信7图）

**Comment by aminic** [comment]
全面隔离阶段

**Comment by zhangn1985** [comment]
都是转转传，道听途说。
岳昕是不重要的人物，不要给她压力。

应该关心一下张震林和深约一丈这个公众号。

**Comment by LittlePrinces** [comment]
如果是真的，说明她连和外界接触的机会都没有，如果不是真的，更加令人担心。

叹息！！

**Comment by zhangn1985** [comment]
这个小姑娘根本承受不了压力，你让她怎么和外界接触，面对媒体？

她不在学校，也就是在家里，没啥问题呀。

**Comment by zhangn1985** [comment]
张震林和深约一丈这个公众号一直是躲在背后的。

**Comment by LittlePrinces** [comment]
@zhangn1985 什么叫承受不了压力，这个社会为什么要让她承受那么大的压力。

她诚然不在学校，也就是在家里， 但是也分为有没有人身自由的在学校还是家里。什么叫没什么问题。

**Comment by zhangn1985** [comment]
她跟母亲吵了一架，就彻底失控啦。关键是不知道什么原因学校突然要求她删除手机里面的资料，没人回答。还有匿名者把她推到了聚光灯下面，用心非常险恶。

如果她在学校，会面临什么情况呢？假设学校也不加阻拦。被一堆媒体包围着，换做你，你受的了吗？

**Comment by zhangn1985** [comment]
所以我断定，这个是假新闻，伪造的。

**Comment by JourneyofRock** [comment]
@LittlePrinces 他自己承认是自干五，还在别的帖子里各种洗地。别和他纠缠了，浪费时间

**Comment by zhangn1985** [comment]
@JourneyofRock 已经是实锤的境外分裂势力。你就别给自己贴金了。

**Comment by Homer-G** [comment]
@zhangn1985 不要妄下结论。字体上来说，伪造的可能性很小。至于岳昕在什么情况下写的信，只能等进一步的消息。

**Comment by gaocegege** [comment]
https://bbs.pku.edu.cn/v2/post-read.php?bid=64&threadid=16398196

**Comment by Homer-G** [comment]
7楼 forresthoho：
不是，不过她发在一个大群里我看到了只是觉得bbs上很多人在自说自话，反倒忽视了岳同学现在的状况，有必要提醒一下在这里转发一下应该不会违背她的意愿吧，如有，立刻删

**Comment by Homer-G** [comment]
Source大概就是微信群了

**Comment by MARESFAC** [comment]
祝平安

**Comment by xiaotiandada** [comment]
希望岳同学顺利完成学业

**Comment by falseLuffy** [comment]
加油

**Comment by PedroLee** [comment]
来源是微信群，群名“沈某事件关注群”。26日早8:50发出，几乎可以确认是本人笔迹。

**Comment by AnyWAT** [comment]
转：留白中却写着不能写出的千言万语

**Comment by aminic** [comment]
岳同学发起了公开信，他的安危必然引发公众关心。
岳同学发起了公开信，就是对事件的走向无法做出，向良好方向发展的判断，从发出公开信起，实质上就是求助于公众舆论。
没有更多信息出来，那么就可以推断岳同学已经是密切控制的。
放出来的消息，要么是岳同学寻找机会放出来的，要么就是刻意如此放出一点消息，消弥封口，淡化影响，强化话语权的掌控能力。

后面的推断是：
1.听话服从安排，也许还能顺利毕业。
2.不听话一味抗争，。。。

愿上天给出最好的结果。

**Comment by AnyWAT** [comment]
brillera | 逼出来的北大师生联名信 – 中国数字时代 - https://chinadigitaltimes.net/chinese/?p=583562 on @CDTChinese

**Comment by DeboutPZ** [comment]
经绝对可靠消息确认，此图确为岳昕亲笔完成，并且图中大片留白是有意为之，即“开天窗”

**Comment by DeboutSQ** [comment]
@vzxxbacq 实在是不便透露，这会给岳同学带来更大的困扰，还望理解

**Comment by qhysjpw** [comment]
一脸闷逼的进来一脸懵逼的出去

**Comment by DaphneChu** [comment]
你(们)是北大的财富

**Comment by xiaomaoxiangxi** [comment]
加油

**Comment by vzxxbacq** [comment]
@gaocegege 岳昕在其最新的文章中详细解释这个声明，我们可以关闭这个Issue了吗？
