### ISSUE TITLE
[Proposal] Setup Static Website

### ISSUE THREAD

**Issue by gaocegege** [sikaozhe1997/Xin-Yue#618]
Ref https://github.com/sikaozhe1997/Xin-Yue/pull/584

> demo: https://zhaobenx.github.io/Xin-Yue/
将所有md都一起展现而且阅读感更佳。
这个需要repo所有者改变git page的默认目录为master branch
同时也可以为每个页面增加gittalk 功能，方便对每个页面进行讨论，此功能同时也需要repo主支持。

/cc @zhaobenx @sikaozhe1997

**Comment by vzxxbacq** [comment]
Owner也许不是计算机专业的

![a98511ea-d05f-4808-9aae-b9c348e34ef4](https://user-images.githubusercontent.com/29952934/39287191-041c39aa-4955-11e8-9abf-a36b0372280d.png)

在setting的option里面，下拉到上图位置，source改为master。
@sikaozhe1997

**Comment by zhaobenx** [comment]
现在主要有两种可行做法
1. 利用git page的jekyll
2. 利用jekyll+docsify（现行做法）

1.的做法比较标准，可扩展性也强，但是要求1.md文件需要储存在相应的文件夹`_post`，而且命名有要求，并且每个md文件必须在开头加入[front matter](https://jekyllrb.com/docs/frontmatter/)后才能正常渲染
2.的做法是利用jekll生成全部md的索引，然后利用[docsify](https://docsify.js.org/#/)对md进行渲染。方法教为简陋，但是不用对现有文件做改变。

当然一切都是基于将git page的根目录改了的结果上

**Comment by sikaozhe1997** [comment]
已经更改git page的根目录

**Comment by vzxxbacq** [comment]
https://sikaozhe1997.github.io/Xin-Yue/#/ 似乎已经能够正常工作
