### ISSUE TITLE
因为你这个话题Github敠被和谐，给其他中国技术群体用户造成不必要的麻烦，不合适

### ISSUE THREAD

**Issue by xianghongai** [sikaozhe1997/Xin-Yue#619]
建议技术站点只讨论技术，别涉及国事政事军事。

建议从Github移除此话题，并购买海外域名和主机搭建PHP类CMS系统，或者静态Web页面加评论系统，我会声援你。

**Comment by gaocegege** [comment]
Ref #530

**Comment by SniperChen** [comment]
Ref #532 
Move to #530

**Comment by huoqiangf** [comment]
@xianghongai 等github被墙了的时候你去买个shadowsocks就能上了。。到时候我给你打call
