### ISSUE TITLE
[Proposal] 添加第三方评论支持

### ISSUE THREAD

**Issue by gaocegege** [sikaozhe1997/Xin-Yue#621]
根据讨论我们支持在静态页面上引入第三方评论的支持

**Comment by l-hammer** [comment]
需要repo主提供以下两个信息：

clientID: 'Github Application Client ID',
clientSecret: 'Github Application Client Secret',

**Comment by gaocegege** [comment]
What tool do you use? I think there are some tools do not need thems.

**Comment by l-hammer** [comment]
[Gitalk](https://github.com/gitalk/gitalk)

**Comment by zhaobenx** [comment]
#627
