### ISSUE TITLE
  [Proposal] : 建议添加彭錞的《约谈是个什么东西？》

### ISSUE THREAD

**Issue by nainoNa** [sikaozhe1997/Xin-Yue#648]
网址如下
https://mp.weixin.qq.com/s/jE9UQ-RpmRfT6vMAk_fDRQ
作者对约谈的形式、制度以及外国学校的「约谈」进行了对比，提出了自己的看法，我觉得写得挺好的。

**Comment by vzxxbacq** [comment]
好的，您也可以参加编辑，具体可看[我该如何提供我掌握的信息](https://github.com/sikaozhe1997/Xin-Yue#%E6%88%91%E8%AF%A5%E5%A6%82%E4%BD%95%E6%8F%90%E4%BE%9B%E6%88%91%E6%8E%8C%E6%8F%A1%E7%9A%84%E4%BF%A1%E6%81%AF)

**Comment by nainoNa** [comment]
其实我觉得 未名bbs 中的一篇文章《对岳同学事件中五个问题的看法》 写得非常好。
https://bbs.pku.edu.cn/v2/post-read.php?bid=64&threadid=16398052
【原文由 Anonymous 发表在 SecretGarden 版 >>>】
但是由于我不是p大人，所以进不了，也不能问作者能不能转载，所以不知道有没有P大的同学能看到这个，帮我问一下原作者能否转载？不胜感激。
