### ISSUE TITLE
[discussion] 另一起不了了之的事件

### ISSUE THREAD

**Issue by SianThor** [sikaozhe1997/Xin-Yue#658]
https://www.baidu.com/paw/c/s/m.douban.com/mip/group/topic/96738283/

**Comment by guoyang1996** [comment]
404

**Comment by chengdong0421** [comment]
从文中好像没有看出女学生是被迫的，这种事是两个人的事，如果说这个教授只是引诱而并没有强迫或要挟的话，只能说这个教授道德败坏。至于这个女学生有没有什么其他意图，文中没有提，也许有什么交易呢。这样没头没脑的事情就不要讨论了吧。。。

**Comment by Seedarchangel** [comment]
@chengdong0421 
Are you for real?

**Comment by chengdong0421** [comment]
@Seedarchangel  不懂你在说啥

**Comment by SianThor** [comment]
北京大学生物系郭红卫教授与本科生发生不正当关系被迫离职 
被北大强压下去，没有任何通报，这位老师转身去了南科大。可以百度查询。

**Comment by SianThor** [comment]
大家了解一下，感觉北大的处理方式总是在掩饰
