### ISSUE TITLE
認為發布政治敏感內容會招致中共封鎖GitHub的,看我教你們怎麼讓git翻牆.

### ISSUE THREAD

**Issue by ssrlive** [sikaozhe1997/Xin-Yue#659]
自由地發布自己的觀點, 無論在什麼地方, 都應該是個人的自由, 不應該自我審查, 自我設限.
至於觀點正確與否, 自有市場的檢驗, 畢竟現在大家都很忙, 垃圾言論在自由環境裡根本沒有存活空間.
這應該是所有心智正常人的共識. 
那種認為 “在GitHub發布讓中共不爽的信息就會導致GitHub被中共牆掉因此就不應該發布” 的人,不用論證都是傻屄(逼, bi).

好吧, 到這裡还沒被我罵跑的人們, 我們繼續, 我教你們 git 命令怎麼翻牆.

>  下面一大坨文字是講怎麼配 VPS 上的 SSR 服務器 和 本地 SSR 客戶端的. 翻牆老鳥可以不看, 直接滾屏到文末看 git 配置.

首先你得有一個位於中共帝國以外的 VPS, 收費的有搬瓦工, vultr, DO, linode 等等. 另外, 谷歌雲 或 亞馬遜雲 均有免費一年的試用期, 一年用一個就可以蹭兩年的免費. 不要問我怎麼弄. 未經Google就問問題的傻屄沒資格做兲朝程序員.

然後在你的 VPS 上安裝 Ubuntu 或者 Debian 操作系統, 然後, 用以下命令編譯安裝我的 ShadowsocksR 服務器.
```bash
sudo su                       # using root account
apt-get install --no-install-recommends build-essential autoconf libtool asciidoc xmlto -y
apt-get install git gcc g++ cmake automake -y
apt-get -f install
apt-get update
apt-get upgrade

cd /                          # switch to root directory
git clone https://github.com/ShadowsocksR-Live/shadowsocksr-native.git
mv shadowsocksr-native ssr-n  # rename shadowsocksr-native to ssr-n
cd ssr-n                      # enter ssr-n directory. 
git submodule update --init
git submodule foreach -q 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'

# build ShadowsocksR-native
cmake CMakeLists.txt && make
```
現在編譯好了, 我們先編輯配置文件 `config.json` 然後以這個配置運行服務器.
```bash
cp /ssr-n/config.json /                                #將樣本配置文件複製一份到根目錄
vi /config.json                                        #編輯根目錄的配置文件
/ssr-n/src/ssr-server -d -c /config.json        #以編輯好的配置文件以後台方式運行服務器.
```
我的配置是這樣的:
```json
{
    "server": "你當前 VPS 的 IP",
    "server_port": 4043,
    "method": "aes-128-ctr",
    "password": "password",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "udp": true,
    "timeout": 300
}
```
服務器配置好了, 現在戰場轉移到你的本機, macOS 或 Linux 或 Windows 都行.
同樣用 git 命令取下 `ShadowsocksR-Native` 代碼, 編譯.
以上訴 `config.json` 文件內容作為配置. 運行編譯出來的客戶端 `ssr-client`, 命令如下. 
```bash
/ssr-n/src/ssr-client -d -c /path/of/your/config.json
```
現在, SSR 客戶端運行起來了, 我們開始配置 git 客戶端.
注意看上面配置文件裡有一行 `"local_port": 1080,` 客戶端的監聽端口是 1080, 那麼我們就把它用起來. 
```bash
# 代理 Proxy 設置
git config --global http.proxy socks5://127.0.0.1:1080
git config --global https.proxy socks5://127.0.0.1:1080

# 取消代理
git config --global --unset-all
```
到這裡, 你就可以通過代理試用 git 命令了. 哪怕中共對GitHub再加90道牆也無濟於事, 擋不住你了.

另外, 通過代理使用 git 還有個好處, GitHub 上的有些項目夾帶有子項目, 而這些子項目可能位於被牆的網站上, 這下不會取不到了. 另外, 關於通過代理使用 git 的另一個好處是隱匿行蹤, 詳情不贅, 參看 `編程隨想` 的博客.

**Comment by gaocegege** [comment]
Sorry it is outdated, thus close it.

**Comment by chengdong0421** [comment]
不用论证我都知道你是个傻屄（逼，bi）

**Comment by chengdong0421** [comment]
你就是那不用论证都知道是傻屄（逼，bi）的人

**Comment by vzxxbacq** [comment]
@chengdong0421 请不要人身攻击

**Comment by ssrlive** [comment]
https://github.com/sikaozhe1997/Xin-Yue/issues/530

**Comment by vzxxbacq** [comment]
@ssrlive 个人觉得现在发这个不太合适，因为这位同学还没有消息，以她的安全为考虑还是最好先别开这种issue，您觉得呢？

**Comment by ssrlive** [comment]
這個 issue 關都關了. 無所謂了吧. 我只是講 GitHub 被封後的應對措施. 是幫大伙的啊.

**Comment by chengdong0421** [comment]
@vzxxbacq 不是我要人身攻击，是有些人张口闭口就别人傻X的，就该以彼之道、还施彼身。。。
