### ISSUE TITLE
[Proposal] 岳昕同学的思想真的很值得我们学习

### ISSUE THREAD

**Issue by wql7013** [sikaozhe1997/Xin-Yue#668]
[我所认识的木 & 田同学](https://terminus2049.github.io/archive/2018/04/26/yx-friend.html)
不考虑文章叙述的真实性，文中所说的思想真的很值得我们思考和学习。
建议将此文章也添加到repo中

**Comment by gaocegege** [comment]
ref https://github.com/sikaozhe1997/Xin-Yue/issues/624

**Comment by wql7013** [comment]
@gaocegege 那个issue中的链接打不开了，那还是关闭这个issue，在下面引用吧
