### ISSUE TITLE
 [Proposal] 给Github的程序员的建议和对本repo的建议

### ISSUE THREAD

**Issue by WayneWang12** [sikaozhe1997/Xin-Yue#674]
淡定点，让这些孩子们玩好了。

不要管后续会不会被墙，专心做你自己的事情。Github有政策，对应的repo如果被国家相关部门投诉以后，是无法被对应的地区访问的。

整体来说，Github不会被墙，最多来说只是这个repo在国内看不到而已。

至于后来如果真的被墙了，那也没办法，这些个小屁孩儿的意见就是如果我没地方说我感兴趣的话，你也应该跟我一样没有地方说你感兴趣的话。

所以你跟他们争论不出来什么东西，就让他们在这里为这个事情关注一下。顶多默默地举报一下这个repo就好了。

感兴趣的程序员自己来关注，不要道德绑架，不要说其他人不关心时事。真关注这些事情的人，自然会不计后果去在国内帮人奔走、支援、帮助。

都是从那个年龄段走过来的，我比较理解他们。没能力没手段没关系的年龄，又想表达，又害怕后果，但是自以为正义，按捺不住，所以撺掇各种人去送死，就跟传说中的柴玲一样。

你看，我们不关心一些事情，就被人shame了：
![image](https://user-images.githubusercontent.com/6812513/39352347-08962eea-4a37-11e8-9585-8ff9025782ca.png)

但是，那又怎样呢？你的价值并不体现在是否为这个事情热心上，普通程序员此时最大的价值就是选择围观和不围观而已。真有需求，找公务员、律师等行业的朋友，远远比我们围观能做出更多的事情。

当然，本心是不希望他们在这里的。因为毕竟这里是我们用代码构建起来的良好社区。

但是，毕竟是个开放的社区，来已经来了，赶也赶不走，之前也没少这样的事情。只是希望你们对不习惯这里出现类似的内容的程序员客气一点点，因为你们确实不是主流；也希望你们不要进行道德绑架，说我们怎样怎样，因为毕竟人各有志，有的人喜欢关注政治，有的人却就是不喜欢，你不能强迫别人喜欢。

所以不要judge早在这里呆了很久的程序员们，不要把这里撕成国内社区的低段位。好好记录这件事情，然后作出理性、客观的评述，并且尽自己所能想出解决办法或者我们所能做的事情（捐款啊、上书啊等等），而不仅仅是情绪发泄。

谢谢。

**Comment by SniperChen** [comment]
ref #532 pls,move to #530 Thanks for cooperation!
