### ISSUE TITLE
一切都可以合理讨论？别人发的不符合你利益的东西你就删，这就是你的合理讨论的标准？

### ISSUE THREAD

**Issue by fuguanghua** [sikaozhe1997/Xin-Yue#677]

**Comment by SniperChen** [comment]
请查看讨论规则谢谢！ref #532

**Comment by chengdong0421** [comment]
双标嘛

**Comment by texzhichen** [comment]
@SniperChen #532 #530 解决了吗？如果没有解决请把状态改成 Open。你把所有这类的都 Close 然后 ref 到一个 closed issue 里的去讨论，真是活久见。第一次用 GitHub 管理 Repo？
