### ISSUE TITLE
建议评论稍微怂一波…

### ISSUE THREAD

**Issue by Rangooo** [sikaozhe1997/Xin-Yue#69]
这篇【帖子】存在的意义在于传播，即让尽可能多的人了解这件事。在事实基本清晰，是非黑白明确的情况下，评论里某些激愤的情绪表达或者对抗对于传播是只能起到反作用的，反而给了auth封堵本帖乃至全站传播的正当借口…就当是为了保存火种，评论怂一怂吧，虽然可能还是改变不了什么结果…

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
