### ISSUE TITLE
[Discussion] 

### ISSUE THREAD

**Issue by haoyuc1** [sikaozhe1997/Xin-Yue#706]

**Comment by haoyuc1** [comment]
并且，我个人是不认同在github上发布此类可能会影响社区氛围的内容的

**Comment by vzxxbacq** [comment]
个人认为现在的 Gitpage 作为项目内容的展示已经足够了，如果您希望在 Gitbook 上存放的话，可以阅读[README中的版权部分](https://github.com/sikaozhe1997/Xin-Yue#%E7%89%88%E6%9D%83%E8%AF%B4%E6%98%8E)，自行上传。

**Comment by aforwardz** [comment]
我认为此类还是放到gitbook上比较好

**Comment by hiliyi** [comment]
还是这里比较适合装逼，gitbook那就太纯粹了。

**Comment by haoyuc1** [comment]
@vzxxbacq 如果对你们来说不方便的话，我可以组织人群放入Gitbook，但我希望在此之后能删除Github上的内容，或改为链接指向gitbook 或改为private。希望能采纳意见，我认为这是应对现有社区利益间矛盾的最好的办法。希望原组织者不要意气用事，维护社区人员的利益并且也维护你们的利益，何乐而不为呢？

**Comment by kdurant** [comment]
支持 @haoyuc1 ，这些东西放到github上并不是很合适

**Comment by pangjunpeng** [comment]
同感。国内的家丑放到全世界都能看到的开源社区，不太好吧

**Comment by oldtree** [comment]
分享，协作，传播......最主要的传播你们拿去了，别人想要的任何伸张你们都像官衙门一样说不合适，那都tm滚回墙内去，那里天生适合你们

**Comment by ewrfedf** [comment]
别人吃饭的地方，突然来个人在这里拉屎，真恶心。

**Comment by aforwardz** [comment]
@oldtree 不是说不能伸张，伸张也要有礼有节，我认为在这里伸张并不合适，况且，有另外更合适的平台。就像你去SO上问今年应不应该在中国买房一样，并不合适。你当然可以说这里没规定不能发这些内容，作者的这些文章记录都是很好的资料，我只是认为这些应该放在更合适的地方，而不只是因为github上人多传播性好。不然和去国外蹭红毯的明星有什么分别？

**Comment by vzxxbacq** [comment]
@haoyuc1 
您可以自行说服Github官方，或去#530 说服Owner，我是无所谓的。就个人来说，我也认为这种行为不值得提倡，Owner明显不是编程相关的人士，也许只是一时情急的T大知情人士，我们不能对这样一个太过分的指责，相信他现在也有些慌吧。既然repo已经开了，我只是不希望这里成为对政府不满者大放垃圾词的地方。把repo做成一个中立的文档管理库，您要是能觉得您有方法能帮助Owner，请与他交流。

**Comment by oldtree** [comment]
@ewrfedf
你吃饭的地方在你家茅厕,滚回去复习通识教育，被扭曲了的滚去看外文版

**Comment by vzxxbacq** [comment]
不要发表无意义的指责和谩骂。 @oldtree

**Comment by aforwardz** [comment]
@oldtree 前两句说“不限定程序员专用”，“工具中立”，第三句又说“程序员的工具”，你的潜在认知是否有矛盾？
我从不反对也很支持理性讨论这件事，“合不合适”每个人的看法也不同，“不合适”是我作为一个程序员的角度，除非哪天社区明确规定不准代码无关，或许我会更有底气
如果哪一天，github上，代码repo，这种repo，买房repo，娱乐repo等等，不一而足，多样繁荣，我会很失望。即便目前从社区协议上看，我没有立场。。
Over

**Comment by haoyuc1** [comment]
@oldtree 我并不反对你说的最后一段话，所以我提出了移步gitbook的解决方案，我认为移步gitbook满足了所有人的利益，并且也包括你说的这些需求，是更有效合适的手段，这还有什么可反驳的呢？当然在这里和你争论没有意义，我还是去和owner说了

**Comment by vzxxbacq** [comment]
讨论似乎又回到该不该放在Github上了，我先关闭这个issue吧。可以移步#530 讨论

**Comment by RockyQu** [comment]
感觉这个就像大学时的辩论会，各自都有自己的理儿，双方激烈讨论，但是事态是向着好的方向发展的，别正聊着呢，TM的就上来了，文明辩论，理性讨论

**Comment by frozenL** [comment]
从参与度上讲，这个repo成功引起了7k+人的注意，这一点gitbook是做不到的，gitbook 450k和github 27million+的用户数量相比还是差了点。

btw，这个repo只是一些人建了一个个人网站，host在github.io上，恰好很多码农contribute了一下，热度高了一点，repo整体结构从无序到有序，现在可以在[网页下](https://sikaozhe1997.github.io/Xin-Yue/#/)留言。意外发现gitalk 不错不错。。。

**Comment by yxtinsz** [comment]
那些只知道从github获取自己所需要的项目和信息的人知道开源的意义吗？开源存在的根本就是自由、共享和平等。就算这个议题不适合发在github上，那你们不能友好的建议和帮助吗？只要不违法github的规定，就没有正当理由去指责开这个issue的人啊。如果只抱着一副github是小众并且对除coder以外所有群体排斥的态度，那为什么不回墙内的csdn呢？

**Comment by w3nchao** [comment]
十分同意 **GitBook 明显是更适合的方式**。

引用之前的评论。

https://github.com/sikaozhe1997/Xin-Yue/issues/530#issuecomment-385559723

不是不能发在github上，只是发在github是单纯的蠢而已。

有什么优点？你需要版本控制？你需要多方频繁协作？恕我直言，总共就二十来篇几乎不会被频繁修改的文章，根本没有必要放在github上。不是不能，是完全没有必要。

而在几乎不能带来任何收益的情况下，导致的是风险。

什么样的风险？整个 github 被墙。整个研发效率降低，学习成本增加。不仅仅是个人，也包括公司。

这些事儿当然需要讨论，但是以github被墙为代价，是绝对得不偿失的。

更何况，社会的变革基本不是靠讨论来推动的，社会的变革是靠科技进步生产力的发展推动的。如果讨论和科技变革有冲突，那我宁愿少讨论一些。

女权，是靠几个女性赤身裸体举着牌子说我可以骚你不可扰，来提高女性地位进步的？不是，是靠生产力的发展，让女性生理上的劣势得以消减，使女性可以创造不低于甚至高于男性的价值。在农业为主的体力劳动时代里，你再怎么抗议怎么讨论都不会提高女性地位的。

我或许是错的，我也同意如果说根本没有任何的别的办法，只有放在github上才可以，那我们可以争议一下这个潜在风险是不是值得。可是现在的情况是有很多安全高效的方式去传播 ，去引发讨论，同时不以github为代价。为什么不呢？

为什么一定要用笨拙的风险极大的方式去做一件你们觉得无比重要神圣的事呢？

我真的不理解。

不是说程序员抵触讨论政治事件，而是程序员习惯以高效率低风险的方式解决问题。

而这，真的蠢爆了。

**Comment by w3nchao** [comment]
@yxtinsz 

> 那些只知道从github获取自己所需要的项目和信息的人知道开源的意义吗？开源存在的根本就是自由、共享和平等。就算这个议题不适合发在github上，那你们不能友好的建议和帮助吗？只要不违法github的规定，就没有正当理由去指责开这个issue的人啊。如果只抱着一副github是小众并且对除coder以外所有群体排斥的态度，那为什么不回墙内的csdn呢？

有更好的方式为什么不用？为什么一定要以整个研发效率降低，学习成本增加的代价去做这些事。
不是因为对非程序员不友好，也不是因为不愿意讨论，而是觉得没有必要做毫无意义的自残。

明明有安全高效的方式，偏偏不用，一定要用风险大的，以卵击石的，杀鸡取卵，飞蛾扑火，自损八百的方式，我觉得负面效果远远大于正面效果。

如果要讨论，就要想长期的可持续性的利益最大化的讨论，而不是为了姿态为了立场。

**Comment by cthraka** [comment]
GitHub并没有对用法有任何要求。记得在教程里面说过用户想用GitHub做什么都可以，不一定要和计算机相关。

**Comment by gaocegege** [comment]
如果真的担心被墙的可能，个人偏向支持放在 GitBook 上，但是没精力也没 permission 去做这件事，需要直接跟 owner 沟通才 OK。

其次，大家讨论的时候请稍微理性一些。我也是码农，不是 GitHub 的重度用户也是中度用户了。我同样在意 GitHub 这个平台，所以真的不需要带着“祸害完你们的 GitHub 就跑”这样的预设立场来讨论问题，都是想解决这个问题，而非树立对立情绪，不是么

**Comment by ewrfedf** [comment]
请注意 GitHub 的定位，为啥搜索的结果筛选都是各种语言而不是各种政治问题，社会问题，这些无聊的话题。

**Comment by ewrfedf** [comment]
有一天，你搜到的都是 XX ，你开心嘛， for all coder

**Comment by Aryastark5339** [comment]
我不知道现在的coder能不能想象上个世纪五六十年代那些信息时代的开拓者们一边吸大麻，冥想，听着披头士，万里迢迢跑到印度去找精神导师，当然，他们也写代码，那是最初的Geek们，不畏权威，挑战一切 foreveryoung。这个开源的社区，有那样的精神在流传。连Geek都不是，coder对你来说又意味着什么呢？只是养家糊口的话干什么不都一样吗？何必敲代码，而且还那么辛苦。移到gitbook是一个合理的建议，只不过你看都快8000star了，就这样吧

**Comment by m5j** [comment]
建议close掉这个ZZ的issue
