### ISSUE TITLE
[Help] 正方有人在人肉我，各位能不能帮帮忙哦

### ISSUE THREAD

**Issue by Woolseyyy** [sikaozhe1997/Xin-Yue#710]
这是一个和项目无关的issue...先说一声抱歉

是这样的，这两天作为反方辩手，和各位在这个repo下进行了“github下是否该发这个repo”的争辩，但今天发现有人在人肉反方用户（[项目地址](https://github.com/JourneyofRock/list))

因为这事也是因这个repo而起，所以很惭愧地在这里发一个这个贴，希望提前知会大家有人在人肉反方...
（貌似我在这个repo和那个人肉repo下同时违反了合理使用github的自我倡议...）

**Comment by gaocegege** [comment]
@JourneyofRock @Woolseyyy 

大家都只是在发表自己的观点而已，也不是非此即彼的，没必要以这种方式进行对抗吧。如果觉得互相看不顺眼相互 block 就好了。在之前 issue 中的不恰当言论，可以在这里说，由维护者们来 abuse 掉。

您觉得呢

**Comment by SniperChen** [comment]
@Woolseyyy 
我们严厉反对任何人肉行为！这在我们的README说的很清楚了。
**无论是支持者或者反对者都不应该以人肉、诽谤、人身攻击等行为参与本repo！**
请各位githubers自觉遵守！

**Comment by vzxxbacq** [comment]
@Woolseyyy 
对于这种行为可以向Github官方举报
> is discriminatory or abusive toward any individual or group;

已帮忙举报
另外，个人觉得对您生活产生影响的可能性较小，毕竟您生活在大陆。

**Comment by huoqiangf** [comment]
人肉就人肉呗。。。反正github都要封了，谁还看得见啊，您说是吗？

**Comment by ethermoto** [comment]
他觉得正方就应该跳坑里淹了，全都得粘到渔网上脱不开身，全都被全面监控，全都毕不了业。

**Comment by jssnow** [comment]
看到你俩的讨论了,支持你

**Comment by JourneyofRock** [comment]
@Woolseyyy 我不是正方，我只代表我自己。你也别把自己的行为美化为反方。

我挂的人都是言语性骚扰或者罔顾事实胡搅蛮缠或者二者兼有之。

我也没有兴趣查看其他正经发言的用户的资料。

如果官方不认可封了那个repo就好。

**Comment by Woolseyyy** [comment]
@JourneyofRock  掐头去尾的谁的话经得住推敲啊 我挂个你的截图你就能被打成轮子

**Comment by kissme666** [comment]
“约吗？？“
叔叔，我们不约！

**Comment by Woolseyyy** [comment]
@vzxxbacq 我更倾向于将那个repo看做是公布前的准备，如果（请允许我做最恶意的揣测）是组织行为的话，那repo本身其实不是公布的地方，会采取更多手段进行公布。我认为让更多人看到他在准备时的repo对我们是一种保护。

**Comment by Woolseyyy** [comment]
@dp199313 @guodong @zhangn1985 是否同意我的看法？如果你们觉得这个issue增加了那个repo的曝光度，从而造成影响的话，我同意close

> 我更倾向于将那个repo看做是公布前的准备，如果（请允许我做最恶意的揣测）是组织行为的话，那repo本身其实不是公布的地方，会采取更多手段进行公布。我认为让更多人看到他在准备时的repo对我们是一种保护。

**Comment by zhangn1985** [comment]
@JourneyofRock 你呢，境外分裂势力无疑，这点大家都不怀疑，你自己也不否认，对于你们境外势力的观点我自然要驳一驳。

在跟你争论惊吓是不是恐吓的时候，我居然还没有发现你是境外分裂势力，居然向你妥协了。真是失误。

我在这里说什么你肯定是不会放弃挂我们的。

多说无意，你呢，好自为之。

**Comment by zhangn1985** [comment]
很多被确认为境外分裂势力的号都是刚注册的，都是鼠辈。不过各位要在大是大非前选择正确的立场。

**Comment by zhangn1985** [comment]
我看了被我点名的几个人，除了有一个人明确是点错了，且我已经道歉。其余的都没错，至少他们自己不否认自己是境外分裂势力。而被我点名的人之中只有 @JourneyofRock 心眼小，估计连境外分裂势力都瞧不上吧。

**Comment by vzxxbacq** [comment]
所以，可以关闭这个Issue了吗 @zhangn1985

**Comment by zhangn1985** [comment]
@vzxxbacq 随意，我帮你们炸出境外分裂势力，记住我点名的人。

其实，你们这些年轻的学生经历这些是非常有意义的，墙外并不是想要的乐土。

如果想做点事，要充实自己，关于中西方政治制度还是要多了解，不仅要了解西方的，也要了解中国的。

两种政治制度都有不少缺陷，都不完美。

西方的过程很好，但是效率太低。
中方的过程不好看，但效率很高。

世界没有完美的东西，选择合适的才重要。

**Comment by vzxxbacq** [comment]
@zhangn1985 您误会了，我只是纯粹心疼这位T大的Owner。我不懂政治，不敢发表高论。

**Comment by zhangn1985** [comment]
中学课本上的：
经济是基础,政治是经济的集中体现,文化是政治和经济的反映.
从这个角度来说，西方的政治制度是不可能凭空嫁接到我国的，我国没有高度发达的私有制。

**Comment by zhangn1985** [comment]
@Woolseyyy 点错名了吧。

再多说一句。

之前我说，“党在你们心中”，意思就是文化，周围就是这种空气。就类似俄罗斯，就算共产党不执政了，还是一党。苏共90年的功劳。起码还要好几代人才能改变，类似的还有东德也一样。

西方的政治制度也不都是多党制，日本就几乎是一党专政了，在野党几乎没有再执政的可能了。

**Comment by guodong** [comment]
我靠，我这么帅啊😄

**Comment by guodong** [comment]
@Woolseyyy 怕啥，大家自有判断，不需辩驳，你说呢？

**Comment by guodong** [comment]
@JourneyofRock 小伙子很有想法，跟我做微商吧，保你一个月喜提宇宙
