### ISSUE TITLE
[Comments] 网民的记忆力越来越短

### ISSUE THREAD

**Issue by QuieroLuz** [sikaozhe1997/Xin-Yue#711]
前天朋友圈就相关事件转发了几小时，然后没了。

昨天中午看到校内某处张贴相关声援内容，今天路过时没了。（考虑了一下图还是不放了）

不知道明天会如何。

**Comment by vzxxbacq** [comment]
图片来源是？

**Comment by QuieroLuz** [comment]
图片为学校内某地张贴物，校名因为可能被黑成“境外势力”不大好说，不过应该看得出。
备注一下图片使用CC-BY-NC

**Comment by clong365** [comment]
我想起了林昭，记忆不短吧？
1954和2018

https://zh.wikipedia.org/wiki/%E6%9E%97%E6%98%AD
