### ISSUE TITLE
[Comments] 岳昕，真英雄也

### ISSUE THREAD

**Issue by ShihchenWEN** [sikaozhe1997/Xin-Yue#713]
得知京师岳同学之英勇举动，自愧不如，羞愤难当。若将我置于岳同学之境地，怕是也难支持得了几个来回。身处异地，无法动身赴京声援，算得上此生一大憾事。然而事已至此，于千里之外传达岳同学的声音，也权当尽自己的一份力量，良知稍为安顿。昨夜挑灯将“湖底群魂”诸义士之墨宝处理清晰，颇为发布，亦做纪念。当然，折损账号若干，此为后语。后生只识外文，不同代码编程，实志大才疏，但恐恣意妄为，使笔迹之气势蒙尘。北京大学，开放包容自此肇始，学术懿范马首是瞻。于我，北大唯有一个，因为有司诸公的北大衰朽如渣滓，于自由、进步的北大何干？
若沉默竟成美德，诸位是否甘心向遗忘妥协？
![page1](https://user-images.githubusercontent.com/25520813/39369574-41fafd90-4a6f-11e8-8858-3fa06823a62b.jpg)
![page2](https://user-images.githubusercontent.com/25520813/39369585-43ec4f6e-4a6f-11e8-873a-28b2ea28151c.jpg)
![page3](https://user-images.githubusercontent.com/25520813/39369593-46fad8b0-4a6f-11e8-988c-f48ef6043475.jpg)

齐鲁大学 文十成

**Comment by vzxxbacq** [comment]
具体对文章的评论可以前往Gitpage进行评论，issue主要用于内容的增删与代码的维护讨论。
