### ISSUE TITLE
[Proposal] 利用现有的区块链虚拟货币的备注功能保存文章

### ISSUE THREAD

**Issue by zombie110year** [sikaozhe1997/Xin-Yue#715]
今天在土豆公社看到一片文章
http://tootopia.me/article/10336
里面提到一个利用以太坊货币可以支付0额度,然后可以在备注中留下信息的特性传播文章的例子,感觉这对我们保存文章是有利的,我们是否将一些敏感的文章使用类似的方式在区块链里传播呢?

以下是例子,就是咱们这个事的,点击转换utf-8就可以看到中英文信息了(不知道是谁干的,至少现在github上没看到相关的issue...).
https://etherscan.io/tx/0x2d6a7b0f6adeff38423d4c62cd8b6ccb708ddad85da5d3d06756ad4d8a04a6a2

**Comment by AnyWAT** [comment]
公开信被写入以太币区块链 #158 
https://github.com/sikaozhe1997/Xin-Yue/issues?utf8=%E2%9C%93&q=%E5%8C%BA%E5%9D%97%E9%93%BE

**Comment by vzxxbacq** [comment]
已有很多相关issue，文章您可以阅读版权说明自行保存
