### ISSUE TITLE
[Help] 请求各位g友也帮大理工陶崇园仓库添加个GitPage服务

### ISSUE THREAD

**Issue by DFVSQY** [sikaozhe1997/Xin-Yue#725]
北大和武汉理工现在成了难兄难弟了，北大这边很热闹。
为此也请求g友援助一下[陶崇园仓库](https://github.com/lonufate/ArchivesOfTaoChongyuan)，帮助陶的事件也创建一个gitpage服务，多谢了。楼主慎关！

**Comment by xinmu99** [comment]
已经pull request。[样例]( https://peacecn21st.github.io/ArchivesOfTaoChongyuan/#/README)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39403618-af07fc46-4bb2-11e8-843e-872757bae2fd.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39407584-a022d73a-4bfa-11e8-90a6-bcf627d456c8.png)
