### ISSUE TITLE
[Proposal] 发布release，将网站内容生成html然后以供下载分发？

### ISSUE THREAD

**Issue by Yrr0r** [sikaozhe1997/Xin-Yue#726]
<h3>是否可以考虑直接生成html格式网站然后发布到release？这样可以方便其他人直接下载。另外也建议release发布方便阅读的格式（如PDF，EPUB），方便归档和分阅？</h3>
-----

>另：
>我写这个issues的时候已经对中国人的素质基本绝望了，看来我们只能在自己的小圈子里孤军奋战，对多数人的素质永远不能抱有一丁点希望。
>改：反不反对建墙不是问题，问题是墙内孤岛繁华，里面的人对自己在墙里这件事没有感觉，他们的素质提升很大程度只取决于政府态度。

**Comment by SeaHOH** [comment]
现状已经足够，加个 gitalk 都是不得已而为之。

**Comment by wql7013** [comment]
可以考虑弄个gulp自动化生成，你有时间也可以弄一下

**Comment by chengdong0421** [comment]
出版成书比较好

**Comment by SeaHOH** [comment]
@chengdong0421 你来？

**Comment by ethermoto** [comment]
一个两个素质问题可以认为是噪点。
群体性的素质问题，那可能就是不合适提高素质的信息洗的太多，合适提高素质稀缺。那么更应该breakwall打破铁幕，经受更广泛的信息冲刷，该是什么样就会是什么样，那时候再说，是不是真的素质低，也许才会有比较客观的认识。

**Comment by Yrr0r** [comment]
现在breakwall的开发圈子本身就很乱，各种黑心运营脚踩开源许可冒充官服抢流量，毕竟是个暴利行业，服务器搭上坐着数钱就行，反倒开发吃力不讨好还容易被喝茶
对打破铁幕希望不大了，这个局域网内部已经相当繁华，多数人都不在乎墙外的样子。能自己搭梯子的也不会怕这些玩意，叫嚣的都是一帮乌合之众，GitHub会不会被墙他们也不怎么关心，只不过是一帮老大哥的傀儡罢了

**Comment by Yrr0r** [comment]
<h1>我Unsubscribe了，这个issue要是不合适就直接close吧，省的踩了</h1>

**Comment by Yrr0r** [comment]
@ethermoto gfw后面有政府，给自己翻墙无所谓，但是让那么多人都翻墙让他们接受合理信息的冲刷，我觉得不大现实。
政府愿意才能让大多数人接受高质量的信息，政府不愿意外加多数人浑然不知，我看没啥希望。
连宣传墙的存在都是“犯法”的，我看还不如独善其身，顺便带上几个朋友。想让那么多人都知道他们在墙里，我觉得很难。偶尔有几个搞计算机相关的能有点了解，大多数人并不在乎。
现在不只是言论自由，连信息自由都有好长的路要走，说不定是有生之年的故事。

**Comment by limjcst** [comment]
看一下[travis的文档](https://docs.travis-ci.com/user/deployment/releases/)，travis支持上传生成的artifacts

**Comment by ethermoto** [comment]
@Yrr0r 天下大势，浩浩荡荡，顺之者昌，逆之者亡。
没必要失望，没必要颓败。仔细观察，认真体验，那么，世界应该是什么样子，不远的未来会是什么样子，会有明显的答案的，或者，是阶段性的答案。尽管每个人的判断会有不同，各个利益群体的诉求也会不同。
回望人类历史时间线，是不难推断结论的。历史总是在不断重演，历史的车轮滚滚向前，过去的永远会过去，未来的一定会来。
认为是对的，自己去做就好了，有同路同伴固然是好，没有，该走的路，要走的路，也是必然要上路的。
这么多年来，至少学历教育程度和数量都是在提高的，数理思想的教化，比思想政治的洗脑，对人的影响更甚，自我觉醒相对就会更容易，组成社会的是每一个人，N分之一的人都变了，整个社会的国家的民族的特征特性，也随之将变，只是时间问题。
认为是对的，坚持忍耐付出奉献，都可以，没有这些，做独狼，也没问题。
高质量的信息，个人认为就是一个有问题的概念。那一朵浪花是贵的，那一朵浪花又是贱的呢？
信息铁幕重重，官样吹舔洗脑，大概也是没有比苏联时期还要严重吧。普遍的数理思想的教育，提高了更多人的信息接收处理输出的能力。只需要打一些软补丁，每个人都可能从486变成7980XE的。
存在即合理，那么，存在也就能是不合理的，差不多是废话了。要找理由是很容易的事，给一个结果编一个因由是很轻松的事，无论是不是有存在真正的因果关系。

**Comment by dyxushuai** [comment]
这个时候 ipfs这样的去中心存储或将更有用
