### ISSUE TITLE
[Proposal]请谨慎利用GitHub发布敏感信息（附解决办法）

### ISSUE THREAD

**Issue by lichuan0620** [sikaozhe1997/Xin-Yue#728]
我支持为真相发声的勇气，也为该事件感到愤慨和遗憾。

但是GitHub是一个属于程序员的工作空间。它还没被封，不代表不会被封。中国各行业的工作者已经失去了太多工具（Google、Pinterest等），在无力反抗的大环境下，请不要竭泽而渔！

自然，我也理解大家对于一个能自由公开信息的空间的需求。所以如果这个repo的主人坚持认为有必要使用GitHub，请在我的github内任意repo下留言建立联系，我有一些折中方案

**Comment by Enter-tainer** [comment]
如果您有这方面的顾虑的话，还请您先读一读#530

另外，不知道您怎么看待Github上一些代理软件的仓库？是不是也要"采用一些折中方案"来保护Github的安全？

**Comment by lichuan0620** [comment]
这些库我了解，甚至我自己也有一个（不是库本身而是一个应用）。Shadowsocks的作者前些年被请去喝茶后采用了折中的办法，我也是在这之后为我自己的repo也做了同样的事。对于还没有对自己的repo做任何保护措施的作者，我觉得他们对自己和自己的工作结果都不够小心。

为了这个环境，也为了自己的安全，也为了自己的repo能活更久呀

**Comment by aifengzheng** [comment]
中共政府不透明、難捉摸的辦事方法成功培養了中國人的自我審查意識。你知道哪些內容是敏感內容嗎？去年，肉包子露餡是在正常不過的話題，然後突然被刪帖了，你知道為啥不？民眾永遠無法捉摸獨裁政府的G點。因此，不在GitHub上發布敏感內容==不在GitHub上發布任何內容

issue主說無力反抗，錯。**非暴力不合作運動**是最有效的反抗方式，它不是立即見效的，而是長年累月累積，而後突然爆發的，就先蘇聯解體一樣。首先，人人都不能聽樓主勸告而**在GitHub上發布敏感信息**，中共僱傭越來越多的五毛黨在GitHub上提刪，中共得付工資給五毛黨，因此教育、基建、醫療、住房等的預算減少。同樣，各地要時常集會遊行，中共必須派軍隊鎮壓，於是軍費必須增加，其他預算必須減少。

後來GitHub上敏感信息越來越多，中共封鎖了GitHub。勤勞勇敢的中國程序員不能上GitHub，必須不合作地**不尋找**代替品，降低工作效率，向上級和同事抱怨。軟件公司因此效率降低，於是外國公司增加在中國的市場份額，促進西方民主國家的GDP。民主國家經濟增強，中國經濟減弱，習近平就不能去非洲撒幣，非洲國家重新向西方民主國家靠攏。在聯合國投票時，中國提出的對自己有利的政策就會被多數否決。

中國經濟變差民不聊生，就會發動革命。

**Comment by zhezhe168** [comment]
github上面比这更严重的政治话题多了去了，在你认为这个话题可能会导致github被封之前，请先联系美国之音，BBC，蓝灯，赛风，自由门，自由之声，亚洲之声等，让他们删除在github上的所有翻墙软件、敏感话题、链接。对了，忘说了，现在国内使用很广泛的shadowsocks，一键安装包的地址就是github的。win，mac和安卓客户端也在github上有下载。
等你把我所说的上述全部删除后，再来担心这个话题会不会使github被封。
做人，要有骨气。

**Comment by liach** [comment]
现在本站还在的原因是好代码都在github上，只要大家继续放好代码就行了，别的花边内容不关我们事。

**Comment by azgh** [comment]
**重读鲁迅作品**

> 聪明人和傻子和奴才

奴才总不过是寻人诉苦。只要这样，也只能这样。有一日，他遇到一个聪明人。
“先生！”他悲哀地说，眼泪联成一线，就从眼角上直流下来。“你知道的。我所过的简直不是人的生活。吃的是一天未必有一餐，这一餐又不过是高粱皮，连猪狗都不要吃的，尚且只有一小碗……”
“这实在令人同情。”聪明人也惨然说。
“可不是么！”他高兴了。“可是做工是昼夜无休息的：清早担水晚烧饭，上午跑街夜磨面，晴洗衣裳雨张伞，冬烧汽炉夏打扇。半夜要煨银耳，侍候主人耍钱；头钱从来没分，有时还挨皮鞭……。”
“唉唉……”聪明人叹息着，眼圈有些发红，似乎要下泪。
“先生！我这样是敷衍不下去的。我总得另外想法子。可是什么法子呢？……”
“我想，你总会好起来……”
“是么？但愿如此。可是我对先生诉了冤苦，又得你的同情和慰安，已经舒坦得不少了。可见天理没有灭绝……”
但是，不几日，他又不平起来了，仍然寻人去诉苦。
“先生！”他流着眼泪说，“你知道的。我住的简直比猪窠还不如。主人并不将我当人；他对他的叭儿狗还要好到几万倍……”
“混帐！”那人大叫起来，使他吃惊了。那人是一个傻子。
“先生，我住的只是一间破小屋，又湿，又阴，满是臭虫，睡下去就咬得真可以。秽气⑺冲着鼻子，四面又没有一个窗……。”
“你不会要你的主人开一个窗的么？”
“这怎么行？……”
“那么，你带我去看去！”
傻子跟奴才到他屋外，动手就砸那泥墙。
“先生！你干什么？”他大惊地说。
“我给你打开一个窗洞来。”
“这不行！主人要骂的！”
“管他呢！”他仍然砸。
“人来呀！强盗在毁咱们的屋子了！快来呀！迟一点可要打出窟窿来了！……”他哭嚷着，在地上团团地打滚。
一群奴才都出来了，将傻子赶走。
听到了喊声，慢慢地最后出来的是主人。
“有强盗要来毁咱们的屋子，我首先叫喊起来，大家一同把他赶走了。”他恭敬而得胜地说。
“你不错。”主人这样夸奖他。
这一天就来了许多慰问的人，聪明人也在内。
“先生。这回因为我有功，主人夸奖了我了。你先前说我总会好起来，实在是有先见之明……。”他大有希望似的高兴地说。
“可不是么……”聪明人也代为高兴似的回答他。

文豪就是文豪，可惜没人看懂，国人还是国人，老调仍可重弹。

**Comment by liach** [comment]
https://github.com/greatfire/wiki/issues/3#issuecomment-87524291

**Comment by brucefeynman** [comment]
有做一个一键上链的网站，可以用区块链来保护信息。
日后会deploy到IPFS上达到完全去中心化
www.onchain.click

**Comment by ethermoto** [comment]
自我审查还真是深入码心

**Comment by Orangem21** [comment]
被封是我们的错吗？
你是不是反抗错了对象？

**Comment by Orangem21** [comment]
>自己有骨气是值得钦佩的，不要拿别人的利益做代价。

这么说，你为了你的利益放弃了你的骨气

**Comment by megatree** [comment]
如果你不能做些什么，那就呆着就好，不要阻碍做事的人

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39461945-c54f0bea-4d40-11e8-8506-636ae7424d8c.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39507537-edeacb7c-4e10-11e8-9428-b2b113ef9a4a.png)
