### ISSUE TITLE
public letter

### ISSUE THREAD

**Issue by ghost** [sikaozhe1997/Xin-Yue#73]
Peking University teachers and classmates:

Thank you for your♂attention!

I am Yue Xin from the 2014 Foreign Languages Institute. I was one of the eight students who submitted the Information Disclosure Application Form to Peking University on the morning of April 9. I dragged my tired body and wrote this text to illustrate some of the things that have happened to me recently.

## part one

After April 9th, I was constantly interviewed by faculty members and leaders of the college, and it continued twice until midnight or even two. During the conversation, the student teacher repeatedly mentioned "Can you graduate successfully," "Do what your mother and grandmother do," and "Student teacher has the right not to contact you directly by your parents." While I was preparing my graduation thesis recently, frequent interruptions and subsequent psychological pressures severely affected my thesis writing.

## part two

At noon on April 20, I received a reply from the school. The Secretary of the Party Committee of the School of Foreign Languages, the teacher of the Xuegong and the head teacher were present. The secretary of the Party Committee read to me the answer to the open information application of the school:

1. Discussing that Shenyang Shide's meeting level is not enough
2. The investigation results of the Public Security Bureau are not in the scope of school management
3. The content of the public review in Shenyang was not found due to work errors in the Chinese Department.

The result of this reply disappointed me. However, the submission of graduation thesis will soon be closed, I can only focus on thesis writing.

## part three

At about 11 pm on April 22, the counselor suddenly called me, but because the time was late, I did not receive it. At one o'clock in the morning, the counselor and his mother suddenly came to my dormitory and forced me to wake up and asked me to delete all the information related to the information disclosure incident on my mobile phone and computer. After dawn, I went to the teacher to make a written guarantee Involved in this matter. Students on the same floor can testify. Later, I was taken home by my parents and I can't return to school at the moment.

My mother and I were awake all night. Schools misrepresented the facts when they contacted their mothers, causing mothers to be overly frightened and emotionally collapsed. Because of the unreasonable intervention of the school, my relationship with my mother was almost broken. The current action of the college has already broken the bottom line. I feel fear and anger.

What is the crime of applying for information disclosure? I did not do anything wrong, nor would I regret having submitted the "Information Disclosure Application Form" to exercise my honorable rights as a college student in Beijing.

Twenty years of envy, I love my mother. In the face of her sorrowful cry, self-sacrifice, kneeling requests, and threats of suicide, my heart is bleeding. In her plea, I can only return home temporarily, but I can't stand back from principle. Compromise can't solve any problems. I have no choice but to write this statement and state the story.

Emotional, please forgive me for being incoherent.

## part four

Here, I formally submitted the following demands to the School of Foreign Languages of Peking University:

1. The School of Foreign Languages of Peking University should openly state in writing the rules and regulations on which I have pressured parents, forced me to interview me in the morning and asked me to delete the relevant information on the disclosure of application information. Illegal and non-compliance operations should be clearly defined during this process. And take measures to prevent such incidents from happening again.
2. The Peking University School of Foreign Languages should immediately cease all acts of pressure on my family, formally apologize to my already frightened mother, clarify the facts, and help repair the family tension caused by the incident.
3. The School of Foreign Languages of Peking University must make an open written guarantee that this matter will not affect my graduation and will not continue to interfere with my dissertation writing process.
4. The School of Foreign Languages of Peking University is responsible for eliminating all adverse effects of this matter on my studies, future employment and family members.
5. The School of Foreign Languages of Peking University should make a clear written response to the appeal and give it to everyone concerned.

I will retain all legal rights to further investigate the responsibilities of relevant individuals and units, including but not limited to reporting to Peking University and higher authorities the serious violation of school regulations by the Foreign Language Institute.

Peking University School of Foreign Languages

April 23, 2018

**Comment by WUKong-YhC** [comment]
支持！

**Comment by zhangyz1997** [comment]
那句How are you感觉怪怪的

**Comment by evzlk** [comment]
@zhangyz1997 已经修改

**Comment by guoqing-tang** [comment]
老哥，你简直要笑死我了。哈哈哈哈，本来中文的一二三 四都翻译成了one，two，我刚贡献给谷歌翻译成part one，how are you要改成Thank you for your attention。

**Comment by Medesol** [comment]
Fuck you可还行

**Comment by GkyHub** [comment]
fxxk you优点过分了……

**Comment by GkyHub** [comment]
fxxk you 有点过分了

**Comment by WUKong-YhC** [comment]
在事实清楚、证据情况下没必要用过于偏激的词语，容易落人话柄。

**Comment by guoqing-tang** [comment]
第二句这样翻译过分了，而且全文大部分还是Google translate的。调侃调侃行了，别把GitHub也弄得乌烟瘴气的。

**Comment by jaegerstar** [comment]
提交PR吧

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
