### ISSUE TITLE
[Proposal]木·田：我在公开信后的一周里

### ISSUE THREAD

**Issue by FormotherChina** [sikaozhe1997/Xin-Yue#730]
[木·田：我在公开信后的一周里](https://sdxf34.gq/archives/4254)

求添加这篇文章。我个人表示读完非常气愤。

**Comment by kilobtye** [comment]
谢谢！我已经在添加了

**Comment by wql7013** [comment]
个人是制度的受害者，包括那些老师和家长，需要改变的是制度，你身边的每个人都可能会因为制度而变得不好。

**Comment by FormotherChina** [comment]
原载于公众号 “木田君的镐头”，并且github上也fork过了，可以直接添加这个md文件。https://github.com/DeboutSQ/Xin-Yue/blob/master/木·田：我在公开信后的一周里.md

**Comment by kilobtye** [comment]
文章已添加。不过 gitalk 评论貌似我没有权限初始化，等评论有了这个 issue 就可以 close 了。

**Comment by wzhb** [comment]
今天新发的已经被删了

**Comment by vzxxbacq** [comment]
@kilobtye 已添加Gitalk~

**Comment by SeaHOH** [comment]
>今天新发的已经被删了

这说明记录是完全有必要的，而且放在这里也好，大家都能看见。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/44000292-c86b2056-9e4f-11e8-99c7-6bbc083c4650.png)
