### ISSUE TITLE
关于前几天我攻击@zhangn1985 的声明和道歉

### ISSUE THREAD

**Issue by ge8528** [sikaozhe1997/Xin-Yue#735]
前几天我由于愤慨使用大号对@zhangn1985 进行了残酷的人身攻击。
此事造成我大号被封。因此注册小号前来声明。

1. zhangn1985此人大脑结构异于常人，估计来至某肮脏恶心的粪池。
2. zhangn1985的DNA丢失大量具有人性的基因，混入了大量不良基因，因此失去基本人性
3. 我对我的同胞的遭遇感同身受。因此过于愤慨，但是祸不及家人，因此不应该辱骂了他的家人，但是其家人也有过错，为什么不教育好这厮
4. 我不应该够狗逼骂人。狗无罪。。。
5. 由于一贯不与没有人性的人辩解和讨论，所以我依然拒绝和zhangn1985之流讨论
6. 大爱无疆，我对任何地方的同胞的不公平遭遇都感同身受。

因此@zhangn1985 我对你说过的那些辱骂的话语，依然有效，并且无数次的继续使用这些语言诅咒你。

对于我对版面造成的不良影响表示对关于此事件的人道歉（不包含 zhangn1985）。

**Comment by ethermoto** [comment]
可惜啊，带鱼侯的名号，多几个就好了，带鱼公，带鱼跛，带鱼子，带鱼烂，带鱼丝，多些名号才好封赏嘛。

**Comment by zhangn1985** [comment]
看来Github的反馈很有效吗。

各位看官，我简单说一下这位为什么要攻击我，原因很简单，我承认我是自干五，没错，我是一个从美分转变过来的自干五。

为什么，对中西方政治制度的学习和比较，自然的觉得中国的制度更有优势，所以自觉的去宣传。

为什么之前我是美分，外媒，直到现在都是掌握舆论的高地，不然怎么现在还有很多人认为西方制度才是最好的。

为什么我会转变成自干五，国家在党的带领下确实强大，西方的社会却在不断暴露出更多的问题，而我也在不断的学习，对比。

比如最近学习的“华盛顿告别演说”，华盛顿明显不支持多党制，要美国人时刻提防外国势力。这个跟中国现在有何不同？

从你再次对我进行人身攻击来看，你确实不会成长。

**Comment by ge8528** [comment]
@zhangn1985 哎呀，你知道粪坑里面的蛆虫也能成长吧，只是变成苍蝇而已，本质一样既然吃屎。你就是那吃屎的蛆。至于苍蝇的声音本来就不重要，你只需要继续吃死，然后被拍死就对了
你那些丑陋的理论都不值得讨论。

**Comment by zhangn1985** [comment]
你确实不入流，从 https://github.com/zuoge85 的repo看，你也不过是国内的小程序员。

在底层苦苦挣扎，现实社会中估计是唯唯诺诺，也就敢那键盘骂骂人。

你还是要认清现实，中国崛起必然会实现，到时候你怕不会气得自杀哦。
