### ISSUE TITLE
多大的事情有啥好封的，无非就是内容或者来源有问题。

### ISSUE THREAD

**Issue by whisperfairy** [sikaozhe1997/Xin-Yue#745]
因此可得结论，该仓库作者无聊到爆炸，要是国家是靠你们这种天天扯犊子的人强起来的，还要我们这些做技术的做啥。有时间不会去写点核心代码嘛，现在缺人做芯片知道吗。

**Comment by ethermoto** [comment]
朋友，你一定不知道一个秘密，芯片研究设计制造的任务全部委派给全国各地中医院了，责成全国著名老中医团队以黄帝内经、易经、太极阴阳五行思想为指导，采用丹道古法配伍，办全国水陆道场加持，以火焰山为地炉，进行通用型量子芯片烧制，此种方法烧制出来的量子芯片不用做旧，自带釉膜包浆，功耗极低，性能极强，顶级品质，可使我国一举成为全球芯片顶级领导者。

**Comment by fact-orial** [comment]
@ethermoto

这位C#码农，能不能别把JavaScript码农当傻子？

**Comment by Seedarchangel** [comment]
做芯片也不是靠js的，朋友。

**Comment by ethermoto** [comment]
@ghost 谁告诉你是C#码农的？我很尊重前端从业者的，JS是全宇宙最强语言，请不要引战。其实大家都知道，PHP才是最好的。
