### ISSUE TITLE
[Bugfix] README.md 中“这个库用来干什么”已经不能涵盖目前内容

### ISSUE THREAD

**Issue by hunt978** [sikaozhe1997/Xin-Yue#746]
详细见[ issue#723 ](https://github.com/sikaozhe1997/Xin-Yue/issues/723)中讨论。

摘录如下：

文章：“岳昕：新年献词--2017的三个追问”相对照

> 这个库用来干什么
客观公正的记录整个事件中的过程，以及各家发出的声音。
监督学校的行为，为保护岳同学尽一点力量
如果您有其他的目的及用途，fork this repo and do whatever you want.
质疑这个库为什么存在，您可以前往 Repo讨论

存在：

- 其一、所收录的文章并没有在记录事件的发展过程；
- 其二、所收录的文章不属于各家发出的声音
- 其三、所收录的文章并没有监督学校行为
- 其四、所收录的文章不属于保护岳姓同学
- 其五、本仓库不是fork仓库，不具备“do whatever you want”的权力
- 其六、所收录的文章没有在讨论库存在合理性

等问题，请尽快修复。

**Comment by ethermoto** [comment]
bugfix嘛，着急什么，慢慢来，信息汇集是需要过程的， 是需要消耗时间的，repo那么多，高质量的总归还是少数，高质量也不是能急出来的。

**Comment by Aryastark5339** [comment]
这个发帖是不负责任的，你没有说清楚你的问题，任何一条都没有说出依据和进行解释，还煞有介事的列出六点，这是捣乱，是在拆台（这是一个开源的库，你可以参与到它的建设中来，提高他的质量，而不是像这样，你没有表达建设性的东西）

关于你所涉及的问题，我看可以要增加一句
“本库亦收录岳昕同学今年早些时候的个人写作，兹备以对其人其文增加了解”
就可以了，做这项改动30s都不需要

**Comment by wql7013** [comment]
这篇文章是我添加的，刚开始我也觉得关系不大，细读之后觉得有必要添加，一是理解木田同学为什么这么做，二是呼吁大家关注社会。

**Comment by hunt978** [comment]
@Aryastark5339 你的提议很好，是解决前述问题的方法之一。即增加：

> “本库亦收录岳昕同学今年早些时候的个人写作，兹备以对其人其文增加了解”

请管理员予以考虑。 @vzxxbacq  @sikaozhe1997

**Comment by hunt978** [comment]
@wql7013 是否将你的这一初衷加入README.md的说明中？

>一是理解木田同学为什么这么做，
二是呼吁大家关注社会。

**Comment by killTheHostage** [comment]
看外媒报道，据说这件事情高层的定性是【颠覆】
消息来源不确保真实性
如果是真的，那github真的成了境外反动势力了
[报道连接](https://buff.ly/2FFox6x``)

**Comment by SeaHOH** [comment]
>@wql7013 是否将你的这一初衷加入README.md的说明中？
>>    一是理解木田同学为什么这么做，
>>    二是呼吁大家关注社会。

反对这个提议， Aryastark5339 的修改建议完全可以覆盖这点。
而且呼吁什么的，不需要，摆出事实就好。
