### ISSUE TITLE
听说本gitpage获得了GFW认证，真假？（从ZeroNet获知）

### ISSUE THREAD

**Issue by funny110** [sikaozhe1997/Xin-Yue#748]
我从ZeroNet看到的。
所以还是建议repo主搬到ZeroNet为好，在ZeroNet无拘无束，自由讨论。

**Comment by wydwww** [comment]
Duplicated with https://github.com/sikaozhe1997/Xin-Yue/issues/600 https://github.com/sikaozhe1997/Xin-Yue/issues/741#issuecomment-385988330

**Comment by Ghostineuro** [comment]
其实可以重开issue，介绍一下零网的。
然后，怎么找到你？我尝试了一下零网，并没有看到你说的被墙消息

**Comment by funny110** [comment]
@Ghostineuro 
帖子在这里。http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/1SunAWK2VUT9GQK32MpwRfFPVgcBSJN9a/16CWdkXYYRnpct8GYS7GgD6yFcJHPXfMy8/1525265776

**Comment by Ghostineuro** [comment]
谢谢，不太会用。。没有节点。。挂代理都不知道怎么弄
Github这一点反而优于zeronet。。
我觉得zeronet发展到最好，可能就是被repo主接纳作为备份发文地址。。

**Comment by Ghostineuro** [comment]
Download profile site
User's profile site not loaded to your client yet.
看不到内容，好不容易有了节点
