### ISSUE TITLE
声援公民岳昕

### ISSUE THREAD

**Issue by GaMaRui** [sikaozhe1997/Xin-Yue#749]
我知道大家了解事情的经过。为了阅读需要，我还是简短地总结一下：4月9日，包括北京大学学生岳昕在内的八位同学向北京大学校方递交了《信息公开申请表》，要求公开学校在1998年对教师沈阳的行政处理信息，沈阳在一篇4月5日发布的网络文章里被实名指控在任教北大中文系期间对女生高岩实施性侵，最终导致高岩在1998年3月自杀。4月23日，岳昕发表公开信称自提交申请起自己不断受到校方施压，严重影响了她的生活，她为此向校方提出了多项诉求。

再补充几点信息：
—— 1998年的调查结果显示高岩为自杀。案件已经过了法律时效。
——发布实名指控文章的作者系北京大学社会学系1995级本科生、高岩生前的闺蜜李悠悠，现居海外。
——沈阳在文章发布不久后做出回应，否认一切指控。

以上且只有以上为事实部分
——————————————————————————————————————————————

太平洋彼岸的蝴蝶轻拍翅膀，引起了席卷全球的发声运动。

我起初并不认同岳昕和她的同学的做法。他们的做法让我很自然地联想到另一群学生，在那个充满理想和浪漫气息的季节，尽情地燃烧激情，在暗夜中划出炫目的轨迹，然后坠落。那起事件在今天看来就是一场巨大的内耗，我持否定态度。当时的学生空有热血，缺乏方法。他们似乎有一万种着陆的方式，但有十万条理由导致他们没有那么做。更凄惨的是时至今日他们并不被记得，甚至不被知道。

随着我的了解深入，我开始意识到岳昕和她的同学不是不讲求方法。从资料中不难发现，岳昕本人一直在关注性侵害的有关问题，并且一直在推进防性侵机制在校园的落地。通过她在文章中的思考和见解，我也能感觉到她不只是“勇士”，不会“为了反对而反对”。我反复地重新推演这件事，结果是我发现在同样的情景里我会做出差不多的事。我只能从结果来论，岳昕和她的同学向校方申请信息公开的做法欠妥。

对于高岩自杀事件，在法律层面上已经不会再有争议了。对于李悠悠的实名指控，我们应该客观地看待。虽然后来陆续有一些别的印证，使得指控具有相当的可信度，但是，这没有办法还原20年前的事实真相。或者试想，假设沈阳确实对高岩实施了性侵害，如果高岩当时立刻寻求有效的帮助，或是留下证据，或是李悠悠在事后的调查中实名指控沈阳，事情就会变得非常不同。因为不能在法律上继续追究，所以岳昕和她的同学希望借助舆论来声讨沈阳，向校方申请信息公开是其中的一个步骤，这也显然触碰到了校方的敏感神经，导致了后来发生的事。

在防止性侵害方面最重要的工作是加强教育，普及知识，没有这一点作为前提，一切的法律，机制都形同虚设。因为性侵害大都发生在权力不平衡的关系里，其中掌权者有太多腾挪的空间方便他们施展罪恶，这时候弱势者所拥有的，对于性侵害的认识和应对方法才是唯一的出路。

至于校方4月9日之后对岳昕的做法，我不做过多评论。我讲一件发生在“另一群学生”中的小事：某天，一名学生领袖在一天之内多次“镇压”了来抢夺广播台控制权的学生的“叛乱”之后说，“我开始理解为什么XX要镇压我们了。”

但是我要聊几句自由。我们总是或多或少地对自由抱有幻想，认为自由是我们应该无条件获得的，大多数情况下还得由掌权者保障，其实不是。学者吴伯凡对“自由”一词下过一个精彩的定义，“自由就是什么都要由你自己来干，你自己来认知，你自己做选择、做决策、做判断，而且你要承担这个选择和判断的后果”。换句话说，自由不会白白降临，也不允许白白拥有。所谓“北大精神”就是在诠释这一点。我对“北大精神”的粗浅理解是，拥有独立性和多样性的精英群体对于强权的制衡。这里的“强权”是一个宽泛的概念，比如说：

强权可以是畸形的社会观念，它盘踞在我们的思维里，控制着我们的行为方式。面对社会上“不敢扶老人”的观念日益牢固，时任北大常务副校长吴志攀说：“你是北大人，看到老人摔倒了你就去扶。他要是讹你，北大法律系给你提供法律援助，要是败诉了，北大替你赔偿。”

这就是我理解的北大精神。只有在与强权的博弈中达到某种平衡，自由才会出现。

无疑，岳昕和她的同学正在践行北大精神。

**Comment by vzxxbacq** [comment]
欢迎您前往Gitalk讨论

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/44000292-c86b2056-9e4f-11e8-99c7-6bbc083c4650.png)
