### ISSUE TITLE
Proposal：新时代，新青年

### ISSUE THREAD

**Issue by lcx19950201** [sikaozhe1997/Xin-Yue#750]
纵观我们走来的千百年，学生这一群体的力量被最大限度的放大的时候是民国。国家危难，社会上需要一个群体站出来，为民族呐喊，为自由呐喊。
反观今天，我们身处在新中国，学生群体的“自由呐喊”被体制最大限度的限制了，现在培养的大学生，无可厚非，都是十分优秀，十分杰出。但这无疑都是“体制内的优秀”，（这里不是说我们国家的体制不好，我们国家的体制很好，但同时也存在着部分问题，而我们就是要在时代进步中不断修正这些问题）
“体制内的优秀”作何解？
1、思想上的奴性，从小我们所接触的教育教给我们：老师在学校就是你的爸妈，打你你不能还手，骂你你不能还口，我们对老师的惧怕和隐性遵从都是从小接受的教育导致的。这也导致了我们的校园出现了一些“沈阳之流”
2、学校的强权性，纵观全球，只有两个国家在学校与医院等民生机构架设了政治机关。当然，这也使我们的思想走向更为正确，同时也会导致这些机构的强权性。学校是否有权利强制约谈学生，限制言论自由，给学生家庭施加压力。（md这感觉不是学校，像51号似的）学生在学校的强权下学习，自然而然也就默认学校的这种强权性，学校也就习以为常。其实这是畸形的社会观念，学校虽然作为学生的第二家庭，但是也有着不可逾越的界限
3、学生的沉默，小时候家庭教育我们，看见别人打架就跑快点，不要管闲事。我相信不会有那个的成长经历例外。我们都习惯了冷眼旁观他人之事，事不关己高高挂起。这就是我们很多社会问题的根源，例如“扶老人”，有人挺身而出，但其他人却袖手旁观。其实，我们学生要敢于说“不”，像当初在天安门喊着“还我河山”一样。沉默让问题的种子生根发芽，遇见问题不能像某某一样，避之不谈，反而我们更加应该将问题拿到台面上来，开诚布公谈，切切实实的解决。
归根结底，学校——人类知识的传承之地，是神圣的，是不容亵渎的。不能将那些肮脏的社会行为照搬到思想自由的学校。

**Comment by vzxxbacq** [comment]
欢迎您前往Gitalk讨论
