### ISSUE TITLE
中国有太多的黑暗与无赖，蝗虫遍地，遍地豪强。这种事情在当下是“不痛不痒“的“小事”，这种事情不该发在 GitHub 上面，讨论无益。请不要利用程序员的单纯，高 Star 数令人汗颜。。。

### ISSUE THREAD

**Issue by leonall** [sikaozhe1997/Xin-Yue#751]

**Comment by Aryastark5339** [comment]
对不起，我是程序员，我认为你的行为才是令人汗颜的，对我来说你存在的意义还比不上我面前的这台机器。另外你无视发帖规则，纯粹的标题党，所以我觉得你不是程序员，只是想写一个长标题闹事的人。请管理员关闭这个issue

**Comment by dean5277** [comment]
程序员只是个职业，而我们却是国人。
而且，程序员并不单纯。

**Comment by haigendong** [comment]
github.cn

**Comment by NEPTLIANG** [comment]
高star数还不能说明什么吗？

**Comment by TaurusD** [comment]
“蝗虫遍地”。。。你怕是从香港渔村潜进来的汉奸吧？

**Comment by AnyWAT** [comment]
RT @shawnchou97 中國大陸高校最後一個學生自治bbs—北大未名 於今晚被校方無視bbs總綱和站規直接接管 高校bbs時代落幕
![default](https://user-images.githubusercontent.com/37962734/43241824-f4daaefa-90cf-11e8-8b09-2a67a8d587d1.png)

**Comment by yu45020** [comment]
昨天怼完正确表示台湾国家的航空公司，今日就顺路收拾自家大学 ╮(╯▽╰)╭

**Comment by AnyWAT** [comment]
转：由于强制性政策规定，所有人的小孩必须在防疫站注射疫苗，除了部分权贵，其他人无一幸免，问题来了，几百万这个警那个警，几千万这个员那个员，通通有份永不落空。普警有孩，国保也有孩，网监有孩，法官也有孩，想知道你们出去维稳打压 #疫苗受害家属 的时候，能够区分自己到底是执法者还是受害者呢？

**Comment by yu45020** [comment]
@AnyWAT 求消息来源。貌似在香港/澳门/国外打过都可以吧？

**Comment by AnyWAT** [comment]
😜要求丁克。。。
【预防接种证】预防接种证制度_儿童预防接种证_亲子百科_太平洋亲子网 https://baike.pcbaby.com.cn/qzbd/1014604.html

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43261539-a18bb60a-910f-11e8-9f4b-76f2727bad0c.png)
![default](https://user-images.githubusercontent.com/37962734/43261546-ac05541a-910f-11e8-8b24-e2f0febeb980.png)

**Comment by AnyWAT** [comment]
中国公民运动 » 许章润：我们当下的恐惧与期待 - https://wp.me/p9aFpB-8PV

**Comment by AnyWAT** [comment]
转：网传，河南媒体已接到关于疫苗问题的封口令！而北京则有个更好玩的事，看下图北晚的图片吧
![default](https://user-images.githubusercontent.com/37962734/43329322-a3c4592a-91f2-11e8-8240-146b96a77bfa.png)
![default](https://user-images.githubusercontent.com/37962734/43329340-aaf056ae-91f2-11e8-9071-6fb128844daa.png)

**Comment by AnyWAT** [comment]
RT @liuhu2017 【中国多地媒体人证实不得再报道疫苗问题】我的微博昨日发布了河南疫苗的一些疑似问题和禁令。到晚间，阅读量已攀升到100多万。不过，我随后失去了我的账号。——媒体人刘虎

**Comment by AnyWAT** [comment]
转：曾因要求校方公开沈阳性侵信息而被打压的北大女生岳昕声援佳士工友：
无论是在深圳还是其它地方，无论在流水线、工地、农田还是课堂，团结起来的人们，堂堂正正站起来的人们，抓是抓不完的！
![image](https://user-images.githubusercontent.com/37962734/43363382-25e2aac6-9336-11e8-93dd-6412bbc860e0.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/43363405-8d76066a-9336-11e8-94f8-3eb18f7a7aa6.png)

**Comment by haigendong** [comment]
疫苗事件马上又要不了了之了

**Comment by AnyWAT** [comment]
JS北大声援团：北大学生就「深圳7·27维权工人被捕事件」的声援书 – 中国数字时代 - https://chinadigitaltimes.net/chinese/?p=590846 on @CDTChinese 
「深圳7·27维权工人被捕事件」全国高校声援团北京大学分团

2018年7月29日

发起人：

岳   昕 北京大学外国语学院2018届本科毕业生

联名人：。。。

**Comment by AnyWAT** [comment]
转：中大碩士流水線女工沈夢雨的出現讓深圳佳士工人維權事件熱鬧了起來，北大、清華、人大、南京大學、西安政法大學的部分大學生髮表公開信聲援工人維權抗爭……儘管有深挖極左背景，但在維權問題上，民主自由派與極左罕見地目標一致：任何人都有維護自身利益的權利……
![default](https://user-images.githubusercontent.com/37962734/43433911-f8960afa-94ab-11e8-9671-972d51c241ba.png)

**Comment by AnyWAT** [comment]
拼多多的假货里，藏着最真实的中国 http://www.myactimes.com/actimes/plus/view.php?aid=1501299

**Comment by AnyWAT** [comment]
新一代访民李宁：用直播、twitter和微博记录八年上访路  https://mp.weixin.qq.com/s/M8_rwSA7JGtpcWAbmEhe_A

**Comment by AnyWAT** [comment]
https://twitter.com/VOAJiangHe/status/1024994303179976704
砸棺赔棺😊 
转：江西抢棺材最新进展：又允许村民把被抢的棺材领回去了，被砸坏了的赔钱。赔的钱来自哪里呢？当然是财税收入……这就是拍脑袋行政的恶果：政府丧失信任基础，同时造成国民财富的极大浪费。 网评：棺材运动宣告失败，最后还是纳税人买单。[惊讶]

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43646398-6cc8f24e-9767-11e8-91ad-919f0a79592a.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/43671893-1e1d8510-97d5-11e8-9b2b-79fc8ec738a5.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43672185-605f1834-97db-11e8-8e75-bd007ab3b6d3.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43673355-16cf3712-97f4-11e8-9dba-d696bbe4cd26.png)

**Comment by AnyWAT** [comment]
转：日本全国持续高温，名古屋今天首次突破40度 。看看日本电力公司如何回应：“我们降低电费，请大家开足空调，防止中暑。”  已经人性化到极点了！ 万恶的资本主义！
![image](https://user-images.githubusercontent.com/37962734/43683426-0cc3f328-98be-11e8-81a4-e7c2fee4253a.png)

**Comment by AnyWAT** [comment]
https://twitter.com/shidaoguo/status/1025898298807267328
![image](https://user-images.githubusercontent.com/37962734/43683464-dd047ed6-98be-11e8-8f88-77be82d5315b.png)

**Comment by AnyWAT** [comment]
关于启动国民制宪程序、创建现代政治体制的公民建议书(张雪忠2018-08-05) · Issue #11 · Thestrangercamus/On-constitution-amendment-NO.1 https://github.com/Thestrangercamus/On-constitution-amendment-NO.1/issues/11?from=timeline&isappinstalled=0

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43722733-8cdf786a-99c8-11e8-9eff-e3ebb36da72c.png)

**Comment by wenqianghao** [comment]
文强，巴蜀英雄

作为 中国 社会人 都知道
贪污 腐败 是 官场 基本功

但是

为啥 文强 被 薄熙来 杀害呢？
啥 原因 薄熙来 要处死 文强

原因 是 文强 挡了 薄熙来 财路
希望 保护 巴蜀人民

薄熙来 为了 政绩
挪用 中央 给 重庆 的 国防经费

从 97年 国家 每年 给重庆 5000亿 以上的 经费
重庆 于是 有了 国家档案馆 的备份
有了 名义上 其他名字 的水雷 等兵工厂

中央 的 计划是
与西方 进行 核战争
牺牲 沿海 经济带
而 到 重庆避难
希望 西方 无法 承受 而 妥协

中央 为了 重庆 人民
每年 有2000 亿 资金
用于 修建 人防工事
给 重庆 市民避难

而 薄熙来 将 这笔钱 挪用
用于 表面工作 讨好 民粹
从他 上台 到 下台
所有 的钱 都 没有 投入建设
而是 薄 与 其重庆党羽 分肥

李作成 将军 与之 决裂
文强 为了 保护 家乡父老
将其 罪恶 上报 中央








于是 被薄 嫉恨
最后 杀害

国家 因为害怕 泄密
无法 为 文公 平反

可是 薄 与 王立军 翻脸
王 叛变
将 重庆 所有 机密 泄漏
各个 国防 工事 的 地址
人事 名单 
与 军工 合作 民企 名单

巴蜀 儿女 
必将 牢记 文公 大德



作为 中国 社会人 都知道
贪污 腐败 是 官场 基本功


但是
为啥 文强 被 薄熙来 杀害呢？
啥 原因 薄熙来 要处死 文强
原因 是 文强 挡了 薄熙来 财路
希望 保护 巴蜀人民


薄熙来 为了 政绩
挪用 中央 给 重庆 的 国防经费
从 97年 国家 每年 给重庆 5000亿 以上的 经费
重庆 于是 有了 国家档案馆 的备份
有了 名义上 其他名字 的水雷 等兵工厂


中央 的 计划是
与西方 进行 核战争
牺牲 沿海 经济带
而 到 重庆避难
希望 西方 无法 承受 而 妥协

中央 为了 重庆 人民
每年 有2000 亿 资金
用于 修建 人防工事
给 重庆 市民避难
而 薄熙来 将 这笔钱 挪用
用于 表面工作 讨好 民粹
从他 上台 到 下台
所有 的钱 都 没有 投入建设
而是 薄 与 其重庆党羽 分肥

李作成 将军 与之 决裂
文强 为了 保护 家乡父老
将其 罪恶 上报 中央


于是 被薄 嫉恨
最后 杀害
国家 因为害怕 泄密
无法 为 文公 平反


可是 薄 与 王立军 翻脸
王 叛变
将 重庆 所有 机密 泄漏
各个 国防 工事 的 地址
人事 名单
与 军工 合作 民企 名单

巴蜀 儿女
必将 牢记 文公 大德

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43823957-4fae9d7a-9b23-11e8-80df-299bcebd3421.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43825686-f860e776-9b27-11e8-9c88-9f4de417e7b7.png)

**Comment by AnyWAT** [comment]
https://twitter.com/yuexinmutian/status/1027201673020682243 
![default](https://user-images.githubusercontent.com/37962734/43846076-07724876-9b60-11e8-8285-1ebe2b1fc57f.png)

**Comment by AnyWAT** [comment]
https://twitter.com/yuexinmutian/status/1027384352999493637
![image](https://user-images.githubusercontent.com/37962734/43883879-14aa39e0-9be7-11e8-858c-d0643aa8f564.png)

**Comment by AnyWAT** [comment]
https://twitter.com/yuexinmutian/status/1027384352999493637
![image](https://user-images.githubusercontent.com/37962734/43884020-943a9b32-9be7-11e8-8103-848776318784.png)

**Comment by AnyWAT** [comment]
https://twitter.com/yuexinmutian/status/1027906049901117440 图片签名 
![default](https://user-images.githubusercontent.com/37962734/43963649-7924feee-9ced-11e8-82ef-d22071e56073.png)
![default](https://user-images.githubusercontent.com/37962734/43963666-87d4edbe-9ced-11e8-9069-6fe613ef4377.png)
![default](https://user-images.githubusercontent.com/37962734/43963681-8e08a446-9ced-11e8-9c87-af0fde415dbf.png)
![default](https://user-images.githubusercontent.com/37962734/43963691-96c22544-9ced-11e8-9cd0-5d6732b52638.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/44000292-c86b2056-9e4f-11e8-99c7-6bbc083c4650.png)
