### ISSUE TITLE
[Proposal]关于此库可能带来后果分析

### ISSUE THREAD

**Issue by taichiyi** [sikaozhe1997/Xin-Yue#754]

**Comment by ethermoto** [comment]
管理员可以关了此issues了。

**Comment by XhstormR** [comment]
前面还有一点点道理，后面的延伸是什么鬼，五毛洗地？

**Comment by FanWuTuoBang** [comment]
智者建桥，愚者建墙。——来自人民日报官微。
顺便我觉得，目前中国经济走势很不乐观。如果还墙Github，肯定对互联网产业造成影响，官方还会再自断一臂么？
