### ISSUE TITLE
[Discussion]人民已经忘记

### ISSUE THREAD

**Issue by DayChan** [sikaozhe1997/Xin-Yue#758]

**Comment by huoqiangf** [comment]
倒不是人民想忘，只不过确实没有什么后续进展了。。。总不能天天炒冷饭吧。。

**Comment by FanWuTuoBang** [comment]
我刚好想问的，请问Xin Yue同学近况如何？
是否还被约谈？学习与生活有没有受到其他影响呢？
希望了解的人可以说一下

**Comment by FanWuTuoBang** [comment]
哎，健忘的国人

**Comment by ethermoto** [comment]
有多少比XinYue重大的被消除，XinYue相关事件不是第一个，也不会是最后一个。
人民又不是硬盘，能把啥都记的牢靠，有个地方记录，能查到，大致过程还算明白，就不错了。

**Comment by gin-lsl** [comment]
多事之秋

**Comment by MAYDAYHAO** [comment]
已经没有后续了。我们无从得知了

**Comment by FanWuTuoBang** [comment]
哎……啥消息都没有么

**Comment by beyondxuxingwang** [comment]
反正没任何报道了

**Comment by GreatWallFire** [comment]
媒体会忘记报道，有良知的人心里都记着哩

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/44000292-c86b2056-9e4f-11e8-99c7-6bbc083c4650.png)
