### ISSUE TITLE
[Discussion]是否应该考虑将本项目复制到GitLab

### ISSUE THREAD

**Issue by sylxjtu** [sikaozhe1997/Xin-Yue#760]
近日GitHub被微软收购，网络上有人猜测此类触动国内当权者利益的项目可能会被微软删除，是否应该考虑将本项目复制到GitLab？

**Comment by XhstormR** [comment]
可以作为备份仓库

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/41030014-e6147e2e-69af-11e8-9941-47f048e47bd7.png)

**Comment by BetterSwifter** [comment]
哈哈哈,老哥,有点夸张了.

**Comment by speechfree** [comment]
@sylxjtu 你在 Gitlab 将本项目 import 后，其会与本项目时刻保持同步，作为备份仓库。
