### ISSUE TITLE
[Discussion]：走过路过上柱香

### ISSUE THREAD

**Issue by yywing** [sikaozhe1997/Xin-Yue#761]

**Comment by jiqing112** [comment]
无疾而终就是最好的结果。开始之初就想到了这个结局，没有交代。

**Comment by AnyWAT** [comment]
中国人大副校长毕业典礼致辞，劝告学生『坚守人生的底线』不要告密-墙外楼 https://www.letscorp.net/archives/132056

**Comment by AnyWAT** [comment]
https://twitter.com/yuexinmutian/status/1027201673020682243
![default](https://user-images.githubusercontent.com/37962734/43846213-5d869c9e-9b60-11e8-95b4-c48b13f2b116.png)

**Comment by AnyWAT** [comment]
https://twitter.com/yuexinmutian/status/1027384352999493637
![image](https://user-images.githubusercontent.com/37962734/43884020-943a9b32-9be7-11e8-8103-848776318784.png)

**Comment by ChineseTaipei** [comment]
上香。默哀。

**Comment by mapicccy** [comment]
默哀
