### ISSUE TITLE
readme.md  岳昕：致北大师生与北大外国语学院的一封公开信 link error

### ISSUE THREAD

**Issue by ZYV037** [sikaozhe1997/Xin-Yue#777]
连接打开失败
已收录文章：
    
    - 岳昕的文章：

        [岳昕：致北大师生与北大外国语学院的一封公开信](https://sikaozhe1997.github.io/Xin-Yue/#/%E5%B2%B3%E6%98%95%EF%BC%9A%E8%87%B4%E5%8C%97%E4%BA%AC%E5%A4%A7%E5%AD%A6%E5%B8%88%E7%94%9F%E5%92%8C%E5%8C%97%E5%A4%A7%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%AD%A6%E9%99%A2%E7%9A%84%E4%B8%80%E5%B0%81%E5%85%AC%E5%BC%80%E4%BF%A1.md)

**Comment by AnyWAT** [comment]
可以，https://github.com/ 相关或需代理

**Comment by ZYV037** [comment]
![1560079742(1)](https://user-images.githubusercontent.com/11004657/59158464-1d010880-8aed-11e9-9d9c-e22ccb17a523.jpg)
![1560079778(1)](https://user-images.githubusercontent.com/11004657/59158465-1f636280-8aed-11e9-8c94-7fb6219a07f3.jpg)

**Comment by ZYV037** [comment]
github文件可以打开。readme.md的ref地址我这边打不开。

**Comment by AnyWAT** [comment]
> readme.md的ref地址我这边打不开。

顶楼的链接？可以 https://sikaozhe1997.github.io/Xin-Yue/#/%E5%B2%B3%E6%98%95%EF%BC%9A%E8%87%B4%E5%8C%97%E4%BA%AC%E5%A4%A7%E5%AD%A6%E5%B8%88%E7%94%9F%E5%92%8C%E5%8C%97%E5%A4%A7%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%AD%A6%E9%99%A2%E7%9A%84%E4%B8%80%E5%B0%81%E5%85%AC%E5%BC%80%E4%BF%A1.md 
![image](https://user-images.githubusercontent.com/37962734/59158638-b9c4a580-8aef-11e9-9587-b90b5a656239.png)
