### ISSUE TITLE
这是个技术交流网站

### ISSUE THREAD

**Issue by diql** [sikaozhe1997/Xin-Yue#86]
希望能够保持技术的纯粹，像这种文章，google+， facebook, twitter 这些社交网站都愿意收录。为什么要提在这里呢？@sikaozhe1997

**Comment by kingsea0-0** [comment]
因为你说的这些不科学上网上不去呀(◔◡◔)

**Comment by leigaoyi** [comment]
心情有些复杂，github是很重要的技术交流平台，但是用作传声工具很可悲了。

**Comment by Uyouii** [comment]
但是如果只有github才能发声的话，这才是真正的悲哀吧。

**Comment by kungcn** [comment]
心情复杂，无法述说。

**Comment by kingsea0-0** [comment]
本来一个没有任何违法乱纪的帖子在社交网站上被随意封禁，这就是赵老爷们违规在先了吧，跟不讲规则的流氓斗争还要讲规则，那毫无胜利的可能。
ps:可以发到quora上，应该可以直连

**Comment by wydwww** [comment]
https://github.com/sikaozhe1997/Xin-Yue/issues/94#issuecomment-383546822

> GitHub is a web-based hosting service for version control using git.
> ——Wikipedia

**Comment by diql** [comment]
@huangzonghao 不管你是哪里人，以下的话不是很妥帖吧。
> 怎么跟墙内的某些人似的动不动就自己造个规定然后拿来压人？你不爽别人讨论政治可以自己回家搭个gitlab自己玩啊   

你自己发的链接，翻到最下面看看，是怎么说的。这个issue我会关闭，原因是重复了，戾气太重对身体不好。
