### ISSUE TITLE
我可去你他妈的吧

### ISSUE THREAD

**Issue by AshoneA** [sikaozhe1997/Xin-Yue#87]
要搞事去其他地方搞，github不欢迎你

**Comment by wydwww** [comment]
https://help.github.com/articles/github-community-guidelines/

请遵守社区守则

**Comment by ifyour** [comment]
你可别当程序员了, [斯德哥尔摩综合征](https://zh.wikipedia.org/zh-cn/%E6%96%AF%E5%BE%B7%E5%93%A5%E7%88%BE%E6%91%A9%E7%97%87%E5%80%99%E7%BE%A4)了解下

**Comment by gaocegege** [comment]
首先注意你的言辞 https://help.github.com/articles/github-community-guidelines/

其次这一类 repo 并没有被 GitHub 禁止 https://help.github.com/articles/github-terms-of-service/#2-content-restrictions

最后，看看用户协议真的有这么难？到底是谁不受欢迎？

**Comment by nidada** [comment]
无知，愚昧，程序员的简单纯粹和正直呢？

**Comment by CeresCheng** [comment]
五毛死一死？

**Comment by thewangcj** [comment]
个人博客是黄网，我可去你妈的吧
