### ISSUE TITLE
在社区谈政治 私以为不太合适

### ISSUE THREAD

**Issue by iofu728** [sikaozhe1997/Xin-Yue#88]
>无关墙与不墙
>无关github的该不该po非code文件
>只是在这一个技术社区 请尽量避免涉及政治
>请诸位 理性看待问题
>
>当然 写软文的 我真觉得[语雀][1] 比github更适合你

[1]:http://https://yuque.com/ "yuque"

**Comment by 513286483** [comment]
装啥呢，大家谈论的不是政治，谈论的是良知

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
