### ISSUE TITLE
深深地感受到了部分码农的自私

### ISSUE THREAD

**Issue by caibirdme** [sikaozhe1997/Xin-Yue#90]
反正上google要翻墙，多一个github怎么了？

**Comment by nainoNa** [comment]
很痛苦啊大哥，同步都麻烦。。

**Comment by jaegerstar** [comment]
@nainoNa 关注一下proxychains。不要因为一个翻墙工具就能搞定的事抹杀正义

**Comment by aswasn** [comment]
不是翻墙不翻墙的问题。

**Comment by guoqing-tang** [comment]
你在胡诌诌什么，github本来就是技术交流网站，放这个东西上来本来就不好。还不能说不合适了。煞笔真多。建议po主把issue直接关了。啥煞笔玩意儿。

**Comment by OscarMCY** [comment]
这不叫自私，这叫保护社区:)

**Comment by ECIZEP** [comment]
呵呵呵 还不叫自私，叫保护社区。。。还不是站在自己利益立场说话，就是怕github被封了自己不方便了。。。人啊，首先关注的就是自己利益是否受损，你们和鲁迅笔下的沉默的大多数有区别吗，甚至不如。

**Comment by jaegerstar** [comment]
@OscarMCY 这还真不是保护社区，GitHub不会因为这个贴就爆炸了

**Comment by jaegerstar** [comment]
只想再指出一点逻辑矛盾的地方，第二段写的都是怕被墙的事，第三段却又说不是墙的事。且这事关什么公权力的事啊，这都是针对北大官方啊

**Comment by OscarMCY** [comment]
您的逻辑我佩服不已，是在下解释不通，告辞:)

**Comment by jaegerstar** [comment]
这逼装得可以，我也溜了

**Comment by narakai** [comment]
虽然同情，但是这里是技术网站

**Comment by nainoNa** [comment]
@jaegerstar  我也支持这个，而且我们学校只有一半的墙，也无所谓这个的。。我就是觉得都有自己的考虑，没有必要骂别人自私。

**Comment by changan1995** [comment]
知不知道aws啊？挂个jetty行吗。

**Comment by KISSMonX** [comment]
微博? 微博删的还能看/

**Comment by monkeylord** [comment]
如果我没记错，github并不限制使用方式。
并不是只能讨论技术的地方。

**Comment by sylxjtu** [comment]
话说怎么report abuse啊，issue骂人这妥妥的abuse吧

**Comment by kituri** [comment]
你在“码农”最多的地方喷码农…………

**Comment by tigermount** [comment]
码农不就是想把头埋在沙子里赚大钱吗？只要有钱挣谁管你别人死活呢。上面建议发到微博的也是醉了，微博还能说话吗？

**Comment by Xian9527** [comment]
虽然上面很多人都说得对，但是微博 以及一些国内的贴吧 论坛或者国外知名的社交软件会像github一样自由？国家一说话怎么也得给个面子删除了，换位思考吧！假如是自己遇到这个事情呢？是否有这个胆量继续怼？github现目前还真不会被墙，除非国内真想在互联网原地踏步

**Comment by pkang2017** [comment]
连翻墙都觉得痛苦，这人一定不是码农，是社区的异端

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
