### ISSUE TITLE
真是充分体现了小资产阶级的软弱性

### ISSUE THREAD

**Issue by Ludibrium** [sikaozhe1997/Xin-Yue#91]
一边想改变环境，另一边又怕被墙。革命需要流血牺牲，现在却连个404都不愿承受。
也难怪国内封杀是这么的行云流水，根本就没有后果嘛，被封杀者自己都在内斗呢。
唉，不知道说什么好...

**Comment by FoggyIce** [comment]
有能力的人早就自己翻了，也犯不着担心这么一片小净土（虽然未必是净土），虽然我必须得承认把这个跟代码无关的信息贴在github上确实不妥，是因为和TOS相关，而不是孝（小）子（资）们的内心所求。

**Comment by Ludibrium** [comment]
> 虽然支持这件事，但是真的是不想失去最后一块地。
这块地以前早就被封过，而且不止一次，后来都因为压力而解封了。反倒是quora之类的地方容易被封，因为国内有替代品，而且不是刚需。

**Comment by gym487** [comment]
发动群众斗群众

**Comment by nidada** [comment]
他们只是一群无力的学生，空有一腔热血，却没有合理的方法与策略，去维护自己合法的权利，而且现在法律手段很多，重要的是，他们要平安顺利毕业，而非现在在那么糟。现在糟死了。事情办砸了

**Comment by gaocegege** [comment]
因为目前重复 issue 太多，所以先关闭了，不过仍可以回复。
