### ISSUE TITLE
虽然同情，但是GitHub是技术网站

### ISSUE THREAD

**Issue by OscarMCY** [sikaozhe1997/Xin-Yue#94]

**Comment by fancz2002** [comment]
GitHub is a web-based hosting service for version control using git.
——Wikipedia

**Comment by OscarMCY** [comment]
@MichaelArchangel 可惜网监可不管我们是谁；）

**Comment by OscarMCY** [comment]
其实只是说句实话，没有任何不崇尚正义的理由，但因为shadowsocks而墙了GitHub也是有先例的。
虽然这个事情无关政治，但好歹也是敏感话题。
以前好多小伙伴好不容易抗议反对解封的社区真的不希望因为这些事情而再次多一个被封掉的理由。
或许这是自私，但请问面对这墙内为数不多的自由之地，在崇尚正义的同时或许也能多一分思考和责任吧：）

**Comment by superlisohou** [comment]
@OscarMCY 还真是自私啊。另外你作为一个技术人员不懂得如何翻墙么？

**Comment by OscarMCY** [comment]
上面两层楼逻辑是真tm无敌，请问作为这个社区的一份子就不能多为他人考虑一下吗？不能维护下这个社区的相对独立吗？墙外人就心安理得了？是不是这也很自私呢？

我能不能翻墙是一回事，GitHub被不被官方墙掉是另一回事。有没有敏感信息是一回事，因为传播范围小。被不被炒热了而被盯上是另一回事。

就为了所谓的为正义发声然后全tm都不顾了？宁愿让这平台跟着在墙内陪葬？

网络匿名是真的好：）
GitHub也变成微博评论区了
希望你们在现实生活中也能这么义愤填膺，大义凌然好吧：）

关issue了，如果你觉得现实很残酷，不好意思，真的这么残酷。是代码打多了便天真了吗？

**Comment by kehao95** [comment]
GitHub是单纯的技术网站么？请你现在点击一下顶端的 Explore，看看第一个Collection是什么？
**Open journalism！！**
