### ISSUE TITLE
富强民主文明和谐

### ISSUE THREAD

**Issue by channel960608** [sikaozhe1997/Xin-Yue#96]
这么做算不算引导舆论，会不会被法律制裁。
另外别以为扔github上就不会被管到了呀，被删的repo还是很多的
申明立场：github是技术性社区，是码农吃饭的东西

**Comment by ECIZEP** [comment]
大多数人的本性就是首先看自己利益会不会受损。。

**Comment by channel960608** [comment]
说出自己心里想的，不觉得可耻。既然人的本性是这样的，没必要装的多么高尚呀。毕竟高尚是给别人看的，自己心里想什么只有自己知道
